### ISSUE TITLE
Match variable inside receive block does not take effect

### ISSUE THREAD

**Issue by Nazari** [elixir-lang/elixir#10247]
### Environment
* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.4 (compiled with Erlang/OTP 23)
* Operating system: 
macOS Catalina 10.15.6

### Current behavior
Line #62 does not have effect ('ate' and 'thunk' fields are not changed). Compiler warns sometimes (and sometimes not):
Compiling 1 file (.ex)
warning: variable "phil" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/philosophers.ex:62: Dine.dine/2

warning: the result of the expression is ignored (suppress the warning by assigning the expression to the _ variable)
  lib/philosophers.ex:62

<img width="574" alt="Captura de pantalla 2020-08-01 a las 19 31 39" src="https://user-images.githubusercontent.com/2345577/89106945-a2502680-d42d-11ea-9fc9-b6ca519f3754.png">

### Expected behavior
'ate' and 'thunk' fields of 'phil' incremented by one, as it occurs when I move line outside 'receive' block as show here:
<img width="630" alt="Captura de pantalla 2020-08-01 a las 19 35 33" src="https://user-images.githubusercontent.com/2345577/89107014-2e624e00-d42e-11ea-9dd7-6df9820c8a74.png">

Below a zip with the mix project. I'm a rookie, maybe this behavior is correct; but after two days searching could not find any info on that. 
[philosophers.zip](https://github.com/elixir-lang/elixir/files/5011009/philosophers.zip)

**Comment by josevalim** [comment]
Hi @Nazari!

That's expected behaviour, that's why you get a warning when you compile the file. Variables in Elixir do not automatically leak from blocks. For example, if consider this:

```elixir
x = 1
if true do
  x = 2
end
x
```

At the end `x` is still `1` because variables set inside a block do not override the ones outside. Instead, you need to return the variables, like this:

```elixir
x = 1
x =
  if true do
    2
  end
x
```

or in your case, like this:

```elixir
phil = receive do
  {:eat, phil} ->
    %{phil | ....}
end
```

This may be see annoying at first but it is really helpful in terms of readability, as it isn't possible for a variable deeply nested to accidentally override the outer one. It is also helpful when refactoring too. For example, you can easily move the `receive do` chunk to a separate function because all of its inputs and outputs are explicit.

**Comment by eksperimental** [comment]
your code from the zip file, should be:

```
    phil =
      receive do
        {:eat, fks} ->
          :timer.sleep(:random.uniform(1000))
          send(table, {:give_up_seat, fks, phil})
          :timer.sleep(:random.uniform(1000))
          %{phil | ate: phil.ate + 1, thunk: phil.thunk + 1}
        end

```

**Comment by Nazari** [comment]
Thanks a lot! Knowing that I agree that it has sense.

**Comment by eksperimental** [comment]
@josevalim, I think the warning should report the with the `receive do` (line 57), and not the line with `phil = %{phil | ate: phil.ate + 1, thunk: phil.thunk + 1}` (line 62). I was 100% why it was still warning once I removed `phil = `,

**Comment by josevalim** [comment]
The warning should point to where the variable is defined, as that is the source of the error.

**Comment by eksperimental** [comment]
true
