### ISSUE TITLE
Application.get_application/1 called from on_load returns nil if module belongs to an optional dependency

### ISSUE THREAD

**Issue by mat-hek** [elixir-lang/elixir#10301]
### Environment

Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Mac OS Catalina 10.15.6

### Current behavior

I have module `B` belonging to an app `:b`:
```elixir
defmodule B do
  @on_load :on_load

  def on_load do
    # here I need to know the application that B belongs to
    IO.inspect(Application.get_application(__MODULE__))
    :ok
  end

  def b, do: :ok
end
```

and project `:a` depending on `:b`. Unless the dependency is marked as optional, it behaves as expected:
```
$ iex -S mix
iex> B.b
:b
:ok
```

otherwise, I get

```
$ iex -S mix
iex> B.b
nil
:ok
```

Can be reproduced with https://github.com/mat-hek/elixir_onload_bug

### Expected behavior

I'd like get_application to return `:b` in both cases

**Comment by josevalim** [comment]
This is not really about optional dependencies. If you compile `b` directly, you see the same issue:

```
$ mix test
Compiling 1 file (.ex)
nil
Generated b app
```

That's because `Application.get_application` looks at the application specification and when you are compiling code, the application specification has not been defined yet. You can try to use `@compile {:autoload, false}`, so you postpone the loading of module and consequently the call to `on_load`, but if any other module inside `b` where to call the module `B` during compilation, the result will continue to be `nil`.

Thanks for the app that reproduces the issue btw, makes my life much easier!

**Comment by mat-hek** [comment]
Ok, I'll probably end up taking it from the mix project directly then, like `Mix.Project.config() |> Keyword.fetch!(:app)`

**Comment by josevalim** [comment]
That works as long as you do that at compile time, yeah.
