### ISSUE TITLE
mix deps.get updates git dependency on option change

### ISSUE THREAD

**Issue by ischepin** [elixir-lang/elixir#10364]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
▶ elixir --version
Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Elixir 1.10.2 (compiled with Erlang/OTP 21)
```
* Operating system:  `Darwin ***.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`

## Setup:
2 mix projects, 2 git repos: https://github.com/ischepin/repo_b and https://github.com/ischepin/repo_a
`repo_a` is a mix dependency of `repo_b`:
`{:repo_a, git: "git@github.com:ischepin/repo_a.git", submodules: true}`
The repos were created solely for this issue, feel free to use/change them

## Current behavior
1. Remove submodules option for `repo_a` from `repo_b` mix.exs file
2. Run `mix deps.get`
3. `repo_a` dependency and `mix.lock` file are updated, in `mix.lock` submodules option for `repo_a` is removed and revision (commit) is updated to the latest available on master branch

## Expected behavior
3. `mix.lock` file is updated, in `mix.lock` submodules option for `repo_a` is removed. Revision of `repo_a` is not updated

**Comment by ericmj** [comment]
If the dependency's lock doesn't match the dependency configuration the dependency is unlocked. Currently we don't make a distinction between if a configuration change requires only a partial update of the lock, a new checkout, or a full revision (commit) change.

Changing the `:sparse` option has the same behavior in that it updates the revision even though it is not required.

Another question is if it should be done when changing to a branch that contains the same commit but the latest commit is different. The lock would be valid if the revision is not changed, but I think users would expect the revision to be updated to the branch head.

**Comment by josevalim** [comment]
@ericmj Do we need a new status? I think we can fix this by returning `:outdated` instead of `:mismatch` when checking the lock status but I haven't checked it in depth.

**Comment by josevalim** [comment]
So I was able to provide a fix for this and it is relatively easy. We just need to break `get_lock_opts` in two, one that checks remote options (branch, etc) and another that checks checkout options (submodules, sparse). On lock_mismatch? we want to check both but on checkout only the first, keeping the rev the same if only the checkout options change.

However, after playing with it a bit, I am not convinced this change is desired. I thought about the following scenarios:

1. I am adding submodules because the dependency was updated to include submodules. Therefore I most likely want to update it too

2. I am adding submodules because I just added the dependency, therefore updating the version is fine, as it was just added

There is a scenario that I am adding submodules because the dependency was broken, but I fail to see how that would be the case outside of scenario 2.

For this reason, I propose to keep the behaviour as is. If you really want to lock it down, use any of the branch, ref, and other flags. Thank you!
