### ISSUE TITLE
Hint when emitting warning: variable "x" does not exist and is being expanded to "x()", but argument in the function is prefixed with underscore

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10362]
```elixir
  def foo(arg1, arg2, _arg3) do
    {arg1, arg2, arg3}
  end
end

```
```Compiling 1 file (.ex)
warning: variable "arg3" does not exist and is being expanded to "arg3()", please use parentheses to remove the ambiguity or change the variable name
  lib/sigils.ex:20: Sigils.foo/3

== Compilation error in file lib/sigils.ex ==
** (CompileError) lib/sigils.ex:20: undefined function arg3/0

```
I found when refactoring code, that sometimes I get hit by this:
Since I was not using the argument I prefixed the argument with a `_` to avoid warning, and now that I am using the argument, I forgot to remove the `_`.

I think that in the same fashion that Elixir warns 
`warning: variable "arg3" is unused (if the variable is not meant to be used, prefix it with an underscore)`
It could additionally hint an argument with that name is prefixed with an underscore.

**Comment by josevalim** [comment]
Unfortunately it is really hard to change this warning Due to backwards compatibility because at this point we don’t know that arg3() doesn’t exist. We only figure it out it is an error only latter, when all functions of the module have been defined.

Also, given this is more of an enhancement, it probably makes more sense to discuss it in the mailing list before, so we can rule it out before an issue is opened. :) thanks!
