### ISSUE TITLE
Unexpected warning in 1.11

### ISSUE THREAD

**Issue by fxn** [elixir-lang/elixir#10412]
Yo! Elixir 1.11 warns that the variable `reason` is unused in this test:

```elixir
test "the failure reason is logged as a warning", %{socket: socket} do
  payload = Map.delete(@default_payload, "longitude")
  reason = ["longitude can't be blank"]

  failed_event = fn ->
    ref = push(socket, @message, payload)
    assert_reply ref, :error, %{reason: reason} # <-- WARNING POINTS TO THIS LINE
  end

  assert_log :warn, failed_event, "... #{inspect(reason)} ..."
end
```

where `assert_log` is a function:

```elixir
def assert_log(assertion_level, function, message) do
  original_level = Logger.level()
  Logger.configure(level: assertion_level)

  try do
    captured = capture_log([level: assertion_level], function)
    ExUnit.Assertions.assert(String.contains?(captured, message))
  after
    Logger.configure(level: original_level)
  end
end
```

Is that warning legit?

**Comment by ericmj** [comment]
Yes, it looks like the warning is correct. `assert_reply` is a macro that binds the variable `reason`. Since it's bound in a an anonymous function it will not escape the scope the function and it is indeed unused.

The `assert_reply` macro in phoenix could be improved to suppress the warning, like is done for the `assert_receive` etc. macros in ex_unit.

**Comment by fxn** [comment]
Oh, I see, the payload is a pattern of course (it is documented).

In this case, I believe I should pin `reason` because I want to test the payload:

```elixir
assert_reply ref, :error, %{reason: ^reason}
```

So 1.10 did not issue a warning here and the suite passed. 1.11 uncovered this test was not testing what I wanted to test. Excellent!

Thanks @ericmj!
