### ISSUE TITLE
Introduce a high-level API for handling OS signals

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#10588]
So we don't have to define gen_event manually. This will allow us to clean up ExUnit a bit too.

**Comment by v0idpwn** [comment]
What are the expected differences from gen_event?

**Comment by jrusso1020** [comment]
@josevalim What do you think about basically taking https://github.com/elixir-lang/elixir/blob/e7cf3016bd98d983887e64bd00a2b333d85d72a8/lib/ex_unit/lib/ex_unit/signal_handler.ex and copying it into Elixir as `Os.SignalHandler`

We could implement a `__using__` macro (kind of similar to`GenServer`) that defines a behaviour with base functionality that is overridable.

If we want to keep it generic we could just have a `handle_event/2` function as in the example or if we want to be more explicit we could have functions defined for each of the OS signals i.e. `sigusr1/1`, etc... that are overridable

Looking at other parts of elixir I feel like the generic `handle_event/2` is proper the preferred approach, but let me know if you think otherwise

If this sounds like a good approach to you, I can give it a go implementing!

**Comment by josevalim** [comment]
See #10648.
