### ISSUE TITLE
Lexer: closing ">>" token not recognised after dot operator

### ISSUE THREAD

**Issue by azizk** [elixir-lang/elixir#10631]
### Environment

* Elixir & Erlang/OTP versions: Elixir 1.11.0 (compiled with Erlang/OTP 23)
* Operating system: Linux Manjaro

### Current behavior
In the following case the lexer creates two `>` tokens, where `.` `>` becomes a member access expression and the second `>` is the greater-than operator.
```elixir
%{>: 1}.>>0
# true
```
### Expected behavior
I'm not sure but I think the lexer should probably create the longest possible token (`>>` in this case) and report a parser error. Putting a space between the characters `%{>: 1}.> >0` would make the example valid.

**Comment by josevalim** [comment]
The current behaviour is correct. In order to see it, just replace the operators by other ones:

    Foo.+*0

Or:

    Foo.**0

In other words, it is not related to binaries. `Foo.*` is a valid call, so is `a*b`, therefore `Foo.**0` must be valid.

You could make a case that this is confusing and we should require the user to put spaces - but this is something the formatter already addresses and we can always add a warning later on. But semantically it is behaving as all other operators. Thank you!

**Comment by azizk** [comment]
@josevalim Thanks for being quick, but I'd like to reply to your comment. I think it's more confusing from a compiler architecture perspective. I can't say for sure but usually there is a "longest match" rule, where the lexer produces the longest possible token for the parser to consume. I don't know about the intricacies in the Elixir compiler but I guess it's basically your judgment call whether you want to have this rule (consistently) or not.

So regarding the examples, I see it as appropriate that `Foo.**b` means `Foo.*` `*` `b` since there is no `**` operator in Elixir, in which case the lexer has to produce two distinct `*` tokens. However, `>>` is the closing bracket for binaries and when the lexer encounters `>>` I think it always needs to return that as a single token (unless, of course, there's a longer match like the `>>>` operator). Let's look at another example. It works as it should because there's no ambiguity with regard to what is the longest match and what becomes a member id or operator.

```elixir
%{>>>: 1}.>>>>0 == true
```
To my mind it really seems strange that `%{>: 1}.>>0` works and doesn't throw a parser error. Even if you don't follow the longest match rule everywhere it still looks wrong to me.

**Comment by josevalim** [comment]
The tokenizer knows the difference between operators and terminators. Since >> is a terminator and not an operator, it doesn’t follow the operator rules above.

knowing what is a terminator and what is an operator is really helpful to improve error messages and give hints, and also allows specific behavior as listed here.

**Comment by azizk** [comment]
Well, I'm still not sure. Maybe I don't understand the whole picture well enough. It's alright, let's move on. Thanks for the time, José! :+1:
