### ISSUE TITLE
Elixir module '__info__' exports_md5 invalid UTF-8

### ISSUE THREAD

**Issue by okeuday** [elixir-lang/elixir#10663]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.11.3 (compiled with Erlang/OTP 23.2.3)
* Operating system: Ubuntu 18.04 LTS

### Current behavior

When using https://github.com/okeuday/reltool_util/blob/master/ex2erl to convert a module from Elixir to Erlang, the syntax tree has a binary that is invalid UTF-8 due to generated Erlang source code like:

    '__info__'(exports_md5) ->
        <<"½EÇ+\2031\\\006\027\031Ò¯K©AÓ">>;

This angers the Erlang compiler, which requires the module be marked as latin1 encoded.  It would be helpful if this binary is instead encoded as `<<189,69,199,43,131,49,92,6,23,25,210,175,75,169,65,211>>` to avoid the problem.

### Expected behavior

Elixir (BEAM) modules have literal binaries that are always valid for UTF-8 encoding.

**Comment by josevalim** [comment]
Note this can happen in other scenarios. That’s because it is much more efficient in Erlang AST to encode binaries as binstrings than each individual element, so that’s what we do, as we are not tied to a textual representation.

My suggestion is for ex2erl to check the contents of the binaries strings and do the translation itself according to the encoding it wants to export.

thanks!
