### ISSUE TITLE
System.cmd blocks usage of `start` on Windows

### ISSUE THREAD

**Issue by bliksemman** [elixir-lang/elixir#10661]
### Environment

* Elixir 1.11.2 (compiled with Erlang/OTP 21)
* Operating system: Windows 10

### Current behavior

Phoenix LiveView's test helper `open_browser` makes use of the Windows [start command](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start) via [open_with_system_cmd](https://github.com/phoenixframework/phoenix_live_view/blob/846c9528471c81cff9972f3cca761394467fa013/lib/phoenix_live_view/test/live_view_test.ex#L1200). It is used to open the HTML in the default browser.

Elixir's `System.cmd`[ has a check](https://github.com/elixir-lang/elixir/blob/b662d32fc3171537778aa896a0b4fd65af06d354/lib/elixir/lib/system.ex#L973) to see if the command exists before executing it. This fails, and thus results in an error.

See below for an IEX session that demonstrates this: 

```
iex(1)> System.cmd("start", [])
** (ErlangError) Erlang error: :enoent
    (elixir 1.11.2) lib/system.ex:815: System.cmd("start", [], [])
iex(1)> :os.cmd('start')
[]
iex(2)> :os.find_executable('start')
false
```

The `:os.cmd` worked correctly and opened a Windows command window.

### Expected behavior

It would be nice if `System.cmd` would work with the `start` command. I am not sure that this API is expected to support this. If not then I can look into a custom Windows logic for Phoenix LiveView's test helper.

**Comment by josevalim** [comment]
@bliksemman this is an intentional difference between `System.cmd` and `:os.cmd`. `System.cmd` invokes an executable while `:os.cmd` executes a script. For example, you can do: `:os.cmd("foo && bar")` but you cannot do that with `System.cmd`. For this reason, `System.cmd` is more secure, as you can't do argument interpolation and so on. In this case, it seems `start` is not an executable, but something specific to windows scripts, which is why it doesn't work.

Maybe Phoenix.LiveView wants to use :os.cmd after all. Or maybe we should find an alternative command to start on Windows.
