### ISSUE TITLE
mix format targets incorrect line length in case statements

### ISSUE THREAD

**Issue by giddie** [elixir-lang/elixir#10677]
### Environment

* Erlang/OTP 23 [erts-11.1.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
* Elixir 1.11.0 (compiled with Erlang/OTP 23)
* ArchLinux

### Current behavior

`mix format` targets an incorrect line length in (at least) case statements

### Testcase

This file contains strings containing digits that represent column numbers.

```elixir
defmodule Example do
  "4" + "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567"
  "4" + "01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678"

  case do
    "6" + "23456789012345678901234567890123456789012345678901234567890123456789012345678901234" ->
      nil

    "6" + "23456789012345678901234567890123456789012345678901234567890123456789012345678901234567" ->
      nil

    "6" + "234567890123456789012345678901234567890123456789012345678901234567890123456789012345678" ->
      nil
  end
end
```

Now after running `mix format`:

```elixir
defmodule Example do
  "4" + "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567"

  "4" +
    "01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678"

  case do
    "6" + "23456789012345678901234567890123456789012345678901234567890123456789012345678901234" ->
      nil

    "6" + "23456789012345678901234567890123456789012345678901234567890123456789012345678901234567" ->
      nil

    "6" +
        "234567890123456789012345678901234567890123456789012345678901234567890123456789012345678" ->
      nil
  end
end
```

* Outside the case statement, line 1 is 98 characters long, and is not split. This is expected.
* Outside the case statement, line 2 is 99 characters long, and is split. This is expected.
* Inside the case statement, line 1 is 98 characters long, and is not split. This is expected.
* Inside the case statement, line 2 is 101 characters long, and is not split. This is **not expected**.
* Inside the case statement, line 3 is 102 characters long, and is split. This is expected.

So it seems that inside the case statement, the formatter is targetting line lengths of 101 instead of 98.

**Comment by josevalim** [comment]
I have investigated this and it is not something we can address. I will update the docs with more details but it is related to how the algebra algorithm works. There are two ways we can format a document. One is as soon as we see a break, a whole group and its children become invalid, the other is how we format things in that we always try to put as much on a given line as possible. Let's see an example:

```elixir
foo(bar, baz + bat, one_more_arg)
```

Now let's imagine due to a choice of line length the function above does not fit in a line. The way traditional inspect algebra documents work is that, once we need to break `foo(...)`, we also need to break all of its inner groups, this means we would format this as:

```elixir
foo(
  bar,
  baz +
    bat,
  one_more_arg
)
```

As you can imagine, this leads to code that is too vertical. So what Elixir does is that inner groups to continue on the same line, in case they fit:

```elixir
foo(
  bar,
  baz + bat,
  one_more_arg
)
```

However, how do we know if a inner group can fit? We basically check if there is an opportunity for breaking the document after the line length. The issue with the code you pasted is that when we see `->` at the end of line, there is no opportunity to break the code! We will only break if `->` is past the line length.

We hint about those things in the docs but I will make it clearer.

Thanks for the report!

**Comment by giddie** [comment]
Thanks for looking into it :) So do you mean that it's actually the width of the `->` lexeme that is the source of the discrepancy?

**Comment by josevalim** [comment]
Yes, once the "largestring" goes over the limit, it splits properly, because the plus operator is the one asking if things fit. Similarly, `"long string" ->` would not split anywhere (because there is no good moment to split).

**Comment by giddie** [comment]
Yeah, that makes sense :+1: And presumably a fix (e.g. trying to re-join inner groups in additional pass) would not be worth the additional algorithm complexity. It does make me curious about whether other formatters have the same behaviour as well. I imagine this must be a known problem.
