### ISSUE TITLE
Warning when aliasing does not do anything

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10773]
```elixir
iex(1)> alias Version
Version
```

Shouldn't we warn?

**Comment by josevalim** [comment]
I can see why we could but I don’t see why we should, especially because this can be an issue for meta-programming as now people will have to check those cases to avoid warnings. So given there is no ambiguity or undefined behavior from it, I think we should not warn unless there is evidence otherwise. Thanks!
