### ISSUE TITLE
mix test --failed ignores compilation error

### ISSUE THREAD

**Issue by devality** [elixir-lang/elixir#10781]
### Environment                                                                                                                   
`➜ elixir -v      `                                                                                                       
`Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]`
`Elixir 1.11.2 (compiled with Erlang/OTP 21)`

MacOs BigSur 11.2.1

I have a pipeline where in case of failing of some test I rerun it with `mix test --failed` but I found out that when there is a compilation error `mix test --failed` ignores it.

### How to reproduce

`mix new bug`
`cd bug`
Change `test "greets the world" do` to `test "greets the world" %{} do` for example
`➜  mix test`
`== Compilation error in file test/bug_test.exs ==
** (SyntaxError) test/bug_test.exs:5:27: syntax error before: '%{}'
    (elixir 1.11.2) lib/kernel/parallel_compiler.ex:416: Kernel.ParallelCompiler.require_file/2
    (elixir 1.11.2) lib/kernel/parallel_compiler.ex:316: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7`

`➜ mix test --failed`
`There are no tests to run`

The problem is `There are no tests to run` returns exit code 0 and my pipeline doesn't fail. Also correct execution of `mix test` with failed test and compilation error return the same exit code 1 so I can't distinguish them and make workaround with bash or something. 
This behaviour seems logical to me because there is no sense to rerun test with syntax error but I would like to get different exit code in that case so I can stop the pipeline without rerunning at all.

What do you guys think?

**Comment by josevalim** [comment]
Hi @devality, I am not sure we should the change you propose. Having on failed tests to run should always be a success and trying to make this conditional can be confusing.

I can think of two other options though:

1. Make syntax errors mark all tests as failed
2. Always re-run the whole suite when --failed is given and there are no failing tests

## 1. Make syntax errors mark all tests as failed

If tests have not compiled, does it mean they have failed? On one side, we could say that "yes". On the other side, imagine this workflow:

1. A test failed
2. I try to fix it but I accidentally introduce a syntax error
3. Now I run `mix test --failed` again

If we say that a syntax error means that all tests have failed, then `mix test --failed` now should run the whole suite, which is most likely not the desired behaviour. So I think there are downsides to considering a syntax error as failed because that will always impact the whole suite.

## 2. Always re-run the whole suite when --failed is given and there are no failing tests

The other option I can think here is to run the whole suite when `--failed` is given and nothing failed previously. Probably with a quick warning on the topic. I can see this being an advantage, because you can always keep calling the suite with the `--failed` flag but I wonder if that may affect some people's workflow.

/cc @myronmarston

**Comment by ulissesalmeida** [comment]
Today we store in the metadata only the "failed tests", right? 

Would it be possible to add the "failed files" concept?

From the error message, looks like we do have "file" information.

```
Compilation error in file test/bug_test.exs == ** 
```

So, if I have a `failed file`, If I try to run again `mix test --failed`, it tries to run failed test scripts again.

**Comment by josevalim** [comment]
@ulissesalmeida it is not about how to implement it but rather what is the best workflow. If we get a syntax failed error, then we need to mark the whole suite as failed because:

1. files are loaded in parallel so if both file a_test and b_test have a bug and a_test is loaded first, we will only know about a but b may still be broken
2. even if they are not parallel, once a_test fails we need to stop loading anything else, especially if we want to avoid cascading errors (maybe a_test failed because it loaded a shared support file that had the error)
2. if test_helper.exs has a failure, then the whole suite is broken anyway

So I think trying to split this per file is not the way to go. The question is rather what is the best workflow.

**Comment by josevalim** [comment]
Ok, based on feedback on Twitter, we can't change how --failed behaves to re-run the suite because apparently some folks are doing `mix test || mix test --failed` on CI (which I *extremely* discourage).

The only option I can think here is to check if the suite has ever ran before or not at all. So if you call `mix test --failed`:

1. and the suite has never run before we can raise saying: "Cannot run --failed tests because the suite did not run before"
2. and if the suite has run we say the current message: "There are no tests to run"

**Comment by devality** [comment]
Will it work if some test suits(from other files) managed to pass before the one with compilation error?

**Comment by josevalim** [comment]
@devality I will check but i don't think so because in case of syntax_error we don't get to write down the manifest.

**Comment by Cohen-Carlisle** [comment]
Wouldn't `mix test || mix test --failed` be okay if `mix test --failed` ran the whole suite with without failing tests? If `mix test` returns `0`, `mix test --failed` won't run and the line returns `0`. However, you still have a problem if there are unconditional retries, e.g., `mix test; mix test --failed`.

Regardless, isn't there a simple fix to this on the user side? You could do something like: `MIX_ENV=test mix compile || exit 1` as a guard or `MIX_ENV=test mix compile && mix test --failed` in place of a simple `mix test --failed`.

Apologies if these have been considered and are lacking for some reason I haven't thought of.

**Comment by devality** [comment]
> Regardless, isn't there a simple fix to this on the user side? You could do something like: `MIX_ENV=test mix compile || exit 1` as a guard or `MIX_ENV=test mix compile && mix test --failed` in place of a simple `mix test --failed`.

`mix compile` doesn't compile .exs files, so in my case this trick won't work.

**Comment by josevalim** [comment]
> Wouldn't mix test || mix test --failed be okay if mix test --failed changed to run the whole suite if no tests previously failed? 

The problem is that when the suite succeeds, then it will run it again. :(

**Comment by Cohen-Carlisle** [comment]
>mix compile doesn't compile .exs files, so in my case this trick won't work.

Ah, oops, I had somehow convinced myself it did. You are right, though.

> The problem is that when the suite succeeds, then it will run it again. :(

Maybe I'm too focused on that `||` but if `mix test` succeeds, then `mix test --failed` doesn't run at all. For example, in `mix test || echo "it failed"`, `it failed` is only printed if `mix test` fails. In any case, this could still lead to unintentional whole reruns for unconditional retries via `mix test --failed`.

Slightly tangential, but this situation is more narrow than I initially understood it to be. You have to have had no failing tests, then introduce a syntax error, then run `mix test --failed`. So under the steps to reproduce, if I add a failing assertion before introducing a syntax error, `mix test --failed` behaves as expected.

But I think what @devality is actually asking for is for compilation errors on `mix test` to have a different exit code than successful compilation with test failures.

**Comment by josevalim** [comment]
> Maybe I'm too focused on that || but if mix test succeeds, then mix test --failed doesn't run at all. 

Oh, thank you! I forgot it is a short-circuiting one!

**Comment by amatalai** [comment]
Is there any workaround to achieve previous behavior of `--failed` flag? This change made it completely useless when working on big umbrella project. 

Previously, `mix test --failed` skipped all umbrella apps without test failures. 
Now, `mix test --failed` runs only few tests less than regular `mix test`.

**Comment by josevalim** [comment]
Thanks for the report. I forgot about umbrellas. I will either revert the behavior or add a flag to control this.

**Comment by TheFirstAvenger** [comment]
I am also hitting this umbrella issue. Ideally, when `mix test --failed` is run in an umbrella app, the individual apps test runs would use the old pattern of not repeating if no failures are found, then the umbrella app would, at the end of the execution of all apps tests, determine if there were no failures, and in that case re run the regular `mix test` across all the child apps. This would give an umbrella app the desired "only run failed, but rerun all if no single test fails" behaviour.

**Comment by josevalim** [comment]
I believe we reverted it but a PR with a flag would be welcome!

**Comment by TheFirstAvenger** [comment]
@josevalim Ahh yes, sorry, I had looked for a revert in PR's but now see the commit was direct to master.
