### ISSUE TITLE
debugger: can't select function breakpoints

### ISSUE THREAD

**Issue by gertcuykens** [elixir-lang/elixir#10795]
### Environment

Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.11.3 (compiled with Erlang/OTP 23)
OSX

### Current behavior

![image](https://user-images.githubusercontent.com/863731/111218556-2e871680-85d7-11eb-865e-cbec42d56f1e.png)

### Expected behavior

 ```elixir
  def hello do
    x = 1
    IO.puts x
  end
```

![image](https://user-images.githubusercontent.com/863731/111218803-84f45500-85d7-11eb-9ea9-bc9d3749e953.png)

To have hello in the list

which brings me to 

![image](https://user-images.githubusercontent.com/863731/111218888-a5241400-85d7-11eb-8891-003145b2e1c2.png)

Probably also not working but can't test it because I don't understand how it works exactly, I only find erlang docs http://erlang.org/doc/apps/debugger/debugger_chapter.html#conditional-breakpoints

Thanks

**Comment by josevalim** [comment]
Hi @gertcuykens! The debugger support is a bit limited because it extracts things like modules and functions, it extracts from the source code. So you need to interpret modules in the command and use line breaks for break points. Here is a getting started guide specific to Elixir: https://elixir-lang.org/getting-started/debugging.html#debugger
