### ISSUE TITLE
Using map syntax %{} as list brackets for integers

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#10964]
### Description

I am not familiar with semantics of elixir's parser but I came across this inconsistency when I was experimenting with Elixir's AST

### Environment

```
Erlang/OTP 23 [erts-11.2.1] [source] [64-bit]
Elixir (1.11.3)
```

### Current behavior

```elixir
iex(2)> quote do
...(2)>   %{x, y, z}
...(2)> end
{:%{}, [], [{:x, [], Elixir}, {:y, [], Elixir}, {:z, [], Elixir}]}
iex(3)> quote do
...(3)>   %{1, 2, 3}
...(3)> end
** (SyntaxError) iex:4:6: syntax error before: ','
```

`SyntaxError` is raised for strings, atoms, modules and things like `%{%{x, y, z}}` too

### Expected behavior

```elixir
iex(2)> quote do
...(2)>   %{x, y, z}
...(2)> end
{:%{}, [], [{:x, [], Elixir}, {:y, [], Elixir}, {:z, [], Elixir}]}
iex(3)> quote do
...(3)>   %{1, 2, 3}
...(3)> end
{:%{}, [], [1, 2, 3]}
```
Or
```elixir
iex(2)> quote do
...(2)>   %{x, y, z}
...(2)> end
** (SyntaxError) iex:4:6: syntax error before: ','
```

**Comment by josevalim** [comment]
Yes, this is intentional. The parser forces pairs (with keywords or =>) to be written between %{}. We have no plans to relax this requirement for now. Thanks!

**Comment by hissssst** [comment]
But why `%{x, y, z}` is being parsed? There is no `=>` or keyrword there...

**Comment by josevalim** [comment]
Oh, I see your question now. I thought that you wanted the behaviour to be extended to integers.

One thing to keep in mind is that we support `%{unquote_splicing(...)}` and `%{unquote_splicing ...}`, which are part of meta-programming. So as a consequence we must at least allow calls and, for consistency, we allow anything like this:

    (Alias.)*fun_name
    (Alias.)*fun_name(*args)
    (Alias.)*fun_name arg

To be honest, we could remove the first entry but I would say it probably doesn't matter much because any subset would be considered arbitrary. The important part is that the subset is, well, a subset.
