### ISSUE TITLE
mix cmd with nonexistent app does not warn or throw error

### ISSUE THREAD

**Issue by vinibrsl** [elixir-lang/elixir#10984]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.11.4 (compiled with Erlang/OTP 23)
* Operating system: Debian GNU/Linux 10 (buster)

### Current behavior

When running `mix cmd` and passing an unexisting app, it prints nothing with the exit code 0 (successful termination).

```
$ mix cmd --app nonexistent_app mix test

```

This can get confusing when passing multiple apps. It won't fail nor warn, but execute the command only in the existing app, with the impression that it ran successfully in both apps.

### Expected behavior

A warning message is expected.

**Comment by josevalim** [comment]
Good call. A warning would be welcome!

**Comment by vinibrsl** [comment]
@josevalim I'd like to tackle this one and discuss the solution. From what it seems, `Mix.Tasks.Cmd.run/1` runs in the context of the child app.

https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/task.ex#L386

IMO, the ideal would be not to change `Mix.Task.run/2` as this function is generic. In this case, can we retrieve the list of the apps inside the umbrella from the child app scope?

**Comment by josevalim** [comment]
Ah, that's a good point. We could use the apps flag itself to detect if we are the first app to run or not, but the issue would be finding which siblings are the available ones. One option is to have a separate task, cmd.child and make the child recursive so we can check on the parent, but that sounds like too much work.

Another option is to introduce an optional callback that runs in the umbrella before recursive tasks... but I am not sure if we want to cross this line either.

**Comment by jmbejar** [comment]
I was playing a bit and come up with a possible solution to this issue:

* Generalize the `--app` argument to be valid for all `recursive` tasks, not only `cmd` (here is the game changer 😄)
* Parse the `--app` args at the parent level, throw warnings for unknown apps there, and only running the task for the valid apps.
* Remove the logic comparing the `app` args with the current local name from `Mix.Tasks.Cmd`, no longer needed.

Maybe it is not a big deal, but I learned that running the `mix cmd` with an `app` argument is always loading all the umbrella applications (because the app filter is checked in the children context as commented above). With this solution, we can only load the apps listed in the args (maybe it is useful in production environments when running a specific task in a specific app?).

Of course, let's think if it is appropriate to generalize the --app thing to more commands. I think so, but maybe someone can think of any problem with that.

I could have a PR soon (since I was already able to test the idea) if the idea is appealing.

**Comment by josevalim** [comment]
Great analysis @jmbejar! What do you think about this:

1. Introduce a `Mix.Task.run_in_app(app, task, args)` function
2. Change the `do` task to accept an `--app` flag
3. Tell people do use `mix do --app foo cmd echo hello`

The reason why I prefer this to generalizing is because I don't think we should inject our own options into user tasks. So we would need to use env vars but env vars are not passible from custom aliases, for example. So I think generalizing `do` is the way to go. WDYT?

**Comment by jmbejar** [comment]
I was thinking of having the `--app` flag as a "top-level" argument, not being injected into the tasks options.

```
# Original
$ mix cmd --app nonexistent_app mix test

# With a top-level `app` flag
$ mix --app cmd nonexistent_app mix test
```

Said that I recognize there are no other examples of "top-level" arguments in `mix`, all of them are also options for the tasks themselves, so it would add some complexity to the project and the way it is used, probably not the best idea.

So, I like the idea of using the `do` command for this purpose :+1:.

I will explore the idea in the code a little bit.
