### ISSUE TITLE
issue with dialyzer and OTP 24

### ISSUE THREAD

**Issue by dvic** [elixir-lang/elixir#11030]
I'm getting new dialyzer errors when trying to upgrade to OTP 24, the issue is reproduced in https://github.com/dvic/otp24_dialyzer_issue (`mix dialyzer`).

In the above repo the error is:

```
lib/my_app.ex:9:app_call
The call _.'foo'/() requires that _@1 is of type atom(), not maybe_improper_list().
```

It seems like dialyzer can't infer anymore that `assigns` in this case is a `map()`. Removing the line `:ok = assign(assigns)` makes the problem go away, so it seems like some kind of inference issue? Furthermore, when you use a guard (like the function `with_guard`) the error also goes away. Lastly, the problem seems to only occur on OTP 24, I've tested the following versions:

No errors:
`1.11.4 + OTP 23.3.3`
`1.12.1 + OTP 23.3.3`

Errors:
`1.11.4 + OTP 24.0.2`
`1.12.1 + OTP 24.0.2`
`1.13.0-dev (2a5e3df) + OTP 24.0.2`

**Comment by josevalim** [comment]
Hi @dvic!

The issue is not that Dialyzer can't infer it is a map, is that it infers it is either a map or a list, and therefore `assigns.foo` emits a warning. The reason why it emits a warning is because Elixir compiles it to this:

```elixir
case assigns do
  %{foo: foo} -> foo
  %{} -> raise BadKey
  _ -> apply(assigns, :foo, [])
end
```

However, we mark all clauses as generated, exactly so Dialyzer doesn't warn (and it doesn't warn in most cases!). So I would say the root cause is either that Dialyzer got smarter or Dialyzer is no longer checking the "generated" annotation we add to clauses and, therefore, it warns.

I suspect it is not an Elixir bug. I will double check if we can add more annotations to stop this but maybe we cannot (and it is down to Dialyzer actually respecting the generated annotation).

**Comment by dvic** [comment]
> The issue is not that Dialyzer can't infer it is a map, is that it infers it is either a map or a list, and therefore `assigns.foo` emits a warning.

Now that I think a bit more about this: if dialyzer infers it's a map or a list, then it would be fine right? I assume this is how the "success typing" of dialyzer works? (find at least one happy path?)

If I remove `or is_list(attrs)` from the guard of the `assign` function, the error indeed goes away. But this is very strange to me, adding a disjunction to a guard should never fail dialyzer right? (again, assuming succes typing)

**Comment by josevalim** [comment]
Dialyzer is sure that clause can never be invoked under any circumstance, so it correctly warns on that. It is effectively dead code (and Dialyzer warns on those).

**Comment by dvic** [comment]
Ah I see, thanks for clearing that up.

**Comment by dvic** [comment]
Nice! This fixes all 24 dialyzer issues in our project :) Thanks a lot! The next question of course 🙂: when can we expect the next release that includes this fix?

**Comment by josevalim** [comment]
~3 weeks. We will probably accumulate enough enhancements by then!
