### ISSUE TITLE
Unmatched parentheses using `String.match?/2` with `~r()` trying to match parentheses

### ISSUE THREAD

**Issue by mrcasals** [elixir-lang/elixir#11050]
### Precheck

I looked for the in the issue tracker, nothing appeared.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 22, Elixir 1.11.4
* Operating system: MacOS 11.0.1

### Current behavior

When trying to match parentheses using the `~r()` sigil with parentheses as enclosing symbols, it gives an `unmatched parentheses` error. The error does not appear when using `~r//` with slashes or `~r[]`:

```elixir
iex(1)> str = "Activity (debate) 12"
"Activity (debate) 12"
iex(2)> String.match?(str, ~r(\(debate\)))
** (Regex.CompileError) unmatched parentheses at position 8
    (elixir 1.11.4) lib/regex.ex:216: Regex.compile!/2
    (elixir 1.11.4) expanding macro: Kernel.sigil_r/2
    iex:2: (file)
iex(2)> String.match?(str, ~r/\(debate\)/)
true
iex(3)> String.match?(str, ~r[\(debate\)])
true
```

### Expected behavior

Regexp should be able to compile just fine using either `~r//` or `~r()`

**Comment by josevalim** [comment]
This is expected. The `\)` in your case is escaping the closing of the sigil, not the parenthesis itself. In order to understand why, just change the sigil:

    iex> ~s(\(example\))
    "(example)"

In Ruby, which may be from where your expectation comes from, it works because %r comes from the parser. So the parser is effectively parsing a regex and knows the regex rules. Elixir, on the other hand, has a generic approach to sigil and the ~r sigil is completely user defined. The good news is that all sigils follow the same rule but it leaves less spaces for specialization. Therefore using // and "" for regexes is typically preferred.

**Comment by mrcasals** [comment]
@josevalim that's correct, I'm coming from Ruby :) Thanks for taking the time to explain this!

> Therefore using // and "" for regexes is typically preferred.

Should docs examples on the `sigil_r` be updated to use `~r//`, then?

https://github.com/elixir-lang/elixir/blob/2a25a72d08e4a7cb3198e0000eb8c76b334f378b/lib/elixir/lib/kernel.ex#L5590-L5607

**Comment by josevalim** [comment]
Yes! Would you like to send a PR? :)

**Comment by mrcasals** [comment]
@josevalim on it!

**Comment by mrcasals** [comment]
Done, see https://github.com/elixir-lang/elixir/pull/11051 😄
