### ISSUE TITLE
Avoid prepending module name when setting functions inside data defined via module attributes

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#11066]
### Environment

```
$ elixir --version
Erlang/OTP 23 [erts-11.2.2.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.4 (compiled with Erlang/OTP 23)
```

### Current behavior

The following piece of code

```
defmodule X do
  @funs %{fun: &foo/1}
  def bar(), do: @funs
  def foo(x), do: x
end
```

gives a compilation error

```
** (CompileError) iex:64: undefined function foo/1
    (stdlib 3.14.2.1) lists.erl:1358: :lists.mapfoldl/3
    (stdlib 3.14.2.1) lists.erl:1359: :lists.mapfoldl/3
    (elixir 1.11.4) expanding macro: Kernel.@/1
```

but the error does not happen if the function name is prepended with the module name like `@funs %{fun: &X.foo/1}`.

### Expected behavior

It would be nicer to not require prepending the module name. Note that this is not required when the map is defined inside a function instead of via an attribute, i.e., the following compiles

```
defmodule X do
  def bar(), do: %{fun: &foo/1}
  def foo(x), do: x
end
```

**Comment by josevalim** [comment]
Elixir has explicit semantics between local/unqualified calls and remote calls. A local call will never go through code reloading, a remote call will. Because of that, a local call always binds at compilation time (the called function must exist at compilation time), but a remote call can't be verified, because the remote call can be added later on, even in the same module, as long as code reloading happens.

For this reason, we don't plan to blurry the lines between those constructs. Therefore, you need to do `&Mod.foo/1` if you want to refer to it at the module body, since the function `&foo/1` has not yet been defined.
