### ISSUE TITLE
Missing line numbers for litterals cause dilayzer to ignore issues (OTP 24)

### ISSUE THREAD

**Issue by lud** [elixir-lang/elixir#11107]
```
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.12.1 (compiled with Erlang/OTP 24)
```

Full description and possible diagnostic were tracked in this elixir forum topic : https://elixirforum.com/t/elixir-ls-not-showing-warnings/40741/13

Probably related to https://github.com/erlang/otp/pull/4890 

This code contains an obvious type error although dialyzer does not pick it up:

```elixir
defmodule MyApp do
  def hello do
    default(1234) # <------- not a binary
  end

  @spec default(binary) :: binary
  def default(bin) when is_binary(bin) do
    "test #{bin}"
  end
end
```

It looks like some literals in the elixir AST are missing line numbers (or other debug info) when translated to erl AST and it gets in the way of dialyzer. My knowledge of the compiler is very limited so can't add much to that.

Also ping @michallepicki .

**Comment by josevalim** [comment]
I can confirm the warning shows up on OTP master. Thanks!

**Comment by michallepicki** [comment]
The issue is still present. One warning is shown but one is missing (in that particular case). Only the vague `Function hello/0 has no local return` warning is shown. The more helpful:
```
lib/my_app.ex:3: The call 'Elixir.MyApp':default
         (1234) will never return since the success typing is 
         (binary()) -> 
          binary() and the contract is 
          (binary()) -> binary()
```

is not shown because the literal integer has line number 0 so warning is not getting added because `is_compiler_generated` returns true for that literal [here](https://github.com/erlang/otp/blob/d7f19868551b10d6f0be48ff1d76626676a4a2aa/lib/dialyzer/src/dialyzer_dataflow.erl#L3160)

**Comment by michallepicki** [comment]
Confirmed fixed, thank you very much! I will keep an eye on potential similar issues, standalone "has no local return" without additional context can be frustrating to deal with

**Comment by lud** [comment]
Great, thank you!
