### ISSUE TITLE
Interpolation formatting bug in 1.12

### ISSUE THREAD

**Issue by pcorey** [elixir-lang/elixir#11118]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

```
➜  elixir --version
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

* Operating system: 
macOS Catalina 10.15.6

### Current behavior

After upgrading from Elixir 1.11 (I was running `1.11.3-otp-23`) to 1.12 (`1.12.2-otp-24`), the following code, which was previously considered formatted:

```
"Posting catalog report #{
  inspect(
    active_id: active_id,
    error_days: error_days,
    facility_id: facility_id,
    last_run_at: last_run_at,
    max_results: max_results,
    last_key_id: last_key_id,
    catalog_type_ids: catalog_type_ids,
    catalog_ids: catalog_ids
  )
}"
|> Logger.info()
```

Formats to this, which seems incorrect:

```
"Posting catalog report #{inspect(active_id: active_id,
error_days: error_days,
facility_id: facility_id,
last_run_at: last_run_at,
max_results: max_results,
last_key_id: last_key_id,
catalog_type_ids: catalog_type_ids,
catalog_ids: catalog_ids)}"
|> Logger.info()
```

Notice the lack of indentation in the interpolated code.

Under 1.12, `mix format --check-formatted` fails on the first example. Reverting to 1.11 reverts the formatting back to the first example.

### Expected behavior

I would expect the formatting to remain consistent from 1.11 to 1.12, and I would expect the formatting in 1.12 to properly indent the code being formatted within an interpolation.

**Comment by josevalim** [comment]
This is noted in the CHANGELOG. Previously the interpolation led to poor break lines, so we choose to no longer break in interpolations. In your case, you should break the code apart and compute the inspection (or the inspected value) outside of the interpolation.

> I would expect the formatting to remain consistent from 1.11 to 1.12

Keep in mind we have historically changed the formatting between versions. For example, in 1.9 we added new places where we respect the user formatting and those would be reverted (or considered invalid) on 1.8. That's why we recommend to run the formatter only on the most recent version in projects.
