### ISSUE TITLE
Compilation error/interruption leave manifest intact but removes compiled code 

### ISSUE THREAD

**Issue by marcandre** [elixir-lang/elixir#11176]
Compilation state can be invalid following #11080:

1) Compile a project successfully.
2) Modify a file `a.ex` and introduce a compile error
3) `mix compile` => compile error
4) Revert `a.ex` to exactly what it was initially
4) `mix compile` says project is up to date, but `_build/dev/.../A.beam` is gone

Probably a more frequent way to create this (at least for me) is:
1) compile successfully
2) switch to a branch that changes `my_app.ex` to check something
3) forget to switch back, do `mix compile`, and when seeing `compiling 370 files...` thinking "oh oh, wrong branch" => abort compilation with control-C twice
4) switch back to original branch
5) state is now corrupted, as most compiled modules are gone but manifest intact.

Obvious solution is to invalidate the digest when we remove the compiled files. Making any of the errors above would imply that the compiled modules would be deleted and then recompiled.

A nicer solution would be to update the compiled files and manifest in sync, i.e. if a compilation fails or is interrupted, no change on the compiled module or manifest happen. Maybe the newly compiled modules could be written to a temporary location and moved to their final destination (overwritting previously compiled files) when compilation succeeds? In both scenarios above, no recompilation would occur on the last step but the compiled files would still be there. How feasible is that?

**Comment by josevalim** [comment]
Because Ctrl+C will abort the VM, so I think there is always chance for a race condition, unless we do multiple writes.

The most obvious solution I can think of is that, if the file has been modified and the digest is the same, we could check if all .beam files defined by modules from said source are in disk. It makes it a bit more expensive but it should be fail proof and it should run this check just once anyway*.

*If you have files with more recent mtimes but no digest changed, we will run the digest check on every `mix compile` until at least one file changes. So we may want to write to the manifest in said cases. I will push a fix for this soon.

**Comment by josevalim** [comment]
Btw, great find!!!

**Comment by marcandre** [comment]
> Because Ctrl+C will abort the VM, so I think there is always chance for a race condition, unless we do multiple writes.

Sorry I wasn't clear. I was proposing to
a) not delete invalidated `.beam` files (but of course not load them on compilation)
b) compile `.beam` files in a separate folder (say `_build/dev/project/currently_compiling/...`)
c) when compilation is successful, move `currently_compiling/*` to `ebin/*` and write updated manifest

> The most obvious solution I can think of is that, if the file has been modified and the digest is the same, we could check if all .beam files defined by modules from said source are in disk.

Sure, we can start with that.

**Comment by josevalim** [comment]
@marcandre I see. Unfortunately it is a bit more tricky than that because the .beam will be automatically loaded as long as the `ebin` directory is in the load path. So we would need to remove it from the load path but doing so would make it impossible for us to load any other .beam file from `ebin` that we may need during compilation. It could work if we moved all .beam files, except the removed ones, to `current_compiling`. But that doesn't sound like it is worth it? 🤔

**Comment by marcandre** [comment]
> The most obvious solution I can think of is that, if the file has been modified and the digest is the same, we could check if all .beam files defined by modules from said source are in disk

Actually, is that sufficient?

a) compile successfully a project
b) modify files `f1.ex`, `f2.ex`, etc.
c) compile and interrupt after a while
Maybe `f1.beam` was created, but not `f2.beam`, and the manifest is kept as it was, right?
d) revert files, now `f1.beam` has a matching digest and there is a `f1.beam`.

Maybe we have to store the mtime of the `.beam` files corresponding to the hash digest?

I.e.: if mtime of `.ex` has changed, but hash digest is same, then check the `.beam` files that are either missing or have a mismatching mtime with what was stored in the manifest.

**Comment by josevalim** [comment]
Currently we only write beam files to disk once compilation finishes.

**Comment by marcandre** [comment]
I should have a PR soon for this
