### ISSUE TITLE
Fix operator precedence in version requirements

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#11200]
The `and` and `or` operators in version requirements have different precedence than the corresponding Elixir operators.

The requirement `>= 3.0.0 and < 4.0.0 or >= 1.0.0 and < 2.0.0` is currently evaluated as `>= 3.0.0 and (< 4.0.0 or (>= 1.0.0 and < 2.0.0))` but it should be evaluated as `(>= 3.0.0 and < 4.0.0) or (>= 1.0.0 and < 2.0.0)`.

Before making this change we need to investigate what the backwards incompatible implications are, one idea is to go through all Hex packages and check if there are any dependency requirements this would cause breakage for.

**Comment by josevalim** [comment]
Hi @ericmj, I have sent a PR for this. Note that the following two new tests:

```elixir
    req = "< 0.2.0 and >= 0.1.0 or >= 0.7.0"
    assert Version.match?("0.1.0", req)
    assert Version.match?("0.1.5", req)
    refute Version.match?("0.3.0", req)
    refute Version.match?("0.6.0", req)
    assert Version.match?("0.7.0", req)
    assert Version.match?("0.7.5", req)
```

```elixir
    req = ">= 0.7.0 or < 0.2.0 and >= 0.1.0"
    assert Version.match?("0.1.0", req)
    assert Version.match?("0.1.5", req)
    refute Version.match?("0.3.0", req)
    refute Version.match?("0.6.0", req)
    assert Version.match?("0.7.0", req)
    assert Version.match?("0.7.5", req)
```

The _second one_ passes in the old suite, which matches what you described. Therefore, in order to potential conflicts in Hex, you will need to lex a requirement (with `Version.Parser.lexer`) and see if the `:and` came before a `:or` at any moment.

Also note I slightly changed the Version.Parser API, I don't know if Hex depends on it. If it does, pls let me know!

**Comment by ericmj** [comment]
There are two packages for which `and` comes before `or`:

https://hex.pm/packages/terraform/1.0.1
https://hex.pm/packages/bamboo_sparkpost/1.0.0-rc.1

But it seems their intention of the requirement was for it to work like how we are changing it to.

Hex does not depend on the `Version.Parser` API.

**Comment by josevalim** [comment]
Perfect, thanks! I will let you go ahead and merge this when you feel it is ready.
