### ISSUE TITLE
Deleting / renaming a `.leex` view does not trigger a recompilation

### ISSUE THREAD

**Issue by marcandre** [elixir-lang/elixir#11202]
Deleting a `leex` view or renaming (e.g. `leex` -> `heex`) does not trigger a recompilation.
More importantly, modifying the renamed view does not trigger a recompilation.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12.2 @ 9df7a548e

(maybe partially related to #11080, I didn't check with stock elixir 1.12, but I suspect not entirely)

**Comment by marcandre** [comment]
Updated after a bit more research

**Comment by josevalim** [comment]
The issue is that, in order to detect if new files were added or removed, Phoenix has a pass that touches the source file: https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/compile.phoenix.ex - and this pass no longer works.

The good news is that this feature has been incorporated into Elixir on v1.11 but users in earlier versions won't benefit from it.

**Comment by josevalim** [comment]
I think I will have to backport the changes to __mix_recompile__? to the v1.5 branch too. Meanwhile I think it is safe to say it is not possible to bring those improvements to v1.12 for now.

**Comment by josevalim** [comment]
I have backported the Phoenix improvements here on v1.11+: https://github.com/phoenixframework/phoenix/commit/8c1ef6c0fa39bda4d543b07e1af64445ed5a75e6 and I have reverted the changes to v1.12. :)
