### ISSUE TITLE
"Compiling <n> files" showing wrong number of files

### ISSUE THREAD

**Issue by marcandre** [elixir-lang/elixir#11252]
### Environment

Erlang/OTP 24 [erts-12.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.12.3 (compiled with Erlang/OTP 24)

Same behavior with Elixir 1.12.1

### Current behavior
```
$ mix compile
[...]
<Add return to a single file>
$ mix compile --verbose
Compiling 12 files (.ex)
Compiled some/path
[... 52 such lines]
```

### Expected behavior

I haven't investigated, but is there a reason not to expect elixir to output "Compiling 52 files (.ex)"?

**Comment by josevalim** [comment]
The Elixir compiler does multiple cycles, as it finds new dependencies once certain files are compiled. We only "log" the initial cycle:

https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/compilers/elixir.ex#L105

I will add logging of the next cycles by adding a similar call here:

https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/compilers/elixir.ex#L380

The reason why I didn't do it before is because the next cycles were often very tiny. But maybe my assumption was wrong (or it changed with time).

**Comment by josevalim** [comment]
To be clear, you will likely see multiple "Compiling 3 files (.ex)" calls, but I think we can give it a try and collect feedback.
