### ISSUE TITLE
Compiling modules of same name but different case silently succeeds (on Windows)

### ISSUE THREAD

**Issue by simonmcconnell** [elixir-lang/elixir#11277]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12.2
* Operating system: Windows 10

### Current behaviour

I was writing a tiny library to have Remix Icon SVGs as Surface components.  It generated two modules:
`RemixIcon.RiBookMarkFill`
`RemixIcon.RiBookmarkFill`

It compiled fine but one module had overwritten the other.  I didn't realise until I tried to run `mix docs`, which threw:
```
Generating docs...

18:43:35.005 [error] Loading of c:/Users/simon/code/surface_remix_icon/_build/dev/lib/surface_remix_icon/ebin/Elixir.RemixIcon.RiBookMarkFill.beam failed: :badfile


18:43:35.005 [error] beam\beam_load.c(158): Error loading module 'Elixir.RemixIcon.RiBookMarkFill':
  module name in object code is 'Elixir.RemixIcon.RiBookmarkFill'



18:43:35.009 [error] Loading of c:/Users/simon/code/surface_remix_icon/_build/dev/lib/surface_remix_icon/ebin/Elixir.RemixIcon.RiBookMarkFill.beam failed: :badfile


18:43:35.009 [error] beam\beam_load.c(158): Error loading module 'Elixir.RemixIcon.RiBookMarkFill':
  module name in object code is 'Elixir.RemixIcon.RiBookmarkFill'


** (UndefinedFunctionError) function RemixIcon.RiBookMarkFill.module_info/1 is undefined (module RemixIcon.RiBookMarkFill is not available)
    (surface_remix_icon 0.1.0) RemixIcon.RiBookMarkFill.module_info(:attributes)
    (ex_doc 0.24.2) lib/ex_doc/retriever.ex:450: ExDoc.Retriever.behaviours_implemented_by/1
    (ex_doc 0.24.2) lib/ex_doc/retriever.ex:436: ExDoc.Retriever.get_impls/1
    (ex_doc 0.24.2) lib/ex_doc/retriever.ex:172: ExDoc.Retriever.get_module_data/2
    (ex_doc 0.24.2) lib/ex_doc/retriever.ex:112: ExDoc.Retriever.generate_node/3
    (elixir 1.12.2) lib/enum.ex:3894: Enum.flat_map_list/2
    (elixir 1.12.2) lib/enum.ex:3895: Enum.flat_map_list/2
    (ex_doc 0.24.2) lib/ex_doc/retriever.ex:43: ExDoc.Retriever.docs_from_modules/2
```

I guess this might work on unix as filenames are case sensitive IIRC?

### Expected behaviour

Compile error.

**Comment by josevalim** [comment]
Thanks for the report!

We check for duplicate modules, but that doesn’t consider the permutation of casings, doing so could be expensive: we would do a filesystem check for each possible permutation. Therefore we don’t plan to change it.

Similarly, we allow beam files to be overridden, because that is a natural outcome of recompiling code (the compilation artifacts are overridden). Therefore we shouldn’t be checking existing .beam files on disk either.

Given the above, the current behavior with log messages is the expected one. In a way, this is not different from a typo in the module name: you will find out you have the wrong module name when you invoke it, which is what ExDoc is doing.

PS: yes, Linux is case sensitive but note that macs are not.
