### ISSUE TITLE
is this normal?

### ISSUE THREAD

**Issue by alaadahmed** [elixir-lang/elixir#11379]
* Elixir & Erlang/OTP versions (elixir --version): __`1.12.3`__
* Operating system: __macOS 11.6.1__

<img width="1063" alt="Screen Shot 2021-11-11 at 02 20 20" src="https://user-images.githubusercontent.com/14099508/141214494-ff7697ef-33ae-47ba-a95c-45e9c4779cf0.png">

<img width="1053" alt="Screen Shot 2021-11-11 at 02 37 35" src="https://user-images.githubusercontent.com/14099508/141215929-9a6783b6-54a6-4179-821f-2a81376a2f66.png">

**Comment by josevalim** [comment]
It is not "normal", but it is expected. A language usually works in two steps, first you tokenize to create tokens, and then you parse them. So the confusion here may be arising that you are not actually terminating those strings. For example, this code:

<img width="200" alt="Screenshot 2021-11-11 at 09 11 28" src="https://user-images.githubusercontent.com/9582/141261825-97f2870f-c3b8-410b-ac15-22d23d756758.png">

The string in the first line does not terminate because you escape the quotes, so it is actually equivalent to:

```elixir
<<"
SOME
LONG
STRING
"
```

and not different from:

```elixir
iex(1)> <<"
...(1)> this
...(1)> string
...(1)> )_(*&ˆ%$S#%ˆ&*()
```

Then when you close one string, you immediately proceed to open up another string and so on. For example, what you are writing in those examples is something like this:

```elixir
<<
  "WEIRD STRING1"
  "WEIRD STRING2"
```

Of course, having one string after another as above is invalid, but the parser is the one to say so. The parser is only invoked when you close the `>>`, which you never do. So the only chance for it to stop before is if you have an invalid token, such as an invalid heredoc, `$`, etc. For example:

```elixir
iex(1)> <<"
...(1)> this
...(1)> string
...(1)> )_(*&ˆ%$S#%ˆ&*()
...(1)> "
...(1)> $
** (SyntaxError) iex:6:1: unexpected token: "$" (column 1, code point U+0024)
    |
  6 | $
    | ^
```

**Comment by alaadahmed** [comment]
Thanks a lot for this very clear explanation and for your time.
