### ISSUE TITLE
Wrong new line placement for anonymous function

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#11469]
Take this code:

```elixir
Macro.to_string(
  quote do
    capture_log(fn ->
      {:ok, pid} = Repl.start_link({self(), opts})
      assert Exception.message(error) =~ msg
    end) =~ msg
  end
)
```

It will render as:

```elixir
capture_log(fn -> {:ok, pid} = Repl.start_link({self(), opts})
  assert Exception.message(error) =~ msg end) =~ msg
```

Note the lack of breaks after `->`.

@doorgan, in case you want to take a look! Otherwise I will do it later on. :heart:

**Comment by doorgan** [comment]
I took a look at it, it seems that the culprit is this line:
https://github.com/elixir-lang/elixir/blob/97ac2742f724494b1d3b55c30639a1e7e631db37/lib/elixir/lib/macro.ex#L960
It's not producing newlines because the max line length is set to `:infinity`, setting a value like `98` solves the issue.

Should we set a new line there?
Doing so causes the following tests to fail due to formatting discrepancies, though we just need to fix the tests here:
https://github.com/elixir-lang/elixir/blob/97ac2742f724494b1d3b55c30639a1e7e631db37/lib/elixir/test/elixir/kernel_test.exs#L726-L727
https://github.com/elixir-lang/elixir/blob/97ac2742f724494b1d3b55c30639a1e7e631db37/lib/elixir/test/elixir/kernel_test.exs#L757-L758

**Comment by josevalim** [comment]
@doorgan good find. If this is depending on new line, then I would say there is another bug lurking somewhere. That should always be break and not depend on newlines. I will investigate. :) The max_length would be nice to support anyway too.
