### ISSUE TITLE
`String.replace/3` crashes if `pattern` is an empty list

### ISSUE THREAD

**Issue by doorgan** [elixir-lang/elixir#11485]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 24 [erts-12.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.13.0 (compiled with Erlang/OTP 24)
```
* Operating system: Ubuntu 20.04

### Current behavior
Passing an empty list as the pattern makes the function crash:
```elixir
iex(1)> String.replace("foo", [], "")
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a valid pattern

    (stdlib 3.16) :binary.matches("foo", [])
    (elixir 1.13.0) lib/string.ex:1521: String.replace_guarded/4
```

In my particular use case, the pattern list is generated from an unrelated piece of code, and then passed to `String.replace/3`. Currently I have to do this to make it a no-op on empty lists:
```elixir
updated_text =
  if patterns != [] do
    String.replace(text, patterns, "")
  else
    text
  end
```

### Expected behavior

An empty list of patterns should behave the same way as a pattern that never matches:
```elixir
iex(1)> String.replace("foo", [], "")
"foo"
```

It's not a big deal but I'm not sure if this is by design or not :slightly_smiling_face:

**Comment by ericmj** [comment]
I agree, we should return the original string if the list of patterns is empty. If anyone would like to send a PR for this it would be appreciated.

**Comment by josevalim** [comment]
@ericmj the reason it raises is because all lists are compiled to patterns via `:binary.compile_pattern/1`. Therefore, by allowing empty lists, we would behave slightly different from Erlang. Which may be fine, but it may also cause problems in the future.

If we want to go ahead with this, then we also need to change `contains?/2`, `ends_with?/2`, `split/3`, `splitter/3`, `starts_with?/2`. Part of me feels the right way to go about this is to support empty lists in Erlang's compile pattern. Note we already have other limitations, such as you can't give an empty binary inside the list of patterns.

Thoughts?

**Comment by v0idpwn** [comment]
Perhaps this could be changed upstream in erlang?

**Comment by josevalim** [comment]
> We have already deviated from the :binary.compile_pattern/1` when we accepted an empty string a valid pattern.

I disagree with this because we also accept regexes and regexes are not valid patterns either. The relationship to me, however, is that the list is always given to `compile_pattern`, but this will no longer be true if we apply these changes.

**Comment by eksperimental** [comment]
> > We have already deviated from the :binary.compile_pattern/1` when we accepted an empty string a valid pattern.
> 
> I disagree with this because we also accept regexes and regexes are not valid patterns either. The relationship to me, however, is that the list is always given to `compile_pattern`, but this will no longer be true if we apply these changes.

It is a matter of interpretation. There is too much overlapping in part due to the limitation of typespecs. As of now,  `t:String.pattern/0` is defined as `String.t() | [String.t()] | :binary.cp()` what I understood from that is an empty string is part of pattern, but based on your comment I see that it is not, and that empty strings are covered by `String.t()` from the function spec itself.
We should probably make a clarification in the typedoc of pattern/0 saying  that no empty strings is allowed.

**Comment by josevalim** [comment]
I think at the moment there are too many open questions to choose a direction, so I will go with the inertial decision of keepig it as is.

@eksperimental a PR that updates the typespec for `pattern` is very welcome.

**Comment by eksperimental** [comment]
Thank you @doorgan for reporting this,

It has brought all these improvements to the String module.
- https://github.com/elixir-lang/elixir/pull/11488
- https://github.com/elixir-lang/elixir/commit/458f2146d7d3ba5c7d7a884e7254a8a0e6d9466a
- https://github.com/elixir-lang/elixir/commit/a2c6f8bd54db31e7b2ee783e32266fd4f7481234
- https://github.com/elixir-lang/elixir/pull/11492
