### ISSUE TITLE
Dialyzer `overlapping_contract` error for overridden function

### ISSUE THREAD

**Issue by tank-bohr** [elixir-lang/elixir#11574]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

```
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
Elixir 1.13.2 (compiled with Erlang/OTP 22)
```

* Operating system: `Linux 5.13.0-25-generic Ubuntu SMP x86_64 GNU/Linux`

### Current behavior

```
defmodule ParentMod do
  defmacro __using__(_opts) do
    quote do
      @spec function_with_spec :: no_return
      def function_with_spec() do
        raise "define me"
      end

      defoverridable function_with_spec: 0
    end
  end
end

defmodule ChildMod do
  use ParentMod

  @spec function_with_spec :: :ok
  def function_with_spec() do
    :ok
  end
end
```

When I run dialyzer for this module, I get an error

```
overlapping_contract
Overloaded contract for ChildMod.function_with_spec/0 has
overlapping domains; such contracts are currently unsupported and
are simply ignored.
```

### Expected behavior

Spec in child module should override the parent one as well as function per se.

**Comment by josevalim** [comment]
Yes, we do not remove the specs when you mark the function as overridable. That's because if we did so, we would remove the specs in cases where someone is using defoverridable simply to refine a function. There is no way we can support both cases at the same time without breaking the other, so we have no plans to change it.

My advice would be to remove the defoverridable function altogether. You don't need a default implementation for something that will fail, let it not exist and then it will naturally fail. Alternative don't define a spec if you expect someone to completely override its meaning. 

Thanks!

**Comment by tank-bohr** [comment]
Hey @josevalim. Thank you for your instant reply. You are awesome! To be honest I couldn't come up with such savage stuff myself :)
But I have to deal with it because freshly generated phoenix app has such defoverridable [here](https://github.com/phoenixframework/phoenix_view/blob/45020d7960eb3e2e2100fdd589f3a01e399d4987/lib/phoenix/template.ex#L153-L156)

Thus I cannot introduce a correct spec for this function. Which is not good. But Phoenix code looks legit, so I thought it's an elixir bug :shrug:

**Comment by josevalim** [comment]
Please send a PR to remove that `@spec` from Phoenix and copy me!
