### ISSUE TITLE
Elixir is collapsing small floats

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/elixir#11645]
I'm on OTP 24 and Elixir 1.13.1

Collapsing long run-off floats makes sense for readability but I wasn't expecting this:

```elixir
iex> 7593.75 + 506.25
8.1e3
```

The answer should be `8100.0`. But Elixir is collapsing it to the less readable scientific notation that should be reserved for much larger values.

**Comment by bcardarella** [comment]
A bit more context, something is strange about `8100.0`:

```elixir
iex> 8100.0
8.1e3

iex 7999.0
7999.0

iext> 8101.0
8101.0
```

**Comment by bcardarella** [comment]
This is likely the culprit:

```elixir
iex(13)> :erlang.float_to_binary(8100.0)
"8.10000000000000000000e+03"
```

**Comment by josevalim** [comment]
We use an algorithm that emits the shortest possible representation. `8.1e3` is shorter than `8100.0` but `8.101e3` is not shorter than `8101.0`. Shortest can be beneficial in situations like sending payloads over the wire and this behaviour comes directly from Erlang. Perhaps there could be an option to prefer the full format up to a certain value but I feel whatever value we pick will be a random choice in contrast to a well-defined algorithm we have today.

/cc @DianaOlympos

**Comment by josevalim** [comment]
We could also keep the shortest in the `to_string` conversion but use the decimal format in inspect for absolute values between >= 1.0 and < 1.0e16. 1.0e16 is the cut-off as any number above 1.0e16, even with no decimal places, has loss of precision.

**Comment by bcardarella** [comment]
@josevalim is it possible or reasonable to have a flag while in IEx to turn off the truncation?

**Comment by bcardarella** [comment]
Yeah that makes sense. I'm OK either way you decide to go with this, just found it confusing today.

**Comment by DianaOlympos** [comment]
oh god not again... not you fault @bcardarella.

So we the problem here is that there is no good solution. We do use the shortest, the same way erlang does. In OTP 24, this use a private API of OTP, so technically there is no way to add stuff.

In OTP 25, this will use a public API, `float_to_list/float_to_binary/2` with the option `:short`. We could considere adding an additional modifier to this, it would not be _too_ hard, but it would still need to change the BIF and add additional modifiers to it. And it would need to be maintained and make a set of tests that are already highly error prone and edge casey even worse. I would say that i doubt the OTP team would accept it.

At the end of the day, I am also favourable to keeping the current behaviour because i _want_ people to see that this is _not an integer_. I get why we keep wanting people to not be surprised, but floats do not work like people tend to think they do and their string representation is barely linked to their "input" representation. I prefer usually to make people do double take than try to push them into false confidence.

For the record, erlang _already_ make things "non shortest" in one case, when something that could be represented as an integer is bigger than 2**53, we force the "exponent" form, to try to make people understand these are _not integers_. This was changed in OTP 23 iirc

**Comment by josevalim** [comment]
@DianaOlympos to make sure we are on the same page, this is not a precision issue. The question is: should we collapse into scientific mode numbers like `90000.0`? I agree collapsing is good for JSON but do we need to collapse it in IEx? I would say the answer is no. :)

**Comment by josevalim** [comment]
AFAIK this would work:

    abs = abs(float)

    with true <- abs >= 1.0 and abs < 1.0e16,
         {num, 1} <- Float.ratio(float) do
      Integer.to_string(num) <> ".0"
    else
      _ -> Float.to_string(float)
    end

**Comment by DianaOlympos** [comment]
You will have to handle the sign too and i suppose... i thought you meant adding an option under the hood but if you want it to live in iex.

I am just wary of having iex be a special case in term of consistency. "Why does the shell give different answer than IO.inspect()" is a question we do not have too much rn and i like that ^^'

**Comment by josevalim** [comment]
The above code handles the sign. I was actually thinking about changing `Inspect` itself, so we may have the question about why `to_string` and `inspect` returns different things, but they do differ frequently.

Then the last remaining question is if this is worth it and if it will make things clearer. To me `8000.0` is quite clearer than `8.0e3`.

**Comment by bcardarella** [comment]
Could this be a setting that users can opt into? That way the default is consistent.

**Comment by josevalim** [comment]
I don't think we should gate this behind an option. Or we believe it is useful to everyone, or we don't support it. :)

**Comment by josevalim** [comment]
Oh, a much simpler conditional check would be ` abs >= 1.0 and abs < 1.0e16 and trunc(float) == float`.
