### ISSUE TITLE
Bring build_embedded: Mix.env() == :prod back to mix new or deep copy syminks

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#11715]
When we added releases to Elixir, we made it so if priv or ebin were symlinks, they would be deep copied to a release, removing the need for `build_embedded: true` in `mix.exs`.

However, new projects like EXLA have symlinks inside `priv/xyz` pointing to the `deps/exla/cache` folder, which means that the release won't assemble if the symlinks are not copied recursively.

We have two options here:

1. Deep copy symlinks when building a release. There is an issue that we may copy something that should remain a symlink, but then we can have an allow/deny mechanism

2. Bring back `build_embedded: Mix.env() == :prod` to `mix.exs` so production builds copy all symlinks by default. Then change both EXLA/Torchx to respect the `:build_embedded` option

/cc @fhunleth @mobileoverlord

**Comment by josevalim** [comment]
My preference is approach 1. It is the one that pushes the least to library authors and users.

**Comment by fhunleth** [comment]
Since you tagged me, I feel like have to mention that I'm uneasy about any library storing build products under `deps`. I regularly send PRs to libraries to change this, since native code under `deps` usually doesn't get rebuilt when changing `MIX_TARGET`. This causes confusion with Nerves and people start adding `rm -fr deps _build` to their development cycle as a workaround.

Back to the issue, I can't recall seeing other libraries symlinking outside of `priv`, so I'm currently focused on the EXLA use case.

The EXLA case is for caching prebuilt xla downloads. Symlinking is used at https://github.com/elixir-nx/nx/blob/main/exla/Makefile#L41-L49 presumably since copying would take an annoyingly long time. Maybe it's just the download that takes a long time and untarring directly to `priv` if it didn't exist wouldn't be bad?

I know that EXLA doesn't work with Nerves yet, but in the future when it does, the cache will need to hold multiple copies of xla for whatever target platform is being built for at the time. Maybe it already does this and I missed it. 

Nerves also downloads and caches pre-built binaries. I wonder if that's what other libraries would be doing that would otherwise symlink to `deps` as well?

If so, then maybe another option would be to add a way to download and cache large binary blobs with `Mix` and encourage library authors to use that instead of rolling their own?

Ignoring all of that commentary, option 1 seems harmless to me. Honestly, option 2 doesn't seem bad either. I feel like you'd expect `MIX_ENV=prod` to enable `:build_embedded` if the `:build_embedded` part actually affected the build for the library anyway.

**Comment by josevalim** [comment]
Perfect. We will go with 1 for now. @wojtekmach mentioned he will tackle it.
