### ISSUE TITLE
Elixir compiler does not pick up changes in external resource in mix.exs

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11761]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  Any knonw Elixir/OTP  version
* Operating system: Linux / Windows

### Current behaviour

Originally reported in https://github.com/phoenixframework/phoenix/pull/4791#discussion_r851766726 by @cw789 

mix.exs
```elixir
  # @external_resource version_path = "VERSION"
  version_path = "VERSION"
  @version File.read!(version_path)

  def project do
    [
      app: :debug_me,
      version: @version,
     ...
    ]
  end
```

if you update `VERSION` and run `mix compile` the version does not get updated.

Here's a sample repo: https://github.com/eksperimental/debug_me/tree/mix_not_recompiles

Apparently this feature has never worked in Elixir
- with external_resource: https://github.com/eksperimental/debug_me/runs/6055378901?check_suite_focus=true
- neither without it: https://github.com/eksperimental/debug_me/actions/runs/2180695163

Here's the script that checks for it.
https://github.com/eksperimental/debug_me/blob/db6e04feeab1f29c4dbddd5a100c40661c7e93fe/check.sh

### Expected behaviour
To pick up changes either with external resources set or not.

**Comment by wojtekmach** [comment]
You can see it works as expected if you make this change to your Mix project:

```diff
  def project do
+   IO.inspect(@version)
+
    [
      app: :debug_me,
```

it looks like it is not working because of this:

```elixir
defmodule Mix.Tasks.DebugMe do
  use Mix.Task

  @version Mix.Project.config()[:version]
# ^^^^^^^^
```

(https://github.com/eksperimental/debug_me/blob/db6e04feeab1f29c4dbddd5a100c40661c7e93fe/lib/mix/tasks/debug_me.ex#L4)

You're fetching the Mix version _at compile time_. So the next time you compile your project, this particular module will not be recompiled and thus the module attribute won't change and you'll have stale value. I believe Elixir never added a compile-time dependency to `mix.exs` when it saw `Mix.Project`. Don't fetch the project version at _compile-time_, do it at _runtime_:

```elixir
defmodule Mix.Tasks.DebugMe do
  use Mix.Task

  def run(_) do
    IO.inspect Mix.Project.config()[:version]
  end
```

**Comment by eksperimental** [comment]
Yes @wojtekmach it was that!
Thank you.

Another solution that could be more performant is to add `@external_resource "VERSION"` to the Task module.
