### ISSUE TITLE
extra_applications does not affect application start order in mix releases

### ISSUE THREAD

**Issue by dvic** [elixir-lang/elixir#11872]
### Current behavior

Adding applications to `extra_applications` only affects the start order of apps when using `mix` and it does not affect the application start order in a mix release (i.e., the `.rel` files is not changed).

### Expected behavior

I expect that `extra_applications` affects also the ordering of the apps in a mix release, so that when it works locally with mix, it works also, without any extra config, in mix releases.

I stumbled upon this when working with `opentelemetry` https://github.com/open-telemetry/opentelemetry-erlang/pull/399#issuecomment-1136754234 and opened a PR with instructions how to make it work: https://github.com/open-telemetry/opentelemetry-erlang/pull/399/files#diff-80d32354ec7bef9afa2dec72e9c79d7e9b75abea54dbb605547ac743db1cf3cdR45-R70.

I just wanted to make sure that this is working as intended or that it's desirable to change this behavior in future elixir versions.

**Comment by josevalim** [comment]
@dvic quick question: does it work if you list `opentelemetry_exporter` as the first dependency?

**Comment by dvic** [comment]
> @dvic quick question: does it work if you list `opentelemetry_exporter` as the first dependency?

Yes I tried that before and it also seems to do the trick locally with mix but not with releases.

**Comment by dvic** [comment]
> > @dvic quick question: does it work if you list `opentelemetry_exporter` as the first dependency?
> 
> Yes I tried that before and it also seems to do the trick locally with mix but not with releases.

Basically, locally with mix, the order of the listed dependencies matches one-on-one with the `applications` list in ` _build/dev/lib/my_app/ebin/my_app.app`

**Comment by tsloughter** [comment]
Note that we document that the user should do this in the release configuration: https://github.com/open-telemetry/opentelemetry-erlang#design -- because the app ordering can't be relied on by release tools and shouldn't be relied on by users.

But this is a more acceptable solution for Erlang users because a `relx` config is required to build a release while with `mix` it is not and you can build a release based on the defaults of the release being named the same as the app/project.

**Comment by dvic** [comment]
Oh wow, totally missed that :D
