### ISSUE TITLE
mix xref graph is only showing first level of dependencies

### ISSUE THREAD

**Issue by timgent** [elixir-lang/elixir#11956]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 24 [erts-12.3.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.13.4 (compiled with Erlang/OTP 23)
```

### Operating system

MacOS Monterey 12.1

### Current behavior

Repo with demo and explanation of the issue here - https://github.com/timgent/xref_playground

The setup is:

- `DepsTest` has a compile dependency on...
- `DepsTest.A` which has a runtime dependency on...
- `DepsTest.B` which has a runtime dependency on...
- `DepsTest.C` which has a runtime dependency on...
- `DepsTest.D`

`mix xref graph --sink lib/deps_test/d.ex` (for example) is only showing one level of dependency in the graph.

```
lib/deps_test/a.ex
└── lib/deps_test/b.ex
lib/deps_test/b.ex
└── lib/deps_test/c.ex
lib/deps_test/c.ex
└── lib/deps_test/d.ex
lib/deps_test/deps_test.ex
└── lib/deps_test/a.ex (compile)
```

### Expected behavior

With Elixir 1.10 I get a more complete output:
```
lib/deps_test/a.ex
└── lib/deps_test/b.ex
    └── lib/deps_test/c.ex
        └── lib/deps_test/d.ex
lib/deps_test/b.ex
lib/deps_test/c.ex
lib/deps_test/deps_test.ex
└── lib/deps_test/a.ex (compile)
```

Though I still feel that the graph following `lib/deps_test/deps_test.ex ── lib/deps_test/a.ex (compile)` should have the full graph back to `d.ex`. i.e.

Ideal output:

```
lib/deps_test/a.ex
└── lib/deps_test/b.ex
    └── lib/deps_test/c.ex
        └── lib/deps_test/d.ex
lib/deps_test/b.ex
lib/deps_test/c.ex
lib/deps_test/d.ex
lib/deps_test/deps_test.ex
└── lib/deps_test/a.ex (compile)
    └── lib/deps_test/b.ex
        └── lib/deps_test/c.ex
            └── lib/deps_test/d.ex
lib/xref_playground.ex
```

Thoughts appreciated! I wasn't 100% sure if this was intentional or a bug.

**Comment by josevalim** [comment]
The whole graph is there. The current output is saying exactly the same as your text:

```
a depends on b  
b depends on c
c depends on d
```

However, the issue is that the terminal (and those lines) are not really good for representing trees. The previous approach generated too deep trees, which were hard to read. The current approach generate flats, which are also hard to read. But the current approach has one benefit: it makes it easy to see all dependencies of a given file, as you can look at each file directly, while before you could get this:

```
lib/deps_test/a.ex
└── lib/deps_test/b.ex
    └── lib/deps_test/c.ex
        └── lib/deps_test/d.ex
└── lib/deps_test/e.ex
```

And that was _even harder_. :)
