### ISSUE TITLE
Downcase URI host 

### ISSUE THREAD

**Issue by lorenzomar** [elixir-lang/elixir#11975]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.13.4 (compiled with Erlang/OTP 25)

### Operating system

macOS Monterey 12.4

### Current behavior

URI module execute a downcase of `scheme` but let `host` as is. Bak in 2013 PR https://github.com/elixir-lang/elixir/pull/1056 already fixed the issue.

```
iex(2)> URI.new("HTTP://hoSt.com")
{:ok,
 %URI{
   authority: nil,
   fragment: nil,
   host: "hoSt.com",
   path: nil,
   port: 80,
   query: nil,
   scheme: "http",
   userinfo: nil
 }}
```

### Expected behavior

According to [rfc3986#section-3.2.2](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2) I would expect `host` to be turned to lowercase.

I'm quite new and maybe there is some historical decision that I am missing but I think that URI module should behave as described on RFC in order to avoid extra work.

**Comment by josevalim** [comment]
Unfortunately the rules for hosts, because they are beyond ascii, are actually more complex than simply downcasing. For example, do you downcase according to which rules? Also, characters have to be normalized before, not only according to Unicode, but also according to IDNA. What is the order of those operations?

Due to the complexity, we don't perform those operations by default, and those who need it can bring it an external library for so.
