### ISSUE TITLE
Inconsistent code positions reported by tracer

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12023]
### Elixir and Erlang/OTP versions

1.13.4

### Operating system

all

### Current behavior

Compile tracer reports columns differently for ordinary calls and captures.
For calls the position is on function (first letter of the function name
```
Some.Module.call(arg)
```
for captures it's on `&` operator
```
var = &Some.Module.call/1
```

### Expected behavior

Positions on captures should be reported on first letter of function name.
Side question: shouldn't we consider introducing new event types for function captures?

**Comment by josevalim** [comment]
@lukaszsamson a PR that makes it consistently point to the first letter would be welcome. Regarding the function capture, instead of introducing a new tracer, we can introduce `capture_meta`, pointing to the meta of the `:&` node in the currently traced events. That's better because there are at least three distinct events inside a `&` (import, local, remote). PRs welcome so we can include them in v1.14!
