### ISSUE TITLE
Wrong code generated by formatter from v1.14

### ISSUE THREAD

**Issue by Ljzn** [elixir-lang/elixir#12199]
### Elixir and Erlang/OTP versions

% iex -v                         
Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

IEx 1.15.0-dev (b1987c7) (compiled with Erlang/OTP 24)

### Operating system

MacOS

### Current behavior

This problem occurs in elixir v1.14 and later.

Create a module and copy this code into that:

```elixir
  def pad_leading(bytes, count) do
    case count - byte_size(bytes) do
      padding when padding >= 0 ->
        <<0::padding*8, bytes::binary>>

      _ ->
        raise ArgumentError, "Invalid binary size"
    end
  end
```

run `mix format`, the result would be like:

```elixir
  def pad_leading(bytes, count) do
    case count - byte_size(bytes) do
      padding when padding >= 0 ->
        <<0::padding()*8, bytes::binary>>

      _ ->
        raise ArgumentError, "Invalid binary size"
    end
  end
```

### Expected behavior

Formatter not generate wrong code.

**Comment by josevalim** [comment]
I think we can fix this one by stopping the normalization on both sides of `*`, right @sabiwara?

**Comment by sabiwara** [comment]
Oh, sorry, I didn't know about the `*` [shortcut syntax](https://hexdocs.pm/elixir/1.14.1/Kernel.SpecialForms.html#%3C%3C%3E%3E/1-unit-and-size) when I implemented this, TIL!
Seems like a good strategy, will try to send over a PR tomorrow 👍

@Ljzn In the meantime, until a version with the fix is released, the [`normalize_bitstring_modifiers`](https://hexdocs.pm/elixir/1.14.1/Code.html#format_string!/2) option can be set to `false` in `.formatter.exs` to disable this.
