### ISSUE TITLE
Devops install experience on Ubuntu 22.04 is broken

### ISSUE THREAD

**Issue by sanford** [elixir-lang/elixir#12247]
### Elixir and Erlang/OTP versions

Hey Jose & Team, I know this isn't a core language issue, but it's a core adoption/Devops/Gettings started docs issue.  

There is no fast path to install Elixir on Ubuntu 22.04.  Making new VMs in production a bit of a challenge.

To reproduce:

* install a fresh Ubuntu 22.04 LTS VM
* follow directions at https://elixir-lang.org/install.html#gnulinux for Ubuntu
* wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
* sudo apt update
* receive:
> E: The repository 'http://binaries.erlang-solutions.com/debian jammy Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

Why?  It seems ESL hasn't updated their repo since April.

Suggestion:
If the Erlang Solutions team is no longer interested in keeping up with LTS releases, then maybe the core Elixir team can figure out a build/hosting solution for .deb packages?  

This is a major stumbling block for people trying to develop on Ubuntu cloud VMs and Windows Subsystem for Linux as well.  

### Operating system

Ubuntu 22.04

### Current behavior

* install a fresh Ubuntu 22.04 LTS VM
* follow directions at https://elixir-lang.org/install.html#gnulinux for Ubuntu
* wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
* sudo apt update
* get:
> E: The repository 'http://binaries.erlang-solutions.com/debian jammy Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

### Expected behavior

A successful install of 1.14 Erlang and Elixir

**Comment by josevalim** [comment]
Hi @sanford,

I will remove the ESL links from the installation page. Unfortunately it is not viable for the Elixir team to maintain packages on several distributions. This is tricky for two main reasons:

1. We could take ownership of the official repositories for Debian / Ubuntu but those always run behind a couple versions, due to stability and due to how LTS are tagged. This is what happens with Python, Ruby, and therefore this won't help you get the latest either

2. Then the alternative is for us to run our own repository but, while I understand this is very important, it is not viable for us to maintain the distribution for Windows, macOS, and several Linux distributions

Therefore we have historically relied on the community to fill in those gaps. There is an open discussion happening on the Erlang Ecosystem Foundation which I recommend you to join and help move forward: https://github.com/erlef/build-and-packaging-wg/issues/59

Thanks!
