### ISSUE TITLE
Warning when module attribute definition is another module attribute definition

### ISSUE THREAD

**Issue by IvanIvanoff** [elixir-lang/elixir#12245]
### Elixir and Erlang/OTP versions

Erlang/OTP 25
Elixir (1.15.0-dev)

### Operating system

MacOS

### Current behavior

```elixir
defmodule Example do
  @list [1,2]
  @extended_list @list ++ [3]
  @unexpected_result @list [3]
  
  def get(), do: {@list, @extended_list, @unexpected_result}
end
```

In the example above the `get/0` function returns `{[1,2], [1,2,3], :ok}`. The problem is that in `@unexpected_result @list [3]` the `++` operator is missing, so `@unexpected_result` gets assigned the result of `@list [3]`, which is just `:ok`. This happens without emitting any warnings.

I only found that I have such a problem after getting an error like `(Protocol.UndefinedError) protocol Enumerable not implemented for :ok of type Atom` when I used some of the `Enum` functions with what I expected to be a list. 

### Expected behavior

I am not aware of any case where such code can be purposefully written, so I think emitting a warning in such cases can be useful.

**Comment by josevalim** [comment]
```
@unexpected_result @list [3]
```

is equivalent to:

```
@unexpected_result(@list [3])
```

Which is the same as setting `@list` with the value `[3]`. The return of `@list [3]` is `:ok`. So your code is actually valid and it has a valid meaning. You can see this because the result is actually:

```
iex(2)> Example.get
{[3], [1, 2, 3], :ok}
```

It probably makes little sense to write it as such in practice, but it can arise from macros, so it should not be something that the compiler rejects. For this reason, it should not raise nor warn.

Thanks for filing an issue and double checking though!
