### ISSUE TITLE
Protocol implementation creating dependecy on protocol definition

### ISSUE THREAD

**Issue by ypconstante** [elixir-lang/elixir#12254]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.2 (compiled with Erlang/OTP 25)

### Operating system

Linux Fedora 35

### Current behavior

When a protocol in implemented for the types Atom, Float, Integer, or Tuple, the protocol definition depends on this protocol implementation

Ex:

`protocol.ex`
```elixir
defprotocol Example.Protocol do
  def run(item)
end
``` 

`lib/protocol_impl.ex` 
```elixir
defimpl Example.Protocol, for: Atom do
  def run(_item) do
    :ok
  end
end
```

Output of `mix xref graph` 
```
lib/protocol.ex
└── lib/protocol_impl.ex
lib/protocol_impl.ex
└── lib/protocol.ex (compile)
``` 

If the protocol is implemented for `Date` we don't have this dependency
```
lib/protocol.ex
lib/protocol_impl.ex
└── lib/protocol.ex (compile)
```

### Expected behavior

Protocol definition shouldn't have dependency on protocol implementation because of their type.

**Comment by josevalim** [comment]
Those runtime dependencies are expected. That's because for the built-in types, the Protocol literally calls `Example.Protocol.Atom.run(_)`.

We may move protocol consolidation from Mix to the compiler, which may give us more flexibility to tackle this, but you can also think that once the Elixir compiler becomes smarter, this runtime relationship still makes sense. For example, imagine you have this implementation:

```elixir
defimpl Example.Protocol, for: Atom do
  def run(item) when is_boolean(item) do
    :ok
  end
end
```

You only support booleans as atoms, so if someone calls `Example.Protocol.run(:atom)`, you may want a warn to be emitted. :) And that requires annotating those runtime dependencies so we can track it all the way up to the callers of the protocol.
