### ISSUE TITLE
Problems with elixir-LS debugger on current master

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12341]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.0-dev (d9450dc) (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

1. When elixir-LS debugger is run on a project in test configuration it crashes with
```
(Debugger) Task failed because an exception was raised:
    ** (Mix.Error) "mix test" is running in the "dev" environment. If you are running tests from within another command, you can either:
```

This is strange. The code setting mix env looks like this
```
if System.get_env("MIX_ENV") do
      String.to_atom(System.get_env("MIX_ENV"))
else
      task = String.to_atom(task)
      Mix.Project.config()[:preferred_cli_env][task] || Mix.Task.preferred_cli_env(task) || :dev
end
```
The project calls `test --trace` mix task, does not set `MIX_ENV` nor override `preferred_cli_env`. `Mix.Task.preferred_cli_env(:test)` returns `nil`.

2. elixir-LS debugger tests fail due to `:i` not being able to set breakpoints.
```
** Invalid beam file or no abstract code: 'Elixir.SomeModule'
```

I believe it is due to recent changes in https://github.com/elixir-lang/elixir/commit/41c1a92371add84f21992747c92f90dab60822fa combined with https://github.com/elixir-lang/elixir/commit/277184535e9d48c17b4b3bceaa5bfbe2175337f2 that the beams are compiled without `debug_info`. Do we now need to inject `test_elixirc_options: [debug_info: true]` into the project config?

### Expected behavior

Not sure. `Mix.Task.preferred_cli_env/1` is deprecated but I expect it to work.
Changes may be needed in elixir-LS debugger so we can force it to generate `debug_info` even in test.

**Comment by josevalim** [comment]
1. Note that Elixir main added a new mechanism for configuring the CLI. See `def cli`. The previous patch had a flaw in that, if the task was not yet compiled and configure to test, we would first compile the project in the default environment and then we would need to recompile it on the `:test` environment according to the preferred env, and that caused bugs. If you change your code to this, you should be fine and backwards compatible:

      Mix.Project.config()[:preferred_cli_env][task] || Mix.Task.preferred_cli_env(task) || @preferred_envs[task] || :dev

Where `@preferred_envs [test: :test, "test.coverage": :test]`.

But in order to be compatible with v1.15, you will need this too:

    project = Mix.Project.get()
    cli = if function_exported?(project, :cli, 0), do: project.cli(), else: []
    cli[:preferred_envs][task] || Mix.Project.config()[:preferred_cli_env][task] || Mix.Task.preferred_cli_env(task) || @preferred_envs[task] || cli[:default_env] || :dev

3. This error happens only to files defined in `_test.exs`, correct? If so, yes, the `debug_info: true` will be required!

**Comment by josevalim** [comment]
@lukaszsamson i will close this for now but if those are not enough, let me know and i will reopen it.
