### ISSUE TITLE
`mix compile` in umbrella does not respect local aliases in apps

### ISSUE THREAD

**Issue by lukyanov** [elixir-lang/elixir#12494]
### Elixir and Erlang/OTP versions

Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.12.3 (compiled with Erlang/OTP 24)

### Operating system

Alpine (docker.io/hexpm/elixir:1.12.3-erlang-24.1.2-alpine-3.13.6)

Tested on Mac OS Ventura as well with local installation.

### Current behavior

I have an umbrealla app. One of the apps in the ubrealla has mix aliases for `compile` and `clean`:
```elixir
  defp aliases do
    [
      clean: ["cmd make -C docs clean", "clean"],
      compile: ["cmd cd docs && make pre-build build", "compile"]
    ]
  end
```

When I run `mix compile` in the umbrella root, the alias `compile` in the local app does not run.
While `mix clean` works as expected (running the alias `clean` properly).

Btw, `mix deps.compile` also respects the alias.

### Expected behavior

Both `mix compile` and `mix clean` in the umbrealla root should respect aliases in the apps.

**Comment by josevalim** [comment]
This behaviour will change per task because it all depends if the task is recursive or not. If the task is recursive, it means it runs inside the children, then the alias work. For `compile`, it really runs in the umbrella, so you can't customize it. However, what you can do, is that you can add to your project config:

    compile: [:docs] ++ Mix.compilers()


And then define "compile.docs", and it should always be picked. Note you will need to return something like :ok | :noop though.
