### ISSUE TITLE
Keyword.merge doesn't validate kw lists if either is empty

### ISSUE THREAD

**Issue by jakub-gonet** [elixir-lang/elixir#12525]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Mac

### Current behavior

Currently, `Keyword.merge` has optimised branches when either of passed lists are empty.
```elixir
  def merge(keywords1, []) when is_list(keywords1), do: keywords1
  def merge([], keywords2) when is_list(keywords2), do: keywords2

  def merge(keywords1, keywords2) when is_list(keywords1) and is_list(keywords2) do
   # ...
  end
```

Problem arises when you pass incorrect kw list to this function:
```
iex(1)> Keyword.merge([], [1])
[1]
```

This problem was originally discovered after `Repo.all(Schema, ids)` didn't crash but started pulling all data from the DB. 
This was caused by current [`prepare_opts` behavior which ignores incorrect options.](https://github.com/elixir-ecto/ecto/blob/7c0e4211f64f8e230ac2314c02b45f18eafd0802/lib/ecto/repo.ex#L264)

Probably using `Keyword.validate!` in Repo functions for options would be nice. Let me know if Elixir versions supported by Ecto allows this (as this is quite recent addition to the Elixir API) and if you're interested. I can give my take on it.

### Expected behavior

I'd expect it to raise an error.

**Comment by josevalim** [comment]
Correct. It is not guaranteed that Keyword will validate all inputs. Other functions are also optimized. It is your guarantee to make sure the keywords are valid upon creation.

I don't think `Ecto` can you use Keyword.validate! because some of the keys depends on the adapter but it could likely do a small check if the first element of the list is a tuple when non-empry.
