### ISSUE TITLE
wrong match?/2 usage with &() should trigger a warning

### ISSUE THREAD

**Issue by lud-wj** [elixir-lang/elixir#12612]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.4 (compiled with Erlang/OTP 25)

### Operating system

ubuntu

### Current behavior

I am mistaken when using the `match?/2` macro as I often put the data first and the pattern in second position.
Today I did that directly with the `&` construct, like this:

```elixir
  def collect(data) do
    Enum.filter(data, &match?(&1, {:ok, %{type: :data}}))    
  end
```

This gives the equivalent erlang code:

```erlang
collect(_data@1) ->
    'Elixir.Enum':filter(_data@1,
                         fun (_@1) ->
                                 case {ok, #{type => data}} of
                                     _@2 -> true;
                                     _ -> false
                                 end
                         end).
```

Which basically boils down to a constant function that retuns `true`.

### Expected behavior

This form should emit a compilation warning.

`match?/2` works well with the pin in a `fn`:

```elixir
Enum.filter(data, fn arg -> match?(^arg, {:ok, %{type: :data}}) end)
```

And without the pin, a warning is emitted:

```elixir
Enum.filter(data, fn arg -> match?(arg, {:ok, %{type: :data}}) end)
```

> variable "arg" is unused (there is a variable with the same name in the context, use the pin operator (^) to match on it or prefix this variable with underscore if it is not meant to be used)

As the following is a valid form:

```elixir
Enum.filter(data, &match?(^&1, {:ok, %{type: :data}}))
```

The same without the pin should emit a warning.

**Comment by josevalim** [comment]
Thank you for the report!

This is tricky. The warning above is emitted by `case` because it seems a variable is defined but never used. `match?(&1)` doesn't raise because the variable is meta-generated. We could add a warning to `match?`, but it would ultimately be a different one than the `case` one. So we have two options:

1. Don't mark the variables generated by &1 as meta-generated (we can try but we may have side-effects)
2. Add a warning to `match?` special casing `&1`, which I am not the biggest fan

We can try option 1 but I would do it after we branch out v1.15 cause I want it to live in main for a while before a future release.

**Comment by lud-wj** [comment]
That seems reasonable :)

**Comment by lud-wj** [comment]
Thank you :)
