### ISSUE TITLE
Code formatted on Elixir 1.14 is considered ill-formatted by 1.15

### ISSUE THREAD

**Issue by michaelklishin** [elixir-lang/elixir#12756]
### Elixir and Erlang/OTP versions

Elixir: 1.14.5, 1.15.2, running on Erlang 25.3.x or 26.x. I don't think the specific patch versions matter here.

### Operating system

macOS, Linux

### Current behavior

When `mix format` is used on [RabbitMQ CLI tools](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_cli) on Elixir 1.14, then `mix --check-formatted` on 1.15.2 will fail as if the code was ill-formatted.

Maybe this is expected, but it is very annoying to developers who support multiple Elixir release series. They will have to require 1.15 everywhere, and it can be a hell of a headache to provision the latest and greatest Elixir on some older distributions, for example.

### Expected behavior

`mix --check-formatted` on Elixir 1.15 accepts what `mix format` on 1.14 produces.

**Comment by josevalim** [comment]
Yes, this is intentional. We should be able to evolve and fix bugs. Especially this release that fixes a bug where the line length was not respected.

What I do in my projects is to run the formatter only on the latest Elixir version on CI. That's even easier with v1.15 because it will show the precise diff of what is not formatter, so you can fix those diffs via GitHub Edits, without having to install latest Elixir. :)

**Comment by michaelklishin** [comment]
Yup, running formatting checks on the latest version is indeed what we ended up doing. Thank you for clarifying.
