### ISSUE TITLE
mix test with multiple files and line numbers

### ISSUE THREAD

**Issue by azizk** [elixir-lang/elixir#12823]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.2 (compiled with Erlang/OTP 25)

### Operating system

NixOS

### Current behavior

```sh
mix test test/first_test.exs:10 test/another_test.exs:20
```
Error:
```
** (Mix) Line numbers can only be used when running a single test file
```

### Expected behavior

Should run both tests in separate files.

CircleCI now supports [repeating failed tests](https://circleci.com/docs/rerun-failed-tests/). I reworked our pipeline and was surprised that `mix test` doesn't let us run specific tests from multiple files and I think it's an issue. All tests from the file will be rerun, not just the failing ones. This will take longer than it needs to and flaky tests may fail that didn't in the previous run.

**Comment by josevalim** [comment]
This is really a feature request but I have one idea I can try it out to implement this. Otherwise we might close this as it is indeed not supported today (and it raises accordingly).

You may also try to do `mix test --failed`, if it uses the same disk cache, or `mix test test/first_test.exs:10 && mix test test/another_test.exs:20` although that will boot the app several times.

**Comment by josevalim** [comment]
For those willing to implement this, the idea is to convert `mix test test/first_test.exs:line` into `--only location:file:line`. We can introduce a function called `ExUnit.Filters.parse_paths` which returns `{[files], exclude: [:test], include: [location: {file1, line1}, location: {file2, line2}]}`. Then `ExUnit.Filters.eval` needs to handle `{:location, {file, line}}` (and we already have the logic for handling the line bits).

**Comment by josevalim** [comment]
It may also be worth breaking this work in two parts:

1. The first one is to change `parse_path` to return `{:location, ...}` tags instead of `{:line, ...}`, without introducing `parse_paths` and without changing `mix test`

2. Then you introduce `parse_paths` and change `mix test` accordingly

---

Btw, once we introduce `parse_paths`, we can rewrite `ExUnit.Filters.parse_path` in favor of it:

```elixir
def parse_path(file) do
  {[file], opts} = parse_paths([file])
  {file, opts}
end
```
