### ISSUE TITLE
mix release: runtime.exs doesn't load permanent apps

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#12853]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.2 (compiled with Erlang/OTP 26)
```

### Operating system

Linux

### Current behavior

* When release is started like `bin/my_app start_iex`, applications set as `permanent` in `def releases` in `mix.exs` are loaded during evaluation of `runtime.exs`.
* When command is executed like `bin/my_app eval "IO.inspect :hey"`, applications set as `permanent` in `def releases` in `mix.exs` **are not loaded** during evaluation of `runtime.exs`.

Repo with reproduction of the bug: https://github.com/hissssst/release_bug

### Expected behavior

No matter what release subcommand is used, applications marked as permanent must be loaded during evaluation of `runtime.exs`

**Comment by josevalim** [comment]
This is intentional and documented as such: https://hexdocs.pm/mix/Mix.Tasks.Release.html#module-one-off-commands-eval-and-rpc - This is because you may want to run a command, such as database migrations, which should not start the app.

You need to start them explicitly (Application.ensure_all_started).

**Comment by josevalim** [comment]
Oh, config/runtime.exs should not load apps either, because loading apps means their configuration is loaded, and you cannot load their configuration while the system is being configured.

**Comment by hissssst** [comment]
@josevalim reopen it again, please. I understand that you want to close an issue as soon as possible, but please at least give me the time to respond, otherwise it is really annoying.

If loading configuration during `config/runtime.exs` is an incorrect behaviour, then you should remove it from `start_iex`, `start`, `deamon`, etc. commands since they load applications, and then evaluate `runtime.exs`.

This issue is not about specific behavior, but more about consistency of different behaviors.

**Comment by josevalim** [comment]
It reopens as easily as it closes. Think about it as an in-flux state rather than written in stone.

**Comment by josevalim** [comment]
Although I want to apologize for misreading the issue. Multi-tasking got the worst of me today, sorry.

**Comment by josevalim** [comment]
I have checked that all apps are loaded on config/runtime.exs, including on regular Mix, so I will make the beheaviour consistent everywhere.

**Comment by josevalim** [comment]
This has been fixed.

About the opening/closing, think about it as an in-flux state rather than written in stone. Regardless if it is a false report or an actual bug, the goal is to close them quickly. I understand sometimes it can be frustrating because some projects treat closing as the end of the conversation, but that's not the case here.

For example, I will close it once more but, if the fix is incomplete, I will be glad to reopen it once more. :) In this case though, my mistake was reading the issue poorly, all relevant information was there.

**Comment by hissssst** [comment]
Great, thanks for fixing it! :heart:
