### ISSUE TITLE
`quote` as entry breaks the face of a macro inside terminal

### ISSUE THREAD

**Issue by shahryarjb** [elixir-lang/elixir#13010]
I hope that I have not reported a duplicate problem and that I have posted the issue in the right place

When we use `quote` in the entry of a macro. In the terminal, if we put `h` behind it. Its shape is broken.
For example, this can be seen in the `dbg` document

```elixir
defmacro dbg(code \\ quote(do: binding()), options \\ []) do
```

Image
![Screenshot 2023-10-16 at 11 09 56](https://github.com/elixir-lang/ex_doc/assets/8413604/9e7e960b-58d2-4814-aabc-7eb3319f3f8a)

Other macro:
![Screenshot 2023-10-16 at 11 10 28](https://github.com/elixir-lang/ex_doc/assets/8413604/344489b0-fdeb-47d8-bff5-9af1c5da70bb)

Thank you in advance

**Comment by josevalim** [comment]
Yes, please go ahead! :)

**Comment by dinocosta** [comment]
After some investigation it seems that the issue might be caused at compilation time, when generating the documentation for the `.beam` file of the corresponding module.

I say this because, it seems like, simply loading the documentation from the `.beam` file returns the function's signature with newline characters:

```elixir
iex(1)> docs_chunk = [?D, ?o, ?c, ?s]
...
iex(2)> {_module, bin, filename} = :code.get_object_code(Kernel)
...
iex(3)> {:ok, {_module, [{_docs_chunk, bin}]}} = :beam_lib.chunks(bin, [docs_chunk])
...
iex(4)> {:docs_v1, _, _, _, _, _, docs} = :erlang.binary_to_term(bin)
...
iex(5)> {{:macro, :dbg, 2}, _, signature, _, _} = Enum.find(docs, fn {{_, name, _}, _, _, _, _} -> name == :dbg end)
...
iex(6)> IO.inspect(signature)
["dbg(code \\\\ quote do\n  binding()\nend, options \\\\ [])"]
```

Worth noting I'm not super familiar with the specifics on this part, so my assumption might be totally wrong but I'm going to try and understand how the documentation for the function signature is generated for the `.beam` file, maybe some of the characters (or combination of characters) in `Kernel.dbg`'s signature are getting converted to newline characters (`\n`). 

Will report once I have more findings 🔍

**Comment by josevalim** [comment]
I think it is ok for the signature to have multiple lines, we just need to align the background when printing it in the terminal. :)

**Comment by dinocosta** [comment]
Thanks @josevalim ! 

I've managed to get it to print the following by simply splitting the `headings`, in `IO.ANSI.Docs.print_headings/2`, by newline character:

<img width="575" alt="image" src="https://github.com/elixir-lang/elixir/assets/6334322/72d6a38f-43ea-447d-aa22-814dfc120674">

Does this look good to you? I'm thinking that maybe, in cases where the heading has newline characters we should try and align it according to  the first line, keeping the indentation correct, instead of centering horizontally, like this:

```elixir
                         defmacro dbg(code \\ quote do                          
                           binding()                                   
                         end, options \\ [])                               

```

What do you think? :)

**Comment by josevalim** [comment]
Looks great. I would align it as:


```
                         defmacro dbg(code \\ quote do                          
                                    binding()                                   
                                  end, options \\ [])

**Comment by dinocosta** [comment]
Awesome, thank you for the feedback @josevalim ! I'll open a PR shortly so you can review and see if my approach makes sense ⭐️

**Comment by dinocosta** [comment]
@josevalim Here it is - https://github.com/elixir-lang/elixir/pull/13018 ✅

**Comment by shahryarjb** [comment]
> Looks great. I would align it as:
> 
> ```
>                          defmacro dbg(code \\ quote do                          
>                                     binding()                                   
>                                   end, options \\ [])     
> ```

Why can't we fill the whole width?
@josevalim @dinocosta
