### ISSUE TITLE
iex.bat in Powershell

### ISSUE THREAD

**Issue by moacirbishopcamata** [elixir-lang/elixir#13015]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.6 (compiled with Erlang/OTP 26)

### Operating system

Windows 10 Home

### Current behavior

A good job to everyone.

As a suggestion, I suggest renaming the iex.bat file to iexw.bat in the Window platform distribution, since 'iex' is a feature 'Invoke-Expression cmdlet for Powershell'.

It's a silly change, but it helps a lot for beginners on this platform.

Grateful for the attention.

exe.: in Powershell
 iex

cmdlet Invoke-Expression na posição de comando 1 do pipeline
Forneça valores para os seguintes parâmetros:
Command:

### Expected behavior

 iexw
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.6) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>

**Comment by josevalim** [comment]
We tell users to type `iex.bat` but you are right that `iexw` is more concise. I suggest `wiex`, WDYT?

**Comment by sbuttgereit** [comment]
I'm only an occasional Windows user, so let that temper your read of my comment.

I think iexw would be better both than the status quo and better than wiex.  iexw is easier to type and avoids the collision.  Java had a precedent here in that they have a javaw executable which is why I'd prefer iexw; it's a known pattern that's easier to remember ... At least for anyone using Java and Windows (yes, the reasons for the special Windows versions are different, but I don't think that matters).

**Comment by PatrickLTew** [comment]
As a Windows user, I'd say simply more awareness that `iex` isn't the right command (whether the correct command remains `iex.bat` or is changed) might be something to consider, as understanding why I was getting the error and what to do about it was the more jarring challenge, compared to actually memorising the correct command, when I was an outright beginner.

For me, I wouldn't say changing it is a major need. But, I don't think it is a bad thing - especially if the goal is a concise command that reminds people of the distinction. For that, I'd probably say `wiex` is good, as I think it flows slightly better on a qwerty keyboard, typing-wise.

But I would say, if possible, to make both the `iex.bat` and the potential new command both useable, for people used to the current version?

**Comment by Morotai** [comment]
As a Windows user, wiex works great. Please keep iex.bat around however for those that don't read on the latest changes.

**Comment by simonmcconnell** [comment]
I have no problem with the status quo. `iex` is a PowerShell alias you see pretty often but a lot people still wouldn't be aware of it. `wiex` matches the naming pattern of `werl`, which users of pre OTP26 are likely aware of. 

I don't see how we're going to get around the fact that 99% of examples/tutorials are writing "type `iex -S mix ...`. If they're not already aware of the platform difference, the Windows user is going to be confused the first time they type that. They're going to google it and learn to add .bat. If we add another way to do it, it might be even more confusing.

Agree that `.bat` needs to stay.

**Comment by CharlesOkwuagwu** [comment]
My simple work around for this has been to have my own global .bat files that internally call iex.bat and set other conveniences.

**Comment by sbuttgereit** [comment]
> `wiex` matches the naming pattern of `werl`, which users of pre OTP26 are likely aware of.

I wasn't aware of that precedent.  That being the case and "in the ecosystem" I'd retract my earlier position and support `wiex`.

I do agree with your other point:

`[...] the Windows user is going to be confused the first time they type that.`

When I first tried Elixir on Windows, I ran into the PowerShell naming collision issue and solution to avoid the naming collision suggested here isn't going to solve the main issue: that being you can't just jump into a tutorial or documentation and go.  Having said that `wiex` would still be an improvement, even if only a relatively minor one.

**Comment by cw789** [comment]
I'm fine with all options. Right now I've just added to my `Microsoft.PowerShell_profile.ps1` → `Remove-Item Alias:iex -Force`. Probably that's also a doable thing for other Windows users...

**Comment by OnorioCatenacci** [comment]
It's been a while since I bothered to try to run Elixir under Powershell.  Those times when I need to work on Windows I drop into WSL these days.  But my recollection is that I'd simply bite the bullet and type iex.bat because most of the time if I wanted to use iex I'd fire up a VM on Windows and work it that way.  

I guess Powershell must be getting a lot more love than it used to.  It seemed for a long time there that I was the only Windows developer I knew of that was actively using PS. 

One thing I'd probably downvote slightly:  removing the iex alias.  I think that will just confuse other developers that are accustomed to Powershell.

**Comment by josevalim** [comment]
Thanks everyone for your input. It seems that adding a shorter alias won't necessarily solve the problem (which is `iex` not immediately working) and folks may employ different ideas to keep it working (have their own alias or remove the shortcut), so I believe the best course of action for now may not be technical, but continue improving the docs and references to mention this pitfall. Thank you.
