### ISSUE TITLE
`:error_logger` report handler not called on Elixir 1.15 

### ISSUE THREAD

**Issue by guisehn** [elixir-lang/elixir#13030]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.7 (compiled with Erlang/OTP 25)
```

### Operating system

macOS 12.4

### Current behavior

Starting from Elixir 1.15, when setting up an error handler:

```elixir
:error_logger.add_report_handler(ErrorHandler)
```

And running code that causes a process to crash (e.g. on IEx, via `iex -S mix run`):

```
iex(1)> Task.async(fn -> raise "foo" end)
```

It does not call the `handle_event` callback on `ErrorHandler`.

I'm using the following error handler module:

```elixir
defmodule ErrorHandler do
  @behaviour :gen_event

  def init([]), do: {:ok, []}

  def handle_call(_, state), do: {:ok, state}

  def handle_event(args, state) do
    IO.inspect(args, label: "ERROR HANDLER CALLED")
    {:ok, state}
  end
end
```

With Elixir 1.15, `ERROR HANDLER CALLED` never appears on the console. When testing the same code in Elixir 1.14 with the same OTP version, it does call the error handler and executes the `IO.inspect` call.

In practice, we have noticed that the [Bugsnag global error handler](https://github.com/bugsnag-elixir/bugsnag-elixir/blob/master/lib/bugsnag/logger.ex) which still relies on `error_logger` is not firing in Elixir 1.15.

I noticed looking at the [error_logger docs](https://www.erlang.org/doc/man/error_logger.html) that it is deprecated, but looks like it's still supported. Has its support been removed in Elixir 1.15?

### Expected behavior

When calling `:error_logger.add_report_handler(ErrorHandler)` and raising an error that crashes a process, the `ErrorHandler` module should receive an event.

Example repo: https://github.com/guisehn/error_logger_issue

**Comment by josevalim** [comment]
The repository is not public. :)

**Comment by guisehn** [comment]
> The repository is not public. :)

My bad! 😅 It's public now

**Comment by josevalim** [comment]
Thank you, I had an idea of what was the root cause, but I wanted to be double sure. I believe it was this commit: https://github.com/elixir-lang/elixir/commit/a7c74e254565242f6ecdf14ee1ae0f7ec231139c

I am not sure there is much we can do. If we continue using `:error_logger`, it means everyone else gets a worse error message with less metadata. Plus, it is just a matter of time until Erlang/OTP fully removes it. If we use both, then they are duplicated.

But perhaps the most important is that you were most likely already not getting failures from Erlang's GenServer and other processes, so you need to move away from `error_logger` much sooner than later.

**Comment by guisehn** [comment]
@josevalim thanks for confirming! I'll try to get that updated on the Bugsnag library we're using.

Would it be a good idea to declare this as a breaking change somewhere, maybe in Elixir 1.15 changelogs?

**Comment by josevalim** [comment]
Yeah, I will include it now.
