### ISSUE TITLE
Automatically compute size for <<^var::binary>>

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#13089]
### Elixir and Erlang/OTP versions

All

### Operating system

All

### Current behavior

Currently it fails to compile.

### Expected behavior

It should automatically become `<<^var::binary-size(byte_size(^var))>>` (if the size is not given).

**Comment by josevalim** [comment]
If we do `<<^var::bitstring>>`, then we can compile to `<<^var::bitstring-size(bit_size(^var))>>`.

**Comment by wojtekmach** [comment]
I was just writing the following doctest:

```elixir
iex> url = ReqS3.presign_url(url: "s3://#{bucket}/key1")
iex> "https://#{bucket}.s3.amazonaws.com/key1?X-Amz-Algorithm=AWS4-HMAC" <> _ = url
```

I've written in such a way that does not reveal `bucket`. This obviously doesn't work because can't use interpolations inside matches.

This works today:

```elixir
iex> "https://" <> ^bucket <> ".s3.amazonaws.com/key1?X-Amz-Algorithm=AWS4-HMAC" <> _ = url
```

WDYT about the following?

```elixir
iex> "https://#{^bucket}.s3.amazonaws.com/key1?X-Amz-Algorithm=AWS4-HMAC" <> _ = url
```

In other words, `"...#{^x}..."` could be rewritten to `<<"...", ^x::binary-size(x), "...">>`. I'm not sure if folks would even expect this syntax to work but I think it would be super concise in this (admittedly pretty rare) cases and so I thought I'd mention this anyway!

**Comment by josevalim** [comment]
Interpolations convert to two string, so someone may expect if `bucket` was an integer or something else, it would be automatically handled, but we can't do the conversion inside patterns, so I am a :-1:.
