### ISSUE TITLE
Add CHANGELOG in hexpm

### ISSUE THREAD

**Issue by epinault** [elixir-lang/elixir#13086]
### Elixir and Erlang/OTP versions

I see there is a CHANGELOG.md. Would love ot have it readble from Hex.pm so we can find the changelog to logger . It s missing when upgrading elixir and found out today that the logger had some changes that I was unaware off in 1.15

trying to see how the doc work but it s different than a normal elixir project so not too sure where to start other than reverse engineer the Makefile and see how I can add that file to the list of file to include and convert to HTML?

### Operating system

all

### Current behavior

no Changelog in Hex.pm for logger

### Expected behavior

having it render in hex.pm

**Comment by josevalim** [comment]
The issue is precisely that we have a unified CHANGELOG, because that's both easier to maintain and write, and it would be tricky to have separate CHANGELOGs per each application in Elixir. If someone wants to add a feature to ExDoc that adds links, then we can consider using it, but for now I think unified on GitHub across branches (and on the releaes page) is the best of the trade-offs. :)

**Comment by epinault** [comment]
ah make sense! thank you ! love the tradeoff. Somehow I must have missed the change
