### ISSUE TITLE
warnings for type aliases

### ISSUE THREAD

**Issue by ericbmerritt** [elixir-lang/elixir#1312]
When you have a type alias. That is a type that just renames another type: 

```
@type t :: array
```

Then elixir generates the following warning.

```
opaque type t() is underspecified and therefore meaningless
```

This is bad because type aliasing is a good way to increase the understandability of code.

**Comment by schnittchen** [comment]
Same here. I want to treat warnings as errors, coming from the Ruby ecosystem where everybody gives a squirrel and `-w` means wading through pages of meaningless to harmful noise.

I'm reverting my @opaque to @type now. I thought @opaque was meant to convey to the reader that the repesentation of the type was internal to the module. Since erlang treats it differently, I must be wrong.
