### ISSUE TITLE
IEx colors should be disabled on Windows by default

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#1329]

**Comment by d-led** [comment]
Hi! As some may experience troubles with Ansicon or other windows ANSI emulators, here's an alternative that seems quite stable: [Cmder](http://cmder.net/)

**Comment by OvermindDL1** [comment]
ConEmu also works well (and has far more features, older, stable, etc...), been using console colors (enabled via my .iex file for a long while now) if anyone comes across this.

**Comment by d-led** [comment]
@OvermindDL1 Yep. P.S. Cmder is a wrapper around ConEmu

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Yep. P.S. Cmder is a wrapper around ConEmu

@d-led Ahh, really?  I may have to look at that then, thanks!

**Comment by d-led** [comment]
![cmder](https://cloud.githubusercontent.com/assets/1716584/21814154/a72af340-d758-11e6-9564-8c5e0fa86bee.png)

**Comment by d-led** [comment]
P.S. the Windows 10 console implements ANSI colors:

![image](https://cloud.githubusercontent.com/assets/1716584/23407168/e9976bce-fdc2-11e6-8396-3492fe987bd9.png)

to enable colorization by default on windows, the following [SO answer](http://stackoverflow.com/a/37911985/847349) helps

**Comment by fdbeirao** [comment]
If anyone reaches this thread because you want to enable colors when you run `elixir some_tests.exs`, please do notice that you need to use `ExUnit.start(colors: [enabled: true])`

I am using Windows 10, integrated terminal in vscode, but I couldn't get the test colors neither in cmder nor cmdemu. I came across this read this remark in [Elixir development on Windows 10](https://medium.com/@rpw952/elixir-development-on-windows-10-ff7ca03769d#.xt8fd48jg).

I hope this saves time to someone. Keep up the good work.
