### ISSUE TITLE
Optional umbrella deps starts in mix release

### ISSUE THREAD

**Issue by Ellocsys** [elixir-lang/elixir#13399]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 25)

But also reproduced with Elixir 1.16.1 (compiled with Erlang/OTP 25)

### Operating system

MacOS 13.6.4

### Current behavior

For example, there’s an umbrella project https://github.com/Ellocsys/optional_deps with a dependency graph like this:
```
app_3
└── app_2
    └── app_1 (optional)
```
When building a release with the command `mix release app_3` (release `app_3` include only `[app_3: :permanent]`), the optional dependency `app_1` will be included in the release with a launch type of `:permanent`. 

### Expected behavior

In Elixir 1.14.2 (compiled with Erlang/OTP 25), the same optional dependency (app_1) will be skipped in release, which is consistent with the [documentation](https://hexdocs.pm/mix/1.15.7/Mix.Tasks.Deps.html#module-dependency-definition-options)

**Comment by josevalim** [comment]
Unfortunately I have not considered the combination of optional dependencies as part of umbrella and, now that I think about it (thanks to your report), I am not sure we can actually support it properly.

Think about it like this. When you compile from the umbrella root, here is your dependency tree:

```
+ umbrella
  + app1
  + app2
    +app1 (optional)
  + app3
    +app2
```

According to the dependency system, the umbrella depends on app1, and therefore we hit this condition in the docs "However, if the other project includes the optional dependency on its own, the requirements and options specified here will also be applied".

But the real issue here is that, because umbrellas have a shared `_build`, we cannot really provide two versions of app2, one where app1 is compiled and another to use via app3 because app1 is not included. This will lead all kinds of conflicts and weird behaviour. I can't see a way to solve this besides emitting a warning that :optional does not really work with :in_umbrella. I am sorry.
