### ISSUE TITLE
Inconsistent naming in IO module

### ISSUE THREAD

**Issue by ponychicken** [elixir-lang/elixir#13721]
### Elixir and Erlang/OTP versions

all

### Operating system

all

### Current behavior

`IO.inspect`, `IO.read `etc all use the grammar case "infinitive" (to inspect, to read, etc).
But `IO.puts` uses an inflected form (it puts) instead of the same form.

While most people using Elixir have probably gotten used to this, these inconsistency are small barriers for new people.

### Expected behavior

--

**Comment by josevalim** [comment]
Many of the IO and File functions follow the Unix conventions. In this case, puts stands for put string. While I understand not everyone is familiar with the Unix convention, it was an explicit design decision to follow that rather than introduce a new one, and we don’t plan to change it. If you want, feel free to submit a PR to puts and gets to clarify what they stand for and where they come from. Thanks!
