### ISSUE TITLE
1.18 macro breaking change undocumented

### ISSUE THREAD

**Issue by wkirschbaum** [elixir-lang/elixir#13965]
### Elixir and Erlang/OTP versions

Elixir 1.18.0-dev (7e1aaac) (compiled with Erlang/OTP 27)

### Operating system

Linux

### Current behavior

The following code compiles in 1.17 
```elixir
defmodule Foo do
  defstruct [:value]
end

quote do unquote(%Foo{value: nil}) end
```

and returns :

```
%Foo{value: nil}
```

In Elixir 1.18.0-dev the following error pops up:
```bash
** (ArgumentError) tried to unquote invalid AST: %Foo{value: nil}
Did you forget to escape term using Macro.escape/1?
    (elixir 1.18.0-dev) src/elixir_quote.erl:542: :elixir_quote.argument_error/1
    iex:3: (file)
```

This happens when trying to compile the ex_cldr_numbers package on this line: https://github.com/elixir-cldr/cldr_numbers/blob/main/lib/cldr/number/backend/decimal_formatter.ex#L78

### Expected behavior

I would expect there to be a changelog entry for this, or for it not to break functioning code.

This seems to be the commit: https://github.com/elixir-lang/elixir/commit/cc68ad91cb3d8f96edbc2aeb28e7cbc6a5dfa3dd

**Comment by josevalim** [comment]
`%Foo{}` is not a valid AST. This was always wrong and before it would either work by accident or crash deep inside the compiler. The new error is exactly to help you catch it early rather than later on. :)

And yes, it is completely fine to file reports now, thank you! Just keep in mind we don't keep the CHANGELOG up to date, it gets up to date from time to time (to avoid conflicts as we work).

**Comment by wkirschbaum** [comment]
@josevalim okay great, will do. I see the documentation already states it should not be valid, so adds up. this should change in the package then.
