### ISSUE TITLE
Mix doesn't consider targets properly when doing dependency resolution.

### ISSUE THREAD

**Issue by Damirados** [elixir-lang/elixir#14040]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.1] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]

Elixir 1.17.3 (compiled with Erlang/OTP 27)

### Operating system

Arch linux

### Current behavior

In a case where different targets require different versions of dependencies, dependency resolution will fail.

For example this 2 nerves systems depend on different versions of nerves toolchains. 
mix.exs
```elixir
      {:nerves_system_rpi3, "~> 1.24", runtime: false, targets: :rpi3},
      {:custom_rpi3,
       git: "https://github.com/Damirados/custom_rpi3.git",
       branch: "gcc14-toolchain",
       targets: :custom_rpi3}
    ]
```

Dependency resolution fail:
```
* Getting custom_rpi3 (https://github.com/Damirados/custom_rpi3.git - gcc14-toolchain)
remote: Enumerating objects: 2716, done.
remote: Counting objects: 100% (2716/2716), done.
remote: Compressing objects: 100% (789/789), done.
remote: Total 2716 (delta 1641), reused 2711 (delta 1636), pack-reused 0 (from 0)
Resolving Hex dependencies...
Resolution completed in 0.026s
Because the lock depends on nerves_system_rpi3 1.29.0 which depends on nerves_toolchain_armv7_nerves_linux_gnueabihf ~> 13.2.0, the lock requires nerves_toolchain_armv7_nerves_linux_gnueabihf ~> 13.2.0.
And because your app depends on the lock, nerves_toolchain_armv7_nerves_linux_gnueabihf ~> 13.2.0 is required.
So, because your app depends on nerves_toolchain_armv7_nerves_linux_gnueabihf ~> 14.2.0, version solving failed.
```

Example repo: https://github.com/Damirados/nerves_mix_target_bug

[Here](https://github.com/nerves-project/toolchains/issues/146) is an issue that goes a bit more in detail about expected behavior.

### Expected behavior

Since mix can compile for single target at time, dependency resolution should consider taking target into account.

**Comment by josevalim** [comment]
Thank you for the report!

The dependency resolution always considers all targets at once: this is good because it will force the most shared dependencies possible. If this is getting in the way, my suggestion is to:

1. Have multiple lockfiles per target: `lockfile: "#{Mix.target()}.mix.lock"`

2. Then define the dependency conditionally: `deps(Mix.target())`

IIRC, this is how things worked in the past (except Nerves used `Mix.env()`) and the goals of introducing targets were precisely to make it easier to share and manage, while decoupling from environments at the same time.

@fhunleth, am I remembering it correctly?

**Comment by fhunleth** [comment]
@josevalim Yes, you are remembering correctly. We used to have a lockfile per target. 

Switching to use one shared lockfile was such a developer experience improvement. I really would try my best to not go back, but if there's no other way, then your recommendation is the way for sure.

I do know more about @Damirados's motivation.

This is in response to us recently finding a bug in GCC 14 that affected some Nerves devices. Nerves brings in the cross compiler via a mix dependency that's set per target. The package name is more complicated, but it's effectively `:gcc` with the package version number being `14.2.0` or `13.2.0`. The alternative solution was to create separate `:gcc13` and `:gcc14` packages. Of course, there's a combinatorics issue since Nerves supplies GCC toolchains for 12 architectures so we'd be publishing 12 packages per GCC version. This seemed inelegant enough to explore other options.

One more data point, Mix targets were introduced December, 2018. Since then, I can only think of two cases where this issue has come up. The GCC case is more interesting since if any of the ML or web kiosk software had a good improvement with GCC 14 (sometimes this happens), then updating the officially maintained Nerves systems to use GCC 14, modulo the affected devices, would be desirable.

Hopefully this makes sense.

**Comment by josevalim** [comment]
Thank you! I don't think we can have our cake and eat it too in this case. :(

Perhaps it is a matter of setting a `MIX_GCC` env var and branching the lockfile according to that instead? At least until it gets all ironed out?

**Comment by Damirados** [comment]
This is another situation where things can get tricky.

Currently, if a project has multiple targets and multiple targets depend on the same toolchain.

For example:
```
nerves_project
|- nerves_system_rpi2 target: rpi2 (direct dependency) 
  |- nerves_toolchain_armv7_nerves_linux_gnueabihf v13.x.x (dependency of the system)
|- nerves_system_rpi3 target: rpi3
  |- nerves_toolchain_armv7_nerves_linux_gnueabihf v13.x.x
...
```

If there’s a major version bump in the toolchain (currently tied to the GCC version), all targets that depend on the same toolchain need to be updated in unison.

In cases where custom systems are involved in the project, which is very common.
I can’t simply update one system to test something quickly without first commenting out the other systems. Once I’m satisfied with the new system, I then have to go through the entire process of updating all custom systems and rebuilding them. This can take a considerable amount of time.

For someone working on hobby projects, this can make a huge difference, especially if they have limited time available in their schedule.

 >  The dependency resolution always considers all targets at once: this is good because it forces the most shared dependencies possible.

However, having two versions of a dependency across different targets should not result in a dependency conflict.

Let me go a bit hypothetical here:
If I were using targets outside of Nerves. For example, to build releases for an ML project deployed on different servers with multiple generations of graphics cards. Older systems might require older versions of some packages. In such a scenario, I would like to use targets as a mechanism to separate dependencies.

> Thank you! I don't think we can have our cake and eat it too in this case. :(

Could something like adding targets into the mix.lock data structure and subdividing target dependencies into `deps/target/` folders work?

**Comment by josevalim** [comment]
> However, having two versions of a dependency across different targets should not result in a dependency conflict.

That's the point. Today's behaviour was an explicit design decision because the choice at the time was to unify the targets as much as possible. I assume that, if you are working professionally, you want to have as little divergence as possible?

> Could something like adding targets into the mix.lock data structure and subdividing target dependencies into deps/target/ folders work?

You could do exactly what was done before, which is to set the appropriate configuration in `mix.exs` for custom locks and deps folders. If something feels clunky in that workflow, then we can try to improve that.

**Comment by Damirados** [comment]
Thank you for valuable insights. I have managed to end up with mix config that provides decent workflow. See linked nesrves issue for details.
