### ISSUE TITLE
Warning in 1.18.0 with module attr that controls some flow control

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/elixir#14103]
In the LVN SwiftUI client we bundle a MacOS binary to run our Xcode project generator. We run this when our generator mix task runs. This is detected at compile-time here:

https://github.com/liveview-native/liveview-client-swiftui/blob/1543f1dec79c8b8785491522d5c53c089f8f7a31/lib/mix/tasks/lvn.swiftui.gen.ex#L6

And then we pass that module attr into a function that will deterministically run the Xcode gen binary or not here: 

https://github.com/liveview-native/liveview-client-swiftui/blob/1543f1dec79c8b8785491522d5c53c089f8f7a31/lib/mix/tasks/lvn.swiftui.gen.ex#L37

Finally this function has a fallback for `false` is this is a non-macos: 

https://github.com/liveview-native/liveview-client-swiftui/blob/1543f1dec79c8b8785491522d5c53c089f8f7a31/lib/mix/tasks/lvn.swiftui.gen.ex#L151

With 1.18.0 I get this warning:

```
Compiling 21 files (.ex)
     warning: this clause of defp run_xcodegen/2 is never used
     │
 151 │   defp run_xcodegen(_context, false),
     │        ~
     │
     └─ lib/mix/tasks/lvn.swiftui.gen.ex:151:8: Mix.Tasks.Lvn.Swiftui.Gen.run_xcodegen/2
```

which I hadn't seen prior to 1.18 so I presume this is with the new typesystem.

I can refactor this to avoid the warning but I don't know if this is something it should be accounting for or not.

**Comment by josevalim** [comment]
Yes, as the type system gets more precise, code generation should get more precise too. In this case, you can define the `run_xproject` function conditionally, and the type system should be happy. Alternatively, move all of your constants to a separate module, such as `LVN.Constants` and have a `macos?` function (especially if used in more than one place).

We may provide ways to opt-out in the future, but we have been conservative about introducing those because it is still early and, for example, if you opted-out from verifying `run_xproject`, then you could have a bug in the first argument, that now would not be spotted.

Thanks for the report! We appreciate the double checking with us!
