### ISSUE TITLE
No Enum.last function

### ISSUE THREAD

**Issue by alexrp** [elixir-lang/elixir#1674]
This seems a bit odd since we have `Enum.first`.

**Comment by vonagam** [comment]
Sorry to touch an old issue but is it really expensive?

As I understand it `Enum.last(input, default \\ nil)` should be the same as `Enum.reduce(input, default, fn last, _ -> last end)`. Yes it will fully traverse an enumerable, but a lot of `Enum` functions do traverse the whole enum too and do more complicated things than that.

Also it should be `Enum.take(-1)` not `drop`. And `take` is more a general method, slower then shown `reduce`.

Am I missing something? Maybe ten years ago there were no such functions, but does it mean that it is ok to add `Enum.first` and `Enum.last` now?

**Comment by v0idpwn** [comment]
`Enum.at(list, -1)`, not `Enum.take(list, -1)`. take will return a list.
There's also `List.last/1`

**Comment by v0idpwn** [comment]
`Enum.first/2` existed at the time the issue was created and was removed.

**Comment by vonagam** [comment]
I said `take` because initially it was `drop` which returns `list`. But checked with `at(-1)` and surprisingly it is even slower than `take(-1)`.

I know that `Enum.first` existed - discussion about its removal linked here. But if `Enum.last` is added then logical to resurrect `first` too.

Unfortunately I deal not with lists, in my case it is a stream that I need to get last item from.
