### ISSUE TITLE
Interaction with erlang's ssh_io yes_no is unworkable

### ISSUE THREAD

**Issue by knewter** [elixir-lang/elixir#2153]
https://gist.github.com/knewter/10013415

There's an example of attempting to use erlang's ssh module inside of iex.  Essentially, it appears that the data entered in `iex` fails to make it back to the `yes_no` function in an acceptable manner.

Here's the code in otp where this is having trouble: https://github.com/erlang/otp/blob/9fa7a3b3514bee6a7136aeaa80ea4c07f7d8b465/lib/ssh/src/ssh_io.erl#L37-L53

I'm not sure why, my guess is we're returning a binary and it's expecting an iolist.  At any rate, it doesn't work.

**Comment by wmnnd** [comment]
Even though @josevalim’s PR was merged into OTP back in 2014, I am currently still having the same problem with :ssh.

The following will indefinitely block IEx:
```elixir
:ssh.start()
:ssh.connect('localhost', 22)
#> New host localhost accept [y/n]?y
#>
```

I tried this with an IEx that identifies as `Erlang/OTP 19 [erts-8.2] [source] [64-bit]` with Elixir 1.4.1.
I am using the Ubuntu packages from Erlang Solutions on Ubuntu 16.10.

The following works fine in Eshell:
```erlang
ssh:start().
ssh:connect("localhost", 22, []). 
%> New host localhost accept [y/n]?y
%> [Execution continues …]
```

Can you confirm that this problem is still occurring?

**Comment by NobbZ** [comment]
According to http://erlang.org/doc/man/ssh.html connect/2 expects
completely different ages then connect/3, so the code lines you showed
aren't equivalent.

Philipp Schmieder <notifications@github.com> schrieb am Do., 23. Feb. 2017,
22:43:

**Comment by wmnnd** [comment]
Thanks for pointing this out, @NobbZ . Unfortunately, the same problem occurs:
```elixir
:ssh.start()
:ssh.connect('localhost', 22, [])
#> New host localhost accept [y/n]?y
#>
```

This is even stranger because `ssh:connect/2` fails right away in Eshell (`no function clause matching proplists:unfold(infinity) `) if you’re not submitting the correct arguments whereas in IEx both `:ssh.connect/2` and `:ssh.connect/3` get stuck with the yes_no prompt.
