### ISSUE TITLE
Saving iex history to a file between runs

### ISSUE THREAD

**Issue by eugmes** [elixir-lang/elixir#2945]
It would be good to be able to save/restore iex history to a file, so it could be used after program restart, like in various unix shells.

**Comment by jeznet** [comment]
@josevalim Any tips how to help looby the OTP team to add this feature IMHO esential for any Erlang REPL user?

**Comment by josevalim** [comment]
No idea. This discussion has even already showed up on Erlang mailing list.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by jeznet** [comment]
If you mean 
http://erlang.org/pipermail/erlang-patches/2012-February/002651.html, 
then wonder how did that meeting went. Let's ask the maintainer @fred 
(Fred Hebert) about that.

**Comment by Tica2** [comment]
:+1: 

Tica2: Any discution to have .iex_history ?
[12:34pm] Tica2: like ~/.bash_history
[12:34pm] Nicd-: that would be cool
[12:35pm] Tica2: I offen restart mix or iex -S mix … and I need to tape/paste again last commands
[12:36pm] asonge: Tica2: https://github.com/elixir-lang/elixir/issues/2945
[12:36pm] asonge: so yeah,

**Comment by ferd** [comment]
I'm the one who worked on erlang-history, and the problem is that the DETS mechanism my lib uses is terrible and corrupts files every other week. To make it work better, we'd need a handwritten library (that depends only on stdlib and kernel) that does logging properly, even when multiple concurrent nodes try to access the files on disk, and without a required third party agent.

I am not good enough at file handling to write that, nobody has stepped up, and I don't want to ship the currently corrupting behaviour of `erlang-history` to OTP and then have to answer for bug reports on that (or have other people have to answer on them) when I have no idea how to even handle that. That stuff, with the library constraints, is beyond my capacity.

**Comment by indera** [comment]
This would make elixir much friendlier to beginners!

**Comment by ferd** [comment]
I have pushed the fixes and they've been merged in OTP-20. Just enable the shell history with `export ERL_AFLAGS="-kernel shell_history enabled"` being set in your environment.

**Comment by indera** [comment]
@ferd I have set the environment variable and upgraded elixir but it didn't work (macOS).
After creating the iex_history file by hand it magically **started to work**.

$ uname -a
Darwin Kernel Version 16.7.0

$touch ~/.iex_history

Thank you.

**Comment by OvermindDL1** [comment]
> After creating the iex_history file by hand it magically started to work.

Ahh, that explains why it was not working on one of my servers!  It is working now!  I did not even think to check for that, thanks!

This is a bug.  :-)
