### ISSUE TITLE
IEx doesn't purge function cache after reloading a module (when running iex -S mix)

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#2985]
Take this module:

```elixir
# foo.ex
defmodule M do
  def foo do
    :ok
  end
end
```

When I run it with `iex foo.ex`, I get the following result:

```iex
iex(1)> M.foo<TAB>
foo/0
# change the file here
# ...
iex(2)> r M
foo.ex:1: warning: redefining module M
{:reloaded, M, [M]}
iex(3)> M.bar<TAB>
bar/0
```

However, when I put this file under `lib/` in a Mix project and then run `iex -S mix`, I get this:

```iex
iex(1)> M.foo<TAB>
foo/0
# change the file here
# ...
iex(1)> r M
lib/foo.ex:1: warning: redefining module M
{:reloaded, M, [M]}
iex(2)> M.foo<TAB>
foo/0
iex(2)> M.foo
** (UndefinedFunctionError) undefined function: M.foo/0
    (event_map) M.foo()
iex(2)> M.bar<TAB>
# nothing
iex(2)> M.bar
:ok
```

**Comment by lexmag** [comment]
It's caused by the fact that `iex -S mix` uses `Code.get_docs/2` which  doesn't reload module docs.
The reason this is not happening with `iex file` is it uses `mod.__info__(:functions)` to display funs.
[iex/autocomplete.ex#L211-L215](https://github.com/elixir-lang/elixir/blob/master/lib/iex/lib/iex/autocomplete.ex#L211-L215)

**Comment by josevalim** [comment]
@lexmag great catch! I don't think we can fix this. Code.get_docs is going to use whatever is defined in the beam file and we want to use the Code.get_docs version so we don't show `@doc false` functions.

**Comment by lexmag** [comment]
:smile: one step closer to v1.0.3
