### ISSUE TITLE
suggestion: iex c default to using _build when running iex -S mix

### ISSUE THREAD

**Issue by jschoch** [elixir-lang/elixir#2995]
it may be helpful to default c/2 to using "./_build" when run via iex -S mix

use case is that you may add a lib in a session and have some variables you are testing with, and rather than restart iex, you can just run c("lib.ex")

I had made a bad assumption that this was the case, and had a terrible time trying to debug why files in <project root>/ were being loaded and impacting some re factoring I was doing.  mix clean does not remove ./Elixir.*.beam  so cleaning the build directory did not help me removed the old beam files that I accidentally compiled via c/2

**Comment by josevalim** [comment]
If you are working inside an existing project, you should use `r` instead of `c`. The issue here is that iex does not know anything about projects, so it cannot compile to build. Plus, compiling to another directory will break flows when working outside projects.

Another solution is to provide a bunch of mix commands you can run inside the terminal. So you don't  run iex basic ones. In any case, I am pushing improvements to c/1 docs. Thanks!
