### ISSUE TITLE
Discuss if we should support monitoring callbacks in agents

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3011]

**Comment by fishcakez** [comment]
Are you suggesting something like this?

```elixir
@doc """
The agent monitors a process and returns the monitor reference.

When the `:DOWN` message is received, or the monitor is de-monitored, the fun is applied with the reference of the monitor as last argument.

If the fourth argument is a fun, it is applied to the state of agent with the monitor reference as second argument. If it is an MFA tuple the reference is appended to the arguments list. If it is `nil` the state does not change.
"""
@spec monitor(agent(), pid(), {module(), atom(), list()} | (any(), reference() ->any()), {module(), atom(), list()} | (any(), reference() ->any()) | nil) :: reference()
@doc """
Gets and updates an agent's state via the given function and monitors a process. Returns the agent value.

When the `:DOWN` message is received, or the monitor is demonitored, the fun is applied with the reference of the monitor as second argument. In the case of an MFA tuple the reference is appended to the arguments list.

If the fourth argument is a fun, it is applied to the state of agent with the monitor reference as second argument. If it is an MFA tuple the reference is appended to the arguments list. The function returns a 2-tuple, first element is returned to the caller and the second element is the new state of the agent.
"""

@spec get_and_monitor(agent(), pid(), {module(), atom(), list()} | (any(), reference() ->any()), {module(), atom(), list()} | (any(), reference() ->{any(), any()})) :: any()
@doc """
Updates the agents state and demonitors the monitor asynchronously. Always returns true.

If the optional third argument is a fun, the fun is applied to the state of agent with the monitor reference as second argument. If it is an MFA tuple the reference is appended to the arguments list and applied to the state. If it is `nil` the state does not change.
"""
@spec demonitor(agent(), reference(), {module(), atom(), list()} | (any(), reference() ->any()) | nil) :: true

@doc """
Updates the agents state and demonitors the monitor synchronously. Returns true if the monitor exists, otherwise false.

If the optional third argument is a fun, the fun is applied to the state of agent with the monitor reference as second argument. If it is an MFA tuple the reference is appended to the arguments list and applied to the state. If it is `nil` the state does not change. This function is only applied if the monitor exists.
"""
@spec sync_demonitor(agent(), reference(), {module(), atom(), list()} | (any(), reference() ->any()) | nil) :: boolean()

@doc """
Gets and updates an agent's state via the given function and demonitors the monitor. Returns false if the monitor does not exist, otherwise the agents value.

If the third argument is a fun, it is applied to the state of agent with the monitor reference as second argument. If it is an MFA tuple the reference is appended to the arguments list. The function is applied before the demonitor callback but only if the monitor exists. The function returns a 2-tuple, first element is returned to the caller and the second element is the new state of the agent.
"""
@spec get_and_demonitor(agent(), reference(), {module(), atom(), list()} | (any(), reference() -> {any(), any()})) :: false | any()
```

**Comment by josevalim** [comment]
Thanks @fishcakez! I haven't given this much thought, I have opened the issue as a reminder.

Initially, I was thinking to make it closer to how one would handle this with a GenServer. `Agent.start_link/2` would accept an `on_down: {m, f, a} | function` option which would be called on DOWN messages with the state. Then it is up to the Agent to track those.

I can see the benefits of providing a specialized API but I can also see the downsides of moving too much away from what a regular process would do.

Thoughts?

**Comment by fishcakez** [comment]
I suggested the above because it allows Agent to get the monitoring right, which is the repetitive bit and certainly possible to do wrong. I really liked that action on monitor and demonitor are defined in the same place. However it is complex, and certainly get_demonitor has significant cognitive load that a GenServer would be better.

I understand that there is a desire to handle monitoring with an Agent. But if the callback is going to be that simple I feel that instead of `on_down` it should be `handle_info: {m, f, a} | fun`? This would allow the Agent to handle any messages and has a less narrow scope. For example it would allow an Agent to spawn async tasks and handle the results or to trap exit and handle `:EXIT`s. However to me it feels unnatural to define that callback in the `start_link/2` of an Agent and I don't think it matches the philosophy.

I am unsure if I like either though. My gut feeling is that neither solve the problem adequately or cleanly enough to warrant inclusion. If there is to be a `handle_info` (or `on_down`) callback would it be better to have an Agent behaviour, with the current callbackless method a default like Supervisor.Default?

Example:
```elixir
@callback init(any()) :: {:ok, any()}
@callback handle_info(any(), any()) :: {:ok, any()} | {:stop, any(), any()}
@callback code_change(any(), any(), any()) :: {:ok, any()}
@callback terminate(any(), any()) :: any()
```
With optional callback:
```elixir
@spec format_status(:normal | :terminate, [[{any(), any()}] | any(), ...]) :: any()
```
This would be require `Agent.start_link/1,2,3`:
```elixir
@spec start_link(mfa() | (()->any())) :: start_return()
@spec start_link(module(), any()) :: start_return()
@spec start_link(mfa() | (()->any()), [option()]) :: start_return()
@spec start_link(module(), any(), [option()]) :: start_return()
```

This creates a very nice story for slowly upgrading a callback-less Agent to an Agent callback module and potentially to a GenServer or GenEvent callback module. The intermediate step between callback-less Agent and a GenServer makes the approach very appealing because very little refactoring is required for the first step and the second step (which would very rarely be needed) is nolonger so great. Of course the return values are not quite the same for `handle_info/2` but the rest is and the full OTP goodness is there.

An Agent behaviour is very much like @sasa1977's ExActor.GenServer but without the macros and slightly like e2's services. I am unsure if this suggestion is a useful pattern or too similar to a GenServer, though I lean towards the former. Would this aid the learning curve? I don't have the teaching experience to even guess on this.

An alternative would be to experiment with something like a `Watcher` (watches many processes not just a GenEvent like Logger.Watcher) that handles the monitoring and storing of the references. I guess it would have the same API as above but also `handle_up` and `handle_down`'s.

**Comment by josevalim** [comment]
@fishcakez I like the GenServer callbacks proposal a lot. However it adds one question: if Agents are then capable of doing everything a GenServer can, when should we use one and when do we use the other? The line becomes much blurrier.

**Comment by fishcakez** [comment]
When picking between Task, Agent, GenServer, GenEvent, gen_fsm and Supervisor it is important to remember the role of the process.

Below is how I personally view each behaviour, others may interpret things differently :).

A Task is for relatively simple work, likely to carry out a single IO or CPU bound job concurrently. It has helpers to return the result of its job to another process. It does not have helpers to be "long lived" like the other process types.

An Agent is for sharing public state. It has helpers to update and fetch this state.

A GenEvent is for sharing public events. It has helpers to dynamically add/remove/track different modules handling the events.

A gen_fsm is for handling a finite state machine. It has helpers for switching between the discrete states and dispatching events.

A Supervisor is for starting processes and reliably handling their failure. It has helpers to decide how to start processes/handle failure to provide fault tolerance.

A GenServer is for a general usage when the use of the process does not immediately fit into just one of the above categories. It has helpers for making arbitrary async/sync calls.

It is useful to reach for the behaviour which best describes the process for two reasons. Firstly that the helpers can act like a "rubber duck" and help to ask the right questions. For example with a Supervisor, what should happen if this process dies? Or with gen_fsm, what should happen when the process receives this event in that state?

Secondly by choosing a behaviour it can help another person (or a future self) quickly understand the role of a process as many things are familiar/the same as there are many "clues" where to look for things. It also highlights important complexities that the behaviour is designed to help with. For example with Agents there are only certain calls where the state can change. Or with gen_fsm, where changes between discrete states occur.

**Comment by fishcakez** [comment]
Unfortunately `Agent.start_link(mod, fun, args)` clashes with `Agent.start_link(mod, args, opts)`.

**Comment by josevalim** [comment]
Closing this. If you need to monitor, it is best to upgrade the agent to a gen server.

**Comment by eksperimental** [comment]
@josevalim shouldn't this be mentioned in the Agent module?
