### ISSUE TITLE
Using Enum.map_reduce in eex results in  unexpected token error

### ISSUE THREAD

**Issue by shankardevy** [elixir-lang/elixir#3017]
When using Enum.map_reduce in eex files in the following manner
```
<%= Enum.map_reduce @messages, initial_value, fn current, prev -> %>
  <li>
    <% if current.type != prev.type do %>
    <span class="msg-type"><%= current.type %></span>
    <% end %>
    <br/><%= current.msg %>
  </li>
<% end |> elem(0) %>
```

I get the following error

```
** (SyntaxError) web/templates/page/index.html.eex:8: unexpected token: end
```

Refer to josevalim's workaround https://gist.github.com/shankardevy/1abea2fe7373c13f7e4c#comment-1376597 if it helps. It works for me but I do not understand it, though ;-)

Not sure if this is a related bug. When I try the following code in eex, I get a similar error

```
<% Enum.each([1,2,3], fn(n) -> %>
<span><%= n %></span>
<% end) %>
```

```
** (SyntaxError) web/templates/page/index.html.eex:3: unexpected token: end
```

**Comment by oneeman** [comment]
The problem is that the `end` EEx tokens are currently only supported if they consist of only `end` and whitespace, which explains why the two examples you have lead to errors while the one in the gist works.  

@josevalim Any thoughts on what the desired behavior would be?  A minimal approach would be to also support `)` characters after the `end`, which would make the second example here work but not the first.  Is that the idea, or is it to support a wider range of syntax?  I assume the idea isn't to allow arbitrary code in the end tokens, since I'm not sure what `start_expr`, `middle_expr` and `end_expr` would then mean (how do you handle something like `<% end; if true do %>`?).  At any rate, I'd be happy to tackle it, whether it's a small change like allowing `)` or something larger to allow more forms.

**Comment by josevalim** [comment]
@oneeman I will leave that decision to you. How can we make it more robust without adding tons of complexity? If we can handle `)` and other use cases, the better. If someone writes `end; if true do`, we could also raise and so on.

**Comment by josevalim** [comment]
But if you want some specific, direct input from me, just let me know and I can be more assertive.
