### ISSUE TITLE
Mixing up Stream.cycle with Enum.drop freezes the compiler

### ISSUE THREAD

**Issue by xavier** [elixir-lang/elixir#3085]
The following trivial piece of code freezes the compiler:

```Elixir
Stream.cycle([1, 2, 3]) |> Enum.drop(1)
```

To reproduce, just copy the line above in a file and run `elixirc`: the compiler should hang.
Reproduced with Elixir 1.0.2, 1.0.3 and 1.1.0-dev (Erlang/OTP 17 [erts-6.3.1] running on Darwin 14.1.0).

Workaround: replacing `Enum.drop` by `Stream.drop` will make the code happily compile.
If this information is of any help to identify the root cause:  `Enum.take` does not cause any compilation issue neither.

**Comment by josevalim** [comment]
This is not a bug! Stream.cycle followed by a drop means you want to drop the first element and then convert the rest of the collection to a list. But since the collection is infinite, it cycles forever. take works because you are taking just the first item. Stream.drop works because it is lazy and you haven't performed any operation but cycle+drop+to_list should "freeze" too!

**Comment by xavier** [comment]
Oh I see, I somehow expected `Enum.drop` to behave like `Stream.drop` when given a stream but it all makes sense now. Thanks for the quick response and sorry for the false alarm. :)
