### ISSUE TITLE
Warn on EXPR OP NO PARENS EXPR

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3104]
The goal is to warn in cases like `1 |> foo 1, 2`. Those cases are already explicit in the parser so it is a matter of emitting this information as warning.

**Comment by oneeman** [comment]
Should this be just for `|>` or for some others as well?

**Comment by josevalim** [comment]
Others too but not all (it doesn't make sense to raise this for `=`, for example). I would say everything in [this range is game](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_parser.yrl#L60-L69). One issue though is that we can't access the file in the parser, so we can't raise warnings there. I think we should cheat for now, store the file in the process dictionary. This won't be an issue once we start raising for cases like this.

**Comment by ericmj** [comment]
We should only warn on `NO PARENS EXPR OP EXPR`, i.e. `foo 1, 2 |> 1`. Since we wont warn on `1 |> foo 1, 2` it means we don't have to special case any operators such as `=`.

**Comment by oneeman** [comment]
I've looked at this somewhat, and it seems pretty tricky, because we need to be able to distinguish `foo 1, 2 |> 3` from `foo 1, (2 |> 3)` and only warn on the first one.  But `2 |> 3` and `(2 |> 3)` have identical AST's and both ultimately get reduced to `matched_expr` before getting reduced to one of the `call_args_no_parens` non-terminals.  I've managed to have it warn on both cases, but of course that's not acceptable.

I'll look into it further, but if anyone has any tips (or if what I've written above isn't right), I certainly won't complain :-)

**Comment by josevalim** [comment]
Maybe we don't need to warn on all cases but on enough cases so that users pick it up. For example, my first attempt was to warn on these cases: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_parser.yrl#L171-L184

**Comment by josevalim** [comment]
Ah, ignore me. My solution is the opposite of what @ericmj suggested.

**Comment by josevalim** [comment]
Well, I think @ericmj suggestion isn't right either, because this is valid code:

    foo 1, x = 2

And I don't think we should warn on it. So maybe going with my earlier suggestion of just warning on cases we know they are wrong should likely be fine.
