### ISSUE TITLE
KeywordList concise syntax doesn't allow @ in keys.

### ISSUE THREAD

**Issue by itsgreggreg** [elixir-lang/elixir#3113]
iex(1)> [{:a@, 1}]  # regular fine
    [a@: 1]
    iex(2)> [a@: 1]     # concise not fine
    ** (CompileError) iex:2: undefined function a/1

just `@` fine:

    iex(5)> [{:@, 1}]
    [@: 1]
    iex(6)> [@: 1]
    [@: 1]

**Comment by bitwalker** [comment]
I think you need to do `["a@": 1]` if I'm not mistaken, when it comes to using special characters in atom names of keyword lists.

**Comment by josevalim** [comment]
Given it works on `:a@b`, we need to make it work for `a@b:` too.

**Comment by oneeman** [comment]
Found a related bug:
`:@` and `:a@` are correctly parsed as atoms, but `:@a` gives a syntax error.  It's tokenized as `[{atom,{1,1,3},'@'},{identifier,{1,3,4},a}]`.

I figured I'd mention it here rather than opening another issue because they presumably involve the same chunks of code and should be fixed together.  I'll see if I can get it sorted out.

**Comment by josevalim** [comment]
@oneeman We allow `:@` because it is an identifier. We allow things like `:a@a` because it can represent a node. `:@a` certainly does not represent a node. So we should actually forbid `:a@` too. :)

**Comment by oneeman** [comment]
@josevalim Ah, I was going by what it says in `Programming Elixir` (P1.0—October, 2014):

```
Atoms are constants that represent something’s name. We write them using
a leading colon ( : ), which can be followed by an atom word or an Elixir opera-
tor. An atom word is a sequence of letters, digits, underscores, and at signs
( @ ). It may end with an exclamation point or a question mark. You can also
create atoms containing arbitrary characters by enclosing in double quotes
the characters following the colon.
```

**Comment by josevalim** [comment]
@oneeman well, that would be one way to go about it but it could end-up being too complex. I guess it is easier to just allow `@` anywhere?

**Comment by oneeman** [comment]
I would certainly vote for allowing them, and not just because I'm biased by what I read in Programming Elixir  :-)

Unless there are other reasons not to which I'm not aware of, in which case I'd suggest discussing the pros and cons on the mailing list.

**Comment by josevalim** [comment]
Ok, let's ignore the related bug for now. After some thought, I think we should keep it as is. `:@` works because it is an identifier, I don't think `:@@` should work though (and we would allow it). It is arguable if `:@foo` should work but (it doesn't in Erlang) as nobody has an use case for it yet, let's ignore it too keeping the current behaviour.

**Comment by oneeman** [comment]
Good point, :+1: for consistency with Erlang (which does allow `a@@b`, etc.).  I think it won't be too hard to fix the keyword bug while continuing to disallow `@@` and similar ones (e.g. `@a@b`).

**Comment by oneeman** [comment]
@josevalim What about `A@b: `?  `:A@b` and `Ab: ` work, so it seems like `A@b: ` should work for consistency.  But, then again `a@b` is for node names, and `A@b` is not (I believe) a node name, so I wasn't sure.

**Comment by josevalim** [comment]
Let's make `A@b:` work too. The logic should be pretty much the same for both, except one has a leading `:` and the other one a trailing. :)

**Comment by oneeman** [comment]
Got it.  BTW, here is a related bug not involving `@`, but involving the functions in the tokenizer which need to be updated:
`:A!` and `a!:` work, but `A!: ` doesn't.

(I was looking at the usages of `tokenize_identifier/2`)

**Comment by oneeman** [comment]
Related question (sorry for all the email notifications!):

Currently, `foo@a ` is being parsed the same as `foo @a` (as a call to `foo/1`).  Would it make sense to instead throw a syntax error saying a space is needed?  I ask because it would simplify the tokenizer changes and resulting code, and it makes sense to me (the way it's written it intuitively looks like an invalid identifier, not a function call).  But it seems to be a breaking change (breaking unintentional behavior?).

**Comment by josevalim** [comment]
> Currently, foo@a is being parsed the same as foo @a (as a call to foo/1). Would it make sense to instead throw a syntax error saying a space is needed?

Yes, definitely.
