### ISSUE TITLE
add option to retain local variables

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/elixir#3114]
Variables inside the body of the for loop revert to their initial value (if any) on each iteration. In the following example, i is doubled twice, but the changed value isn't retained. So, instead of moving up to 84, the value reverts to 21 and gets doubled again to 42:

    iex> i = 21
    21
    iex> for n <- (1..2) do
    ...>   i = i + i
    ...>   IO.puts i
    ...> end
    42
    42
    [:ok, :ok]

This complicates retention of state between iterations. It is possible, though awkward, to save state in other ways: another process, the process dictionary, etc. However, this seems overly dramatic.

Worse, because for is a Special Form (implemented in Erlang), this behavior isn't readily modifiable (e.g., by a macro). It would be nice if an option could be added to for, allowing it to retain state. However, elixir_for.erl comprises 300+ lines of Elixir source code. Worse, José Valim says "it could, but it is complex to implement". Sigh.  Here's hoping that a simple solution emerges...

**Comment by josevalim** [comment]
Please bring this discussion to the core mailing list. Before we make this work, we actually should decide if we *want* to make this work. We had similar discussion in the past and people were more inclined to a "no" because it relies on using variables to pass state/accumulate instead of explicitly accumulating it (which would be the more functional approach).

I would like to it to be more explicit too but I have never found a good syntax for it.
