### ISSUE TITLE
Add lazy definition of Dict.put_new, Dict.get and Dict.pop

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3133]
Where we calculate the default value only if required.

**Comment by ephe-meral** [comment]
So as it seems the issue is how to distinguish between calls where the user would want to store a function in the dictionary and calls where they would want to have the function evaluated lazily and then store the result.

If the distinction is by naming, we could maybe append or prepend "lazy" to the method names, or find a special character that signifies lazyness similar to how Dict.fetch and Dict.fetch! signifies raising an error?

**Comment by whatyouhide** [comment]
I'm in favour of appending `_lazy` to the function names.

**Comment by josevalim** [comment]
Question: why not `lazy_put_new` and friends?

**Comment by whatyouhide** [comment]
@josevalim there's no difference really :). Appending `_lazy` makes functions like `put_new` and `put_new_lazy` appear close to each other in the documentation, while `lazy_*` makes all lazy functions appear together. Just choose one and we'll go with it :smile:

**Comment by lexmag** [comment]
@whatyouhide :+1: great point.

**Comment by ephe-meral** [comment]
@whatyouhide I personally also like appending them... If I wouldnt know that there are specifically lazy functions I would be much more likely to find them when I search for the documentation of the normal function and then happen to see the lazy version right below it

**Comment by josevalim** [comment]
Appending sounds good then. Let's get feedback from @ericmj and @alco so @ephe-meral can send a pull request (if still interested). :)

**Comment by ericmj** [comment]
:+1:

**Comment by ephe-meral** [comment]
Will do.

**Comment by alco** [comment]
+1 for putting _lazy at the end.
