### ISSUE TITLE
Add :trim mode to EEx

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3154]
So it removes spaces "\n\s*" on the left side and "\s*\n" on the right side.

**Comment by shankardevy** [comment]
@josevalim can you pls more context to this issue? When is it occurring and to what method on eex, this support is needed?

Just adding some related discussion on irc:

```
shankardevy: any one knows what jose is taking here: https://github.com/elixir-lang/elixir/issues/3154
shankardevy: Add :trim mode to EEx
chrismccord: shankardevy: probably a way to not have eex add whitespace for times you want to do <% if something do %>
chrismccord: stuff
chrismccord: <% end %>
chrismccord: eex sould add a blank line there if fasley
chrismccord: where it would be nice to have syntax to trim any space that would be added
shankardevy: thanks chrismccord. so is he talking about adding :trim as an additional option to "EEx.eval_string"? http://elixir-lang.org/docs/v1.0/eex/
```

```
iex(1)> EEx.eval_string "<%= if false do 'false' end %>"
""
iex(2)> EEx.eval_string """
...(2)> <% if false do %>  
...(2)> This text will never get executed
...(2)> <% end %>
...(2)> """
"\n"
```

**Comment by josevalim** [comment]
@chrismccord is correct. Here is a better example:

```iex
iex(1)> EEx.eval_string """
...(1)> foo
...(1)>
...(1)> <% if false do %>
...(1)> This text will never get executed
...(1)> <% end %>
...(1)>
...(1)> bar
...(1)> """
"foo\n\n\n\nbar\n"
```

The idea is that, when trim mode is enabled. All the whitespace until the previous new line is removed from the left side of `<%` and all the whitespace until the next new line from the right side of `%>`. The example above should then only return `"foo\n\nbar".

Keep in mind the new line restriction is very important. We don't want to strip whitespace in cases like this:

```
iex(2)> EEx.eval_string "foo <%= bar %> baz"
```

We only strip if whitespaces end-up finishing on a new line. :)

**Comment by shankardevy** [comment]
I assume `:trim` goes to options keyword list like [trim: true] (default being false). `:trim` option gets passed on to private method `do_eval/3` where  the compiled code gets evaluated. 

@josevalim for the example you have given
```
iex(1)> template = """
...(1)> foo
...(1)> <%= if false do %>     # there are some whitespace after '%>'
...(1)> some text
...(1)> <% end %>      # there are some whitespace after '%>'
...(1)> bar
...(1)> """
"foo\n<%= if false do %>     \nsome text\n<% end %>      \nbar\n"

```

Here is the AST

```
iex(2)> EEx.Compiler.compile(template, [])
{:<>, [context: EEx.Engine, import: Kernel],
 [{:__block__, [],
   [{:=, [],
     [{:tmp, [], EEx.Engine},
      {:<>, [context: EEx.Engine, import: Kernel], ["", "foo\n"]}]},
    {:<>, [context: EEx.Engine, import: Kernel],
     [{:tmp, [], EEx.Engine},
      {{:., [],
        [{:__aliases__, [alias: false], [:String, :Chars]}, :to_string]}, [],
       [{:if, [line: 2],
         [false,
          [do: {:<>, [context: EEx.Engine, import: Kernel],
            ["", "     \nsome text\n"]}]]}]}]}]}, "      \nbar\n"]}
```
Regex.replace on the evaluated string won't work because it might also replace the user entered spaces and new lines in the text, rather than eex inserted.

So I believe, we need to do something with the AST to bring about the changes you look for "All the whitespace until the previous new line is removed from the left side of <%" and "all the whitespace including the next new line from the right side of %>". Am I right? How to filter out AST corresponding to code between `<%=` and `%>`?

Not sure if I am complicating things more than necessary.

**Comment by josevalim** [comment]
@shankardevy We definitely don't need a regex. It should likely go in the tokenizer. Everytime we find a <% token and trim is true, we clean up the space before. Similar to %>.

**Comment by oneeman** [comment]
I'm on it.
