### ISSUE TITLE
Easier to analyze compilation output.

### ISSUE THREAD

**Issue by iraasta** [elixir-lang/elixir#3175]
When using Erlang compiler or Dialyzer compilation output has consistent 

    main.erl:13: Warning: record nazwa is unused
    main.erl:47: Warning: variable 'A' is unused
    main.erl:47: Warning: variable 'Mean' is unused
    main.erl:57: Warning: function test/1 is unused
    main.erl:57: Warning: no clause will ever match
    main.erl:57: Warning: the guard for this clause evaluates to 'false'

It can be easily reasoned about.

    [File, Line, Priority , Message] = line.split(":")

But in Elixir

    == Compilation error on file elixirtest_test.exs ==
    ** (SyntaxError) elixirtest_test.exs:94: syntax error before: worker
        (elixir) lib/kernel/parallel_compiler.ex:95: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

It's nice for the eye. But cannot be split into parts with any regular expression, which disallows output analysis in programmatic way.

**Comment by josevalim** [comment]
Thanks for opening this. Question: do you care about warnings, errors or both?

**Comment by josevalim** [comment]
Also, do you care about the stacktrace or not at all?

**Comment by iraasta** [comment]
I'm building compilation errors analysis in IDE. So I care about all compilation messages.
Runtime errors are not my concern for now, but they might be in future (when trying to make breakpoints work), but even then I don't think I'll be needing stacktraces

**Comment by josevalim** [comment]
> Runtime errors are not my concern for now, but they might be in future (when trying to make breakpoints work), but even then I don't think I'll be needing stacktraces

This makes it clear. :) In Elixir, there isn't much distinction between runtime and compilation time because we effectively *execute* code during compilation. So compilation can fail with any reason runtime would and I agree this makes it hard to effectively pinpoint on which line the error happened.

The only times we will have an explicit line with the failure when you get a compile or syntax error. So I would rather match on:

    ** (SyntaxError)
    ** (CompileError)

If you get anything else, the editor should rather show it to the user.

Btw, when we talked during the event, you mentioned warnings, so I thought the issue was explicitly about warnings. If you have inconsistent warnings, those are definitely bugs. But regarding the compilation errors, there isn't much we can do to help your case (sorry!).

**Comment by iraasta** [comment]
Oh.
But what about common warnings like "Unused private function" or "Unused parameter".
Aren't they supported [yet]?

**Comment by josevalim** [comment]
We have those and the follow the same format as Erlang:

    iex(1)> defmodule Foo do
    ...(1)> def bar do
    ...(1)> baz = 1
    ...(1)> 2
    ...(1)> end
    ...(1)> end
    iex:3: warning: variable baz is unused

**Comment by iraasta** [comment]
Oh. That's my bad. I didn't realize there are warnings like that (seems that my code was perfect so far ;) )
Then there's no problem with that. 
Thank You. I've put it through the same RegExp that I use for Erlang and it works great.
Issue can be  closed
I guess Alchemide will be ready before April :smile: 
![Uploading Screenshot from 2015-03-16 18:54:36.png . . .]()

**Comment by josevalim** [comment]
Awesome! In any case, don't hesitate to ping us if you have any issues!
