### ISSUE TITLE
Deprecate as: true in alias, import, require

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3190]

**Comment by tony612** [comment]
I'm working on this, but I'm not sure what's the proper way to do deprecation in Elixir. For this example, I think we should remove `:as` option in the repo first. Then we need to add the doc about the deprecate. At last, we should warn users when they use `:as` in the code. The first 2 step seems not difficult. But I have no idea for the 3rd step, how to do this?

I try to print some warning in `no_alias_opts` function of `elixir_exp.erl`, but it seems not to work.

**Comment by oneeman** [comment]
@tony612 There are functions in `elixir_errors.erl` for issuing warnings: https://github.com/elixir-lang/elixir/blob/e49a806e8abe43c62c9c1b21ea7eb2217bef1966/lib/elixir/src/elixir_errors.erl#L9-L30.  I think `warn/3` is the one to use, since `form_warn/4` seems to be used with data structures rather than English messages.  But I may be wrong about that.   Maybe @josevalim can clarify which is the appropriate one.

But you may have some other issue if you can't get output from the warning you tried. For example, I just tried (just to see what happens, not that this is the way to do it):
```
  case lists:keyfind(as, 1, KV) of
    {as, true} -> io:write('FOOBAR'), lists:keystore(as, 1, KV, {as, no_alias_expansion(true)});
    {as, As} -> lists:keystore(as, 1, KV, {as, no_alias_expansion(As)});
    false -> KV
  end;
```
and after running `make clean test` I get (with `bin/iex`):
```
iex(1)> alias List, as: true
'FOOBAR'nil
```

Anyway, hope this helps.  By the way, I think maybe the place to do this warning is in `no_alias_expansion` (but I haven't looked at that module almost at all, so I don't really know how those two functions fit in, so take this thought with a grain of salt).
