### ISSUE TITLE
Document and test if Enum.usort and Enum.dedup use === or ==

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3214]
The correct semantics would be to use `===`. Here is another bug:

    iex> Enum.usort(Stream.concat([1, 1.0], [1, 1]))
    [1, 1.0, 1]

**Comment by MSch** [comment]
I feel responsible for that :)

**Comment by MSch** [comment]
Seems this is caused by `sort_by` and the relative sort order of `1` and `1.0` not being defined in Erlang (according to https://github.com/uwiger/sext/blob/master/README.md#1-introduction)

```
iex> [1, 1.0, 1, 1] |> Enum.sort_by(fn x -> x end)
[1, 1.0, 1, 1]
```

Unfortunately I have no idea how to go about fixing the problem.

**Comment by josevalim** [comment]
I don't have an idea either. Let's talk about it later. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by josevalim** [comment]
Following up: the least we can do for now is to document and add a test that dedup_by uses `===` behind the scenes.

Now, to solve the sorting issue, the only option is to change our sort algorithms so it returns `:lt | :eq | :gt` instead of `true` if `a <= b`. This is a bigger change but it can certainly be done, including in a backwards compatible fashion. The biggest issue is that we would need to rewrite the `:lists.usort` in Elixir.

Thoughts?

**Comment by josevalim** [comment]
Right now I have removed usort.  We can add it back but it requires our own implementation that uses `:lt`, `:eq` and `:gt`. Huge thank you to @ThomasArts for finding this bug before we shipped it!

**Comment by MSch** [comment]
@josevalim can I get `List.usort` in instead?

**Comment by josevalim** [comment]
No. :) You can just use the erlang one.

**Comment by ThomasArts** [comment]
José is right. One should not just put it in because it is convenient. Language design must be more than 
convenience for a specific moment in time, it's a long time investment. And a language should not have surprises,
but have very clear and understandable semantics.

In the case if usort:

One should write a variant of sort that takes a relation =<
The standard relation can be whatever you like. For normal sorting you would say A comes before B if A =< B.

For usort one would say A comes before B if A =< B, but is removed if also B <= A.

You can then write 
usort(L, fun(X,Y) -> X < Y orelse X =:= Y end)
or
usort(L, fun(X,Y) -> X < Y orelse X == Y end)

the second one is, I guess the same as the default =<.
The work to be done is to overload the operators such that they also work for tuples, lists etc.

/Thomas
