### ISSUE TITLE
Binding issue with eval_quoted and quote/unquote

### ISSUE THREAD

**Issue by zambal** [elixir-lang/elixir#3220]
Since you have to perform quite some steps to reproduce this issue, I wrote some code that highlights the issue in this gist:

https://gist.github.com/zambal/b83c198fb4d58186c733

It boils down to:

If you eval a nested quote:

```elixir
quoted = quote do
  quote do
    n = 12
    square(n)
  end
end

{ res, _ } = Code.eval_quoted(quoted, [], __ENV__)
```

and unquote `res`

```elixir
quote do
  unquote(res)
end
```

The compiler complains with `function n/0 undefined` if `square/1` is a local macro. If `square/1` is a macro from another module there is no error. Also, if you call `square/1` with a value instead of a variable, everything works fine too.

**Comment by zambal** [comment]
@josevalim I would like to try solving this, however I have not much experience with Elixir's internals, so could you maybe give some pointers where to look for? I'm comfortable with reading and writing Erlang code, so that shouldn't be an issue.

**Comment by zambal** [comment]
No problem, I think I just dive in. I guess it will be educational at least for me and who knows I find something :)

**Comment by josevalim** [comment]
Ok, I understand why this happens.

The way quote works is that all variables are annotated with the current module as a context. For example:

```elixir
defmodule Foo do
  def bar do
    quote do
      x + y
    end
  end
end
```

The variable `x` is expressed as `{:x, [], Foo}` in the example above.

The way hygiene works is that after a macro is expanded, all variables in the context of the called module, in this case Foo, are assigned a counter that will from now on identify the variable. That's the source of your problem. Once you do this:

```elixir
quoted = quote do
  quote do
    n = 12
    square(n)
  end
end
```

Because `n` is inside a quote, it will be assigned the context of the current module, which is the same as when `square(n)` is defined. This means that, from that moment on, there is no distinction between the variables defined inside of the `square` macro and the one you are passing in.

One solution is not to pass the `__CALLER__` to `eval_quoted` so the code is not first expanded as part of the module itself. Just pass file and line. That's pretty much how the code behaves anyway. At least, it is expanded in the module body and not inside functions (so you don't have things like local function calls anyway). Another idea is to not put precompiled and not precompiled code together in the first place, so you can get rid of eval.

I will leave this open for a while but I am almost certain the result will be "won't fix".

**Comment by josevalim** [comment]
I am closing this one. There isn't a fix for this in Elixir. You will need to handle it in one of the ways i mentioned above.
