### ISSUE TITLE
Online documentation is formatted incorrectly for Process.exit

### ISSUE THREAD

**Issue by lsimoneau** [elixir-lang/elixir#3320]
The markdown for inline code seems to cause the rest of each list point to be formatted as a code block:

![screen shot 2015-05-12 at 11 40 41 am](https://cloud.githubusercontent.com/assets/31768/7578695/d433fe06-f89b-11e4-8741-b0a62f586c53.png)

This is the case for both the stable and master documentation (http://elixir-lang.org/docs/master/elixir/Process.html#exit/2).

The markdown in the module doc seems correct, I can't see any recent edits that would have fixed this issue, and when I build the documentation locally (`make docs`) I get correct formatting. Is the process that generates the online documentation using a different markdown processor?

**Comment by josevalim** [comment]
This is an issue recently fixed on earmark. @ericmj is earmark also updated every time bob builds the docs?

**Comment by ericmj** [comment]
@josevalim Bob will use the locked earmark in ex_doc. There is a bug currently that caused the documentation to fail over the last days. The bug was caused https://github.com/elixir-lang/ex_doc/blob/master/bin/ex_doc#L2-L3 by always using the `dev` environment but bob was running with MIX_ENV=prod causing ex_doc to build into the prod dir.

**Comment by ericmj** [comment]
Master docs have been updated now.
