### ISSUE TITLE
Support delayed evaluation of code in .iex.exs

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#3328]
It is not currently possible to define a module in .iex.exs and import it at once.

```
defmodule MyIExHelpers do
  def s do :init.stop end
end
 
import MyIExHelpers
 
 
λ iex
...
Error while evaluating: /Users/alco/tmp/.iex.exs
** (CompileError) .iex.exs:5: module MyIExHelpers is not loaded but was defined. This happens because you are trying to use a module in the same context it is defined. Try defining the module outside the context that requires it.
    (elixir) src/elixir_exp.erl:123: :elixir_exp.expand/2
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (elixir) src/elixir_exp.erl:49: :elixir_exp.expand/2
```

Even if the module definition is extracted into a separate file, it doesn't work:
```
Code.require_file "my_iex_helpers.exs"
import MyIExHelpers
 
λ iex
...
Error while evaluating: /Users/alco/tmp/.iex.exs
** (CompileError) .iex.exs:2: module MyIExHelpers is not loaded and could not be found
    (elixir) src/elixir_exp.erl:123: :elixir_exp.expand/2
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (elixir) src/elixir_exp.erl:49: :elixir_exp.expand/2
```

A suggested workaround for this would be the ability to return a quoted expression from .iex.exs which would then be evaluated in the IEx process and therefore in a different context from the one the module has been defined in.

**Comment by whatyouhide** [comment]
@alco I'd like to help on this as I feel IEx "custom helpers" (trivial to implement if we fix this) are a very desired feature :). So, let me make sure I got things straight, your suggestion is to delay the evaluation of the (quoted) contents of `.iex.exs` so that they're executed in the IEx process: you mean still defining the module in a different file, right?

```elixir
defmodule Foo do
  def foo, do: 1
end

import Foo
```

should always fail, right?

**Comment by alco** [comment]
@whatyouhide I meant that this should work:

```elixir
defmodule Foo do
  def foo, do: 1
end

quote do: import Foo
```

In other words, the last expression in `.iex.exs` is evaluated as a quoted expression in the context of the IEx shell (more specifically, as the first thing in IEx server's loop, I think), after the file itself has been evaluated normally, by `IEx.Evaluator.eval_dot_iex`.

**Comment by whatyouhide** [comment]
@alco ah, I see. I'm not a fan of this solution from a usability stand point as it looks a little bit cryptic IMO (you need to roughly understand what's going on in order to understand why you're quoting the last expression). That said, I think the solution could work and I can't come up with any better one.

**Comment by josevalim** [comment]
I am not a fan either and since I can't think of anything better too, I think we should roll with it.

@alco shouldn't we also change `import_file` as the whole goal of import_file is to load stuff like this?

**Comment by josevalim** [comment]
Gah, I guess we can't make it work with `import_file` because it works as a macro... :(

**Comment by whatyouhide** [comment]
@josevalim yeah :( we could extract the last `quote` expression from the file when we use `import_file` and keep it separated from the rest, so that we can defer its execution, but it's a (bad) hack which would be a mess to maintain and would include some limitations on `.iex.exs` that users will found weird for sure.

It's a tricky issue for how things are designed right now :(

**Comment by alxndr** [comment]
I'd love to see this feature as well; anything I can do to help?

**Comment by hunterboerner** [comment]
Status?

**Comment by josevalim** [comment]
There is no update. If there was one, it would likely be here. So please avoid pinging issues. :)

**Comment by antipax** [comment]
I'm going to do some r&d on this issue unless anyone opposes. :)

**Comment by whatyouhide** [comment]
@antipax go ahead, this is a really nasty one. :)

**Comment by antipax** [comment]
A couple of ideas I've had:

* add a separate file, like `.iex.helpers.exs`, where you define helpers in the file scope, and we wrap it in a defmodule with a unique name and then import it after

* define a module like `IEx.Helpers.MyApp` in `.iex.exs`, check what modules are loaded before eval, and after we import the ones with the prefix `IEx.Helpers` that weren’t loaded before

**Comment by josevalim** [comment]
@antipax it could be tricky to automatically import all modules :(

The quoted expression approach may work but I think it should be more explicitly opt-in, like:

    {:eval, quote do
        import Foo
      end}

Alternatively, we could use the tuple return to select imports:

    {:import, Foo}

**Comment by antipax** [comment]
@josevalim that works for me, is it ok if I get started on a PR for both of those forms? I'd also add `{:import, [Foo, Bar]}`.

**Comment by whatyouhide** [comment]
For the record, in the months I worked on Elixir since last time, I really started to feel the need for this feature less and less. If I want helpers, I just `defmodule H do ... end` in the `.iex.exs` file and use *two* more characters to get the same effect.

Wdyt if we keep the discussion going a bit before starting to work on a PR?

**Comment by antipax** [comment]
I'm totally fine with waiting. Believe it or not I think I was the one who originally got this issue raised a year ago: https://github.com/elixir-lang/elixir/pull/3232#issuecomment-89026164 😛 

I do think this should be implemented though, if only because I think users should be able to do everything they can do in IEx in a `.iex.exs` (within reason).

**Comment by whatyouhide** [comment]
@antipax yes, that's a good point of course, but returning `{:import, Foo}` (or similar solution) doesn't feel like "doing what they want" IMO, they can't just write Elixir code in `.iex.exs` and call it a day, they explicitely have to know they have to write some "special" parts to make it work.

**Comment by josevalim** [comment]
Ok, let's close this for now and see if people will bring this complain back. Short module names is a good enough starting point.
