### ISSUE TITLE
Remove Float.to_string/2 and Float.to_char_list/2 and use proper representation on Float.to_string/1 and Float.to_char_list/1

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3413]
As per the discussion in the mailing list, `Float.to_string` and `Float.to_char_list` have poor and imprecise defaults. The plan is to remove the functions with arity 2 (one can always use the Erlang version) and make the ones with arity/1 use `:io_lib_format.fwrite_g(float)`.

Of course, we can't remove the ones with arity/2 now, so the plan is to just soft deprecate them for now.

**Comment by doomspork** [comment]
@josevalim what is the best practice for deprecation in Elixir?

**Comment by josevalim** [comment]
Right now we are not deprecating anything. Just adding TODO and removing the docs. Please search for TODO in the repo.

**Comment by doomspork** [comment]
Thanks for the tip, have a great day @josevalim :+1:

**Comment by ewildgoose** [comment]
Please see my code here:
* https://github.com/ewildgoose/elixir-float_pp

This code implements:
a) Optimal conversion of a double, to the shortest list of decimal digits that can be converted back again to the identical double value. (ie you can convert 1.2 to "1.2" and back again to 1.2)
b) Rounding of a list of digits to arbitrary precision in decimal/scientific notation (they are the same thing, just the location of the decimal point changes), ie round 19.999 to 20.0
c) Display of a list of digits in either decimal or scientific format, optionally with zero padding to arbitrary length, ie you can have output of 1.2 or 1.200000 or 1.2e+00

I think a) in particular is re-usable in a number of situations.  

b) could be replaced by other modules, for example a core implementation of a Decimal type would be nice?

Interestingly we can use this module to also resolve the Float.round issue #3400. Examples of using this module to implement Float.round / ceil / floor are here:
* https://github.com/ewildgoose/elixir-float_pp/blob/master/test/rounding_test.exs

**Comment by wishdev** [comment]
@ewildgoose 

While FloatPP.to_string(0.3) works better (in theory) then Float.to_string(0.3) FloatPP.to_string(0.1 + 0.2) certainly does not so I'm not sure anything is gained here. The odds are most items are going to be calculated so this would be problamatic. 

As well with the celi/round/floor functions - this fails if added to your test file

assert ceil(7.14 - 5.94, 2) == ceil(7.11 - 5.91, 2)

**Comment by ewildgoose** [comment]
Can you please also keep an eye on issue #3400.  I think your comment should really be posted there?

This is an interesting example you have found. Because the two numbers are different by 1.2 decimal, this is an irrational IEEE double value, so depending whether you add or subtract the difference you end up with an IEEE value slightly above or below 1.2. This obviously shows up if you chose a rounding which forces the two values in different directions. Essentially you are using rounding to split two values which differ only by the smallest error we can introduce using double calculations.

However, I think we are off topic?  The code I'm proposing here is an implementation of "Printing Floating-Point Numbers Quickly and Accurately" in Proceedings of the SIGPLAN '96 Conference on Programming Language Design and Implementation. This is an "optimal" implementation which finds the shortest decimal string which can be reversed back into the original double value.

Now, additionally I have implemented various "rounding" algorithms, in order to be able to display the output in various different ways. eg we implement truncation, floor, ceiling and various roundings.  

So this issue here, is about whether we should replace the existing Float.to_string implementation with something like my code linked above:

a) If all you need is straightforward printing of the output to N decimal places using "rounding ties upwards", then my code offers you nothing... You have this today with Float.to_string.

b) If you want your output to be human readable, WITHOUT needing to do a bunch of maths to compute decimal precision, then my code will allow you to do FloatPP.to_string(1.2) and get "1.2"  (In contrast, default Float.to_string gives you "1.19999999999999995559e+00" - you would need to know how many decimal places of rounding are optimal to get back to "1.2".  For example if the input changes to 1.21 you need different config of Float.to_string, but no difference to FloatPP.to_string)

c) If you need alternative rounding implementations then you cannot get this from Float.to_string. Eg if you want the output representation of 1.25 to be "1.2" then you will need to implement your own rounding functions.  Note that at present you *cannot* do this accurately using only built-in Elixir functions because the current implementation of Floor/Ceil uses IEEE double multiplication, which then introduces numerical instability and inaccuracies in the rounding algorithm.

I just need to re-iterate c) because I think we might be tripping over it.  The code I'm proposing here *will* reliably implement a specific algorithm to round a given decimal. eg if you ask for any number ending in a 5 to be rounded up, then we will *always* round up all inputs which start out as a decimal ending in 5. This is *not* the case with the current Elixir functions, currently ceil/floor will round slightly differently (and differently to Kernel.round) depending on digits preceding the 5.  I believe we all understand why this is, my point is only that the current implementation is NOT a documented rounding algorithm AND it gives different answers to other Erlang functions which implement rounding. Inconsistent algorithms are bad...

But to be clear - decimals are not accurately handled by IEEE doubles, so once we start doing arithmetic with them, then all bets are off.

BUT: I think that with the aid of documented rounding algorithms, such as we have here, it's possible to achieve certain goals to rescue calculations which have been "damaged" by float calculations.  I need to think this through, but for example I think you can do error analysis on adds/multiplies and as long as you pre-round out the implied imprecision you can recover the original decimal calculation.

Specifically: In your calculation above, I *think* you should observe you have a subtract (negative add) hence you lose precision at the 16th sig figure? So if you first do a "nearest" rounding at the 15th sig figure (scientific: 15) and then do your floor/ceiling I *think* you will correctly recover the decimal calculation?  Be careful, I'm shooting from the hip here? Not 100% sure of this...

My point is that IEEE computations are imprecise, care must be taken not to inadvertently apply them to a decimal value if you want to round trip them! The code I present can accurately recover a decimal value and print it in various formats/precisions.  However, if you inadvertently offset the decimal slightly (as your calculation does) then you need to take manual action to deal with the imprecision introduced.  I think this is out of scope of a pretty printer though?

**Comment by josevalim** [comment]
That's why I asked to not discuss rounding issues here. We are *again* discussing two different topics on a single issue. :)

**This** issue is clear: it is about removing the Float.to_string/2 and Float.to_char_list/2 functions. We are not adding replacements. If you need something else, use `:erlang.float_to_binary/2` or another library (like float_pp).

To be precise: we are not adding float pretty printing with options. We will simply use the existing pretty printing algorithm, without options, in `Float.to_string/1` and `Float.to_char_list/1`.

I am locking this for now to avoid further off-topic discussion. Please ping me on the mailing list or on IRC if you have any questions.

**Comment by josevalim** [comment]
I will do a follow-up comment on #3400.

**Comment by c0b** [comment]
the float_pp looks good and is exactly what I want, could you make it available on hex.pm ? @ewildgoose

**Comment by c0b** [comment]
will lose the convenient `:compact` conversion as a keyword list, will have to write in full format like `:erlang.float_to_binary 7/2, [{:decimals, 4}, :compact]`

```elixir
iex(23)> Float.to_string 7/2, decimals: 4, compact: true
"3.5"
iex(24)> :erlang.float_to_binary 7/2, decimals: 4, compact: true
** (ArgumentError) argument error
    :erlang.float_to_binary(3.5, [decimals: 4, compact: true])
iex(24)> :erlang.float_to_binary 7/2, [{:decimals, 4}, :compact]
"3.5"
```

**Comment by josevalim** [comment]
You can write `[:compact, decimals: 4]`. I don't think this tiny convenience justifies keeping a function that can yield unexpected results, specially because you can also easily do the wrapping yourself as well.
