### ISSUE TITLE
Mix fails to fetch dependency in umbrella project

### ISSUE THREAD

**Issue by jonhkr** [elixir-lang/elixir#3436]
I've created an umbrella project and added an umbrella children that depends on `erlware/relx`, the deps looks like this:

```Elixir
defp deps do
    [{:relx, github: "erlware/relx"}]
end
```

When I run `mix deps.get`, I get the following error:
```
** (Mix) :path option can only be used with mix projects, invalid path dependency for :erlware_commons
```

Is it a bug?

**Comment by bitwalker** [comment]
You no longer need to add a dependency on relx, just taking the dependency on exrm is enough now. There was a bug in relx not long ago which produced that error, but it has since been fixed in relx master (and is fixed in the version hosted on hex.pm which exrm depends on).

**Comment by bitwalker** [comment]
Oh god, I just realized this was the elixir issue tracker and not exrm /facepalm

In any case, this issue was fixed in relx master and is also fixed in the latest release on hex.pm. Ignore the stuff about exrm if you aren't using it.

**Comment by josevalim** [comment]
It looks like a bug given there is no path dependency in erlware_commons or relx.

**Comment by jonhkr** [comment]
@bitwalker Yes, you are right, actually I've got this error while testing exrm. I'm now using the hex.pm instead of github for relx and it is working fine.

Anyway, I also think it is a bug, but I have no idea on how to solve it, though.

**Comment by bitwalker** [comment]
@jonhkr Just to clarify, you don't need to declare the dependency on relx at all actually, it's pulled in by exrm for you. I used to have something in the README about adding it, but that was because relx wasn't up on hex.pm yet.

@josevalim Looking back through the commits in the relx repo, I'm not sure what caused the issue in the first place, since I can't find any references to `erlware_commons` ever having a path dependency, but once it was pushed to hex.pm, it worked again. I think the issue was that pulling in relx as a git dependency while relx was configured to pull it's deps from hex (/cc @tsloughter), as the order events from the exrm side was:

- relx is updated to use hex.pm for it's dependencies
- exrm is still pulling relx as a git dependency
- users installing exrm during this period encounter the error seen above
- relx is pushed to hex.pm (version 2.1.1 for reference)
- exrm changes relx to a hex dependency
- problem disappears

Hopefully that helps track down the problem.

**Comment by jonhkr** [comment]
@bitwalker thanks for the clarification, I've removed the relx dependency from my project, everything is fine now.

I've forgotten to mention that if the `{:relx, github: "erlware/relx"}`  dependency is set on a regular project (not inside an umbrella) everything works.
