### ISSUE TITLE
assert on a match should raise if false or nil

### ISSUE THREAD

**Issue by chrismccord** [elixir-lang/elixir#3488]
assert foo = nil

should raise. Today is passes.

**Comment by chrismccord** [comment]
I'll take this one on with a PR soon

**Comment by edgurgel** [comment]
I'm pretty sure there's some context why this is an issue. What's the reason that `assert foo = nil` should raise? (I'm asking just out of curiosity, I have no opinion about this.)

**Comment by ericmj** [comment]
I'm not sure about this, if you are explicitly matching on false or nil you are doing that because you want to verify something is that value. I don't see the benefit of failing on those values.

**Comment by josevalim** [comment]
@ericmj my rationale was that the behaviour of assert (which is raising on false or nil) should not change because of the `=` operator.

**Comment by ericmj** [comment]
Right, maybe it's just my assumption of how `assert =` is supposed to work. For me it's a match assertion, but I can understand if it should be consistent with the other assertions and be a boolean assertion with matching.

**Comment by fishcakez** [comment]
:+1: for consistency.

**Comment by josevalim** [comment]
I tried adding this but it gets really weird with `refute`. Because things like this will now fail: `refute {:ok, _} = {:error, _}` because the value is not false nor nil (and refute expects only nil and false). So refute needs to be changed to only check for nil or false or only check for matches. Thoughts?

**Comment by josevalim** [comment]
Fixed in master.

**Comment by MSch** [comment]
We just ran into this when upgrading to the latest master 539b71fdf4d3b32a76a933e3e865d9de400ce372.

The new behavior doesn't change anything when `assert`ing on a pattern that's not just a single variable, because only a "single-variable pattern" could be falsy. (e.g. `{:ok, foo}` is always truthy)

But as @josevalim said, this basically makes `refute left = right` useless, because now I can only refute on either `false` or `nil`, I can no longer use `refute` to check if a pattern match fails. And for checking if something is `false` or `nil` I can already use either `refute right` or `refute false == right` if I want to make sure it's `false`.

Only when `assert`ing on a "single-variable pattern" does the behavior change, which reflects IMO one specific use case: I want to bind the result of some function to `foo`, and I want that function to not "fail" by Elixir convention, like e.g. `Dict.get/2` does by returning `nil`, so I write `assert foo = Dict.get(dict, :key)`, expecting that to fail if `:key` is not in `dict`, instead of using `Dict.fetch!/2` or `assert {:ok, foo} = Dict.fetch(dict, :key)`. Is there any other use case for doing `assert foo = nil` (not `assert ^foo = nil`) that I'm missing?

I'm very much with @ericmj about how I would expect `assert` to work, I always assumed `assert left == right` is an assertion that `left` equals `right`, while `assert left = right` is an assertion that `left` matches `right` (and so on for `>`, `<`, etc).

**Comment by josevalim** [comment]
Well, there are definitely two ways to view this but I believe that not changing the semantics of the code is arguably the simplest to explain. All `assert` does is interpret your code and nice errors, it doesn't change the code behaviour.

**Comment by MSch** [comment]
That is a good argument, can't argue against that :) 

What about adding `assert_match` and `refute_match` with the old behavior?

**Comment by josevalim** [comment]
I would hate that but if it is necessary... we can definitely discuss them. @MSch, an you provide some concrete examples of when it would be useful? I did rewrite some assertion on phoenix after this change but they ended-up better.

**Comment by josevalim** [comment]
Also:

    assert match?({:ok, _}, some_fun())
    refute match?({:ok, _}, some_fun())

We could likely make `assert` understand those and provide good error messages for them too.

**Comment by lexmag** [comment]
> We could likely make assert understand those and provide good error messages for them too.

That would be great.

**Comment by josevalim** [comment]
PR please? :)

**Comment by josevalim** [comment]
Or open up an issue!

**Comment by lexmag** [comment]
> PR please? :)

Of course. :smile:
