### ISSUE TITLE
Improve error message for var.foo when var is not a map nor atom (grr, nor tuple)

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3494]

**Comment by c-rack** [comment]
@josevalim could you please provide examples of current and expected error messages?

**Comment by fishcakez** [comment]
@c-rack The current error message is an `ArgumentError` with no message  (actually `:error, :badarg` before normalisation) and a stacktrace pointing to `apply/3` because that is what a dynamic remote call (https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_translator.erl#L270-L273) does in Erlang.

I think we should raise a `RuntimeError` which inspects the term and explains that `var` is not a map or module so can not fetch the value or call the function. There's an example KeyError exception in the function linked above which should help you if your not familiar with exception internals.

The comment "grr, nor tuple" is there because `{atom, ..}` is a valid module name for tuple calls and so we must check also allow that. See #3254 for more info on those.

**Comment by josevalim** [comment]
I am on this already :) should have it in tomorrow.


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Nothing we can do for now, unfortunately.
