### ISSUE TITLE
build_embedded should warn about config set for applications not in :applications`

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#3556]

**Comment by bitwalker** [comment]
This would be nice to have regardless of the `build_embedded` flag (IMO), since it's by far the most common issue people encounter with releases, even with warnings in the exrm docs about it, so :+1: to any progress towards making it more obvious when an app has been missed, but I think it probably makes even more sense to always warn about this.

Also, should it really apply just to `:applications`? Shouldn't it also be the case for `:included_applications`? If an app is not started, `Application.get_env` will still return nil of course, but since an application could be started manually, we probably want to warn for both, since it will catch you in both cases.

**Comment by fishcakez** [comment]
In 1.0.5+ build_embedded is enabled for new :prod in new apps template.
There could be dev/test deps not in :applications so we can't warn always.
Really its a precursor to releases.

Yeah, all nested applications and included_applications. Just lazy with
title. We may need to introduce load_applications or something at some
point to handle load only apps for releases so don't warn for their config.

**Comment by josevalim** [comment]
Reopening because we can still configure compile time dependencies and we shouldn't warn on those too...

**Comment by fishcakez** [comment]
Could we change this so that we warn when starting if a configured application is not in the code path and is not loaded? This way we could always warn - even if not build_embedded - and the warning would never be a false positive.

**Comment by josevalim** [comment]
@fishcakez :+1: let's try that

**Comment by fishcakez** [comment]
Done in https://github.com/elixir-lang/elixir/commit/786089b7225a9f872b14a58837870fba1002885e.

**Comment by josevalim** [comment]
Beautiful. :+1:
