### ISSUE TITLE
Stacktrace cut short

### ISSUE THREAD

**Issue by elliotcm** [elixir-lang/elixir#3562]
The actual bug causing the exception is no doubt my fault, but I have heard previously that unhelpful error messages are considered bugs worth fixing.

In this case the whole of the printed error is:
```
[error] Error in process <0.401.0> with exit value: {#{'__exception__'=>true,'__struct__'=>'Elixir.Protocol.UndefinedError',description=>nil,protocol=>'Elixir.Enumerable',value=><<36 bytes>>},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file... 
```

I'll find the problem eventually but it would've been nice to know the file and line number in my code.

**Comment by fishcakez** [comment]
Hi @elliotcm!

Yes, any unhelpful error is a bug! You can get a much better log because when using `Task.start(_link)` instead of `spawn(_link)`. This will produce a much nicer log message. At some point in the future we may do more to promote the former over the later, see #2795.

Alternatively, upgrade Erlang/OTP to 18.0 and Elixir to 1.0.5. Prior to 18.0 the error was sent as a character list in Erlang format by the VM and so we could not really do anything about it. However in 18.0 the error is sent as a term. Elixir 1.0.5 recognises the 18.0 error messages and formats the error as nicely as possible.

**Comment by elliotcm** [comment]
Thanks @fishcakez, I will do one or the other (or both).
