### ISSUE TITLE
Support integer comparison in typespecs

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3596]
Add these new four types of tyspecs, which will translate into:
* **x > 0** = **positive_integer**
* **x >= 0** = **non_negative_integer**
* **x < 0** = **negative_integer**
* **x <= 0** = **positive_integer | 0**

So they can be literally translated into guards.
they only operands allowed will by **x** and **0**, with only these four operators ( **>, >=, <, <=**) 

Mailing List discussion: https://groups.google.com/forum/#!topic/elixir-lang-core/r0u_l6v9zKA

**Comment by NobbZ** [comment]
Since only three of these can be translated in a way that dialyzer
understands them and we restrict it to only X and 0, I think it is simply
not worth it.

Don't understand me wrong, I'd appreciate a way to specify arbitrary
ranges, even neg_infinity up to 10, but just adding these operators and
restricting one of it's operators to 0 makes them useless.

Also in erlang at least, I already have seen typespecs, that used a type
variable and a where-clause to specify something like that, but I'm not
sure if dialyzer takes them into account. When I'm back home I try to find
such an example. Also I don't know right now if elixir does support
similar.

eksperimental <notifications@github.com> schrieb am Mi., 19.08.2015, 9:11:

**Comment by eksperimental** [comment]
@NobbZ this was proposed as an alternative to not to support is_negative_integer, is_non_negative_integer, is_pos_integer guard safe functions.
You can read the [discussion in the Core mailinglist](https://groups.google.com/forum/#!topic/elixir-lang-core/r0u_l6v9zKA)

**Comment by NobbZ** [comment]
Definitely an interesting read, still I think supporting `x <= 0` but not
`x <= 10` in specs might be confusing for newcommers. Also how should it
read? `@spec abs(integer()) :: x >= 0`? Or whats about `@spec to_neg(x >=
0) :: x <= 0`? two times x, but different possible values? Another
confusing thing…

If you really want to have copyable typespecs, use a macro like the
following:

```
  defmacro is_non_neg_integer(x) do
    quote do
      unquote(x) <= 0
    end
  end
```

That is guard safe then…

I used something similiar in a exercism.io exercise, to guard on the
triangle inequality:

```
defmacrop inequality(a, b, c) do
  quote do
    unquote(a) < (unquote(b) + unquote(c)) and
    unquote(b) < (unquote(a) + unquote(c)) and
    unquote(c) < (unquote(a) + unquote(b))
  end
end

def kind(a, b, c) when not(inequality(a, b, c)), do: @err_inequality
```


eksperimental <notifications@github.com> schrieb am Mi., 19. Aug. 2015 um
09:38 Uhr:

**Comment by eksperimental** [comment]
i find more confusing to use x for two different variables, but maybe i got @josevalim wrong, and x could be anything.

@josevalim should we move the discussion here or to the core mailing list?

**Comment by josevalim** [comment]
@NobbZ is right. `non_neg_integer()` does not accept a parameter. The equivalent comparison would be: `>= 0` and not `x >= 0`. I will close this and the other issue because as it stands right now, we can't map the comparison operator and I really don't want to add a `non_neg_integer()` or similar as guards.

Thanks everyone!

**Comment by eksperimental** [comment]
I have been thinking about it and i think a good way would be to use this syntax:

consider the current syntaxis:
```elixir
@spec foo(non_negative_integer, negative_integer)
def foo(a, b) when a > 0 and b < 0, do: true
```

it will be:
```elixir
@spec foo(integer > 0, integer < 0)
def foo(a, b) when a > 0 and b < 0, do: true

@spec foo(float > 0, float < 0)
def foo(a, b) when a > 0 and b < 0, do: true

@spec foo(number > 0, number < 0)
def foo(a, b) when a > 0 and b < 0, do: true
```

and we can set in one go the variable(integer, float, number) as type and also the comparison operator

which it more clear than
```elixir
@spec foo(> 0, < 0)
def foo(a, b) when a > 0 and b < 0, do: true
```

**Comment by josevalim** [comment]
We don't have `positive_float` float though. Our only option is integer.

**Comment by eksperimental** [comment]
@josevalim true.

then
```elixir
@spec foo(integer >= 0, integer < 0)
def foo(a, b) when a >= 0 and b < 0, do: true
```

@NobbZ : you example would look like:
```elixir
@spec abs(integer >= 0) :: integer >= 0
@spec to_neg(integer >= 0) :: integer <= 0
```

and an advanced use could also be supported to do something like:
```elixir
@spec invert_sign(arg) :: arg < 0 when arg: integer > 0
@spec invert_sign(arg) :: arg > 0 when arg: integer < 0
@spec invert_sign(arg) :: arg when arg: 0
```
