### ISSUE TITLE
String.to_existing_atom/1 in macros has surprising effect

### ISSUE THREAD

**Issue by phanimahesh** [elixir-lang/elixir#3654]
It is possible for the compilation to succeed, and fail immediately with the same codebase when a macro uses `String.to_existing_atom/1`.

See branch `buggy_macro` from https://github.com/phanimahesh/elixir-bugs-poc for a minimal complete proof. Just clone it and run `make`.

It fails consistently for me.

**Comment by ericmj** [comment]
`String.to_existing_atom` will raise if the atom does not exist. An atom will only exist in the system after the module containing the atom literal is loaded or after someone called `String.to_atom` or similar.

I'm guessing you are getting this issues because mix compiles modules in different orders. You can ensure the atom exist in the system by loading the module with `Code.ensure_loaded`.

During compilation I see no reason for using `String.to_existing_atom` since it's used to protect against external input and you should have no such input during compilation.

**Comment by phanimahesh** [comment]
I still consider this a bug because:
 1. It is not obvious what causes the compilation to fail. Anyone trying to reproduce this by cloning the repo and building it will not see the error.
 2. The module defining the macro also has the atoms listed. Hence if it is used and imported, it should be compiled before the module that is using the macro, and the atoms should exist in the system.
 3. The behaviour is consistent no matter how many times I try.

A compile that succeeded should succeed no matter how many times it is recompiled if the code has not changed and compilation does not depend on external environment. Atleast that is what I believe any sane compiler should do.

You may say that the function `String.to_existing_atom/1` depends on the environment, but see point 2 above.

**Comment by josevalim** [comment]
> The module defining the macro also has the atoms listed

It has the atoms listed at *compilation time*. You need to move them to a function otherwise it won't work, regardless if it is a macro or not. It would have failed if you were calling to_existing_atom from a simple function too.

**Comment by josevalim** [comment]
Part of using Elixir macros is understanding the difference between runtime and compile time, this is what making the atoms disappear here. The compilation cycle just make it work by accident, the compilation cycle is not the one that makes it fail.

**Comment by ericmj** [comment]
1. Can you paste the error output?
2. Are you sure? If that's the case it's a VM bug and should be reported to erlang.

> A compile that succeeded should succeed no matter how many times it is recompiled if the code has not changed and compilation does not depend on external environment. Atleast that is what I believe any sane compiler should do.

Yes, as long as you don't depend on side effects, in this case you are depending on the side-effect of loading modules. For obvious performance reasons Mix only compiles files that changed, the second time the project is compiled the modules may not be compiled because they didn't change.

Elixir allows execution of code when compiling so there are always possible side effects that can affect compilation on sub-sequent runs. Example: `if :random.uniform(2) == 1 do raise "..." end`.

**Comment by phanimahesh** [comment]
Thanks!

I already know that:
 1. The atoms were defined as module attributes, and module properties are not persisted unless explicitly registered.
 2. There is a difference between compile time execution and runtime execution.
 3. A module is not recompiled if it has not changed.

But I did not realize that these in combination cause the atoms to be unavailable in Erlang VM's atom table during compilation if one of the dependents changes but the BuggyMacro itself doesn't change.

**Comment by josevalim** [comment]
Just to be clear, the bug is caused by 1. If you treat your macros as regular runtime code, which they are (runtime code running at compilation time), you would have escaped the issue. :)
