### ISSUE TITLE
Inconsistent behaviour in Exceptions when using Exception.exception/1 and Exception.message/1 callbacks

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3663]
This issues is closely related to https://github.com/elixir-lang/elixir/issues/3657

It is recommended by that an exception can be defined with either `Exception.exception/1` or `Exception.message/1` call back,
While they raise with no problem they behave accordingly, when there is a problem building the exception, they will behave different, and the users has no way to know which one to except.

```elixir
iex(1)> raise CompileError 
** (CompileError) got FunctionClauseError with message `no function clause matching in IO.chardata_to_string/1` while retrieving Exception.message/1 for %CompileError{description: "compile error", file: nil, line: nil}
    
iex(1)> raise Code.LoadError 
** (KeyError) key :file not found in: []
    (elixir) lib/keyword.ex:235: Keyword.fetch!/2
    (elixir) lib/exception.ex:659: Code.LoadError.exception/1
```

both raises an exception, because the required  `:file` field was not provided, but they behave differently because `message/1` catches the error, and returns the original exception being called (`CompileError`),
and `exception/1` doesn't do any handling and pass the new exception directly (`KeyError`).

I think we we should either make `exception/1` try/rescue as in `message/1`, or reraise in `message/1` with the new exception that was just thrown.

I have created an test for this
https://github.com/eksperimental/elixir_fail/blob/master/test/exception_vs_message.exs

**Comment by josevalim** [comment]
exception/1 is correct. It fails and you can see your call in the
stacktrace. We shouldn't wrap it because it is the same as calling any
function. The issue is with message, which should never fail and, when it
does, it fails in a completely different place than the one that defines
the exception. Furthermore, message is usually called when you are doing
error reporting, which is where you absolutely don't want errors to happen,
hence the fallback message.

They are different things, happening in different places. They should not
be the same.



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by eksperimental** [comment]
I see it clearly now, once the validation is done, this should not be an issue any more.

**Comment by josevalim** [comment]
Exactly. :)
