### ISSUE TITLE
Missing conflict resolution for subdependencies with :only option

### ISSUE THREAD

**Issue by grundrauschen** [elixir-lang/elixir#3664]
When running `mix test` after downloading the dependencies for a package with the same dependencies in dependencies (two dependencies wanted to use hackage) but just one with the `only: :test` option set, I got the following output:

```
Unchecked dependencies for environment test:
* hackney (Hex package)
  the dependency hackney

  > In deps/httpoison/mix.exs:
    {:hackney, "~> 1.0", [only: :test, optional: false, hex: :hackney]}

  does not match the environments calculated for

  > In deps/hello/mix.exs:
    {:hackney, "~> 1.1.0", [hex: :hackney]}

  Remove the :only restriction from your dep
** (Mix) Can't continue due to errors on dependencies
```

As far as I understood the :only option, it means that a dependency should just be installed when a certain environment is set (:dev or :test) to minimize dependencies in production, but not harm if it is still installed.
In this case I would expect `mix` to resolve the problem to install hackney in any cases because it is required by the second library, but by the first one just in the test environment.
When I override the dependency in the mix file of the library itself, I just get more dependencies that actually needed directly.

**Comment by josevalim** [comment]
Can you provide a mix.exs that reproduces the error? We need a way to
reproduce it to understand what is really wrong. Thank you!

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by grundrauschen** [comment]
Hej José,
Thank you for the fast response.
It happened in the following project: https://github.com/travelping/hello_test_server
There you also find the mix.exs file and can clone the repo to reproduce it if necessary.
I was just running `git pull ...`, `cd ..`, `mix deps.get` and `mix test`.
The same problem occurred when using `MIX_ENV=test mix deps.get` instead.

**Comment by josevalim** [comment]
Here is what is happening:

* the current project specifies coverex, that depends on hackney with only: :test. So you are saying you want hackney only for test

* the project hello specifies hackney for all environments, which means you are saying you want hackney for all environments

The issue though is that those come from different branches in the dependency tree and so far we are only handling cases that come from the same branch. So let's consider those cases side by side.

### Sharing

In the tree below, it is possible to access the parent hackney dependency by going levels up in the child:

    * hackney (parent)
    * some_dep
      * hackney (child)

Let's see what should happen when each of them specify something:

Parent :only | Child :only  | Result
------------------------------------
all          | all          | OK
:test        | all          | Error: the parent is specifying :test but child requires it for all
all          | :test        | OK
:dev         | :test        | Error: the parent is specifying :dev but child requires it for test

So the parent must ensure the dependency is available in the environment the child requires. Note this behaviour happens even when overriding because you can't remove a dependency from a child. So your only option is to guarantee the environment matches, i.e. you can't say the dep will only run on :dev if the child requires it in test, even with override: true.

Now let's consider the cases where the parent is not visible from the child when looking up.

### Non-sharing

    * some_dep
      * hackney (parent)
    * another_dep
      * hackney (child)

We have two options here:

* Automatically merge the enviroments
* Add a dependency alongside some_dep and another_dep that has all the environments from both children. This is required because of what was described in "Sharing" section. Once we add a dependency alongside some_dep and another_dep, we go to the rules defined above, and the only valid mechanism there is to satisfy environments for both dependencies.

Ultimately, both solutions are the same, it is a matter if we want to solve it explicitly or implicitly. For the sharing case, we chose explicit. What we will chose here? Since the only option is to actually merge them, we may as well do it automatically without bothering the user to define it up in the tree.

/cc @ericmj
