### ISSUE TITLE
Consider removing proc_lib overhead in Task.Supervised

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3677]
Of all the benefits given by proc_lib, we cover them all manually:

1. Setting up initial calls
2. Custom error handling

The only thing proc_lib is adding:

1. start_link with acks
2. setting up ancestors

Which we could easily do ourselves. Thoughts? /cc @fishcakez

**Comment by fishcakez** [comment]
What overhead are we hoping to remove from not using `:proc_lib` by rewriting those parts ourselves? I think that only `Task.async` (but not `Task.Supervisor.async`) might be slightly faster to start because we can spawn, link and monitor atomically. However if that performance difference is noticeable, the task fun must surely be very fast that concurrency may be counter productive?

I am unsure if setting the initial call or ancestors will do anything when not using `:proc_lib`, i.e. whether debug tools will read them (except when showing process dictionary) or if `:proc_lib` will use the ancestors when spawning a child.

I don't think we cover the same error handling as `:proc_lib`. `:proc_lib` always does it owns logging, it sends a sasl `crash_report`, which contains information about the parent if it isn't trapping exits and other linked processes. These process would not send their own `crash_report` because the exit signal will cause them to exit abruptly.
```
10:35:15.980 [error] Process #PID<0.125.0> terminating
Initial Call: Kernel.exit/1
Ancestors: [#PID<0.123.0>]
Messages: []
Links: [#PID<0.123.0>]
Dictionary: []
Trapping Exits: false
Status: :running
Heap Size: 376
Stack Size: 27
Reductions: 106
Neighbours:
    #PID<0.123.0>
        Initial Call: :erlang.apply/2
        Current Call: :code_server.call/2
        Ancestors: []
        Messages: []
        Links: [#PID<0.125.0>]
        Dictionary: [iex_history_start_counter: 1, iex_history_counter: 1]
        Trapping Exits: false
        Status: :waiting
        Heap Size: 2586
        Stack Size: 35
        Reductions: 1059
** (exit) :foo
    (elixir) lib/task/supervised.ex:103: Task.Supervised.exit/3
    (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
```
The initial call of the parent would usually be of the form: `MyOTPCallbackMod.init/1` but the example was from the shell. This is something that `:proc_lib` is adding that we wouldn't replicate and is nice to have but might be rarely used.

**Comment by josevalim** [comment]
I meant more as conceptual overhead than performance overhead. Today, it is hard to look at task and know what it does. I need to understand proc_lib first. If we gain little from proc_lib (which is the question here), it may be worth removing it. It is mostly your decision to make, @fishcakez. :)

**Comment by fishcakez** [comment]
Using `:proc_lib` shouldn't effect the code greatly :/, perhaps we can cleanup the implementation a little.

**Comment by fishcakez** [comment]
I think #3878 is all we can do here.
