### ISSUE TITLE
Consider adding keyword/0 and keyword/1 built-in types

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3679]
Since keyword and map are used a lot side by side, it feels inconsistent to write "Keyword.t | map". It is probably preferrable to treat both as built-in types.

/cc @fishcakez @ericmj. Thoughts?

**Comment by fishcakez** [comment]
OTP deprecated several native types in 18, and uses `module.type` now. It would be interesting if the reasoning is available anyway.

Do you mean `keyword/2`, i.e. `keyword(key, value), not `keyword/1`?

**Comment by fishcakez** [comment]
Forgot to say, it would be very convenient to have the built in types :).

**Comment by josevalim** [comment]
The key type is always `atom()`. If you want a particular atom, then you should probably be using `[key: type()]` anyway.

**Comment by fishcakez** [comment]
Why would someone use `Keyword.t` | `map` and not `Dict.t`? If we are using it a lot, are we promoting an anti-pattern?

For keywords on their own I much prefer:
```elixir
@type option :: {key, value} | {key2, value2}
@spec fun([option]) :: :ok
```
Over:
```elixir
@type options :: [key: value, key2: value2]
```
Because the later is not composable. I literally sigh and curse like a grumpy old man every time I see it used by a library where I may want to use `Keyword.split` to split options between multiple functions. In that case I have to redefine type:
```elixir
@type option :: {key, value} | {key2, value2} | {new_key, new_value}
@spec caller([option])
```
When I could just do:
```elixir
@type option :: Module.option | {new_key, new_value}
```
A classic example is `GenServer.options`.

**Comment by josevalim** [comment]
@fishcakez good point. Btw, feel free to change `GenServer.options`.

Regarding `Dict.t`, my plan is to have it gone by 2.0. I have no idea if it will actually happen but here is my thought process:

1. We will only have two dicts in Elixir, Keyword and Map

2. Most of the common functionality can be done with Access (get and update) and Enum (traversing and merging) anyway

If there is something extremely important, maybe a direct put or pop operation, it can be absorbed by Access.

**Comment by fishcakez** [comment]
Seems like a good idea then :+1:

**Comment by whatyouhide** [comment]
This can be closed :tada:
