### ISSUE TITLE
Potential regression in Elixir 1.1 re NIF compilation

### ISSUE THREAD

**Issue by MSch** [elixir-lang/elixir#3728]
https://github.com/elixircnx/comeonin uses a NIF for bcrypt. On Elixir 1.0.5 it compiles nicely, on Elixir 1.1 the first time it's compiled it fails because the `.so` isn't found, on the second try it succeeds.

See https://github.com/elixircnx/comeonin/issues/40 for the exact steps to reproduce and a sample repo.

**Comment by ericmj** [comment]
This happens because comeonin writes the .so file into the local project's priv/ instead of `:code.lib_dir(:comeonin, :priv)`. It works the second time because the `priv -> _build/.../comeonin/priv` symlink is only created if `priv` exists.

comeonin should be fixed to use proper dirs but maybe we should force create priv if it doesn't exist?

**Comment by josevalim** [comment]
We need to fix this or have an official answer for it. I will think a bit
more on the topic.
