### ISSUE TITLE
as_boolean/1 type is not documented anywhere

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3788]
I found out that `as_boolean/1` is an Elixir built in type, but it is not documented anywhere.
It should be added it to the list in Kernel.Typespec

**Comment by josevalim** [comment]
Yes, please. Those are all Elixir built-in types: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir.erl#L12-L15

**Comment by tejasmanohar** [comment]
@eksperimental Unless you've already started, I'd like to help out on this issue to get more familiar w/ Elixir's core. I see `boolean()` defined [here](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/typespec.ex#L97) in [`elixir/lib/elixir/lib/kernel/typespec.ex`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/typespec.ex). Is that different from what's missing here? Sounds like functionality should be the same; is there a difference I'm missing?

**Comment by eksperimental** [comment]
yes @tejasmanohar go for it
but someone else sent a https://github.com/elixir-lang/elixir/pull/3833, i don't know if it covers all of the built-in functions

**Comment by tejasmanohar** [comment]
@eksperimental Is the definition of the `as_boolean()` function in PR #3833 correct? If so, I'll pass on this one since looks like the issue will be closed. I'll look through to see if there are any other types missing though.

How is the `as_boolen()` type different from `boolean()` already listed there? Trying to find this in the source...

**Comment by eksperimental** [comment]
boolean is the same as `true | false`

as_boolean(),  is a funtions that returns `true | false`

**Comment by eksperimental** [comment]
@tejasmanohar if you want to look into it, @fishcakez mentioned that OTP 18, either removed or introduced new types ( i can't recall exactly).. you may want to update those in either case.. since 1.2 supports only OTP 18.

**Comment by barisbalic** [comment]
@eksperimental @tejasmanohar of the three linked to by @josevalim it looked like `as_boolean/1` was the only one missing from the list of built-ins.  I was unsure of how it should be defined because other built-ins look like calls, `improper_list` for example is "defined" as `improper_list(t1, t2)`.  I'm a bit noobish regarding typespecs and erlang so if this was wrong, I apologise!

**Comment by josevalim** [comment]
It should be `as_boolean(t)`. `as_boolean` is used to signal that the result will be considered true, if the given type is anything other than true or false. It does not imply that true or false will be returned. It is used as documentation purpose.

**Comment by josevalim** [comment]
: :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
> It should be `as_boolean(t)`. `as_boolean` is used to signal that the result will be considered true, if the given type is anything other than true or false. It does not imply that true or false will be returned. It is used as documentation purpose.

@josevalim so if the result is `nil` will it be considered `true` ?
