### ISSUE TITLE
`Task.await/2` should abort with a friendly error when called from a different process then the original caller

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#3894]
Following up on a [discussion from the core mailing list](https://groups.google.com/d/msg/elixir-lang-core/nDM6DfEQv2o/CoyT2HvuCAAJ).

@josevalim, you mentioned adding an `owner` field to the `Task` struct.  This is also the implementation I had in mind.  Any gotchas I should be aware of before I take a stab at implementing this?  In particular, are there any other functions besides `Task.await` that should also abort if called from a different process than the task owner?

I also wonder if `owner` is the right name for the field.  I like it, but the docs use "caller".  I think I'd prefer `owner` if not for the different terminology used by the docs.

**Comment by josevalim** [comment]
@myronmarston I think owner is better because, in the future if we allow you spawning a task to be read elsewhere, we don't care about the caller, but the owner.

We need to change await, shutdown and yield. Keep in mind it should look something like this:

    def await(%Task{owner: owner}, _timeout) when owner != nil and owner != self() do
      raise ArgumentError, "..."
    end

We need the "nil" check so we don't break other things building tasks and not setting up the owner. Please leave a TODO above every check with something like this: "# TODO: Remove nil check on Elixir 1.3"

**Comment by myronmarston** [comment]
Will do.  I'm heading out of the office but I plan to take a stab at this tomorrow.  Thanks!

**Comment by myronmarston** [comment]
BTW, is `ArgumentError` the right exception to raise?  It seems like the problem is who the caller is, not what the argument is, but I guess that's a matter of perspective.

**Comment by josevalim** [comment]
I think `ArgumentError` is alright. Awesome, more tomorrow then! :)
