### ISSUE TITLE
`Task.shutdown/2` never times out when called when its monitor has already been received or cancelled

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#3896]
In working on #3895, @katiespiders and I noticed something odd about `Task.shutdown/2`: it never times out when called from a non-owner process.  In contrast, `Task.await/2` and `Task.yield/2` do properly timeout.  Here's a short snippet demonstrating the problem:

``` elixir
caller = self()
spawn fn -> send caller, Task.async(fn -> :timer.sleep(:infinity) end) end
task = receive do: (t -> t)
Task.shutdown(task, 1)
```

If you run this, it just sits there indefinitely.  If #3895 gets merged this may be a moot point as that will make it raise an error in this case, but it seems like there's a bug in the timeout mechanism and it perhaps deserves a closer look.

**Comment by josevalim** [comment]
The reason is because shutdown will trigger a brutal_kill after timeout which always kills the tasks. Unfortunately, we would never notice the task was dead though because of the wrong owner. So your patch definitely solves this issue too. Thank you!

**Comment by fishcakez** [comment]
The reason for these tasks functions for blocking is that the task's monitor does not exist in the calling process and so can't be received. We can only be sure this is true for sure if the caller is not the owner but the useless blocking could still occur if the caller is the owner if the monitor does no exist. With `shutdown/2` we can still block forever with the owner process because the it waits for the `:DOWN`.

It is probably possible to perform a dance using a second monitor to not block forever if the monitor does not exist.

**Comment by lexmag** [comment]
@fishcakez if you remember we had a discussion about relevant issue with `Task.shutdown/2` – double call on same task.

**Comment by fishcakez** [comment]
@lexmag yes I do but do you remember what was said about it? I was inclined not to handle these cases because the documentation was clear. However if they are causing people to trip up we may need to look at this.

I am particularly concerned with someone attempt to `shutdown/2` inside a `terminate/2` clause, where `Task.await/2` was called in a callback that crashed and so the monitor does not exist. `shutdown/2` is not needed however because the processes exit signal will propagate to it.

**Comment by lexmag** [comment]
@fishcakez the "documentation make it clear the monitor needs to exist" and "all `Task` funs rely on the monitor being active" were the arguments to wait with a second monitor until it triggers any complaints. :smile:

**Comment by josevalim** [comment]
I think we should still wait and see if anyone will reach it, specially now with the new safeguards.
