### ISSUE TITLE
doc_test_test.exs is not using 4 spaces for indenting iex> code

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3918]
https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/test/ex_unit/doc_test_test.exs

the tests here are not being properly indented with 4 spaces as in the rest of the elixir code.
while the test pass, i think it makes more sense to follow the standard of coding.

```elixir
defmodule ExUnit.DocTestTest.IndentationMismatchedPrompt do
  @doc ~S'''
  iex> foo = 1
   iex> bar = 2
  iex> foo + bar
  3
  '''
  def mismatched, do: :ok
end |> write_beam
```

in addition to this, I can add a test that checks doc_test are valid when indentation of 0, 1, 2, 3, 4, 5, 10 spaces are given

just let me know if you are interested in this fix.

PS: this code is the only code that uses iex> with not 4 tabs in the whole code base

**Comment by josevalim** [comment]
I would leave it as is because they are meant to be test files. There are
some particular examples that follow specifically the documentation style
but I don't think we should be worried about consistency here.



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by eksperimental** [comment]
Alright
