### ISSUE TITLE
Give helpful error message if a string is used to name a GenServer/GenEvent/Agent etc.

### ISSUE THREAD

**Issue by TattdCodeMonkey** [elixir-lang/elixir#3932]
I recently came across an exception when I tried to name a GenServer using a string. The same will happen for GenEvent, Supervisor, Agent etc.

```elixir
iex(1)> pid = GenEvent.start_link(name: "this is a test")
** (CaseClauseError) no case clause matching: "this is a test"
    (elixir) lib/gen_event.ex:375: GenEvent.do_start/2
iex(1)> pid = GenEvent.start_link(name: :this_is_a_test)
{:ok, #PID<0.60.0>}
``` 
Instead of ` (CaseClauseError) no case clause matching: <string>` would it be possible to match on name keyword being a string and throw a more helpful error message?

**Comment by josevalim** [comment]
This is a tricky question. It would be really annoying to add such clauses to every time we parse a parameter. On the other hand, the error messages could be clearer. Ideally, it would be great to do such programatically.

**Comment by bill-mybiz** [comment]
I know this is closed, but I am still pretty new to Elixir and I just got bit by this. This GitHub issue itself + Google was what helped me figure it out, because I was not explicitly passing a string but was passing in `context.test`, and it was not obvious that this was the problem.

I mention this because there have been so many awesome error messages so far with Elixir that it has really helped overcome the lack of intellisense/type inference that I am used with with tooling in other languages (I am a continuing convert from the Windows world). So, yes, I would say it would get annoying for individual messages for all parsing errors, absolutely!...But Elixir's documentation has been so superior in almost all regards and is one of its shining qualities :heart:, so this would have been a great error message tweak for newbs like me! :wink:

**Comment by josevalim** [comment]
Thank you @bill-mybiz! @TattdCodeMonkey looking back I may have closed this a bit too hastily, sorry about that. Since this is a common case, let's definitely improve the error message, both on start_link and whereis.

**Comment by whatyouhide** [comment]
Since we should likely do this for `GenEvent` and `Supervisor` as well, should we abstract this somewhere @josevalim?

**Comment by whatyouhide** [comment]
@alecspopa I think we're missing such error only in `Agent`, correct?

**Comment by josevalim** [comment]
Doesn't Agent use GenServer?

**Comment by whatyouhide** [comment]
Whoops, it does, I'm already getting tired today 😛 Sorry!
