### ISSUE TITLE
Allow guards in `with` and `for` matches 

### ISSUE THREAD

**Issue by zambal** [elixir-lang/elixir#4015]
As discussed here:
https://groups.google.com/d/msg/elixir-lang-core/lzNhT87-XUU/Wn4EANOkEQAJ

This would make patterns like this possible:

```elixir
iex> with x when x < 2 <- 4, do: :ok
4

iex> with x when x > 2 <- 4, do: :ok
:ok
```
and
```elixir
iex> for x when x < 2 <- 1..4, do: x
[1]
```

**Comment by zambal** [comment]
BTW, I tried to make a pull request myself, but having no experience with the Erlang side of Elixir's implementation, all the stuff going on in in elixir_exp:expand/2 is a bit too advanced for me at the moment to implement this idiomatically. However, if I can help out with writing tests or updating documentation, please let me know!

**Comment by lexmag** [comment]
I'm wondering, shall we support guards in `with` though? Of so, we'll have two ways for quite the same thing:
```elixir
for x when x < 2 <- 1..4, do: x
# same as
for x <- 1..4, x < 2, do: x
```
Note that the way we have today isn't real guard and accepts any expression.
Otherwise, I think we could make it consistent with `with` by having real guards and treating any "bare" expression as just an expression inside.
@josevalim what are your thoughts on it?

Hey @zambal, we could team-up on it if you'd like, I could ping you when initial implementation will be done. :bowtie:

**Comment by zambal** [comment]
@lexmag Yes, I like :) Please ping me when I can help.

**Comment by josevalim** [comment]
It doesn't make sense to use guards along-side "with" but I would still
support them for consistency.

**Comment by lexmag** [comment]
@zambal ping. :)
I got working guards in `for`, and they are available in `with` but lacking documentation.

**Comment by lexmag** [comment]
Documented in #4334.

**Comment by zambal** [comment]
@lexmag Sorry for missing the ping. My GitHub activity was almost non existing for the last couple of months. But awesome to see that this has been implemented in the meanwhile :)
