### ISSUE TITLE
mix optional dep requirement clashing with only

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4025]
In my library, ecto_fixtures I am setting `postgrex` to be a test env only dep: https://github.com/dockyard/ecto_fixtures/blob/e0cf50ed3fde682fb5e90f9ab480978b1ca6b325/mix.exs#L46

but with Elixir 1.1 I get the following error:

```
Unchecked dependencies for environment test:
* postgrex (Hex package)
  the dependency postgrex

  > In mix.exs:
    {:postgrex, "> 0.0.0", [hex: :postgrex, only: :test]}

  does not match the environments calculated for

  > In deps/ecto/mix.exs:
    {:postgrex, "~> 0.9.1", [optional: true, hex: :postgrex]}

  Remove the :only restriction from your dep
** (Mix) Can't continue due to errors on dependencies
```

I've confirmed that this does not exist on Elixir 1.0.x

/cc @bcardarella

**Comment by ericmj** [comment]
Isn't the error because in Elixir 1.1 we enforced that a dependency should always be in the same environment?

Ecto has a dependency on postgrex, ecto is in the prod environment hence its dependency postgrex should also be in prod. This clashes with the top-level definition of postgrex which is in the test env. It shouldn't matter that ecto has set postgrex as optional.

**Comment by bcardarella** [comment]
@ericmj but Ecto's postgrex dependency is optional. Am I mistaken in understanding in the purpose of that option?

**Comment by ericmj** [comment]
@bcardarella Optional only means that ecto will only use the dependency if it has also been defined higher up in the dependency tree, like you have done. Optional dependencies, such as mariaex, that have not been defined higher up will not be used.

Optional was added as a way for a library such as ecto to set version requirements on dependencies it may or may not use. For example, you don't want to fetch the mysql driver when you only postgres. It also makes sure that postgrex is compiled before ecto.

**Comment by bcardarella** [comment]
@ericmj so does the dependency still get installed and compiled despite it not being used?

**Comment by josevalim** [comment]
@ericmj right, the bug is that he needs postgrex only for tests, to test the integration with Ecto. He definitely does not need to make it a production dependency. We should just skip such checks if the dependency is optional.

**Comment by ericmj** [comment]
@bcardarella If you have defined it as a dependency of your project it will be fetched and compiled, otherwise it won't.

We error in this case because we try to merge your dependency definition with the one in ecto, it clashes because you and ecto have specified different environment. But it seems like we should be able to handle this in a better way if the dependency is optional according to @josevalim.

**Comment by bcardarella** [comment]
sounds good, if someone can point me in the right direction in the source I can take a stab at fixing this

**Comment by josevalim** [comment]
Code: https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/dep/converger.ex#L215-L258

Tests: https://github.com/elixir-lang/elixir/blob/master/lib/mix/test/mix/dep_test.exs#L276-L422
