### ISSUE TITLE
Strange compile error: macro with defstruct and rescue

### ISSUE THREAD

**Issue by skirino** [elixir-lang/elixir#4055]
I've been playing around Elixir macro and one day I encountered a strange compilation error.

Here's a simplified mix project that reproduces the issue (with some notes):
https://github.com/skirino/elixir_struct_compile_order_issue
There are 3 modules:
- A macro that is expanded to a `defstruct`, but with a try-rescue
- A module that invokes the macro (i.e. defines a struct)
- A module that contains a function which uses the struct

I believe the code should be compiled but `mix compile` results in the following error:
```
$ mix compile
Compiled lib/macro.ex

== Compilation error on file lib/struct_user.ex ==
** (CompileError) lib/struct_user.ex:2: S.__struct__/0 is undefined, cannot expand struct S
    (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3

```

Apparently when compiling "the user of the struct", "the struct" must be defined beforehand. Usually this kind of flow control is automatically done by the compiler, but in this specific case, the compiler is somehow confused.
Any idea what's going on?

**Comment by josevalim** [comment]
Yes, this is a compiler bug one that is not easily fixable. The main issue is that, every time you try to invoke a module during compilation, Elixir will wait until that module is available. If that module is not available, we will raise and mark the module as tainted. Once that module needs to wait on another module, in this case, `%S{}`, it won't wait because it has been marked as tainted.

Can't you use Code.ensure_compiled? and function_exported?/macro_exported? instead of relying on try/rescue?

**Comment by skirino** [comment]
Thank you for your comment Jose!
I now understand a bit more about how Elixir compiler resolves interdependencies between modules.

Concerning my macro-related project, I'm not stuck with this bug; I can live without `module_info` and `try-rescue` in macro. So personally I don't care if it won't be fixed for a while. :)
(This is just a nitpicking but `Code.ensure_compiled?` does not save us sicne it relies on `mod.__info__` under the hood: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/code.ex#L549 .)

**Comment by josevalim** [comment]
Good point. Let's leave this open, I will need to tinker on this one for a while until we come up with a solution.
