### ISSUE TITLE
Access syntax should raise when used on lists and key is not an atom

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#4071]
```elixir
list = [{0, "a"}]
list[0] # <= this does not raise
Keyword.get(list, 0) # <= this raises correctly
```

We can't check if the full list is correct because we use `:lists.keyfind/3` for performance reasons, but we should at least check that the given key is an atom.

**Comment by liveforeverx** [comment]
Why it shouldn't be possible to use something else instead of keys? For maps it is possible.

I'm not sure, but I think, that since this `bug` exists we use it for binary keys in lists.

**Comment by ericmj** [comment]
@liveforeverx Because `Access` is implemented for `Keyword` where only atoms are allowed for keys. Map is another data structure where any type is allowed for keys.

**Comment by liveforeverx** [comment]
@ericmj Understand, but it is a very synthetic restriction, which is not possible to overwrite, since `Access` is not protocol anymore.

This will transform code: `data["key"]` to something much more verbose: `List.keyfind(data, "key", 0)` if it used by many people... I'm not sure, if it used oft or not, or it is considered a bad style to get values but something else instead of atoms with Access protocol.

**Comment by ericmj** [comment]
@liveforeverx If you need a data structure that supports the access syntax and arbitrary types for for keys you should use maps. This is an inconsistency in the language that should be fixed, this is the only place where keyword can be used with any type for the keys.

**Comment by josevalim** [comment]
What did we do on 1.0?

**Comment by ericmj** [comment]
> What did we do on 1.0?

https://github.com/elixir-lang/elixir/blob/v1.0.0/lib/elixir/lib/access.ex#L48

**Comment by josevalim** [comment]
That settles it, thanks @ericmj.
