### ISSUE TITLE
Elixir crashes on Windows 10.

### ISSUE THREAD

**Issue by GeorgeGibson** [elixir-lang/elixir#4092]
Every time I run Elixir, I get this: `{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_it,1,[{file,"init.erl"},{line,1054}]},{init,start_em,1,[{file,"init.erl"},{line,1034}]}]}}`. I installed using Chocolatey, and definitely have the Windows executables. I'm on Windows 10 with all updates installed. A pastebin of the crash dump can be found [here](http://pastebin.com/a2Pt6Bk9).

**Comment by josevalim** [comment]
This happens because we cannot find Elixir beam files inside lib/elixir/ebin directory. Copying @OnorioCatenacci in case he can help :)

**Comment by OnorioCatenacci** [comment]
Double check that both the Erlang exe's and the Elixir batch files are in
your path.  You can do this by typing "erl" (less the double quotes of
course) at a command prompt.  Also add the
/ProgramData/Chocolatey/lib/Elixir/bin directory to your path.  I may be
wrong on that directory because I am replying from my phone so I can't
double check my Elixir machine.

**Comment by GeorgeGibson** [comment]
@josevalim @OnorioCatenacci Found out the problem: Chocolatey had installed copies of the `.bat` files in it's own `bin` directory, and they were higher in the `PATH` variable.

**Comment by josevalim** [comment]
Thanks @OnorioCatenacci and @GeorgeGibson!
