### ISSUE TITLE
Allow erlang/yecc/xerl compilers to abort on first error

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4107]
Today those compilers show all errors which sometimes may be inconvenient. We should support aborting on first error.

Original report: #4099

**Comment by whatyouhide** [comment]
Do we have an API in mind for selecting to abort on first error vs. continue? I'd love to give this a try.

**Comment by josevalim** [comment]
Nothing in particular, @whatyouhide. Suggestions are welcome.

**Comment by whatyouhide** [comment]
I'm looking into this. Aborting on the first error is not trivial because `yecc`/`leex` have no way of doing that. To me it looks like the only solution is to pass `[report: false, return_errors: true]` to `:yecc.file/2` and `:leex.file/2` so that errors are not printed but returned (as in `{:error, errors, warnings}` instead of just `:error`). That way, we can take just the first error for each file, format it with `:yecc.format_error/1` and only print that. Wdyt of this strategy? I don't love it as we have to reformat stuff as `yecc`/`leex` do in order to avoid confusion; it may be worth to always set `report: false` and always manually set `return_errors: true` and print errors at this point.

**Comment by josevalim** [comment]
Agreed. We should just own the error formatting then.

On Friday, January 1, 2016, Andrea Leopardi <notifications@github.com>
wrote:

> I'm looking into this. Aborting on the first error is not trivial because
> yecc/leex have no way of doing that. To me it looks like the only
> solution is to pass [report: false, return_errors: true] to :yecc.file/2
> and :leex.file/2 so that errors are not printed but returned (as in {:error,
> errors, warnings} instead of just :error). That way, we can take just the
> first error for each file, format it with :yecc.format_error/1 and only
> print that. Wdyt of this strategy? I don't love it as we have to reformat
> stuff as yecc/leex do in order to avoid confusion; it may be worth to
> always set report: false and always manually set return_errors: true and
> print errors at this point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4107#issuecomment-168303281>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fishcakez** [comment]
I think the proposed solution by @whatyouhide is trying to do something different to the complaint in #4099. I think we want to show all errors/warnings of the first Erlang file to fail to compile and then error. Currently the compiler will try to compile all files regardless of failures.

**Comment by whatyouhide** [comment]
Yeah, @fishcakez is right, I guess the main problem is that all files are compiled, regardless of there being an error in one of them. This happens because of `Mix.Compilers.Erlang.compile/6`, which doesn't abort on the first error (in fact, the same behaviour happens for yecc/leex/Erlang files). I'm not sure what the best approach is here, we may add an option like `:erlc_abort_on_first_error` or something like that (using `:erlc` as in `:erlc_paths` since the option would be shared by all the "Erlang" compilers).

**Comment by josevalim** [comment]
What if we just drop it for now and wait until more people are interested on this?

**Comment by whatyouhide** [comment]
@josevalim yeah I guess for now it may not be worth it as the changes are more extended than I expected. :\
