### ISSUE TITLE
`mix compile.elixir --elixirc-paths <path>` breaks using manifest to detect changes. 

### ISSUE THREAD

**Issue by hamiltop** [elixir-lang/elixir#4122]
Originally reported in https://github.com/phoenixframework/phoenix/issues/1432

Whenever `mix compile.elixir` is run, it updates the `.compile.elixir` manifest, and therefore its `mtime`. This happens even when `--elixirc-paths` is provided.

Whenever `mix compile.elixir` is called, it compares the `mtime` of each file in the `elixirc-path` and only compiles it if it is newer than the mtime of `.compile.elixir`.

The result is that if `--elixirc-paths` is provided, it prevents modified files outside of those specified paths from being compiled ever (unless the force flag is provided).

To reproduce:

`mix.exs`:
```elixir
  def project do
    [app: :test_lib,
     version: "0.0.1",
     elixir: "~> 1.2-rc",
     elixirc_paths: ["lib", "lib2"],
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end
```

Two files, `lib/a.ex` and `lib2/b.ex` are both valid modules.

1. `mix compile`
2. `touch lib/a.ex`
3. `touch lib2/b.ex`
4. `mix compile.elixir --elixirc-paths lib2`
5. `mix compile`

Following those steps, you will only see `lib2/b.ex` recompiled. Compare to:

1. `mix compile`
2. `touch lib/a.ex`
3. `touch lib2/b.ex`
4. `mix compile`

Where both `lib/a.ex` and `lib2/b.ex` are compiled.

**Comment by hamiltop** [comment]
Proposal: Scope `.compile.elixir` to each `elixirc_path`. You would then have:

`.compile.elixir.lib`
`.compile.elixir.lib2`

You can then compare the mtimes for each, fixing the issue.

**Comment by josevalim** [comment]
Thanks for the detailed report!

Phoenix had exactly this same problem when it came to configuration files. We have fixed this in Phoenix by checking if any configuration file changed and, if so, we aborted telling users to restart the server. We could do the same for files outside of the `--elixirc-paths`.

Alternatively, having different manifest files could work too and it doesn't seem to be a big change but Phoenix may want to do the check above anyway. Otherwise folks may expect changes in lib to just work.

That said, we have two options:

1. raise if something outside elixirc_paths changes
2. have one manifest per elixirc_paths

/cc @chrismccord

**Comment by chrismccord** [comment]
Either approach is fine with me. In Phoenix's case, raising makes sense because it protects the users from confusion of why changes aren't being picked up.

**Comment by hamiltop** [comment]
Doesn't raising undermine the entire purpose of `--elixirc-paths` ? If we
raise we are no longer limiting ourselves to just the provided paths. A
change in any of the original paths is going to affect compile. It is very
different behavior than if I were to edit mix.exs and provide the same
limited set of paths, which is what a command line overrode suggests.

If we go that route, I think the naming and semantics need to change.

If we go the multi-digest route, then we may want to add a separate warning
to Phoenix when something in lib changes.

**Comment by hamiltop** [comment]
I took a look at the code and in a lot of ways (if I'm reading the code correctly) this will greatly simplify some of the code.

In order to support `elixirc-paths`, the code is currently written to filter out entries in the manifest that aren't part of the specified paths. We then add those entries back in after compiling. If we scope each manifest to a particular path, the notion of `skip_entries` is gone, since by definition each file in a manifest will only contain files from that path.

Does that sound correct? My implementation is going to gut quite a bit of code here, so I want to make sure I'm not overlooking anything.

**Comment by josevalim** [comment]
The notion of skip entries will be gone but, because we need to process all manifest entries together, when writing down those files we will need to detect and break them apart into different manifest files. So reading will be easier but writing will get more complex. At the end we will likely end-up with the same amount of code. :)

**Comment by josevalim** [comment]
So to be clear, your implementation sounds correct, as long as you process all manifest entries together. You should not process each manifest in isolation as then it would be unable to recompile parts of lib2 when parts of lib1 change.

**Comment by hamiltop** [comment]
I'm trying to test the behavior you describe: "it would be unable to recompile parts of lib2 when parts of lib1 change."

When is that necessary? It looks to me like we only depend on `:external_resource` attributes. Is that the only case?

**Comment by josevalim** [comment]
If lib2 depends on a module from lib1, changing the module in lib1 should
recompile only that module from lib2 (when both paths are present).

On Tuesday, December 29, 2015, Peter Hamilton <notifications@github.com>
wrote:

> I'm trying to test the behavior you describe: "it would be unable to
> recompile parts of lib2 when parts of lib1 change."
>
> When is that necessary? It looks to me like we only depend on
> :external_resource attributes. Is that the only case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4122#issuecomment-167866494>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by hamiltop** [comment]
How do we define "depend"?

Using 1.2.0-rc1:

```
➜  test_lib  cat lib/a.ex
defmodule A do
  def hi do
    B.hi
  end
end
➜  test_lib  cat lib2/b.ex
defmodule B do
  def hi do
    IO.puts "Hello!"
  end
end
➜  test_lib  mix clean
➜  test_lib  mix compile
Compiled lib/a.ex
Compiled lib2/b.ex
Generated test_lib app
Consolidated List.Chars
Consolidated String.Chars
Consolidated Collectable
Consolidated Enumerable
Consolidated IEx.Info
Consolidated Inspect
➜  test_lib  touch lib2/b.ex
➜  test_lib  mix compile
Compiled lib2/b.ex
➜  test_lib
```

However, if `@external_resource` is used:

```
➜  test_lib  cat lib/a.ex
defmodule A do
  @external_resource "lib2/b.ex"
  def hi do
    B.hi
  end
end
➜  test_lib  mix compile
Compiled lib2/b.ex
Compiled lib/a.ex
Generated test_lib app
Consolidated List.Chars
Consolidated Collectable
Consolidated String.Chars
Consolidated Enumerable
Consolidated IEx.Info
Consolidated Inspect
➜  test_lib  touch lib2/b.ex
➜  test_lib  mix compile
Compiled lib2/b.ex
Compiled lib/a.ex
➜  test_lib
```

So is `@external_resource` the only dependency mechanism? or should A depend on B in the first example?

**Comment by josevalim** [comment]
We have three kinds of dependencies:

1. external resources - when you depend on a separate file, they don't matter for the manifest though
2. runtime dependencies - when you call another module from inside a function
3. compile time dependencies - when you call another module from the module body (outside of a function)

I am talking about 2 and 3. In your example, we have a runtime dependency, so mix knows changing B won't affect the result of A and that's why it did not recompile A. However, if you invoke B from A module's body, changing B should recompile A. We should never need to use `@external_resource` for other modules.

**Comment by hamiltop** [comment]
There we go. 3 was the case I was missing. I should be good to go then. Hopefully will have a working implementation in the next day or so.

**Comment by hamiltop** [comment]
Quick update here. This became a bit of a rabbit hole. I've got all the use cases I've come across working (there were quite a few more weird situations), but there are a few existing tests around protocols that aren't working yet. Hopefully will have a bit of time today to work on this.

**Comment by hamiltop** [comment]
Could still use a bit of polish, but https://github.com/elixir-lang/elixir/pull/4165/files is ready for some feedback.

**Comment by josevalim** [comment]
This feature no longer exists so this is "fixed". :)
