### ISSUE TITLE
[MIX] select a manager automatically

### ISSUE THREAD

**Issue by scrogson** [elixir-lang/elixir#4230]
Opening an issue as request by @josevalim in IRC.

I ran into an issue while including a dependency in a phoenix app. The dependency depends on `{:ranch, "~> 1.0"}`.

Because `cowboy` depends on `ranch`, attempting to `mix deps.get` produces the following error:

```
λ mix deps.get
Running dependency resolution
Dependencies have diverged:
* ranch (Hex package)
  different specs were given for the ranch app:

  > In /Users/scrogson/Forks/telly/mix.exs:
    {:ranch, "~> 1.0", [hex: :ranch, manager: :make]}

  > In deps/cowboy/rebar.config:
    {:ranch, "~> 1.0", [optional: false, hex: :ranch, manager: :rebar]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

This was due to the difference in the `manager` option. Changing the dependency to `{:rebar, "~> 1.0", manager: :rebar}` in the `telly` app fixed this. But that seems like a usability issue and seems that `mix` should handle this automatically.

**Comment by ericmj** [comment]
The problem here is that we chose a specific manager too early. For "cowboy -> ranch" we chose rebar as manager because we assume that dependencies of a rebar project can always be compiled with rebar. For "your mix.exs -> ranch" we chose make as a manager because ranch has a Makefile but no rebar.config. If we instead kept [rebar, make] as a manager for "cowboy -> ranch" we could more easily converge managers.

Another solution would be to automatically override managers when converging unless a manager is explicitly set by a user. If mix infers two different managers we could just chose one, it shouldn't matter, if one of them doesn't work we will have issues in other cases anyways.

**Comment by josevalim** [comment]
@ericmj I am thinking we should just automerge. If one is coming high in the tree, it automatically wins, if from the disjoint trees, we will do (mix > rebar3 > rebar > make). There is no reason to raise conflicts for managers. Let me know when you have a sec to discuss this before we ship 1.2.2.

**Comment by josevalim** [comment]
We are missing the steps to reproduce this, unfortunately.

**Comment by josevalim** [comment]
I was able to reproduce it with these deps:

```elixir
  defp deps do
    [{:cowboy, ">= 0.0.0"},
     {:telly, github: "trarbr/telly"}]
  end
```

**Comment by josevalim** [comment]
This has been fixed, thank you for the report @scrogson!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
@ericmj I am waiting for you to confirm the fix before a release. :)

**Comment by ericmj** [comment]
@josevalim Looks good.
