### ISSUE TITLE
ExUnit.Case functions arent running serially using Agent global state

### ISSUE THREAD

**Issue by hdcos** [elixir-lang/elixir#4234]
I read this issue ( https://github.com/elixir-lang/elixir/issues/3580 ) and it seems test functions inside a Case are run serially. 
When I run a simple test case without global state cases are indeed run serially.

But when I use global state with Agent the order of execution depends on luck. For the same call to 

    mix test --trace

the order of execution change. Here is my test suite:

    defmodule SerialTest do
      use ExUnit.Case

      test "1" do
        Agent.update(:card_id, fn nil -> 1 end)
        assert true
      end

      test "2" do
        res = Agent.get(:card_id, fn res -> res end)
        assert res == 1
      end

      test "3" do
        Agent.update(:card_id, fn id -> 3 end)
        assert true
      end

      test "4" do
        res = Agent.get(:card_id, fn res -> res end)
        assert res == 3
      end
    end

Sometimes passes sometimes not.
Is it a bug or am I doing something wrong? Or is there a better way to achieve that?

**Comment by josevalim** [comment]
The tests run serially but they run in **random order**. Your tests are failing because they are order dependent as they change some global state.

When you run your suite you see this at the bottom:

    Randomized with seed 596046

You can disable it by adding `ExUnit.configure seed: 0` to your `test_helper.exs` but I would rather advise for your tests to be order independent.

**Comment by tuvistavie** [comment]
They are indeed run serially, but the order is not guaranteed, which is why your tests sometime fail.

**Comment by hdcos** [comment]
Ok thank you very much :)
