### ISSUE TITLE
GenServer.cast/2 can crash calling process

### ISSUE THREAD

**Issue by bharendt** [elixir-lang/elixir#4251]
`&GenServer.cast/2` behaves differently whether event is casted to non-existent name or to non-existent pid. This makes it unsafe to call and make elixir differ significantly from erlang in that regard where it's always safe.

`&GenServer.cast/2` throws `ArgumentError` if no pid is associated with the given name. [This is also documented](http://elixir-lang.org/docs/v1.2/elixir/GenServer.html#cast/2).
That differs from the behaviour if an event is casted to a non-existent pid and also differs from the erlang implementation of [`&:gen_server.cast/2`](http://erlang.org/doc/man/gen_server.html#cast-2).

```elixir
iex> non_existing_pid = pid(0,12345,0)
iex> GenServer.cast(non_existing_pid, :foo)
:ok
iex> GenServer.cast(:non_existing_name, :foo)
** (ArgumentError) argument error
             :erlang.send(:non_existing_name, {:"$gen_cast", :foo})
    (elixir) lib/gen_server.ex:639: GenServer.do_send/2
iex> :gen_server.cast(:non_existing_name, :foo)
:ok
```

 Is that really the desired behaviour? Especially if it's not expected to know whether a casted event is handled in any case which also the documentation says: 
 *"Therefore it is unknown whether the destination server successfully handled the message"*. 
 
 This makes arbitrary processes to crash when they cast to named processes that don't exist or (temporarily) died, e.g. if a named process crashed and is restarted by a supervisor. Example:

```elixir
defmodule NamedServer do
  use GenServer

  def handle_cast({:log, something = <<_,_::binary>>}, state) do
    IO.puts "logged #{something}"
    {:noreply, state}
  end
  
  # crashes on any other event
end


import Supervisor.Spec
children = [
  worker(GenServer, [NamedServer, [], [name: :named_server]])
]
{:ok, _} = Supervisor.start_link(children, strategy: :one_for_one)
is_pid(Process.whereis(:named_server)) == true

arbitrary_pid = Process.spawn fn ->
  GenServer.cast(:named_server, {:log, "hello"}) # everything is fine
  GenServer.cast(:named_server, {:log, :crashing_argument}) # named server crashes ...
  # this process does not notice that, which is ok
  GenServer.cast(:named_server, {:log, "hello again"}) # this process crashes ...
  # even if it does not care so much about whether the message is logged in that case.
  # the :hello message from the cast before was not logged either
end, []

monitor_ref = Process.monitor(arbitrary_pid)
receive do
  {:DOWN, ^monitor_ref, :process, ^arbitrary_pid, reason} ->
    IO.puts "Damn, arbitrary process died because of reason #{inspect reason}"
end
```
Output:

```txt
logged hello
14:19:16.078 [error] GenServer :named_server terminating
** (FunctionClauseError) no function clause matching in NamedServer.handle_cast/2
    iex:4: NamedServer.handle_cast({:log, :crashing_argument}, [])
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:log, :crashing_argument}}
State: []
Damn, arbitrary process died because of reason :noproc
```

It's even impossible to perform a "safe" cast, the only way to avoid crashing the own process while casting to a named process is to sourround it by a try-rescue clause.

```elixir
if is_pid(Process.whereis(:named_server)) do           
  # :named_server could die in that (µ)second before casting                  
  GenServer.cast(:named_server, {:log, "hello world"}) # would crash then
end
```

```elixir
def safe_cast(name, event)
  try do
    GenServer.cast(name, event)
  rescue _ -> :ok
  end
end
```
 or of course using the `:gen_server.cast/2` otp function. 
 
 I would suggest changing that behavior and I'd be happy to provide a pull request if you're open to changing the behavior.

**Comment by josevalim** [comment]
The solution for this case is also mentioned in the docs:

    GenServer.cast({name, node()}, event)

I will let @fishcakez decide if this is worth changing, we could potentially special case atoms and handle this particular error, but I believe using `:gen_server.cast` is not an option due to behaviour with remote nodes.

**Comment by josevalim** [comment]
In any case, thank you for the detailed report @bharendt!

**Comment by mk** [comment]
I also just read about the workaround. For what it's worth, I'd be in favor of changing the behavior to be safe by default. We didn't really know about this difference until it's bitten us and I'm afraid we're not alone.

**Comment by fishcakez** [comment]
I definitely don't think we should change this because it is backwards incompatible.

However the reason we have this behaviour is for consistency with `send/2` and when using `:global` or `:via` we delegate to the custom module's `send/2`. It is actually `:gen_server.cast/2` that has the inconsistencies. Firstly it catches the `ArgumentError` for locally registered process and secondly it does not guarantee order of messages to other nodes.

**Comment by fishcakez** [comment]
> it does not guarantee order of messages to other nodes.

But only when using pids or locally registered names. The guarantee exits when using `via` or `:global`.

**Comment by bharendt** [comment]
Thanks for the quick reply. I understand that changing that behaviour is a problem because it is not backwards compatible.
But I don't think there are many cases where it makes sense to get an argument error, if the process of the registered name is down. You also don't get that information if you cast to a pid directly, to a name on a different node or to a globally registered name. You also don't want to handle that case because you don't know in any case whether the casted event will be received. I think that behaviour is more inconsistent as to vary from the behaviour of the `send/2` function when casting events and differs from the [actual intention of the erlang implementation](http://erlang.org/doc/man/gen_server.html#cast-2):

> Sends an asynchronous request to the gen_server ServerRef and returns ok immediately, ignoring if the destination node or gen_server does not exist.

Using the node name tuple works. Thanks for the hint. But one might be suspicious whether it also works if erlang runs without distribution and `node()` returns `nonode@nohost`, but it works then too. 

Raising that error makes each call of `GenServer.cast` a potential risk of terminating the calling process. 
I understand that you don't like to change that behaviour, but I think we then always have to use the workaround or the erlang implementation in our code to be safe. I also think many people will run into that issue if they migrate code from erlang to elixir or are used to the erlang behaviour.

Maybe it would be an option to add an additional function to `GenServer` that casts an event and always returns `:ok` and never throws an error, like `safe_cast` or `erl_cast`. Maybe that would also underline that there is a difference to the erlang behaviour.

**Comment by josevalim** [comment]
> But I don't think there are many cases where it makes sense to get an argument error, if the process of the registered name is down.

The point is that this is how `send` behaves anyway, so as much as we could argue it doesn't make sense, it is right there in the main primitive for sending messages and `cast` mirrors that. Which is a great "lesson" because if you expect `cast` to work, someone may expect `send` to work as well, and with Elixir they both won't.

That's without mentioning the fact via and global will still fail. We could make the `cast` docs clearer on the semantics differences but I believe the consistency with `send` is indeed important.

**Comment by fishcakez** [comment]
Oh we catch exits for :global and :via cast but reverted that for locally registered names to match send/GenEvent.notify behaviour. I thought we reverted all the catching. This is indeed inconsistent.

**Comment by josevalim** [comment]
@fishcakez OK. Let's revisit this then, specially because we should not worry about GenEvent.notify.

**Comment by mk** [comment]
I'm trying to find out how much the safe solution using `node()` is used in Elixir projects on GitHub. If anyone knows a better way to search for it, please let me know.

Here's what I tried: 
* Search GitHub for language:Elixir and `GenServer.cast node` brings up [171 results](https://github.com/search?utf8=✓&q=GenServer.cast+node+language%3AElixir&type=Code&ref=searchresults). Looking through them there's actually only a few that use the safe way or rescue on error.
* Searching for `GenServer.cast` only brings up [2,539 results](https://github.com/search?l=elixir&q=GenServer.cast+language%3AElixir&ref=searchresults&type=Code&utf8=✓).
* Searching on Google for safe usages brings about [21 results](https://www.google.com/search?as_q=%22GenServer.cast%22+node&as_epq=&as_oq=&as_eq=&as_nlo=&as_nhi=&lr=&cr=&as_qdr=all&as_sitesearch=github.com&as_occt=any&safe=images&as_filetype=swf&as_rights=#as_qdr=all&q=%22GenServer.cast%22+node+site:github.com+filetype:ex)
* Searching on Google for all GenServer.cast usages brings about [225 results](https://www.google.com/search?client=safari&rls=en&q=%22GenServer.cast%22+site:github.com+filetype:ex&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=P5iwVpq4LaPD8gfG0574BA)

This search is by no means ideal but I hope it proves that most people don't know about how to safely cast using `GenServer`. I strongly feel that `GenServer.cast` as one of most used building blocks of OTP apps should always be safe and the Elixir apps out there will work better if it is. I don't really see the reasoning to keep it in line with how unsafe `send` is. `GenServer` is a higher-level abstraction so it should be good for it to be safer than send.

If you want, I'd gladly start a survey in the community to find out how many people know about the current caveats of `GenServer.cast/2`.

**Comment by fishcakez** [comment]
@mk can you clarify what you mean by "safe"? I personally view the current behaviour as "safe" because it raises when there is likely to be an error and your suggested default behaviour as "unsafe" because it can hide bugs or errors.

**Comment by mk** [comment]
@fishcakez what you're saying is only true if the receiving process never crashes. What we ran into with our poker sever was the following: we have a process for each table that casts to a supervised process responsible for saving log data to the database. We wrongfully assumed this would be fire and forget. One of the messages crashed this receiving process (the same would happen if the database went down) which in turn caused a second table to crash because it tried to cast a message to this process before it was restarted by the supervisor.

I feel that `GenServer.cast/2` should always behave in a way that you can use it to hand off responsibility of the message arriving regardless of how it's called.

**Comment by bharendt** [comment]
It's mainly a problem for processes which were alive and a pid for the registered name existed, but then terminated. For all other ways to cast to a process, meaning a pid which is down, a locally registered name on a different node which is down, for a globally registered name etc. this does not cause `GenServer.cast` to fail, but if a locally registered name is down. This is especially a problem if that process is restarted by the supervisor. The example from above does not always show the problem because of the timing, but here is an updated version which shows the error every time:

```elixir

defmodule NamedServer do
  use GenServer

  def init(_) do
    receive do after 1000 -> :ok end    
    Process.register(self, :named_server)
    IO.puts ":named_server started"
    {:ok, :state}
  end

  def handle_cast({:log, something = <<_,_::binary>>}, state) do
    IO.puts "logged #{something}"
    {:noreply, state}
  end

  # crashes on any other event
end


import Supervisor.Spec
children = [
  worker(GenServer, [NamedServer, [], []])
]
{:ok, _} = Supervisor.start_link(children, strategy: :one_for_one)
receive do after 1100 -> :ok end    
is_pid(Process.whereis(:named_server)) == true

arbitrary_pid = Process.spawn fn ->
  GenServer.cast(:named_server, {:log, "hello"}) # everything is fine
  GenServer.cast(:named_server, {:log, :crashing_argument}) # named server crashes ...
  # this process does not notice that, which is ok
  receive do after 100 -> :ok end    
  GenServer.cast(:named_server, {:log, "hello again"}) # this process crashes ...
  # even if it does not care so much about whether the message is logged in that case.
  # the :hello message from the cast before was not logged either
  IO.puts "this line is never logged"
end, []

monitor_ref = Process.monitor(arbitrary_pid)
receive do
  {:DOWN, ^monitor_ref, :process, ^arbitrary_pid, reason} ->
    IO.puts "Damn, arbitrary process died because of reason #{inspect reason}"
end

```

Output:

```
true
logged hello
#PID<0.108.0>
14:44:14.042 [error] GenServer #PID<0.94.0> terminating
** (FunctionClauseError) no function clause matching in NamedServer.handle_cast/2
    iex:11: NamedServer.handle_cast({:log, :crashing_argument}, :state)
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:log, :crashing_argument}}
State: :state

Damn, arbitrary process died because of reason {:badarg, [{:erlang, :send, [:named_server, {:"$gen_cast", {:log, "hello again"}}], []}, {GenServer, :do_send, 2, [file: 'lib/gen_server.ex', line: 639]}, {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 669]}, {:erl_eval, :exprs, 5, [file: 'erl_eval.erl', line: 122]}]}
14:44:14.141 [error] Process #PID<0.108.0> raised an exception
** (ArgumentError) argument error
    :erlang.send(:named_server, {:"$gen_cast", {:log, "hello again"}})
    (elixir) lib/gen_server.ex:639: GenServer.do_send/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
:ok
:named_server started

```

This is also one of the reasons why locally registered names are used, because the pid might not be valid any more if the process is restarted by a supervisor, but the name still is. 

If you run a production system you don't want any process that casts an event to another process to crash itself if the receiver is down temporarily.

**Comment by fishcakez** [comment]
@mk @bharendt the point I was trying to make is that crashing when the target process is down can be considered "safe" because a crash is occurring when an error has occurred. If we did not crash then an error is being hidden, which would then be "unsafe". This is an opposing opinion to yours and I think this blanket statement is not always true:

> If you run a production system you don't want any process that casts an event to another process to crash itself if the receiver is down temporarily.

Of course it is sometimes true. If we take the position that either behaviour is equally worthwhile and we crash on error, those who wish to ignore the error can rescue it. However if we ignore the error, those who wish to error have no options. If anyone is currently relying on the former behaviour and we change it they have a problem.

Your argument at the moment is that we should blindly handle the error case in all situations because we never want to error. This is a very unconvincing argument in the "let it crash" philosophy of OTP, no matter how many times you state it. However if you could show that the situations where someone would want to crash when the target of casts crashes are always naturally handled by some other mechanisms, such as the supervision tree, then perhaps we could make the change.

Obviously we do have the inconsistency with `:global` and `:via` and if we are to leave locally registered names the same, we should probably change `:global` and `:via` to crash - or rather not to be caught and rely on the decision of `module.send/2`.

**Comment by mk** [comment]
@fishcakez like a said I could hardly find any cases on GitHub where the errors that can occur when calling `GenServer.cast` are currently handled. The way we use GenServer is the following:
 * we either want to make sure that the message is received and handled correctly, in that case we're using a `call`
 * if we want to offload the work to another process we never want the calling process to be affected by the state of the process being called and we're using `cast` in that case

I've not yet seen cases where you use `GenServer.cast` and care about if the message was delivered. You can only see if the process exists at the time of when you cast but that won't tell you if it will still be alive when your message will be processed.

For me this is the main benefit of `GenServer`, being able to decide if you want to crash when a message can't be delivered and use `call` or `cast` accordingly. 

Is this behavior generally something you could imagine addressing in a future (major?) release? I feel this change in behavior is too drastic to have it change depending on how you address the process. If you really care about the process being alive before you perform the cast and want to crash doing it explicitly (by using a monitor or `Process.alive/1` and `Process.whereis/1`) is much clearer I think.

I just think it's way too easy to overlook, see e.g. https://github.com/ericmj/postgrex/blob/master/lib/postgrex/protocol.ex#L83

Would you expect `delete_parameters` to throw a `ArgumentError` and not execute `queries_delete`? https://github.com/ericmj/postgrex/blob/master/lib/postgrex/parameters.ex#L34

If we'd go down the other route you suggested and let `cast` using `:global` and `:via` change would you still leave the option to cast safely with `node()`?

**Comment by fishcakez** [comment]
@mk likely because `GenServer.cast` does not need to rescued and crashing is perfectly acceptable. In most cases the supervision tree will handle the situation where the target dies due to a `rest_for_one` or `one_for_all` relationship. If the sender does not exist it is very likely a bug/error and so if in doubt we want to crash. If we do not crash we are potentially hiding the error. If there is a bug you want your application to tell you loudly.

I am sorry for the push back on this but I find your argument that we should blindly ignore all errors very worrying. I understand you got burnt but this and want to ensure others don't face the same situation. However I think your use of "safe" is very subjective, and in the majority of cases wrong. If there is an error the safe default is to raise rather than ignore it. For your definition of "safe" it is good to be explicit that we want to ignore the error and we have discussed three ways to avoid raising. One of which is mentioned in the documentation. Of course there is a consistency issue and the docs even mention this inconsistency and we should look to resolve it.

I am not keen on the mindset that we must never crash and I think of this as ** too** fault tolerant and overly defensive programming. It is important to understand the error kernels of an application and handle errors in the appropriate place so that they don't propagate. Usually this is the parent supervisor.

I also think it is important to understand that if we ignore errors by default it is not obvious how to un-ignore them. Whereas when an error is raised it is easier to understand how to handle the error and what the code is doing.

It is ok for `delete_parameters` to raise in that situation and doesn't matter if `queries_delete` isn't called because the process will exit and then the unnamed ETS table will be automatically deleted. In that example I don't think it matters which behaviour we get. Given that the connection process depends on the parameter process it could be argued we exit too late there and should be linked - if the parameter process goes down then parameter fetching doesn't work but its also been cleaned up. That is part of the beauty of OTP, we don't need to handle these situations.

I don't think that is the right use case for `Process.alive?`. Rather it should be used to avoid the race condition where process A has received an exit/monitor signal from process B but another process C has not yet. In this situation if process A calls process C with a call that requires process B to be down, process C needs to check whether process B is exiting. This is a frequent problem with pools or process registries.

Instead of `Process.whereis/1`, you may want to use `GenServer.whereis/1` which will handle all naming schemes used by a GenServer, i.e. pid, name, {name, node}, :global and :via. Note that if a process is making multiple casts to a target process and it wants to ensure that as single process handles them or that its messages are being handled, then `GenServer.whereis/1` is exactly for this case. The `pid` or `{name, node}` is looked up and then monitored (or possibly linked) and the sender exits or handles the error when the target process exits.

`{name, node}` would never raise because those are the semantics of `send/2` and it would be far to expensive to check if a process is registered on another node.

**Comment by bharendt** [comment]
> If the sender does not exist it is very likely a bug/error and so if in doubt we want to crash. If we do not crash we are potentially hiding the error. If there is a bug you want your application to tell you loudly.

I think you mean *receiver* and that might be your interpretation, but it differs [from the erlang interpretation](http://erlang.org/doc/man/gen_server.html#cast-2):

> Sends an asynchronous request to the gen_server ServerRef and returns ok immediately, ignoring if the destination node or gen_server does not exist.

On a running node there are now two modules with almost the same name `:gen_server` and `GenServer` and the same function `cast` which have two different understandings of whether it's acceptable that a generic server process you cast a message to should be alive or not (in one particular case). 

> I am sorry for the push back on this but I find your argument that we should blindly ignore all errors very worrying. 

Its not about blindly ignoring all errors, its about whether casting an event to a process that does not exist is an error or not. 

What we know is, that the erlang implementation of `gen_server:cast` thinks it is not an error. What we also know is, that sending any event to a nonexistent pid, port etc is also not an error:

```elixir
iex(1)> send pid(0,12345,0), :foo
:foo
iex(2)> send {:global, :bar}, :foo
:foo
iex(3)> send {:foo, node}, :foo   
:foo
iex(4)> send {:foo, :"nonode@nohost"}, :foo
:foo
iex(5)> send {:foo, :"foo@nohost"}, :foo   
:foo
iex(6)> port = Enum.reverse(:erlang.ports) |> List.first  
#Port<0.848>
iex(7)> Port.close(port)
true
iex(8)> Enum.member?(:erlang.ports, port)   
false
iex(9)> send port, :foo                     
:foo
```

I don't know why `send/2` differs from that behavour in that single case (nonexistent local name) as the onliest exception, but the `:gen_server.cast` implmenetation circumvents this by catching that error.

That's the behaviour that is assumed by all erlang applications using that essential function and one might also assume the same for elixir applications at least because the name of the module and function is the same (e.g. its not `cast!` or something) It's also the normal behavour if you send asynchronous events for which you never have the guarantee that they would be processed.

I think that is the problem we are talkinkg about and I think we don't need to discuss about the definition of "safe" here or how to write fault tolerant software.

**Comment by fishcakez** [comment]
> Its not about blindly ignoring all errors, its about whether casting an event to a process that does not exist is an error or not.

Unfortunately this is exactly how you came across to me and I am sorry for we have had a miscommunication.

Please note that it is very hard to talk about expectations for other people. `:gen_server.cast` works differently to all other asynchronous messages functions in OTP, `send/2`, :gen_fsm.send_event`, `:gen_fsm.send_all_state_event` and `:gen_event.notify`. `GenServer.cast` currently behaves the same as the later group.

I was pushing the discussion of "safe" not to argue what safe means but to try to explain that there are two common patterns of asynchronous messaging used and the desired error handling is opposite for each of them and one of them was getting ignored. In my last comment I explained that other one and said in those situation an alternative mechanism, link/monitor/supervision tree are used and that raising if anything does not help those cases. I tried to hint at this in the comment preceding that hoping to move the discussion that way, I should have been clearer what I wanted to talk about.

The discussion I wanted to have was that when we want to error because of a failure of the receiver during asynchronous messaging we want to setup a relationship using links, monitors or the supervision tree. If we setup this relationship then raising on a cast may not matter but is slightly less than ideal. One could view a call as the basic example of this: Monitor, send asynchronous message, receiving `DOWN` or asynchronous message.

I suppose I got to have the discussion with myself at least and do think we should move forward with your proposed change. I know that @josevalim would like to see the change so that we are consistent with both Erlang and ourselves.

**Comment by mk** [comment]
@fishcakez I was just writing up another message which seems to be obsolete by your reply now. We'll come up with PR for this tomorrow. Should this be against `master`?

I was discussing another possibility with @bharendt of introducing an additional `GenServer.cast!/2` method in Elixir 2.0 that always throws an `ArgumentError` when called with a nonexistent process, regardless of how it's called. One could even go further to introduce `send!/2` which would do the same and have `GenServer.cast/2` and `GenServer.cast!/2` just call `send/2` and `send/2` respectively. If you want us we'll open another issue to discuss that. 

Thanks for all your hard work on Elixir, it's really a joy to use.

**Comment by josevalim** [comment]
This has been a great discussion, thanks everyone.

@mk yes, the PR should be against master.

About the need for `cast!/2`, let's wait. Everyone involved on this discussion knows there is an opportunity for introducing `cast!/2`. As soon as we need in an actual application, let's open up an issue with the proper use case and move forward.

**Comment by bharendt** [comment]
Thanks for taking this issue seriously, for all that information and for changing that behaviour.

**Comment by fishcakez** [comment]
Just as an update the new `:gen_statem` behaviour coming in OTP 19 has `cast/2` that works the same as `:gen_server.cast/2` and so does not raise.
