### ISSUE TITLE
mix compile hangs infinitely in a case of undefined behaviour + struct

### ISSUE THREAD

**Issue by liveforeverx** [elixir-lang/elixir#4294]
This is a minimal reproducible example, which I found.
Application, without dependencies, which tries to access undefined @behaviour and undefined struct in a code hangs infinitely.

```elixir
defmodule TestCompiler do
  @behaviour :sbroker

  def test do
    %MaybeUndefinedStruct{broker: 1}
  end
end
```

Tried in 1.2.2 and in master.

**Comment by lexmag** [comment]
I think this issue is here for very long time.
The reason is following: a compiler process for that file is waiting for two modules (`:sbroker` and `MaybeUndefinedStruct`) to be available, and when `length(waiting) == length(queued)` is reached we "release" module usually with error, but in that particular case, we emit warning for `:sbroker` and then we hang in waiting when `MaybeUndefinedStruct` will be "released", and that's not happening as `length(waiting)` gets bigger than `length(queued)`.

The `==` –> `>=` change is enough there: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/parallel_compiler.ex#L119.
Nevertheless I'll look tomorrow if we have another option, remove released elements from `waiting` for example.

**Comment by josevalim** [comment]
@lexmag i am working on a patch that solves those bits in the compiler so please wait. :)
