### ISSUE TITLE
Using a module as a key in a map only works if => is used

### ISSUE THREAD

**Issue by Theemuts** [elixir-lang/elixir#4379]
### Precheck

* Do not use the issues tracker for help or support requests (try Stack Overflow, IRC or mailing lists, etc).
* For proposing a new feature, please start a discussion on [elixir-lang-core](https://groups.google.com/forum/#!forum/elixir-lang-core).
* For bugs, do a quick search and make sure the bug has not yet been reported.
* Finally, be nice and have fun!

### Environment

* Elixir version (elixir -v): 1.3.0-dev
* Operating system: Ubuntu 15.10

### Current behavior

    iex(1)> x = %{Mod => 1}
    %{Mod => 1}
    iex(2)> x[Mod]
    1
    iex(3)> x = %{Mod: 1}
    %{Mod: 1}
    iex(4)> x[Mod]
    nil

### Expected behavior

If `%{Mod: 1}` is not supposed to work, a SyntaxError should be raised. If it is supposed to work, both calls to `x[Mod]` should return the same value, 1.

**Comment by michalmuskala** [comment]
Maybe you figured this already out and closed because of that, but for every body else who arrives here:

This issue is caused because the `[key: value]` syntax is shorthand for `[{:key, value}]`.
This means that using `[Mod: value]` gives you `[{:Mod, value}]`.
But `:Mod != Mod` and hence the issue. `Mod` is an atom, but because it's a module name it is encoded to `Elixir.Mod` so that it's easy to distinguish from regular atoms.

**Comment by Theemuts** [comment]
Yes, I assumed the same when I saw the key returned by Map.keys. Thank you
for confirming my assumption!
