### ISSUE TITLE
Incorrect SemVer validation on metadata

### ISSUE THREAD

**Issue by pdilyard** [elixir-lang/elixir#4407]
### Environment

* Elixir version (elixir -v): 1.2.2
* Operating system: Mac OSX

### Current behavior

I have versioning in my project set up to use the git SHA in the version number, for example `0.0.1+sha.d1af69c`. Here's the function that generates this:

```
  defp full_version(sem_ver) do
    {result, _exit_code} = System.cmd("git", ["rev-parse", "HEAD"])
    sha = String.slice(result, 0, 7)
    "#{sem_ver}+sha.#{sha}"
  end
```

By chance, I got a commit hash where the first 7 characters were all numbers, and where the first number was 0, so my full version number should be: `0.0.1+sha.0702245`. However this raises the following error:

```
** (Mix) Expected :version to be a SemVer version
```

### Expected behavior

By my understanding of the SemVer spec, numeric prerelease versions after a hyphen cannot begin with a leading 0 (see http://semver.org/#spec-item-9).

However, metadata coming after a plus sign do not have this limitation, see: http://semver.org/#spec-item-10.

I believe this error was thrown due to incorrect SemVer validation.

**Comment by josevalim** [comment]
@pdilyard perfect, thank you!

**Comment by whatyouhide** [comment]
From my research, it looks like the problem is not the leading `0`, it's the `.` in the build metadata. Right now, the regex we're using to parse versions ([here](https://github.com/elixir-lang/elixir/blob/4fb70d9ebf0da297eec295ea1043bab722ae9fe6/lib/elixir/lib/version.ex#L368)) is this:

```elixir
    @version_regex ~r/^
      (\d+)                 # major
      (?:\.(\d+))?          # minor
      (?:\.(\d+))?          # patch
      (?:\-([\d\w\.\-]+))?  # pre
      (?:\+([\d\w\-]+))?    # build
      $/x
```

As you can see, `.`s are allowed in the pre info but not in the build info. This is against the SEMVER spec which says (in [section 10](http://semver.org/#spec-item-10)):

> Build metadata MAY be denoted by appending a plus sign and a series of **dot separated identifiers** [...]

(emphasis added by me)

The leading 0 spec for pre info is actually not enforced by `Version` (as I think it would make the code much more annoying :smile:), but that's a story for another day.

Anyhow, I pushed a possible fix to #4409, let's see how it goes!

**Comment by ericmj** [comment]
> The leading 0 spec for pre info is actually not enforced by Version (as I think it would make the code much more annoying :smile:), but that's a story for another day.

We can fix this in the parser but we it internally to support `~>`. `~> 2.0` is implemented as `>= 2.0.0 and < 3.0.0-0`.

**Comment by whatyouhide** [comment]
@ericmj I see. I don't think being loose with the spec here is a problem though, as I don't think people would expect `3.0.0-0` to break anyways (or actually, they'd probably be surprised it broke :smiley:).

**Comment by ijunaid8989** [comment]
I got this error just now

```
"** (Mix) Expected :version to be a SemVer version, got: \"1.0.1-0662026\""
```

as in past few minutes ago versions like
```
1.0.1-08f6b0c  1.0.1-7d6efe0
```
was working fine? where am I wrong?

**Comment by ijunaid8989** [comment]
It needs an alphabet I think

```
Interactive Elixir (1.7.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Version.parse("1.0.1-0662026")
:error
iex(2)> Version.parse("1.0.1-06620d6")
{:ok, #Version<1.0.1-06620d6>}
iex(3)>
```
