### ISSUE TITLE
Nasty compilation error with character literals

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#4419]
### Environment
```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.2.3
```
Ubuntu 15.10

### Current behavior

When incorrect syntax is reported that involves character literals the integer instead of character is reported.

```iex
iex(1)> :abc ?a
** (SyntaxError) iex:1: syntax error before: 97
```
This makes discovering where the error lies difficult and is quite confusing since the erroneous code does not have integers at all. It took me some time to understand what is happening.

### Expected behavior

```iex
iex(1)> :abc ?a
** (SyntaxError) iex:1: syntax error before: ?a
```
I would also accept just `?` instead of full `?a`

**Comment by whatyouhide** [comment]
Sadly, this is a very hard problem to solve. In Elixir, the tokenizer takes care of integers ([here](https://github.com/elixir-lang/elixir/blob/c5a34ef4424775fe1b3b73c237a754e89baad85f/lib/elixir/src/elixir_tokenizer.erl#L137-L147)) exactly the same way it takes care of `?char` literals ([here](https://github.com/elixir-lang/elixir/blob/c5a34ef4424775fe1b3b73c237a754e89baad85f/lib/elixir/src/elixir_tokenizer.erl#L178-L191)). For both literal integers and `?char`s, the tokenizer will output a `{:number, _, number}` token:

```
iex> :elixir_tokenizer.tokenize('?a', 1, []) == :elixir_tokenizer.tokenize('97', 1, [])
true
```

This means that the parser never sees `?a`, it just sees an integer: when generating the syntax error, you can't tell if the integer causing the error was written out as `?a` or `97`. One quick & dirty solution would be to always say something like `iex:1 syntax error before: 97 (or '?a')`, regardless of how the integer was written in the source (we'd do this just for integers representing printable characters or something). I don't like this solution as I tried implementing it but it's pretty cumbersome (bunch of edge cases, e.g., `?\s` where you'd have to map the actual space to the escaped `\s` and so on).

Another solution I can think of (but this is just a thought, I'm absolutely not sure of the consequences) would be to make `?/1` a macro, so that we can handle this very easily of course.

**Comment by michalmuskala** [comment]
Making `?/1` a macro is an interesting approach,  but I'm not sure of the consequences either.

It seems the only way to solve this is for the tokenizer not to convert `?a` into `97` and return an additional token handled accordingly by the parser.

**Comment by whatyouhide** [comment]
@michalmuskala yep, but if the consequences of the `?/1` macro are not crazy I'd go with that so we don't have to handle an additional special case in the parser :). Let's hear what the others have to say on this, then I'd be superhappy to tackle it.

**Comment by josevalim** [comment]
Let's do a small step first and handle it in the parser. I am not
necessarily against an unary ?/1 but I worry with certain ambiguities like
the meaning of "? A" or "?1" or "?foo".

On Saturday, March 26, 2016, Andrea Leopardi <notifications@github.com>
wrote:

> @michalmuskala <https://github.com/michalmuskala> yep, but if the
> consequences of the ?/1 macro are not crazy I'd go with that so we don't
> have to handle an additional special case in the parser :). Let's hear what
> the others have to say on this, then I'd be superhappy to tackle it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4419#issuecomment-201777877>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by whatyouhide** [comment]
@josevalim ok, I'll open a PR in a while :)
