### ISSUE TITLE
Improve error message for syntax error in anonymous fn pipe

### ISSUE THREAD

**Issue by Gobiner** [elixir-lang/elixir#4435]
### Current behavior

```
elixir -e "5 |> (fn x -> x + 5 end) |> IO.puts"
** (CompileError) nofile:1: expected -> clauses in fn
```
```
elixir -e "5 |> (fn x -> x + 5 end).() |> IO.puts"
10
```

The necessary syntax to use anonymous functions in this kind of situation is not obvious (to me, at least) and the error message from the compiler doesn't help. My intuition is that I'm "piping values through functions"; my intuition is not that I'm using a macro to rewrite my function calls, and of course my anonymous function needs to be called instead of merely defined.

##### Environment

Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.2.3
MacOS X El Capitan 10.11.3

**Comment by josevalim** [comment]
> My intuition is that I'm "piping values through functions"; my intuition is not that I'm using a macro to rewrite my function calls, and of course my anonymous function needs to be called instead of merely defined.

I don't mean this in a negative way but you will need to adjust your intuition. The issue with supporting "anonymous functions" is that we would only support literal ones. For example, if you write this:

    var = (fn x -> x + 5 end)
    5 |> var |> IO.puts

It is not going to work as expected. It will try to call the local function `var()` and not the anonymous function. And there is no way to solve this because Elixir on purpose makes a distinction between calling anonymous and local functions.

In this case, however, your first example is revealing a parser bug, so I will leave this open until it is fixed. Thank you!

**Comment by whatyouhide** [comment]
I'm slowly but steadily looking into this :)
