### ISSUE TITLE
Unclear error message for undefined method name

### ISSUE THREAD

**Issue by ssbb** [elixir-lang/elixir#4502]
### Environment

* Elixir version (elixir -v): Elixir 1.2.4
* Operating system: OS X 10.11.4 (15E65)

### Current behavior

I just followed this example: 

```#---
# Excerpted from "Programming Elixir",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/elixir for more book information.
#---
defmodule Frequency do
  
  def start_link do
    Agent.start_link(fn -> HashDict.new end, name: __MODULE__)
  end

  def add_word(word) do
    Agent.update(__MODULE__, 
                 fn dict ->
                      Dict.update(dict, word, 1, &(&1+1)) 
                 end)
  end

  def count_for(word) do
    Agent.get(__MODULE__, fn dict -> Dict.get(dict, word) end)
  end

  def words do
    Agent.get(__MODULE__, fn dict -> Dict.keys(dict) end)
  end
  
end
```

and made a mistake in `words` function. Instead of `Dict.keys` I wrote `Dict.Keys` (capitalized). I got this error:

```
** (SyntaxError) agent.exs:18: syntax error before: '('
    (elixir) lib/code.ex:363: Code.require_file/2
```

### Expected behavior

Should it be something like `Module Dict does not have method Keys`?

**Comment by josevalim** [comment]
Thanks for the report.

`Dict.Keys` is called an alias. Invoking an alias is simply not possible, the parser does not support it and that's why it is a syntax error. Another way to put it, there is no straight-forward way to invoke a function named "Keys", that's why the proposed error message feels like a mismatch. :)

The syntax errors could arguably be better but that's a major effort we don't plan to tackle in the short term (because it requires implementing a parser :D).
