### ISSUE TITLE
restart: :transient does not affect Task.Supervisor.async/async_nolink

### ISSUE THREAD

**Issue by sikanhe** [elixir-lang/elixir#4517]
For task supervisors, the processes can only be restarted when using start_child method. We cannot currently await on a task that we want to retry. 

```
{:ok, tas} = Task.Supervisor.start_link(restart: :transient)

Task.Supervisor.async_nolink(tas, fn -> 1 = 2 end) 
// does not restart
```

I understand there is a limitation that a Task is tied to a process, so it cannot possibly know about the new process that could get started. But this was unclear in the documentation. 

Do you think there is a way to await on  a supervised task that be restarted on crash? If so we should implement it because there is many cases where this could be helpful. If not I think we should clarify this in the docs more.

**Comment by josevalim** [comment]
Transient works. If you use Task.Supervisor.children, you will see new PIDs, showing the task is being restarted. Your conclusion is correct though, transient won't work for `async`  because it will never receive the initial request.

@fishcakez is there something we can do here? Maybe if the supervised task timeouts and the parent process is dead, maybe there is a better error message we can use?

**Comment by fishcakez** [comment]
https://github.com/elixir-lang/elixir/commit/eba153d0398c6d4ac39951e76c0e4618b52b950d prevents the Task.Supervisor from reaching max restarts if the caller is dead and restarts is `:transient`. That's about all we can do in this situation.

It is not possible to await on a restarted task because the monitor reference can not be reused or new pid detected by the caller. An improvement to the docs is very welcome.

**Comment by josevalim** [comment]
Thank you @fishcakez :heart:

@sikanhe you mentioned the docs were unclear, if so, please submit a pull request to improve them, we would really appreciate it. Thank you!
