### ISSUE TITLE
Vi style keybindings in `iex`

### ISSUE THREAD

**Issue by sbdchd** [elixir-lang/elixir#4533]
In `ipython`, `irb`, and  the`python` REPL, Vi style keybindings can be enabled via the [`.inputrc`](https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File.html) file.

However, this doesn't work with `iex`.

Environment
* Elixir version (elixir -v): 1.2.4
* Operating system: OSX 10.10.5

**Comment by parkerl** [comment]
I'm not sure this is the right place for this issue but I have had good luck with `rlwrap` and vi bindings on OS X. I have this alias `alias iex='rlwrap -m ''\'' -a dummy iex`. Sorry I don't have access to all my dotfiles right now, can't remember how I have vi bindings enabled.

**Comment by josevalim** [comment]
It is not possible because we are tied to Erlang's bindings and it is not high priority to do so. :)

**Comment by parkerl** [comment]
@sbdchd `.inputrc` is picked up by rlwrap. Using the alias above you can set `vi` mode and it works well for me in `iex`.

```
#.inputrc
set editing-mode vi
```

**Comment by arcseldon** [comment]
You lose auto-completion, but `rlwrap` does work as others have pointed out. More info here:

https://elixirforum.com/t/iex-vi-command-line-editing/3365

https://gist.github.com/jfreeze/8894279

You cannot have vi bindings through rlwrap AND command completion at the same time.
The author of rlwrap explains the reason here: http://stackoverflow.com/questions/9210931/is-there-a-way-of-running-rlwrap-with-tab-completion-disabled
