### ISSUE TITLE
:debugger.start loses module location after doing a Code.load_file

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#4543]
Related to this pull:  
https://github.com/erlang/otp/pull/977

Not sure if this belongs Erlang or Elixir, but you are only affected by this bug if you are using Elixir.

The debugger module was patched recently to find the modules, but doing a Code.load_file to hotload code breaks the heuristic, and you need to restart the whole app in order for it to find the module.

```
:debugger.start
:int.ni(MyModule)
{:module, MyModule}

Code.load_file mymodule.ex
:int.ni(MyModule)
** Invalid beam file or no abstract code: 'Elixir.MyModule'
:error
```

**Comment by antipax** [comment]
Grabbing this one.

**Comment by antipax** [comment]
https://github.com/erlang/otp/blob/maint/lib/debugger/src/int.erl#L548 

```
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.3.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :int.interpretable Test
true
iex(2)> :code.which Test
'/Users/ericentin/Documents/Code/test/_build/dev/lib/test/ebin/Elixir.Test.beam'
iex(3)> :int.ni Test
{:module, Test}
iex(4)> Code.load_file "lib/test.ex"
warning: redefining module Test (current version loaded from _build/dev/lib/test/ebin/Elixir.Test.beam)
  lib/test.ex:1

[{Test,
  <<70, 79, 82, 49, 0, 0, 3, 228, 66, 69, 65, 77, 69, 120, 68, 99, 0, 0, 0, 94,
    131, 104, 2, 100, 0, 14, 101, 108, 105, 120, 105, 114, 95, 100, 111, 99,
    115, 95, 118, 49, 108, 0, 0, 0, 4, 104, 2, 100, 0, ...>>}]
iex(5)> :int.interpretable Test
{:error, :badarg}
iex(6)> :code.which Test
:in_memory
iex(7)> :int.ni Test
** Invalid beam file or no abstract code: 'Elixir.Test'
:error
```

so it looks like that the problem is that Erlang won't treat a module as "interpretable" unless `:code.which` returns a file and not `:in_memory`. Looking into if we can take care of that on our end or if it will require another change in Erlang/OTP.

**Comment by antipax** [comment]
`:code.which/1` is returning `:in_memory` because the module is indeed only in memory after a `Code.load_file`, which seems to be intentional. Since `Code.load_file` does not write a .beam, we cannot use any modules loaded using it with `:int`, because to be interpretable, a module must have a .beam file.

Unless I'm misunderstanding something, I think this issue should be closed, because `Code.load_file` shouldn't write anything to disk and, without that, the module is not interpretable.

If you recompile and reload using Mix, such as recompile/0 does in iex:

```
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.3.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :int.ni Test
{:module, Test}
iex(2)> recompile
Compiling 1 file (.ex)
:ok
iex(3)> :int.ni Test
{:module, Test}
```

then everything works fine.

**Comment by josevalim** [comment]
Agreed. Perfect, thank you @antipax!

**Comment by vans163** [comment]
thanks @antipax

**Comment by vans163** [comment]
Wait nevermind. recompile restarts the entire app, that is not a valid solution.  I am trying to use 
Kernel.ParallelCompiler.files and files_to_path but cant figure out how they work.

I am using Code.load_file for all my hot loading hence why in the example.

**Comment by josevalim** [comment]
recompile in master no longer restarts the entire app. :)

**Comment by vans163** [comment]
@josevalim Perfect in that case.Now if only master (1.3) didn't break a bunch of old libs.

**Comment by josevalim** [comment]
Master should be backwards compatible. If some lib is breaking, please
include source and error message.

On Tuesday, May 24, 2016, vans163 <notifications@github.com> wrote:

> @josevalim <https://github.com/josevalim> Perfect in that case.Now if
> only master (1.3) didn't break a bunch of old libs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4543#issuecomment-221282207>
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by vans163** [comment]
@josevalim retracted that because fellow dev told me he tried switching to 1.3 and it broke some of the libs he was using.   If I actually get source/error will def file a report.
