### ISSUE TITLE
Make mix test accept a capture_log argument

### ISSUE THREAD

**Issue by ibizaman** [elixir-lang/elixir#4588]
I just found out about this argument by checking ExUnit's source code. It would be awesome if mix test could handle this argument and pass it to ExUnit.

Use case is that my tests produce a lot of output and 99% of the time I only want output relevant to the failed test(s).

**Comment by whatyouhide** [comment]
If 99% of the time you *don't* want any output from the logs, you may be better off using `@moduletag :capture_log` in your test cases, or `config :ex_unit, capture_log: true` in your configuration to capture the log from all tests. The [documentation for `ExUnit.Case`](http://elixir-lang.org/docs/stable/ex_unit/ExUnit.Case.html) has a "Log capture" session with more information about this.

Also, Elixir's issue tracker is reserved for bugs and issues with Elixir. The [elixir-lang-core](https://groups.google.com/forum/#!forum/elixir-lang-core) mailing list is where feature proposals should be posted so that the community can discuss them :) Thanks!

**Comment by josevalim** [comment]
Yes, there are multiple ways of doing this today!

  1. In your config:

        config :ex_unit, capture_log: true

  2. In your test_helper.exs:

        ExUnit.start capture_log: true

So you should probably go with one of the existing mechanisms. :)

**Comment by ibizaman** [comment]
I'm sorry for the confusion, I did not see those two ways of doing it @josevalim but I added `ExUnit.configure capture_log: true` in the test cases which works too, like @whatyouhide suggested.

I explicitly meant a way to set or not log output capture from the command line. But disabling it by default is good for me too.

I'm sorry to not have used the mailing list for those features, will do next time!
