### ISSUE TITLE
Add to_rfc3339 and from_rfc3339 to Time, Date and NaiveDateTime

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4676]
As specified here: http://www.ietf.org/rfc/rfc3339.txt

## Notes

  * `to_rfc3339`: Returns a string
  * `to_rfc3339`: All entries (hour, minute, second, ...) must be padded per the standard
  * `to_rfc3339`: Must match the calendar field on its inputs to be `Calendar.ISO`

  * `from_rfc3339`: Returns `{:ok, struct} | {:error, atom}`
  * `from_rfc3339`: Each parsed values must be checked for validity. The `new` function can be used for such after parsing
  * `from_rfc3339`: Microseconds must be parsed for times and naive datetimes. If higher precision is given, the value must be *truncated*.

For NaiveDateTime, given they do not store timezone information, we will make an amendment to the RFC3339 and make the timezone information optional. If the timezone information is given, it will simply be discarded.

/cc @lau @bitwalker

**Comment by bitwalker** [comment]
Just to recap my comment from #4672:

> I'm not strongly opposed to ignoring it, but I really kind of feel like if we have the UTC offset, we should shift it to UTC if we're going to discard the information.

I can tackle this, but I'm interested how you wish to see it implemented. Do you want a proper handwritten parser for RFC-3339, or is a regex sufficient? I'm assuming the former, but don't want to go down that road if it's more than what you are looking for here.

**Comment by lau** [comment]
I can kind of see the logic in using "RFC 3339" for parsing NaiveDateTimes.

But for formatting why not just use `o_iso8601`? And the documentation will say something like: returns a string with the NaiveDateTime formatted as a ISO 8601 datetime.

**Comment by lau** [comment]
- `to_iso8601/1`: you get a valid ISO 8601 string
- `to_rfc3339/1`: you get an invalid RFC 3339 string

**Comment by josevalim** [comment]
@bitwalker we already have a parser for RFC3339 in Ecto. I plan to port it tomorrow.

@lau maybe `to_rfc3339/2` where the second parameter is the missing timezone information (and defaults to incomplete empty string)?

**Comment by bitwalker** [comment]
@josevalim Oh that's right, never mind then :)

**Comment by lau** [comment]
@josevalim to_rfc3339/2 with no defaults might be less bad. But rfc3339/1 is just super dangerous and confusing IMHO. The name says rfc3339 but it is impossible to get a valid RFC 3339 string no matter the input. 100% invalid all the time.

What is wrong with `to_iso8601/1`? Super simple. 100% valid all the time. No surprises.

**Comment by josevalim** [comment]
Maybe we should call it to_string and go with a format that is parsed by
from_rfc3339?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
To answer your question directly, it feels a bit inconsistent to have
from_rfc and to_iso. Maybe to_string is the proper balance though given
DateTime will also only have the to_string one.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by lau** [comment]
Remember that if you take an RFC3339 string a lop off the UTC offset you have a perfectly valid ISO8601 string. So with `to_iso8601` you have a string which you can add "Z" to and you have a valid RFC3339 string.

The naming might seem assymetrical, but that is only because that is the truth. By calling it to_string we have a less telling name. Is it worth that just in order to "hide" the asymmetry?

**Comment by lau** [comment]
I would reconsider calling the parsing function `from_iso8601` for a moment:
Documentation:  `Parses an ISO 8601:2004 extended date time string. Discards any UTC offset information.`

Doesn't that describe the function OK?

Note that ISO 8601:2004 does not allow specifying years with two digits. 8601:2000 did.

RFC 3339 is more about requiring a UTC offset and how those are handled. We don't need to care about the UTC offsets.

Sure ISO 8601 also has rules for dates without time, week numbers etc., but by specifying an extended date time string in the documentation, it is pretty clear that we are not parsing a simple date. Also the module name is `NaiveDateTime` so that is also a sign that we are talking about a date time.

**Comment by lau** [comment]
Just noticed that it is also for Date and Time. ISO 8601 suports that too. RFC 3999 does not. I can implement these for ISO 8601.

**Comment by josevalim** [comment]
@lau you are correct. I have just read the spec and they also allow omitting T:

> NOTE By mutual agreement of the partners in information interchange, the character [T] may be omitted in applications where there is no risk of confusing a date and time of day representation with others defined in this International Standard. 

Source: http://www.uai.cl/images/sitio/biblioteca/citas/ISO_8601_2004en.pdf, page 19

However I think the to_iso8601 function must always include the T, correct? I will work on this today.

**Comment by josevalim** [comment]
ISO parsing functions were added.
