### ISSUE TITLE
Mix does not call a script located in rebar.conf's pre_hooks section

### ISSUE THREAD

**Issue by Annwenn** [elixir-lang/elixir#4695]
I'm opening this issue because Mix does not call a shell script located in the `pre_hooks` section of @tatsuya6502's h2leveldb's `rebar.conf` : leveldb-erlang/h2leveldb#9

**Comment by josevalim** [comment]
Thank you @Annwenn!

I believe this is a known limitation as Mix cannot really run on the same environment as Rebar. @ericmj, can you please confirm?

**Comment by ericmj** [comment]
Even if we did execute the pre_hook it wouldn't work correctly since it is manually git cloning into the deps dir. Mix has to control all dependencies for it to work correctly.

Looking at the code I can't see why it manually clones instead of adding the dependencies as "raw" deps in rebar.config. If you move the deps to rebar.config it might work better.

**Comment by Annwenn** [comment]
Alright, thanks :)

**Comment by tatsuya6502** [comment]
Thanks for the comment. I think when I created my project, there was no "raw" deps support existed in rebar. I will change the dependency to "raw" to see if it works.
