### ISSUE TITLE
Unpack archives after installation

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4733]
There is no reason to keep archives as .ez files after they are installed. Unpacking should improve boot times and possibly solve issues with update on Windows.

**Comment by ericmj** [comment]
We can further optimize it by calling a specific module, named by convention from the archive name (like `Mix.Tasks...`). That module has a function that registers all tasks and hooks into Mix.

This way we don't have to traverse every module in the archive.

**Comment by michalmuskala** [comment]
We talked a little bit about this on IRC. It seems the main issue is not unpacking the archives, but discovering the mix tasks.

What if we could somehow cache the list of available tasks? I see two solutions for that:
* compile a module mapping task name to module name similar to how protocol consolidation works. This module would only need to be recompiled if a task is not found or if a task was found but the module does not exist. Moreover we could always recompile on tasks like `mix help`. This is similar to having a module in archive with a callback registering the tasks, but done automatically by mix, and work for local tasks as well. 
* maintain a list of available tasks in `_build/tasks/*.beam` in a form of symlinks to real compiled modules. This list could be build at compile time when a module is detected to be a mix task. We always know what modules are compiled/recompiled so that list would always be fresh.

**Comment by ericmj** [comment]
> maintain a list of available tasks in _build/tasks/*.beam

This would work for dependencies but for archives all beam files are in the same directory. We could of course extract this list of beams and store it in the archive.

**Comment by michalmuskala** [comment]
If the archive is unpacked when installed, there could be a similar directory for each archive with it's tasks or for all archives with all the tasks from them. It would be easy to populate either one when installing the archive.

**Comment by josevalim** [comment]
> This way we don't have to traverse every module in the archive.

I am not worried about traversing all modules in the archive because we only do this for paths and we do this for everything in the load path. So I am not sure what we are gaining?

This PR is simply about unpacking them so the VM doesn't have too every time we boot.

**Comment by ericmj** [comment]
If we never traverse modules more than in `mix help` then ignore my suggestion.

**Comment by josevalim** [comment]
This has been merged but we should keep it open until we verify it works on Windows.

**Comment by michalmuskala** [comment]
So what is the main reason for lots of archives being slow? Is that unpacking or traversing all the modules in archives looking for tasks?

**Comment by josevalim** [comment]
I have verified this also works on Windows.

**Comment by josevalim** [comment]
@michalmuskala packing and unpacking the archives on boot. If we keep them unpacked, it is mostly a matter of having more load paths to handle.
