### ISSUE TITLE
ExUnit intermittently crashes on my project on Elixir 1.3

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#4771]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.0-rc.0 (7881123)
```
* Operating system:

OS X el capitan

### Current behavior

When running `mix test` on my project, I got this error from within ExUnit:

```
** (EXIT from #PID<0.47.0>) exited in: GenServer.call(ExUnit.Server, :take_sync_cases, 60000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in ExUnit.Server.handle_call/3
            (ex_unit) lib/ex_unit/server.ex:43: ExUnit.Server.handle_call(:take_sync_cases, {#PID<0.3534.0>, #Reference<0.0.3.7309>}, %{async_cases: [Delorean.Util.NetworkTest], loaded: :done, sync_cases: [Delorean.Util.CompressorTest], waiting: nil})
            (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

The test run immediately aborted at that point even though I was running `mix test` in the context of an umbrella project and there were many apps left to run tests for.

Unfortunately, it's only happened once and I have not been able to reproduce -- but hopefully the stacktrace will provide sufficient info.

### Expected behavior

I expect ExUnit not to crash :).

**Comment by eksperimental** [comment]
If you have the randomized generated seed it will probably help as well

**Comment by myronmarston** [comment]
> If you have the randomized generated seed it will probably help as well

I don't, unfortunately.  Although, I tried to use it to reproduce and wasn't able to reproduce with the same seed.

**Comment by fishcakez** [comment]
In 1.3 we started running tests as soon as they are loaded. Looks like we have a race condition where asyncs are empty only for more to get loaded before we try to grab synchronous ones. Likely we need to have one take function and let the server decide what to give.

**Comment by josevalim** [comment]
@myronmarston do you remember if another error got reported? For example, you were trying to load some file that had a syntax error on it? I believe that it is the only situation this error would happen.

**Comment by josevalim** [comment]
Here is some rationale why I don't think this can happen except in case of errors.

`mix test` will spawn a task to run tests, that's the one effectively calling `take_sync_cases`. Then the main process will proceed to load all files and signal that all cases have been loaded only after all files have been loaded:

https://github.com/elixir-lang/elixir/blob/2a1d3d65303c96da56200d29a333310adfd8bace/lib/mix/lib/mix/compilers/test.ex#L45-L53

The test runner will keep getting async cases until `nil` is returned by take async cases:

https://github.com/elixir-lang/elixir/blob/2a1d3d65303c96da56200d29a333310adfd8bace/lib/ex_unit/lib/ex_unit/runner.ex#L71

And nil can only be returned in take async cases if all cases have been loaded:

https://github.com/elixir-lang/elixir/blob/2a1d3d65303c96da56200d29a333310adfd8bace/lib/ex_unit/lib/ex_unit/server.ex#L70

Given that cases are marked as loaded only after all files are fully loaded, it is impossible for us to add a new async cases after cases have been loaded.

On the other hand, if a test file fails to load, the file loader will exit here:

https://github.com/elixir-lang/elixir/blob/2a1d3d65303c96da56200d29a333310adfd8bace/lib/mix/lib/mix/compilers/test.ex#L48

Which will invoke cases_loaded as part of `after` while other test files are still being loaded. In such scenarios, we will call add_async_cases and add_sync_cases **after** cases_loaded, possibly leading to the error reported. This can happen only from time to time because it requires a case to be loaded and the runner to ask for new cases between the parent process crashing.

I think we can improve this in two ways:

1. Remove the try/after from when we call cases_loaded(). We should call it only if loading files succeed

2. Add guards here to ensure loaded is not `:done` so we can catch potential race conditions early on: https://github.com/elixir-lang/elixir/blob/2a1d3d65303c96da56200d29a333310adfd8bace/lib/ex_unit/lib/ex_unit/server.ex#L58-L64

I will push those changes oon.

**Comment by myronmarston** [comment]
@josevalim When I got the error I believe it was the only error I got.  I don't have the output from that run handy at this point so I could be remembering wrong.

Regardless, thanks for looking into the issue and applying a fix.  I'll let you know if I see it again.  If it does happen again (and is still non-reproducible for me), is there any additional information I should make sure to provide?

**Comment by josevalim** [comment]
Having the full run should be useful. Plus, if the error still exists, I
hope it will show up closer to the actual source now!

On Monday, June 6, 2016, Myron Marston <notifications@github.com> wrote:

> @josevalim <https://github.com/josevalim> When I got the error I believe
> it was the only error I got. I don't have the output from that run handy at
> this point so I could be remembering wrong.
>
> Regardless, thanks for looking into the issue and applying a fix. I'll let
> you know if I see it again. If it does happen again (and is still
> non-reproducible for me), is there any additional information I should make
> sure to provide?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4771#issuecomment-224033157>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbqLahWZg3UVFRlgJbJqJib8cn04Iks5qJFydgaJpZM4It_eA>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
