### ISSUE TITLE
mix is not respecting clean.

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#4773]
mix.lock holds relics to old versions of repos.  When those repos get updated (on github) doing a mix clean, mix deps.get,  or deleting _build directory does not give you the latest version.

You need to delete mix.lock file. 

Should mix clean not clear out any mix.lock relics?

Perhaps a related mix issue: https://github.com/elixir-lang/elixir/issues/4770

**Comment by michalmuskala** [comment]
I think this is perfectly intentional and correct behaviour. `mix.lock` ensures that the builds are fully repeatable - until you explicitly change a version of a dependency you should get exactly the same code each time you get it. 
If you want to update a dependency you can use `mix deps.update` or unlock it with `mix deps.unlock`.

**Comment by fishcakez** [comment]
It is intentional for the `mix.lock` file to remain beyond a `mix clean --deps` so we get repeatable builds. This is a feature :). It is much safer to use the commands @michalmuskala suggested to unlock/update.

**Comment by vans163** [comment]
I see okay thanks. I just found it really unintuitive then, also checking 'mix help' did not help much to explain how to clean out all the project deps and start from scratch.
