### ISSUE TITLE
Add --force flag to mix deps.compile

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#4776]
When the flag is set build artifacts should be cleaned before compiling.

**Comment by felipesere** [comment]
@ericmj I'd love to take this one

**Comment by josevalim** [comment]
@felipesere all yours. :)

**Comment by felipesere** [comment]
Quick question:
How would I check that deps were actually re-compiled?
I thought about using the mtime of `_build` or some other folder, but I just get second-resolution...

**Comment by josevalim** [comment]
Since you will be cleaning before compiling, you can write a bogus file
inside the application directory in _build and ensure it is no longer there
after compilation.

On Saturday, June 4, 2016, Felipe Seré <notifications@github.com> wrote:

> Quick question:
> How would I check that deps were actually re-compiled?
> I thought about using the mtime of _build or some other folder, but I
> just get second-resolution...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4776#issuecomment-223763803>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbs9-mFTIi3xKXR2wixhVK6C6dB-iks5qIaOYgaJpZM4IuHq->
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
@ericmj I just realized that cleaning the target in _build is not going to
do anything for make and rebar dependencies since the artifacts are added
deps/app.

On Saturday, June 4, 2016, Felipe Seré <notifications@github.com> wrote:

> Quick question:
> How would I check that deps were actually re-compiled?
> I thought about using the mtime of _build or some other folder, but I
> just get second-resolution...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4776#issuecomment-223763803>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbs9-mFTIi3xKXR2wixhVK6C6dB-iks5qIaOYgaJpZM4IuHq->
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by felipesere** [comment]
This is my first stab, though its not working: https://github.com/elixir-lang/elixir/pull/4780
Pointers/advice/suggestions either here or on the PR are super-welcome.

**Comment by myronmarston** [comment]
Since `mix compile` will compile dependencies if needed (as well as your project files), will `--force` in `mix compile --force` apply only to your project files or to dependencies, too?

Ideally, I'd like it to apply to only your project files, because in our CI builds we:

* Have travis configured to cache `deps` and `_build` so that dependencies do not have to be re-compiled on every CI build
* Use `mix compile --force --warnings-as-errors` to force compile all our project code and surface any warnings as errors

It'd be nice if `--force` didn't trigger compilation of our dependencies, too.

**Comment by ericmj** [comment]
> I just realized that cleaning the target in _build is not going to
do anything for make and rebar dependencies since the artifacts are added
deps/app.

Can't we do the same thing we do for `deps.clean` or are you saying that `deps.clean` is also broken?

> Since mix compile will compile dependencies if needed (as well as your project files), will --force in mix compile --force apply only to your project files or to dependencies, too?

`mix compile --force` should not clean deps.

**Comment by felipesere** [comment]
@myronmarston I haven't touched `Mix.Tasks.Compile` so your setup with CI should remain unaffected. 😄 

@ericmj @josevalim I have updated the PR and the tests pass.
I am not sure on how to name a function that _may_ do something (like cleaning in this case) or not.
`?` felt like a predicate and `!` like it could raise...

More feedback is welcome.
