### ISSUE TITLE
Unzip escript on installation

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#4902]
On installation unzip the escrip contents into a directory and generate a shell script (or bat file for windows) that will load the escript code and call the `main` function. The benefits of this is faster start time for the escript and that we should be able to use `priv` directory from the escript.

Here is an example of how rebar3 does it: https://github.com/erlang/rebar3/blob/master/src/rebar_prv_local_install.erl

**Comment by ericmj** [comment]
@antipax This is up for grabs if you want it :)

**Comment by antipax** [comment]
Cool, happy to tackle this.

**Comment by antipax** [comment]
As discussed in IRC, due to limitations in how `erl -run` works we need to generate an extra beam as part of the extraction process which defines `main/0` and `main/1`, where the `main/0` calls `main/1` with an empty list and `main/1` calls the escript's entry point with the given argument.

**Comment by antipax** [comment]
A couple issues:

* Not all escripts can be safely extracted. The only example I've come up with so far is that any escripts with their shebang modified from the default should not be extracted. Thus, we need a way to determine which escripts can be extracted and which cannot. It would seem that the two options would be to do some kind of analysis on the escript (i.e. that the shebang is the default, and other checks if anyone can come up with other exceptions) or adding a key of some kind to the comment like `%%ELIXIR_EXTRACTABLE_ESCRIPT%%` that indicates Elixir should extract the escript. @ericmj said he preferred the latter and I agree. 

  Additionally, @ericmj suggested adding a flag like `--no-extractable` to `escript.build` so that you have to explicitly disable extraction. Without this flag, changing any options which would make the escript unextractable (shebang) would produce an error during build. This would give us an opportunity to document that the priv dir will only work for extractable escripts.

* Currently `escript.install` will only install escripts with a shebang line, a comment line, a emu_args comment line, and a archive section. Since escripts can omit the comment line and the emu_args line, or even not use an archive, perhaps this check should be improved, or removed entirely.

Looking for feedback before moving forward, so please share any ideas. :)

/cc @josevalim

**Comment by josevalim** [comment]
>  This would give us an opportunity to document that the priv dir will only work for extractable escripts.

Actually, it would only work if you install extractable escripts, which is even more constrained still. Btw, how does rebar solve those issues?

@ericmj, @antipax - the issue I am seeing is that, if we are going to provide such flags, we would make the line between escripts and archives even blurrier. :( So now escripts may support priv depending on how they are installed? But still both escripts and archives are unpacked now?

**Comment by ericmj** [comment]
> Actually, it would only work if you install extractable escripts, which is even more constrained still. Btw, how does rebar solve those issues?

The same is true for archives. Rebar doesn't have these issues because they fully control how the escript is built and installed.

> [...] we would make the line between escripts and archives even blurrier.

Why is the line blurrier? Should we not add features to escripts because those features already exist in archives and that would make the distinction confusing?

**Comment by josevalim** [comment]
> The same is true for archives. Rebar doesn't have these issues because they fully control how the escript is built and installed.

Don't we fully control as well? :)

> Why is the line blurrier? Should we not add features to escripts because those features already exist in archives and that would make the distinction confusing?

Well, not adding it is one possible outcome. But generally it just means we need to be more careful, even if the final solution just ends-up meaning "adding more documentation".

**Comment by antipax** [comment]
I've flip-flopped a few times on whether this is worth it or not myself. I think if we can support the priv dir in escripts there's obvious use cases for that, and so far it's pushed me in the direction of this being worth doing.

Maybe instead of opt out, extractability should be a special mode of escript generation? They would allow use of the priv dir, but also require extraction. If they are not installed, they would produce an error with install instructions. We could also produce an error if you attempt to generate an escript from a project with a non-empty priv dir that is not in extractable mode.

**Comment by josevalim** [comment]
Well, we started on this road exactly because we thought extracting by
default is a good idea. The other downside is that if we are extracting
because of priv, it only works if you extract it, which means the escript
only works if Elixir installs it, which defeats part of the purpose behind
escripts.




*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by antipax** [comment]
So, what do we see as the reasons for extracting by default? As I understand it, there are two:

* *Performance* - we have not yet profiled what kind of speed up is actually achieved by extraction, and if it is worth the ~50% increase in disk space usage (measured with a minimal 1-module escript), so currently this seems like a "nice to have" rather than a good reason to handle all the complexity of extracting escripts

* *Ability to use priv* - this is a solid reason, but it is important to note that if an escript which uses priv is not extracted, it will not work because priv will not be available. As @josevalim notes, this defeats part of the purpose of escripts, but I could imagine, for example, an escript of a short-running web app which needs to bundle css/img/js as part of its distributable. Thus I believe there is a strong argument to support this kind of use case.

So, firstly, I think we need to measure what kind of performance improvement is gained by extraction to determine whether it is worth it in the general case.

Second, if we add extraction, we will need to add some way for escripts which use the priv dir to require installation. Otherwise it will be confusing, IMO.

Thoughts?

**Comment by ericmj** [comment]
> The other downside is that if we are extracting because of priv, it only works if you extract it, which means the escript only works if Elixir installs it, which defeats part of the purpose behind escripts.

I think a major source of escripts usage will be from `mix escript.install foo`. That is much easier to do than to build an escript yourself (for the oldest OTP version), host it somewhere and ask users to manually download them and copy them to PATH.

**Comment by josevalim** [comment]
Well, everyone using escripts today is not for this reason. :) if the
reason why we think this will be useful is because of mix escript.install I
think we should wait until we have more data points.

On Thursday, June 30, 2016, Eric Meadows-Jönsson <notifications@github.com>
wrote:

> The other downside is that if we are extracting because of priv, it only
> works if you extract it, which means the escript only works if Elixir
> installs it, which defeats part of the purpose behind escripts.
>
> I think a major source of escripts usage will be from mix escript.install
> foo. That is much easier to do than to build an escript yourself (for the
> oldest OTP version), host it somewhere and ask users to manually download
> them and copy them to PATH.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4902#issuecomment-229677644>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbjJQ8O6rBPTbFim1R5_HP0AuW000ks5qQ9R2gaJpZM4JAp6r>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
@ericmj @antipax I am more inclined to postpone this. Does everyone agree?

**Comment by antipax** [comment]
👍

**Comment by ericmj** [comment]
As with the typespec discussion the other day I don't think you can compare usage data of an existing feature with one that doesn't exist yet :).

I am for postponing this if we can't decide right now on how to handle the edge cases.

**Comment by josevalim** [comment]
Yes, let's wait so for more use cases so we consider if we should optimize it. :)
