### ISSUE TITLE
Elixir's Kernel defines both to_char_list and to_charlist

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#4909]
### Current behavior

Elixir's Kernel defines the macro `to_charlist/1` as well as `to_char_list/1`. The first version includes documentation, the second version does not.

### Expected behavior

I am not sure if there is a reason for the second version (`to_char_list/1`) to exist. 

- If it is a duplicate, we could remove it. 
- If however there is a reason for its existence, it should receive documentation.

**Comment by Qqwy** [comment]
Hmm... Diving in the source, I see that it already is marked as 'TODO: Deprecate in version 1.5', so maybe I spoke too soon and this issue is already kown.

Right now it has `@doc false`. Is it better to give it documentation that states that it is deprecated as well?

**Comment by whatyouhide** [comment]
The second version (`to_char_list/1`) will be deprecated in future versions of Elixir 1.5, and for now it's softly deprecated, meaning it's not shown in documentation but no warning is emitted when it's used. You can see `TODO: ...` deprecation comments [here](https://github.com/elixir-lang/elixir/blob/dfd5e79590bf743795d182bd05cd4277fcbb2f7a/lib/elixir/lib/kernel.ex#L4313).

 We shouldn't show documentation for these functions, so that users will just not see them as available.

**Comment by michalmuskala** [comment]
If it's soft-deprected, should that mean, it shouldn't show up when TAB-completing in iex? It currently does show up.

That's contrary to `String.strip/2` that was deprecated as well, but does not show up when TAB-completing.

**Comment by eksperimental** [comment]
When i read this issue, i thought of thw same tging michal is mentioning. How did qqwy find out about the function if he hadn't read the source code by the. And IEx came to my mind

**Comment by whatyouhide** [comment]
Oh, @michalmuskala is right, it appears in IEx. This appears to be a problem just in `Kernel` though, since if you try to autocomplete `String.to_char` it only shows `String.to_charlist/1` as expected. `Kernel` however behaves differently, i.e., `Kernel.to_char` and just `to_char` both show `to_char_list/1` as well.

**Comment by lexmag** [comment]
Should be fixed in https://github.com/elixir-lang/elixir/commit/9740544f54824e720738413820b83b7e3b911fc7. :bowtie:

**Comment by whatyouhide** [comment]
I definitely missed that it was commented D: Thanks @lexmag!

**Comment by eksperimental** [comment]
thank you @lexmag  for the fix, it was my fault

**Comment by josevalim** [comment]
And of everyone who reviewed it, like me. :) it happens!

On Saturday, July 2, 2016, Eksperimental <notifications@github.com> wrote:

> thank you @lexmag <https://github.com/lexmag> for the fix, it was my fault
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4909#issuecomment-230113732>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbt7ja7-8OVf5eerUcuUjIGD6ncptks5qRqO6gaJpZM4JBHaw>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by eksperimental** [comment]
@josevalim  I think we should backport this to 1.3.x

**Comment by eksperimental** [comment]
nevermind, @lexmag already took care of it https://github.com/elixir-lang/elixir/commit/cc35c8fc222fb8665be0efd5dd8a91a246d87680

**Comment by Qqwy** [comment]
Guys, you are awesome :heart_eyes:
