### ISSUE TITLE
Support -abc in OptionParser

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4920]
It should be equivalent to -a -b -c. For example, `-abc foo` should be equivalent to `-a -b -c foo`.

**Comment by c0b** [comment]
:clap: a good start here, from https://github.com/elixir-lang/elixir/pull/4412#issuecomment-198810626 (I have some unfinished code from there but if anybody here already have an implementation, that's better) 

Can we clarify if someone defined `aliases: [abc: :long_option_for_abc]` that won't be supported, right? this is an undocumented behavior and will be broken?

```elixir
iex(3)> OptionParser.parse(["-abc", "foo"], aliases: [abc: :long_option_for_abc])
{[long_option_for_abc: "foo"], [], []}
```

**Comment by josevalim** [comment]
Yes, aliases must be single letters. We should make it as clear as possible.

**Comment by whatyouhide** [comment]
I was quickly investigating this and found out that we currently use multiletter aliases in some places in Elixir (for example [here](https://github.com/elixir-lang/elixir/blob/0e073b83e3f065968610ae82c87f91eb6c6d40cf/lib/mix/lib/mix/tasks/run.ex#L49), we support `-pr` in the `mix run` task as an alias for `--parallel-require`, and we have the same for the `elixir` executable). We can't rename these aliases because it would break backwards compatibility, and supporting both multiletter aliases as well as `-abc -> -a -b -c` would make the implementation convoluted and error prone, so we decided to not support this. Maybe in Elixir 2.0 :) 

Thanks anyways @c0b! 💟

**Comment by tuvistavie** [comment]
Not having this feature is IMO a deal breaker to use `OptionParser` for CLI apps.
Nobody wants to set verbosity with `-v -v -v`. 
Maybe we could have an option to enable/disable this feature? For example let's say:

```elixir
OptionParser.parse(["-abc", "foo"], posix: true)
```

Also, I think it's perfectly fine to have multiletter aliases, but I think it should conform
to the POSIX guidelines, so that `-abc` expands to `-a -b -c` whatever alias is defined,
while `--abc` actually use the multiletter alias.

If you think adding an option is ok for now, I would be very glad to give the implementation a try.

**Comment by josevalim** [comment]
I have an idea. If `-pr` is the only value we use in Mix, we can break it apart in two options: `--parallel` and `--require`, with aliases `-p` and `-r`. We can deprecate `--parallel-require` specially as we will be able to use `-pr` in the past and in the future. The only downside of this change is that you won't be able to mix both `-r` and `-pr` options anymore but I think that's an acceptable compromise?

**Comment by whatyouhide** [comment]
That's a good compromise @josevalim. If that's ok I can take care of splitting `--parallel-require` and then @c0b you can work on making `-abc -> -a -b -c` :)

**Comment by whatyouhide** [comment]
@josevalim however, I am not 100% sure I got that right: you mean `--parallel` should become a boolean switch that accompanies the following `--require`, so that basically `--parallel-require FOO` becomes `--parallel --require FOO`?

**Comment by josevalim** [comment]
--parallel is a Boolean switch that changes how require work but it doesn't
need to be given in order. It could be anywhere.

On Saturday, July 2, 2016, Andrea Leopardi <notifications@github.com> wrote:

> @josevalim <https://github.com/josevalim> however, I am not 100% sure I
> got that right: you mean --parallel should become a boolean switch that
> accompanies the following --require, so that basically --parallel-require
> FOO becomes --parallel --require FOO?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4920#issuecomment-230095008>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbq4qDxdztXarndQc_I9O-JEHfaFXks5qRj0PgaJpZM4JDW-I>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whatyouhide** [comment]
@josevalim so it will change all `require`s to be parallel requires? Sorry it's tooking me a while to get it right 😄

**Comment by josevalim** [comment]
@whatyouhide yes!

**Comment by whatyouhide** [comment]
@c0b I just deprecated `-pr` in the Mix tasks, so if you want you can work on splitting `-abc` to `-a -b -c` :) If you want me to work on that, just ping me! 💟

**Comment by josevalim** [comment]
@whatyouhide should we update the Mix tasks where we have added the `-pr` workaround? :)

**Comment by whatyouhide** [comment]
@josevalim yep, doing that right now :)
