### ISSUE TITLE
`mix deps.get` wrongly tells "All dependencies up to date" when not connected to the internet

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#4963]
Running master

with no internet connection,

```sh
$ mix deps.get
Registry update failed (http_error)
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :nxdomain}]}
Running dependency resolution
All dependencies up to date
```

I wouldn't expect to see 
```
Running dependency resolution
All dependencies up to date
```

which is not true

may be a friendly and more informative message message saying "please check your internet connection, or firewall"

**Comment by ericmj** [comment]
How do you know it's not true? By the flow you showed there would be no new dependencies being fetched even if the registry was successfully fetched.

As far as hex knows all dependencies are up to date according to the registry it has. Hex is still supposed to work even if your internet connection is down and I think the error message shows that there was an issue fetching the registry.

**Comment by ericmj** [comment]
On hex master, the message "Registry update failed" has changed to "Failed to update registry (using the cache)" and is shown in yellow text to more clearly show that it failed to fetch the registry.

**Comment by josevalim** [comment]
> On hex master, the message "Registry update failed" has changed to "Failed to update registry (using the cache)" and is shown in yellow text to more clearly show that it failed to fetch the registry.

Beautiful, I was going to propose just something like this! 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by ericmj** [comment]
To clarify, if all your dependencies are locked (as in your example) you will still get the message "All dependencies up to date" even if you have an older registry. This message does not mean that you have the latest version of all dependencies, it's meant to inform you that all your dependencies are up to date compared to your lock and mix.exs file.

The reason the error message in hex was updated was to make it more clear that the registry failed to fetch because there is a possible DoS attack by making the registry fail to fetch and force users to use an older, cached registry with older packages that has known security issues. On the other hand you still want to be able to use hex if you are on a flight or if your internet is down for some reason. So we have to weigh that against the potential security issue and I think the new error message is a good compromise.

**Comment by eksperimental** [comment]
Thanks for the explanation, and for updating the message, but still i think there is a something that is telling me it's not right.. and it is this.
`All dependencies up to date`

I think it is deceiving to run a command to update your dependencies, and it fails to connect and it still shows such a message.

given we get the :failed_to_connect error, could the message be more details as such:
`All dependencies in cached registry are up to date`

**Comment by ericmj** [comment]
> I think it is deceiving to run a command to update your dependencies, and it fails to connect and it still shows such a message.

But you are not updating your dependencies, that is `deps.update`, you are calling `deps.get`.

The message is from mix and it has no idea if the hex registry is fresh or not. I don't think "All dependencies in cached registry are up to date" makes sense because "up to date" != "latest". As I said earlier "up to date" means the dependencies are up to date compared to the mix.lock and mix.exs files. For example you will still get the same messages if you are fetching git dependencies and there have been new commits to the git repositories.

If we should change anything we should update the message to more clearly indicate what we mean with "up to date".

**Comment by eksperimental** [comment]
Well, I think the message should be improved then to explain what we mean by  "up to date".
only when you do `mix help deps.get` you can find out about the mix.lock, (and no mentions to mix.exs).

Also by running `mix help deps.update` is hard to tell what is the difference between the two commands.

**Comment by ericmj** [comment]
Agreed that we can improve the docs and messages. A PR would be very appreciated.

**Comment by eksperimental** [comment]
sorry eric, i don't feel qualified for this one as I have a hard time understanding the differences as you can see :-P
