### ISSUE TITLE
Fail when calling use and __using__/1 is a function

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#4967]
This is a followup on a discussion we had on IRC.

\cc @whatyouhide @antipax @fishcakez 

It's a common error (and not just a beginner error) to define `__using__/1` as `def` instead of `defmacro`. The worst thing is that the code silently passes that point, but fails somewhere else down the road because of not imported functions, not required macros, etc. 

However, it would be bad to special case this on the level of function definition and look for `def __using__(opts)` - it's a slippery slope, as there are much more functions that could be special-cased (like `handle_call/2`, etc.). Fortunately, there is a good place to check for this, without special-casing anything in  the compiler, and that's the expansion of `use Module` call. Instead of just blindly calling `Module.__using__(opts)` there could be a check to verify it's indeed a macro, and fail if it isn't.

There might be a valid use case of `__using__/1` being a function, but we failed to find any reasonable ones.

**Comment by josevalim** [comment]
All of the callbacks can be a functions by design. Maybe you just want to
register the module itself and not actually generate anything.

I don't think we should remove this feature. I understand the need to
provide a good development workflow but use is already a slightly advanced
feature and I don't think it is worth at the cost of removing features or
introducing special cases for advanced features.

On Friday, July 8, 2016, Michał Muskała <notifications@github.com> wrote:

> This is a followup on a discussion we had on IRC.
>
> \cc @whatyouhide <https://github.com/whatyouhide> @antipax
> <https://github.com/antipax> @fishcakez <https://github.com/fishcakez>
>
> It's a common error (and not just a beginner error) to define __using__/1
> as def instead of defmacro. The worst thing is that the code silently
> passes that point, but fails somewhere else down the road because of not
> imported functions, not required macros, etc.
>
> However, it would be bad to special case this on the level of function
> definition and look for def __using__(opts) - it's a slippery slope, as
> there are much more functions that could be special-cased (like
> handle_call/2, etc.). Fortunately, there is a good place to check for
> this, without special-casing anything in the compiler, and that's the
> expansion of use Module call. Instead of just blindly calling
> Module.__using__(opts) there could be a check to verify it's indeed a
> macro, and fail if it isn't.
>
> There might be a valid use case of __using__/1 being a function, but we
> failed to find any reasonable ones.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4967>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbsETlfn5DRabVNOM0jjXTXwemqgMks5qToEBgaJpZM4JINZk>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by michalmuskala** [comment]
I understand you could use `__using__` function for evaluating for side-effects. But that seems like a horrible idea anyway - using something that normally is used for macros to process some side-effects at compile time.

Do we have some examples of people actually using that?

**Comment by josevalim** [comment]
`import` is a side-effect. ExUnit.Case uses it for a side-effect as well: registering the test case. However it also does other things (and that's why it ends up being a macro). I likely don't have an example where someone is using it only for side-effects but recall using before_compile and after_compile callbacks for side-effects and I wouldn't introduce an inconsistency.

**Comment by whatyouhide** [comment]
The thing is that we (somehow heavily) advertise `__using__/1` to be a macro. We don't do the same for `@before_compile` and `@after_compile` though. Should we say `__using__/1` can just be anything and stop saying it has to be a macro then?

**Comment by ericmj** [comment]
> The thing is that we (somehow heavily) advertise __using__/1 to be a macro.

Where do we say this? We should definitely fix that.

**Comment by whatyouhide** [comment]
@ericmj we say that in the [docs for `use/2`](http://elixir-lang.org/docs/master/elixir/Kernel.html#use/2). Should I fix that then? I can do it later today :)

**Comment by ericmj** [comment]
Please do :)
