### ISSUE TITLE
`x in [1 | rest]` raises `undefined function |/2`

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#4968]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.1
```

* Operating system:

OS X El Capitan

### Current behavior

```
iex(1)> x = 5
5
iex(2)> nums = 2..5 |> Enum.to_list
[2, 3, 4, 5]
iex(3)> x in [1 | nums]
** (CompileError) iex:3: undefined function |/2
    (elixir) expanding macro: Kernel.in/2
             iex:3: (file)
```

### Expected behavior
 
I'd expect to be able to prepend to a list on the right side of an `in` expression.  I also tried using parens (`x in ([1 | nums])`) -- which seems like that should force the prepend to be evaluated first -- but that also fails.  It works if I do this, though:

```
iex(3)> list = [1 | nums]
[1, 2, 3, 4, 5]
iex(4)> x in list
true
```

**Comment by antipax** [comment]
Looks like this is because the [code](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel.ex#L2860) is not taking the appropriate branch because it's not technically in a module in IEx.

I think the in_module? check needs to be changed to an in_guard? check? If I'm on the right track happy to do a PR for the fix.

**Comment by antipax** [comment]
Yeah, I was wrong. It's because the quoted form of `[1 | nums]` is `[{:|, [line: 7], [1, {:nums, [line: 7], nil}]}]`, so the `[h | t]` clause in `in` is pulling the `:|` call out of the list as an element to compare against. One option would be to special case lists like the one above so that they use `Enum.member? `instead of the optimized static check, which can't be used for this.

**Comment by josevalim** [comment]
We should actually compile such cases to "x === 1 or Enum.member?(rest,
x)". This way we can keep similar logic as today and optimize as far as we
can go.

On Saturday, July 9, 2016, Eric Entin <notifications@github.com> wrote:

> Yeah, I was wrong. It's because the quoted form of [1 | nums] is [{:|,
> [line: 7], [1, {:nums, [line: 7], nil}]}], so the [h | t] clause in in is
> pulling the :| call out of the list as an element to compare against. One
> option would be to special case lists like the one above so that they use
> Enum.member?instead of the optimized static check, which can't be used
> for this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4968#issuecomment-231498933>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbuaZIxv1VHT-6094WqM83nj_T1Szks5qTuL6gaJpZM4JIeap>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by antipax** [comment]
Oh cool, that's even better. @josevalim ok if I do a PR?

**Comment by josevalim** [comment]
Yes please.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
