### ISSUE TITLE
String.split with parts and trim: true doesn't trim last substring

### ISSUE THREAD

**Issue by MSch** [elixir-lang/elixir#5069]
Elixir 1.3.2 on Erlang 19.0.2

Using `String.split` with `trim: true` doesn't trim the last part if it returns exactly `parts` parts.

```elixir
["x", ""] = String.split("x-", "-", parts: 2, trim: true) # should return ["x"]
["x", "x", ""] = String.split("x-x-", "-", parts: 3, trim: true) # should return ["x", "x"]

# these do trim
["x"] = String.split("x-", "-", parts: 3, trim: true)
["x", "x"] = String.split("x-x-", "-", parts: 4, trim: true)
```

**Comment by whatyouhide** [comment]
I can look into this.

**Comment by cogle** [comment]
I believe this is due to the fact that is the parts is exactly one more then the number of expected results the code will execute line number 353.

In the first case where the string is `"x-"` the returned value from executing the case statement at line 355 will be `{"x", ""}`. 
This pattern matches with the first condition with the following values `["x" | split_each("", "-", :true, 1)]`.
This will then invoke the `split_each` function at line number 353. Which will immediately return the empty string. This case will occur for anytime the parts is exactly one more then the size of the expected results.

Is the empty string ever a valid return? If not an addition function could be made
` defp split_each("", _pattern, _trim, 1) when is_binary(string), do: []`

Hope this helps.

**Comment by cogle** [comment]
I created a pull request #5077 for this issue.

**Comment by whatyouhide** [comment]
Thanks @cogle, I got caught up a bit and didn't have time to finish looking into this, great job :)
