### ISSUE TITLE
Add Core Infrastructure Iniative Best Practices badge

### ISSUE THREAD

**Issue by devonestes** [elixir-lang/elixir#5184]
The Linux Foundation has their Core Infrastructure Initiative now to ensure that key open source projects are well taken care of and are following best practices that will help us avoid the next HeartBleed. One of the things that they've done is to create a badge that projects can put on their repos to show that they're following the best practices laid out by the foundation. This is currently missing from Elixir, and I think it would be both a good thing to show to Elixir users so they know that Elixir is doing all it can to be safe and secure, as well as a good reason to do a quick survey to be sure that Elixir is indeed meeting all these best practices 😉 

More information about the badge can be found here: https://github.com/linuxfoundation/cii-best-practices-badge, including information about how to sign up to get the badge.

**Comment by josevalim** [comment]
Thank you @devonestes. If someone wants to double check we follow their principles, a pull request is welcome in case anything is missing, but we would skip the badge for now as I am personally not a fan of badges. The only badge we currently have is the CI one since it helps those running tests on their machines.
