### ISSUE TITLE
put-element does not functioning as expected

### ISSUE THREAD

**Issue by koti-ave** [elixir-lang/elixir#5209]
### Precheck

* Do not use the issues tracker for help or support (try Elixir Forum, Stack Overflow, IRC, mailing list, etc.)
* For proposing a new feature, please start a discussion on the Elixir Core mailing list
* For bugs, do a quick search and make sure the bug has not yet been reported
* Finally, be nice and have fun!

### Environment

* Elixir version (elixir -v):
Erlang/OTP 18 [erts-7.0] [64-bit] [smp:4:4] [async-threads:10]
Elixir 1.3.2
* Operating system:
Windows 7

### Current behavior

iex> tuple = {:ok, "hello"}
{:ok, "hello"}
iex> put_elem(tuple, 1, "world")
{:ok, "world"}

### Expected behavior

iex> tuple = {:ok, "hello"}
{:ok, "hello"}
iex> put_elem(tuple, 1, "world")
{"hello", "world"}

**Comment by josevalim** [comment]
Tuple indexes start from 0. Generally indexes in Elixir start from zero.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by koti-ave** [comment]
So the in the line 3 when we say (tuple,1,"world") the 1 indicates the index? if so it should be "hello". Isn't it?

**Comment by whatyouhide** [comment]
Hey @koti-ave, as you can read in the documentation for [`Kernel.put_elem/3`](http://elixir-lang.org/docs/stable/elixir/Kernel.html#put_elem/3), yes the second argument (`index`) indicates the index. In your example (`put_elem(tuple, 1, "world")`), `1` indicates the index and since indexing is zero-based, it indicates the *second* element. That second element is `"hello"` in the original `{:ok, "hello"}` tuple, which means replacing it with `"world"` yields `{:ok, "world"}`. Look at the examples in the docs for `put_elem/3`, they may be helpful to understand how it behaves (and if you have suggestions on how to improve such docs, please don't hesitate to write them here even if I'm closing this issue right now 💟).
