### ISSUE TITLE
%{...} invalid typespec

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#5360]
Working on https://github.com/elixir-lang/elixir/issues/5351 and writing a test that checks every single typespec described in the documentation, I found another bug.

```elixir
  @spec foo(number) :: %{...}
  def foo(a) do
    a
  end
```

```console
== Compilation error on file lib/specs.ex ==
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Macro.map_list_to_string/2
    (elixir) lib/macro.ex:904: anonymous fn({:..., [line: 16], nil}) in Macro.map_list_to_string/2
    (elixir) lib/enum.ex:1215: anonymous fn/4 in Enum.map_join/3
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1214: Enum.map_join/3
    (elixir) lib/macro.ex:609: Macro.to_string/2
    (elixir) lib/kernel/typespec.ex:769: anonymous fn/5 in Kernel.Typespec.typespec/3
    (stdlib) lists.erl:1238: :lists.map/2
    (elixir) lib/kernel/typespec.ex:748: Kernel.Typespec.typespec/3
```

The [Maps](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Typespecs.md#maps) section is not particularly clear, but what I get from this is that i could use the elipsis for maps as in `%{foo: integer(), ...}`, which results in the same error. Please, correct me if I'm wrong.

**Comment by josevalim** [comment]
@eksperimental if it doesn't work, I would remove it for now. Alternatively we can make `...` be equivalent to `optional(any) => any`. @ericmj thoughts?

**Comment by eksperimental** [comment]
Additionally I would like to know if `%{type1 => type2}` is equivalent to `%{required(type1) => type2}`

**Comment by ericmj** [comment]
`%{...}` and `%{optional(:foo) => bar(), ...}` is supposed to work but it seems like the tests are missing for it. It's not equivalent to `optional(any) => any` in the erlang AST so we need to support it I think.

> Additionally I would like to know if %{type1 => type2} is equivalent to %{required(type1) => type2}

No, the former is not valid syntax.

**Comment by josevalim** [comment]
@ericmj are we sure `...` is supported in Erlang? I couldn't find the docs. In any case, if it is supported, it is only on 19.

**Comment by eksperimental** [comment]
`...` does not appear in the documentation, and `%{type1 => type2}` does

**Comment by ericmj** [comment]
> are we sure ... is supported in Erlang? I couldn't find the docs. In any case, if it is supported, it is only on 19.

`#{...}` was supported in OTP 18 but was dropped when OTP made breaking changes to the typespec syntax and AST for maps in OTP 19. It should now be `#{_ => _}` or `#{any() => any()}`. I guess we can also drop `...` since no one noticed it didn't work until now? I'm not even sure it worked before we updated the map typespec syntax.

> ... does not appear in the documentation, and #{type1 => type2} does

`#{type1 => type2}` is equivalent to `%{optional(type1) => type2}`. `#{type1 := type2}` is equivalent to `%{required(type1) => type2}` or `%{atom: type}`.

We need `optional` and `required` because we don't have two operators for key assignment in match that maps to erlang's `=>` and `:=`. `%{type1 => type2}` is not allowed because it's not clear if the default should be optional or required.

Relevant OTP commits:
https://github.com/erlang/otp/commit/a07a1d465994427d322c523f26dcabefeb14cf01 `#{...}` added.
https://github.com/erlang/otp/commit/af761914c9a94a9d54c1bcc2d4fff96a58674078 `#{...}` removed.

**Comment by eksperimental** [comment]
thanks for all the info.
just one remark `%{type1 => type2}` does compile with no warning.

**Comment by ericmj** [comment]
> just one remark %{type1 => type2} does compile with no warning.

It's only soft-deprecated for now. It's going to warn in the future.

**Comment by eksperimental** [comment]
@ericmj great. good to know.

I have just submited a PR related to this, I can remove `%{..}` and include it to that PR if you guys agree on getting rid of it.

**Comment by ericmj** [comment]
> I have just submited a PR related to this, I can remove %{..} and include it to that PR if you guys agree on getting rid of it.

Thank you. I vote yes for dropping `%{...}` but lets wait for the rest of the core team's input.

**Comment by josevalim** [comment]
Yes, let's drop it and including it in the existing PR. :)
