### ISSUE TITLE
Cannot use pin operator with structs to match a variable key name

### ISSUE THREAD

**Issue by sschneider1207** [elixir-lang/elixir#5378]
### Environment

* Elixir version (elixir -v): 1.3.2
* Operating system: Win10

### Current behavior
```elixir
defmodule MyStruct do
  defstruct a: nil, b: nil
end
```
```
iex(1)> map = %MyStruct{a: 1}
iex(2)> key = :a
iex(3)> %MyStruct{^key => val} = map
** (CompileError) iex:3: unknown key {:^, [line: 3], [{:key, [line: 3], nil}]} for struct MyStruct
iex(4)> %{^key => val} = map
iex(5)> val
1
```

### Expected behavior
Pin operator to work with a struct match similarly to how it does if the struct part of the match is omitted

**Comment by ericmj** [comment]
I wonder if this should be allowed since we are losing the compile time guarantees. You also can't construct structs with dynamic keys: `%Struct{key => value}`.

**Comment by josevalim** [comment]
@ericmj I think the match scenario is less troublesome because the only way it will succeed for an invalid key is the original struct has been "corrupted". However, we could argue that, for consistency with creation, we also shouldn't allow dynamic keys on matching.

It is indeed probably better to stick with structs at compile time only. You can always do `%{^key => ...}`.

**Comment by josevalim** [comment]
Let's wait until others chime to take a final decision.

**Comment by lexmag** [comment]
I think consistency is quite important on this matter, and "structs at compile time only" sounds reasonable.

> You can always do `%{^key => ...}`.

👍

**Comment by josevalim** [comment]
Closing this then.
