### ISSUE TITLE
Who are Elixir programmers?

### ISSUE THREAD

**Issue by lk-geimfari** [elixir-lang/elixir#5485]
Yes, I know that that's off top, but how Elixir-programmers call themselves in the your (and in my, I hope) community?

For example Python programmers are Pythonistas. Thanks!

**Comment by josevalim** [comment]
Elixir developers. If you really need a name, Elixirists.

Also please, please don't use the issues tracker for questions. There are many places where this discussion could happen, such as the elixirforum.com.

PS: I will lock this issue because those discussions tend to side track quickly from the focus of the issues tracker and I want to work this friday. 😅
