### ISSUE TITLE
Garbage output in Elixir 1.4.0 on Windows

### ISSUE THREAD

**Issue by KeeperB5** [elixir-lang/elixir#5615]
OS: Windows 10 64-bit.

This is what Elixir 1.3.4 outputs:
```
Eshell V8.0  (abort with ^G)
Interactive Elixir (1.3.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 1
1
iex(2)> a
** (CompileError) iex:2: undefined function a/0

iex(2)>
```

And this is what Elixir 1.4.0 outputs:
```
Eshell V8.0  (abort with ^G)
Interactive Elixir (1.4.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 1
[33m1[0m
iex(2)> a
[33mwarning: [0mvariable "a" does not exist and is being expanded to "a()", please use parentheses to remove the ambiguity or change the variable name
  iex:2
 
[31m** (CompileError) iex:2: undefined function a/0[0m
[31m    [0m
```

**Comment by KeeperB5** [comment]
I used `IEx.configure []` to disable syntax coloring, got `[33m[36m:ok[0m[33m[0m` back, but the problem persists.

**Comment by KeeperB5** [comment]
After `IEx.configure [colors: [syntax_colors: []]]` the problem still persists. Did I do this correctly? I just picked up Elixir yesterday, so I am not quite sure of even the basics.

**Comment by josevalim** [comment]
What is the result of `IO.ANSI.enabled?`?

**Comment by QuantamHD** [comment]
The value is true.

**Comment by josevalim** [comment]
Ok, that's the issue. :) Does it make a difference if you start `iex` or `iex.bat`?

**Comment by KeeperB5** [comment]
PowerShell: true
Erlang Shell: false
Command Prompt: `[33m[35mtrue[0m[33m[0m`

**Comment by josevalim** [comment]
If you run `set OS` or `set os` in your terminal (outside of the Erlang/Elixir shell), do you see a variable named `OS` (or `os`)? If so, what is its value?

**Comment by QuantamHD** [comment]
In command prompt the value is OS=Windows_NT. In powershell the command is blank

**Comment by josevalim** [comment]
Thank you @KeeperB5 and @QuantamHD.

So just to confirm, the issue happens only on Powershell, where the OS variable is not set. In Powershell, there is also no difference between running `iex.bat` or `iex`.

Finally, one last question. What is the result of running this in Powershell?

    $ test -t 1 -a -t 2
    $ echo $?

Those are Unix commands, you may need small changes to run them on Powershell.

**Comment by QuantamHD** [comment]
The weird character output happens in both Powershell and CMD just to a lesser extend in powershell. The first command is blank, and the second one is true

In powershell for example this happens with the default text encodeing of 437
`[0m
  ΓÇó [36mb/1[0m           - prints callbacks info and docs for a given module
  ΓÇó [36mc/1[0m           - compiles a file into the current directory
  ΓÇó [36mc/2[0m           - compiles a file to the given path
  ΓÇó [36mcd/1[0m          - changes the current directory
  ΓÇó [36mclear/0[0m       - clears the screen
  ΓÇó [36mflush/0[0m       - flushes all messages sent to the shell
  ΓÇó [36mh/0[0m           - prints this help message
  ΓÇó [36mh/1[0m           - prints help for the given module, function or macro
  ΓÇó [36mi/1[0m           - prints information about the data type of any given
    term
  ΓÇó [36mimport_file/1[0m - evaluates the given file in the shell's context
  ΓÇó [36ml/1[0m           - loads the given module's BEAM code
  ΓÇó [36mls/0[0m          - lists the contents of the current directory
  ΓÇó [36mls/1[0m          - lists the contents of the specified directory
  ΓÇó [36mnl/2[0m          - deploys local BEAM code to a list of nodes
  ΓÇó [36mpid/1[0m         - creates a PID from a string
  ΓÇó [36mpid/3[0m         - creates a PID with the 3 integer arguments passed
  ΓÇó [36mpwd/0[0m         - prints the current working directory
  ΓÇó [36mr/1[0m           - recompiles the given module's source file
  ΓÇó [36mrecompile/0[0m   - recompiles the current project
  ΓÇó [36mrespawn/0[0m     - respawns the current shell
  ΓÇó [36ms/1[0m           - prints spec information
  ΓÇó [36mt/1[0m           - prints type information
  ΓÇó [36mv/0[0m           - retrieves the last value from the history
  ΓÇó [36mv/1[0m           - retrieves the nth value from the history`

With utf-8 encodeing this is the output

`                                  IEx.Helpers

Welcome to Interactive Elixir. You are currently seeing the documentation for
the module IEx.Helpers which provides many helpers to make Elixir's shell more
joyful to work with.

This message was triggered by invoking the helper h(), usually referred to as
h/0 (since it expects 0 arguments).

You can use the h/1 function to invoke the documentation for any Elixir module
or function:

    iex> h Enum
    iex> h Enum.map
    iex> h Enum.reverse/1

You can also use the i/1 function to introspect any value you have in the
shell:

    iex> i "hello"

There are many other helpers available:

  • b/1           - prints callbacks info and docs for a given module
  • c/1           - compiles a file into the current directory
  • c/2           - compiles a file to the given path
  • cd/1          - changes the current directory
  • clear/0       - clears the screen
  • flush/0       - flushes all messages sent to the shell
  • h/0           - prints this help message
  • h/1           - prints help for the given module, function or macro
  • i/1           - prints information about the data type of any given
    term
  • import_file/1 - evaluates the given file in the shell's context
  • l/1           - loads the given module's BEAM code
  • ls/0          - lists the contents of the current directory
  • ls/1          - lists the contents of the specified directory
  • nl/2          - deploys local BEAM code to a list of nodes
  • pid/1         - creates a PID from a string
  • pid/3         - creates a PID with the 3 integer arguments passed
  • pwd/0         - prints the current working directory
  • r/1           - recompiles the given module's source file
  • recompile/0   - recompiles the current project
  • respawn/0     - respawns the current shell
  • s/1           - prints spec information
  • t/1           - prints type information
  • v/0           - retrieves the last value from the history
  • v/1           - retrieves the nth value from the history

Help for all of those functions can be consulted directly from the command line
using the h/1 helper itself. Try:

    iex> h(v/0)

To learn more about IEx as a whole, type h(IEx).`

**Comment by KeeperB5** [comment]
No, the issue only happens in Command Prompt. PowerShell works fine.

**Comment by josevalim** [comment]
If you start IEx as `iex --erl "-elixir 'ansi_enabled' false"`. Does the problem disappear for good?

**Comment by KeeperB5** [comment]
`iex --erl "-elixir 'ansi_enabled' false"` appears to fix the problem.

**Comment by josevalim** [comment]
Ok, this has been caused by #4942. I have reverted it.

Can you please locate the "bin/elixir.bat" from your installation and remove the same lines of code removed in commit 414a26627c4aae2f5ab6a25a63352f057e8d910d and let me know if it effectively fixes the problem?

**Comment by KeeperB5** [comment]
Removing those lines does fix the problem as well.

**Comment by bryannaegele** [comment]
@josevalim when you republished the SHA changed on the precompiled zip which the official Docker image is using to build the image. Might it be better in the future to do a version bump rather than republish?

https://github.com/docker-library/official-images/pull/2512
https://github.com/c0b/docker-elixir/pull/21

**Comment by josevalim** [comment]
@bryannaegele I have commented on the docker-elixir issue. This was not the issue that caused the republish but rather the Windows installer one. I have some automation that generates packages and shas for the Windows installer and that ended-up republishing when investigating a bug. I will make sure to add safe guards to avoid doing so in the future.

**Comment by jwfearn** [comment]
Oh dear! I wrote the original #4942 I'm sorry it's no longer working properly. I'll work on a fix an resubmit.
