### ISSUE TITLE
Improve error messages for invalid expression in match

### ISSUE THREAD

**Issue by grych** [elixir-lang/elixir#5649]
### Environment

* Elixir & Erlang versions (elixir -v):
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.4.0
* Operating system:
OS X El Capitan

### Current behavior

```
iex(1)> f = &List.first/1
&List.first/1
iex(3)> case f do
...(3)>   &List.first/1 -> 11
...(3)> end
** (CompileError) iex:4: invalid expression in match
    (stdlib) lists.erl:1354: :lists.mapfoldl/3

```
however the other way works as expected:
```
iex(3)> case &List.first/1 do
...(3)> f -> 22
...(3)> end
22

```

### Expected behavior
As a first-class citizen, function should work in `case` as it works in other pattern matching cases.

```
iex(3)> case f do
...(3)>   &List.first/1 -> 11
...(3)> end
11


```

**Comment by josevalim** [comment]
It is not about being first-class, the issue is that `&List.first/1` is not a valid *pattern*. There are many other data types that are first-class, such as a PID, that are also not valid patterns.

For example, imagine you want to match exactly on the pid `0.10.0`. There is no way you can write such as a pattern. You would first need to build the pid, store it in a variable, and then match on it. That's exactly what you can do with functions:

```elixir
x = &List.first/1
case &List.first/1 do
  ^x -> true
end
```

There are also cases like maps, where patterns and values are different. `%{}` means the empty map as a value but means all maps in a pattern.

I believe there is very little interest in making functions valid patterns in Elixir. So I would recommend going the route of `^x`.

**Comment by grych** [comment]
I see. Actually I found this when I tried to use such syntax, but I agree the case is very rare. Maybe  I did not understand what `invalid expression in match` means.

Thanks for explanation!

**Comment by josevalim** [comment]
Ok, I will reopen this because we can definitely use a better error message. Plus using the term "expression" in there is not quite correct.
