### ISSUE TITLE
Linter friendly compilation

### ISSUE THREAD

**Issue by tsubery** [elixir-lang/elixir#5651]
Hi,

I want to make elixir compiler more useful for linting. There are couple of things that make it cumbersome. The first is inconsistent error output. For example:
```
warning: variable "var" is unused
  lib/project/file.ex:123
```
is quite different from 
```
** (CompileError) web/controllers/error_controller.ex:27: undefined function user/0
...
```
It makes sense to me to have a uniform output. If we want to have different human readable output and machine readable one we could have a flag to control the output format.

The other issue is the actual binary output create race condition with live reloading mechanisms like the one used by phoenix.
The solution I thought of is to add a ```--dry-run``` flag that skips the binary/manifest output. This will enable capturing all the errors without any conflict.

What do you thing?

**Comment by josevalim** [comment]
Because Elixir compiles code by executing code, compilation errors are regular exceptions and therefore I am not sure we could unify the warning format with the exceptions one.

About `--dry-run`, I believe that's probably OK but it is quite a large change, because it is about all compilers, and I am not quite sure it would work with custom compilers, such as Phoenix's or Gettext's. If you explore this option and achieve positive results, then it is likely we could consider a PR.

Btw, it is best to send feature proposals to the elixir-lang-core mailing list. Thank you!
