### ISSUE TITLE
Send test fails to stderr instead of stdout

### ISSUE THREAD

**Issue by Eiji7** [elixir-lang/elixir#5726]
Tests fails are errors, so output of them should be returned to stderr.
Example command:
```
make clean test > stdout.log 2> stderr.log
```

### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10]
```
any Elixir version (checked also master branch)
* Operating system:
Funtoo Linux (Gentoo based) Intel64-nehalem funtoo-stable standard from stage 1
Note: I installed erlang package from official distribution repository and I don't have installed Elixir (I just compile from git).

### Current behavior

1. stderr.log:
* deprecation warnings (good)
* undefined warnings (good)
* make error message (good)
2. stdout.log:
* compilation messages (good)
* make messages (like: commands executed, entering directory, targets - good)
* tests messages (good)
* **tests fails (for example test fail described at: #5664 - bad)**

### Expected behavior

1. stderr.log:
* deprecation warnings
* undefined warnings
* make error message
* **tests fails (for example test fail described at: #5664)**
2. stdout.log:
* compilation messages
* make messages (like: commands executed, entering directory, targets)
* tests messages

**Comment by josevalim** [comment]
In previous attempts to implement this we would get garbled messages because the test progress and the test failures would be sent to two different processes (stdin and stdout) and then there is no guarantee on the ordering. In very drastic scenarios, we could have something saying "Finished in 0.123 seconds" and the test failure printed only after. One obvious solution would be serialize everything through a single process but the simplicity of the current approach works best. You can always resort to custom formatters if you want output to be logged on different devices or different formats.
