### ISSUE TITLE
Warn if manager dependencies diverge

### ISSUE THREAD

**Issue by Gazler** [elixir-lang/elixir#5830]
### Environment

* Operating system: Linux and Mac OS

### Current behavior

Compilation fails with: `** (EXIT) {:error, {:error, {:open_error, -10}}}`

### Steps to reproduce:

1. git clone git@github.com:VoiceLayer/dispatch.git
2. cd dispatch
3. mix deps.get
4. mix test

Oneline version:

    git clone git@github.com:VoiceLayer/dispatch.git && cd dispatch && mix deps.get && mix test

A full error log is available at https://gist.github.com/Gazler/6ff814f03e6e8970f78b3ccc09725009

This uses the https://github.com/VoiceLayer/hash-ring library which is implemented as a port driver.

**Comment by Gazler** [comment]
Just ran a bisect (10 steps!) and it was this commit. 9fe897f39dd4306debf7fb6cae62f47a17d4ecf0

It is worth noting that if you are trying this yourself, the `deps` directory should be removed each time.

**Comment by Gazler** [comment]
Just ran a bisect (10 steps!) and it was this commit. 17557aa39

It is worth noting that if you are trying this yourself, the deps directory should be removed each time.

**Comment by whatyouhide** [comment]
Without having investigated this at all, have you tried with `manager: :rebar` in the list of deps?

**Comment by Gazler** [comment]
@whatyouhide You are fast. I was in the middle of trying that! It does fix the issue.

**Comment by ericmj** [comment]
This is technically a breaking change in 1.4 but we made the change because not changing it would cause more breakage.

More projects use rebar3 than rebar2 today (thank goodness) and the experience is bad for new developers if they add a rebar3 dependency that doesn't work. They need to learn or ask to know that they should add `manager: :rebar3` the dep config. The experience is just as bad in the reverse but it should be less common.

Unfortunately there is no way for us to know if compilation broke because of a rebar2/rebar3 mismatch. There is no indication in a rebar project if it uses rebar2 or rebar3 :(, we add this metadata to Hex, but that information is not available for git dependencies.

**Comment by josevalim** [comment]
@ericmj shouldn't we have a mechanism then for package owners to set the manager for rebar in those cases?

**Comment by ericmj** [comment]
@josevalim You can set that with `:build_tools` option in package config https://hex.pm/docs/tasks#hex_publish.

**Comment by josevalim** [comment]
Ok. @Gazler i would recommend updating it to rebar3 OR set the build_tools option.

**Comment by Gazler** [comment]
One thing I noticed when attempting to use the fix suggested by @whatyouhide in my main application, is that using a different manager for two different apps in an umbrella doesn't cause a conflict with the dependency.

In my case it happened to use rebar3 because I only set `manager: :rebar` on one of the two apps in my umbrella application using the hash_ring dependency.

**Comment by ericmj** [comment]
@Gazler Were both umbrellas at the same level, i.e. none of them depended on the other? The :manager option is silently overridden without adding an explicit :override flag.

**Comment by Gazler** [comment]
@ericmj Both were at the same level.

**Comment by ericmj** [comment]
We should try to error if the dependency definitions diverge on the same level.
