### ISSUE TITLE
ExUnit setup callback: error message inconsistent

### ISSUE THREAD

**Issue by nhjk** [elixir-lang/elixir#5898]
### Environment

* Elixir & Erlang versions (elixir --version):
1.4.0
* Operating system:
macOS Sierra

### Current behavior

The ExUnit setup callback expects a return type of `:ok | keyword | map`, so when you do
```setup do: {:foo, ":)"}```
it errors with
```(RuntimeError) expected ExUnit callback in Director.Web.AuthControllerTest to return :ok | keyword | map, got {:foo, ":)"} instead```

However, when the first element in the tuple is `:ok` it doesn't print out the full tuple.
```setup do: {:ok, ":)"}```
errors with
```(RuntimeError) expected ExUnit callback in Director.Web.AuthControllerTest to return :ok | keyword | map, got ":)" instead```

### Expected behavior

```setup do: {:ok, ":)"}```
error
```(RuntimeError) expected ExUnit callback in Director.Web.AuthControllerTest to return :ok | keyword | map, got {:ok, ":)"} instead```

**Comment by jeffkreeftmeijer** [comment]
This seems to be a regression introduced in 58377cde, caused by `ExUnit.Callbacks__merge__/3` being recursive now, which drops the `:ok` from the input value before `raise_merge_failed!/2` is called.

We could fix this by adding a new argument to `__merge__/3`, which holds the value passed originally (`{:ok, ":)"}` in this case), so we can use it to pass to `raise_merge_failed!/2` if the value turns out to be invalid. I’m not sure if that’s the nicest solution though. Any thoughts on this? :)

**Comment by josevalim** [comment]
@jeffkreeftmeijer that sounds like the way to go, yes. :)
