### ISSUE TITLE
Mix.Tasks.Test ignores --exclude option

### ISSUE THREAD

**Issue by wbednarski** [elixir-lang/elixir#5951]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 18 [erts-7.3.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.4
```
* Operating system: 
```
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E192b
```

### Current behavior
```
defmodule SomeModuleTest do
  @tag internal: true
  (more code here)
  for order_json <- File.stream!(@all_orders_json, [], :line), Tools.filter_by_vendor(order_json) do
    (more code here)
    test ""
      (more code here)
    end
  end
end
```

`mix test --exclude internal` runs all tests including excluded tests

### Expected behavior
`mix test --exclude internal` should run all tests expected tagged by `internal`

**Comment by michalmuskala** [comment]
`@tag` definitions apply only to the next `test` definition - in this case, it would apply only to the first pass of the loop. You should either move the tag inside the loop, or use moduletag or describetag.

**Comment by wbednarski** [comment]
Hi, Michal! What a small world™

I've tried that as well, and it doesn't work, the only difference is when I run code from the snippet ^
```
8683 tests, 1661 failures, 1 skipped
```

When I move `@tag` above the test:
```
defmodule SomeModuleTest do
  (more code here)
  for order_json <- File.stream!(@all_orders_json, [], :line), Tools.filter_by_vendor(order_json) do
    (more code here)
   @tag internal: true
    test ""
      (more code here)
    end
  end
end
```

I got `8683 tests, 1 failure, 8424 skipped`

So tests are skipped but not excluded. They still run. I even had to increase `case_load_timeout` :- )

**Comment by michalmuskala** [comment]
It seems like it works as expected. You still need to compile the modules to read the tags (and I assume that's the problem if you're complaining about high load times).

The problem with defining tests like this is that all the iterations of the loop are compiled separately, which creates a lot of work for the compiler - that's why it's slow. Extracting some parts from inside test, into common, shared functions should speed things up significantly.

Alternatively, you could put things in separate paths and manipulate the [`test_path` mix option](https://hexdocs.pm/mix/Mix.Tasks.Test.html#module-configuration) based on some env variables to skip loading and compiling certain test cases altogether.

**Comment by wbednarski** [comment]
> Alternatively, you could put things in separate paths and manipulate the test_path mix option based on some env variables to skip loading and compiling certain test cases altogether.

Thanks, this is kind of what I did as a workaround. However, the best solution would be `@tag` per module as well as per test.

**Comment by josevalim** [comment]
> However, the best solution would be @tag per module as well as per test.

This still wouldn't change the fact the module needs to be loaded for us to check the tag and this wouldn't solve it. One option is to avoid loading the file depending on the value of `ExUnit.configuration[:exclude]`.
