### ISSUE TITLE
Mix tasks do not use config.exs settings for Logger

### ISSUE THREAD

**Issue by brainlid** [elixir-lang/elixir#6016]
### Environment

* Elixir: 1.4.2
* Erlang/OTP 19 [erts-8.3]
* Operating system: Arch Linux, 64-bit

### Current behavior

In the mix project's `config/config.exs` file, configuring the log formatting and configuration works correctly at run time, but are not respected when running mix tasks. This is particularly a problem with `mix ecto.migrate` as it is not a custom mix task.

See "Steps to reproduce" below.

### Expected behavior

The logging configuration for the project should be respected at all times when the project is run. Makes consuming application log files difficult as they are inconsistent and not following the pattern we want. 

### Steps to reproduce

* create a new mix project `mix new log_test`
* edit the `config/config.exs` file and add logging config like following
```elixir
config :logger, :console,
  format: "$date $time level=$level $metadata msg=$message\n",
  metadata: [:request_id, :application, :module, :ip, :endpoint, :uid, :oid, :type]
```
* verify it works as expected... run `iex -S mix`
```elixir
iex(1)> require Logger      
Logger
iex(2)> Logger.info("Hello")
2017-04-19 13:46:49.659 level=info module=  msg=Hello
:ok
```
* create mix task in `lib/sample_task.ex`
```elixir
defmodule Mix.Tasks.SampleTask do
  use Mix.Task
  require Logger

  @shortdoc "Description of sample_task. Logs stuff."

  def run(_) do
    Logger.info("Running sample_task...")
    Logger.info("Pretend work is happening.")
    Logger.info("Almost done...")
    Logger.info("Completed running sample_task.")
  end
end
```
* compile and run the mix task `mix do compile, sample_task`
```bash

13:56:46.991 [info]  Running sample_task...

13:56:46.991 [info]  Pretend work is happening.

13:56:46.991 [info]  Almost done...

13:56:46.991 [info]  Completed running sample_task.
```

The logging configuration is not respected. This is the same for `mix ecto.migrate`. This makes it difficult to get consistent logs out of the system.

**Comment by josevalim** [comment]
Thank you.

Because your application has not been started yet, the logger configuration won't take any effect. I am not sure what we should do here. If we restart the logger after loading the configuration, then we will be restarting it multiple times and increase the time for running Mix tasks.

On the other hand, we don't want to boot the app while we migrate. Maybe ecto.migrate itself could restart the logger but not the app.

For your own task, you can simply run Mix.Task.run "app.start".

**Comment by brainlid** [comment]
The tip to `Mix.Task.run "app.start"` works well for custom tasks. I would appreciate any solutions that could help with the migrations. Thanks for looking at this.

**Comment by josevalim** [comment]
Glad to hear! Can you please open up this issue in the Ecto repo then?

**Comment by spencerdcarlson** [comment]
Are there any thoughts on how to improve this?

**Comment by spencerdcarlson** [comment]
Are there any thoughts on how to improve this -- especially for in the case of umbrella apps?

The problem as I see it, is that `Mix.Task.run "app.start"` tries to start every application, even if it is already started, or doesn't need to be started.

A common workaround, which I feel like is overly complicated, to completely start the _correct_ supervision tree and execute some code has been to use a persistent environment variable and then pattern match in the `application.ex` file to ensure you only start (and don't try and start something that is already started) the children that are required for the given mix task. 

Here is a condensed example:

```elixir
# in custom_mix_task.ex file
@impl Mix.Task
def run(_) do
   Application.put_env(:my_app, :process_type, :custom_mix_task, persistent: true)
   Mix.Task.run("app.start")
end

# in :my_app application.ex file
def start(_type, _args) do
  process_type = Application.get_env(:my_app, :process_type)
  {:ok, _} =
      process_type
      |> children(Mix.env())
      |> Supervisor.start_link(strategy: :one_for_one, name: MyApp.Supervisor)
end

defp children(:custom_mix_task, _), do: [Database.Repo]
defp children(_, _), do: [ ]
```

Is the a current pattern that could be better to follow, or any thoughts on improving this?

Is it possible to augment `Application.ensure_all_started/1` to follow the same startup process as `Mix.Task.run("app.start")` so that in a mix task we could simply call `Application.ensure_all_started(:my_app)` and have the configs and Logger running correctly?
