### ISSUE TITLE
Introduce non-ambiguous alternatives to Enum.find/Enum.find_index/Enum.find_value

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6164]
Today `Enum.find/2` is ambiguous because it is impossible to retrieve a `nil` value from it. The alternative is to pass a fake a value as a default and make a distinction on that.

However, a much simpler solution would be for `Enum.find/2` to return `{:ok, tuple} | :error` and allow others to map on the result.

Similarly, `Enum.find_value/3` suffers from this ambiguity twice, because it is impossible to find a value that returns `nil` from the inner function.

Both `Enum.find` and `Enum.find_value` could be replaced by a single function, called `Enum.search/2` with this signature:

    Enum.search(Enumerable.t, (element -> {:ok, any} | :error)) :: {:ok, any} | :error

One downside of search is that it is more verbose in cases where the value can never be nil. Here is an actual example from Elixir's source:

```elixir
    find = fn %Task{ref: task_ref} -> task_ref == ref end
    if Enum.find(tasks, find) do
      exit({reason(reason, proc), {__MODULE__, :find, [tasks, msg]}})
    end
```

It would have to be rewritten as:

```elixir
    search = fn %Task{ref: ^ref} = task -> {:ok, task}; _ -> :error end
    case Enum.search(tasks, search) do
      {:ok, _} -> exit({reason(reason, proc), {__MODULE__, :find, [tasks, msg]}})
      :error -> :ok
    end
```

I personally find the former clearer. My suggestions are:

  1. Introduce `Enum.search` and deprecate `Enum.find_value`
  2. Keep Enum.find (still handy for non-nil values - similar to at/fetch) and Enum.find_index (notice there are no issues with find_index)

Overall we are removing one function and adding a new function that is much clearer.

And if we are introducing tuple centric functions to Enum, I would also suggest the addition of `Enum.filter_map(Enumerable.t, (element -> {:ok, value} | :error))` (note the old filter_map/3 has already been deprecated in master).

I am copying @seancribbs because I believe he proposed a similar feature to Erlang a long time ago and he may have feedback from that discussion.

**Comment by michalmuskala** [comment]
I have to admit, I'm not a fan of the proposed `Enum.filter_map` function. It's going to be extremely surprising that if works completely differently from either `filter` or `map`.

Especially, because the same can be already achieved with:
```elixir
Enum.flat_map(Enumerable.t, (element -> [value] | []))
```

**Comment by whatyouhide** [comment]
I am a big fan of the proposed `filter_map`. Many times I used `flat_map` for that and I do not believe `flat_map` shows intent clearly or is built to do that. I also love what `Enum.search/2` does and how it behaves personally (the name, I'm not quite sure yet but that's for another time).

**Comment by josevalim** [comment]
By the way, the `filter_map` name came from Rust, which has a function with exactly the same functionality. And I agree with @whatyouhide, `filter_map` is much clearer in intent than `flat_map`.

Also, let's please hear better alternatives for `Enum.search/2`, because if there is a time to discuss names, it would be now. :)

**Comment by ericmj** [comment]
I don't think there is a strong enough reason to deprecate `find_value` compared to the pains of a dealing with a deprecated function. If we are completely replacing the function I would agree but in this case we are introducing one with overlapping functionality.

`fetch` would work as name instead of `search`. It has a similar signature to our other existing `fetch` functions and we could introduce `fetch!` if we would like to later.

I agree with @michalmuskala that unless we come up with a better name than `filter_map` it's better to keep using `flat_map`. For me I think filtering when I see `flat_map` and if I saw `filter_map` I would think it worked like the deprecated `filter_map/3`.

**Comment by josevalim** [comment]
@ericmj I would say the current implementation of find_value is ultimately broken and leading people to a better alternative will help them avoid bugs in their codebase.

I like the suggestion of using `fetch` instead of `search`. The signature is the same... but do we want to overload it? And does it mean we should support `at(..., fun, default)` as well? Because the last one doesn't quite work.

> I agree with @michalmuskala that unless we come up with a better name than filter_map it's better to keep using flat_map.

That's exactly why the previous one was deprecated, so we can rewire what `filter_map` means. :)

**Comment by whatyouhide** [comment]
> For me I think filtering when I see flat_map

But that's not really what `flat_map` is *for*, it's what most of us use it for most of the time (I would guess? for me at least) exactly because there's not a proper "filter map" function.

> I don't think there is a strong enough reason to deprecate find_value compared to the pains of a dealing with a deprecated function.

I agree that there's a pain in deprecation but in the long run the pain in a too extended and flawed API might be more.

**Comment by ericmj** [comment]
> And does it mean we should support at(..., fun, default) as well? Because the last one doesn't quite work.

What would `at` do and why do we need it?

> But that's not really what flat_map is for, it's what most of us use it for most of the time (I would guess? for me at least) exactly because there's not a proper "filter map" function.

It's a common pattern in functional programming so I don't agree that it's not what it's used for. Having a `filter_map` function that doesn't work like `filter` nor `map` is confusing though. If we can find another name that doesn't reuse names associated with other behaviour I would be fine with it.

> I agree that there's a pain in deprecation but in the long run the pain in a too extended and flawed API might be more.

That's always the other side of the argument. `find_value` is not ideal but there are workarounds for all of its flaws and the flaws we are discussing are a small edge case.

**Comment by josevalim** [comment]
> Having a filter_map function that doesn't work like filter nor map is confusing though.

It does filter and map though. :P In any case, if we can come up with a better name, then by all means let's use it. By I do think `filter_map` encapsulates what it does quite well.

> That's always the other side of the argument. find_value is not ideal but there are workarounds for all of its flaws and the flaws we are discussing are a small edge case.

Besides the workaround being horrible, the issue is not realizing that you need the workaround in the first place. Imagine you have a list of expressions and you want to return the first that returns an atom. You may try:

    value =
      Enum.find_value(exprs, fn expr ->
        {val, _} = Code.eval_string(expr, [])
        if is_atom(val) do
          val
        end
      end)

And then just later you notice there is a bug. If the expression evaluates to nil, which is an atom, it won't be returned. To fix it, you need to implement a poor `search/fetch`:

    value =
      Enum.find_value(exprs, :error, fn expr ->
        {val, _} = Code.eval_string(expr, [])
        if is_atom(val) do
          {:ok, val}
        end
      end)

    case value do
      {:ok, value} -> value
      :error -> nil
    end

The implicit return of nil and use of `:error` as a default are there only to make it cope with find_value API.

@ericmj is there any place you use find_value that you personally think it would be worse with the new API?

**Comment by michalmuskala** [comment]
I would actually argue, this will make the code using `find_value` much more convoluted. Let's look at some examples and replacements.

In Phoenix [here](https://github.com/phoenixframework/phoenix/blob/c3351478748779fe0b777a4f41e7ace7ae5e2452/lib/mix/phoenix.ex#L15-L17) we would change from:
```elixir
Enum.find_value(sources, fn source ->
  File.exists?(source) && File.read!(source)
end) || raise "could not find #{source_file_path} in any of the sources"
```
to
```elixir
res = 
  Enum.seach(sources, fn source ->
    if File.exists?(source) do
      {:ok, File.read!(source)}
    else
      :error
    end
  end) 
case res do
  :error -> raise "could not find #{source_file_path} in any of the sources"
  _ -> :ok
end
```

Another similar use case is present just couple lines lower in the same file. I also found a couple more uses with an `||` after it in Phoenix, but those could be arguably replaced by passing the default value. It's not possible in case we wanted to raise, though. 

Another [use that would require more convolution](https://github.com/mschae/cors_plug/blob/e64918d28ca0abae65d75d33edb6966ba9970f90/lib/cors_plug.ex#L100) would require changing from:
```elixir
Enum.find_value(headers, fn({k, v}) -> k =~ ~r/^origin$/i && v end)
```
to
```elixir
Enum.search(headers, fn({k, v}) -> if k =~ ~r/^origin$/i, do: {:ok, v}, else: :error end end)
```
with additional modification of the consumer, from a simple `if` to a `case` match on the ok tuple.

Last [use I found](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/multi.ex#L399-L406) after a brief grep of deps of my app is in ecto (and that one I wrote myself). It would require changing:

```elixir
defp check_operations_valid(operations) do
  Enum.find_value(operations, &invalid_operation/1) || {:ok, operations}
end

defp invalid_operation({name, {:changeset, %{valid?: false} = changeset, _}}),
  do: {:error, {name, changeset, %{}}}
defp invalid_operation(_operation),
  do: nil
```
to
```elixir
defp check_operations_valid(operations) do
  case Enum.search(operations, &invalid_operation/1) do
    :error -> {:ok, operations}
    {:ok, invalid} -> {:error, invalid}
  end
end

defp invalid_operation({name, {:changeset, %{valid?: false} = changeset, _}}),
  do: {:ok, {name, changeset, %{}}}
defp invalid_operation(_operation),
  do: :error
```

While it does not introduce more code, it's much harder to understand, since we're looking for an error, but have to return it tagged in an `ok` tuple, just to switch tags at the end.

**Comment by josevalim** [comment]
Alright, I think we have enough evidence that the new mechanisms are not good enough. :) Thanks everyone.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by seancribbs** [comment]
Not that it is relevant any longer, but my rejected PR adding `lists:find/2,3`: https://github.com/erlang/otp/pull/102
