### ISSUE TITLE
elixir-lang.org blocked in Russia

### ISSUE THREAD

**Issue by yaBliznyk** [elixir-lang/elixir#6172]
Blocking date:
May 10, 2016
Status URL:
In registry
Domain:
k-shkaf.ru
IP:
104.24.104.149 | 104.24.105.149 | 104.28.10.110 | 104.28.11.110

ip elixir-lang.org
104.28.10.110

**Comment by yaBliznyk** [comment]
blocked by IP

**Comment by josevalim** [comment]
We are using Cloudfare and it seems some of their IPs are blocked in Russia. Does anyone know of a free service alternative we could use to provide SSL to elixir-lang.org?

**Comment by esdrasedu** [comment]
I use https://letsencrypt.org/, it is free and good!

**Comment by josevalim** [comment]
Any idea if it integrates with Github pages and custom domains?

**Comment by maennchen** [comment]
Unfortunately, no. See isaacs/github#156

**Comment by OvermindDL1** [comment]
> Any idea if it integrates with Github pages and custom domains?

If you just need basic file hosting with SSL then I'd be happy to supply hosting on one of my servers, the least I could do with how useful Elixir has been.  :-)

**Comment by ericmj** [comment]
Currently we are using Cloudflare which seems to be blocked in some places, previously we were indirectly using Fastly which is also hard to reach from parts of the internet. Whatever we use someone is going to have problems reaching the website. Unfortunately this is the reality of the internet and there isn't much we can do from our end. 

https://elixir-lang.org is a pretty static website so if anyone wants to mirror it they are of course free to do so and please make the URL public for other people if you do.

**Comment by OvermindDL1** [comment]
> Currently we are using Cloudflare which seems to be blocked in some places, previously we were indirectly using Fastly which is also hard to reach from parts of the internet. Whatever we use someone is going to have problems reaching the website. Unfortunately this is the reality of the internet and there isn't much we can do from our end.

Yeah both Cloudflare and Fastly have major issues, they are definitely not recommended with anything that should be accessible everywhere.

> https://elixir-lang.org is a pretty static website so if anyone wants to mirror it they are of course free to do so and please make the URL public for other people if you do.

Sure, I setup a container, setup SSL on it, now up at https://elixir-lang.overminddl1.com/ however I'm having issues with the git repo of https://github.com/elixir-lang/elixir-lang.github.com where it does not seem to have the usual github-pages 'site' or so branch that has the output files that are actually hosted (or where else can I clone the output files?).  I do not have ruby on this file host so compiling on git-clone is not available.  I guess I could git clone it and compile it locally then rsync it over (or I can give you the key to be able to do so yourself if you have a CI that auto-builds and updates the website for you so I would not need to pull it on occasion, which would be vastly nicer).

For now I set up a cron on my local computer to git pull, jekyll build, rsync it over a few times a day, so I guess that will work.  :-)

Is there an actual API that you expose for setting up and keeping mirrors in sync?

Mine 'should' load faster as well, initial tests confirm that (including taking into account the distance, Cloudflare has never been terribly fast on any tests I've done at any location).

The URL is public as seen above, is there any place that you would like me to post it at?  Just the forums or so, or anywhere else?

**Comment by ericmj** [comment]
> Yeah both Cloudflare and Fastly have major issues, they are definitely not recommended with anything that should be accessible everywhere.

We need to pick something that is big enough that we can rely and has free SSL. There's unfortunately not much to chose from.

> Sure, I setup a container, setup SSL on it, now up at https://elixir-lang.overminddl1.com/ however I'm having issues with the git repo of https://github.com/elixir-lang/elixir-lang.github.com where it does not seem to have the usual github-pages 'site' or so branch that has the output files that are actually hosted (or where else can I clone the output files?).

Thank you! I don't know how github-pages work, I had just a simple HTTP mirror in mind which should be fine since we are only looking to have the site available on a different IP. But if something else works better for you please go ahead with that of course.

> The URL is public as seen above, is there any place that you would like me to post it at? Just the forums or so, or anywhere else?

I don't know a good place to post it. For now I think this place is fine since this is probably where people will end up when they search for the issue.

**Comment by OvermindDL1** [comment]
> We need to pick something that is big enough that we can rely and has free SSL. There's unfortunately not much to chose from.

If you can afford a few dollars a month I know a few good hosts that I'd like referrer links for.  ^.^
Otherwise I'm fine with hosting it myself, this is stuff I've been doing for 15+ years now.  :-)

> Thank you! I don't know how github-pages work, I had just a simple HTTP mirror in mind which should be fine since we are only looking to have the site available on a different IP. But if something else works better for you please go ahead with that of course.

Github Pages is a bit, odd.  Generally for a given github-pages repo the 'master' branch hosts the compiled site and the 'source' branch hosts the source is most traditional, but there are a few ways.  Overall the output is always in git so it can be hosted by github's servers, but I was not finding that on Elixir's, I'm at a loss as to how you are hosting it currently through github-pages (which honestly I'd say it should just be dropped anyway).  ^.^;

> I don't know a good place to post it. For now I think this place is fine since this is probably where people will end up when they search for the issue.

Perfect, works for me.  If my cron ever stops or something and I get too out of sync, just yell at me and I'll fix it.  If, however you generate the site now is pluggable, then I can give you an SSH key to push the output to this mirror as well so it can always be as up-to-date as the main site is too without me needing to poll it a few times a day.  :-)

**Comment by josevalim** [comment]
If it is a matter of making a mirror available, maybe we should allow folks to access it directly via elixir-lang.github.io as well and ensure that also uses HTTPS?

**Comment by OvermindDL1** [comment]
> If it is a matter of making a mirror available, maybe we should allow folks to access it directly via elixir-lang.github.io as well and ensure that also uses HTTPS?

That would be great as well as a default!  Github Pages does allow direct https to work without issues.  There are a few places where github is blocked too but I'd imagine they have larger issues at that point.  ^.^;

**Comment by KernelMadness** [comment]
@josevalim it would be great if we have a mirror, Elixir Russian community is suffering from cloudflare ip ban :(

**Comment by OvermindDL1** [comment]
@KernelMadness Multiple mirrors are being set up, all linked at:  https://elixirforum.com/t/elixir-lang-org-mirrors/5618/
:-)
