### ISSUE TITLE
Dependency checking ignores except/only 

### ISSUE THREAD

**Issue by pragdave** [elixir-lang/elixir#6345]
~~~ elixir
  def deps do
   [
    { :pollution, [ path: "../pollution", only:   [ :dev, :test ] ] },
    { :pollution, "~> 0.9.1",             except: [ :dev, :test ] },
    { :ex_doc,    ">= 0.0.0",             only:   [ :dev, :test ] },
  ]
  end
~~~

Then run mix:

~~~
warning: the dependency :pollution is duplicated at the top level, please remove one of them                                                         
Dependencies have diverged:
* pollution (../pollution)
  different specs were given for the pollution app:

  > In mix.exs:
    {:pollution, [env: :prod, path: "../pollution", only: [:dev, :test], manager: :mix]}                                                             

  > In mix.exs:
    {:pollution, "~> 0.9.1", [env: :prod, repo: "hexpm", hex: "pollution",  except: [:dev, :test], override: true]}                                   

  Ensure they match or specify one of the above in your deps and set "override: true"                                                                
** (Mix) Can't continue due to errors on dependencies
~~~

### Environment

~~~
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-thr
eads:10] [hipe] [kernel-poll:false] [dtrace]                              

Elixir 1.6.0-dev (6bacc8f05)
~~~

(also happens in previous versions...)

* Operating system:  OS X

**Comment by josevalim** [comment]
Mix doesn't support duplicate dependencies because, even if we filter them
when starting your app, there are many commands that work across all
environments in order to provide a nice development experience, such as
"mix deps.get" and "mix clean". Nobody wants to run "mix deps.get" per
environment and there would be a lot of complexity if we try to make the
dependency resolver work with duplicates.

If you want mixed dependencies, you can use "Mix.env" to build different
sets of deps. That's the code we were used to generate in early Elixir
days, and we stopped exactly for the reasons above. But if you need it:

    deps(Mix.env)

And then match accordingly when defining your types.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Here is another approach:

```elixir
  def deps do
   [
    {:pollution, "~> 0.9.1", opts_for_pollution(Mix.env)},
    {:ex_doc,    ">= 0.0.0", only:   [ :dev, :test ]},
   ]
  end

  defp opts_for_pollution(env) when env in [:dev, :test], do: [path: "../pollution"]
  defp opts_for_pollution(_), do: []
```

**Comment by josevalim** [comment]
Closing this as won't fix. Thanks for the report @pragdave!
