### ISSUE TITLE
Add start_supervised! to ExUnit

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6379]
This may allow us to have better error reports than this:

```
     ** (MatchError) no match of right hand side value: {:error, {{:EXIT, {%KeyError{key: :name, term: []}, [{Keyword, :fetch!, 2, [file: 'lib/keyword.ex', line: 371]}, {KV.Registry, :start_link, 1, [file: 'lib/kv/registry.ex', line: 13]}, {:supervisor, :do_start_child, 2, [file: 'supervisor.erl', line: 365]}, {:supervisor, :handle_start_child, 2, [file: 'supervisor.erl', line: 724]}, {:supervisor, :handle_call, 3, [file: 'supervisor.erl', line: 422]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 615]}, {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 647]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}, {:child, :undefined, KV.Registry, {KV.Registry, :start_link, [[]]}, :permanent, 5000, :worker, [KV.Registry]}}}
```

**Comment by maisonbleu** [comment]
I just did upgrade to Elixir 1.5 and to get used to it I tried to my source of the guide on elixir-lang.org. For hours I did wonder why the test as written on the homepage don't run. So if I understand this right, the guide says to use `start_supervised` ([Supervisor and Application](https://elixir-lang.org/getting-started/mix-otp/supervisor-and-application.html)) for the test but it actually isn't implemented? If so one might make a note on the guide so people like me don't try to find out what is going wrong for hours :-). Any temporary workarounds? Or am I missing something here?

Best wishes,
Patrick

**Comment by josevalim** [comment]
Yes, the goal of this PR is to improve that. The error you are getting is that the registry expects a `:name` option and you are not passing it. Try this out instead:

```elixir
  setup context do
     {:ok, registry} = start_supervised({KV.Registry, name: context.text})
     %{registry: registry}
  end
```

**Comment by maisonbleu** [comment]
Thank you very much for your help, but what I was getting at is that the changes to the tests in the Elixir guide seem wrong. I am just a newbee in Elixir and my source from the guide was adapted to Elixir 1.5 so maybe the mistakes are on my side, but in the guide the setup call is

```
  setup do
     {:ok, registry} = start_supervised(KV.Registry)
     %{registry: registry}
  end
```

in `kv/registry_test.exs` and at the same time uses opts to pass a name to the GenServer

```
  def start_link(opts) do
    # 1. Pass the name to GenServer's init
    server = Keyword.fetch!(opts, :name)
    GenServer.start_link(__MODULE__, server, opts)
  end
```

which leads to the error in question. To make it work, I changed the setup call in `kv/registry_test.exs` to (because in the tutorial the pid of the start_supervised call is passed as registry name which fails of course)

```
  setup context do
    {:ok, _} = start_supervised({KV.Registry, name: context.test})
    %{registry: context.test}
  end
```

The second thing is that the creation of the bogus bucket, `KV.Registry.create(registry, "bogus")` after `assert_receive {:DOWN, ^ref, _, _, _}` in the Elixir 1.5 guide was removed, which leads to another error in the tests as the the bucket still exists for the lookup.


Best wishes,
Patrick

**Comment by josevalim** [comment]
We talk about the setup+registry changes here: https://github.com/elixir-lang/elixir-lang.github.com/blame/master/getting-started/mix-otp/ets.markdown#L131. Or is it missing somewhere else?

About the :DOWN issue, Agent.stop is synchronous, so it should not be a problem.

**Comment by maisonbleu** [comment]
The test in the guide uses Process.exit instead of Agent.stop, waits for the down message and immediately does the lookup afterwards which fails. There should be a call to create a bogus bucket (which was there in the guide for Elixir 1.4). 

Anyways, thank you very much and for pointing me to the setup+registry changes document as well, I'll take a look there!

**Comment by josevalim** [comment]
> The test in the guide uses Process.exit instead of Agent.stop, waits for the down message and immediately does the lookup afterwards which fails. 

It is also there in the new guide: https://github.com/elixir-lang/elixir-lang.github.com/blame/master/getting-started/mix-otp/ets.markdown#L245-L250

**Comment by kelvinst** [comment]
This is the next one I plan to tackle, anyone else interested or already doing it?

**Comment by josevalim** [comment]
No, please go ahead!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
