### ISSUE TITLE
binread and lines

### ISSUE THREAD

**Issue by pragdave** [elixir-lang/elixir#6424]
I wonder if it is correct for `IO.binread/2` to have the option `line_or_chars`.

Is the idea of lines meaningful when reading in binary?

**Comment by josevalim** [comment]
Partially yes. Because you can consider binread as reading the contents of a file where you do not care about the encoding. As long as the encoding uses \n as the line separator - which are most of them - it is still meaningful.

It can also be used as an optimization. If the file is certainly in UTF-8, you may avoid checking the contents of the file when reading, so you open it in binary and read until the next line.

**Comment by pragdave** [comment]
Is this an Erlang thing, or would if be possible to make it more general
then

~~~ elixir
   binread(pid, «count»)
   binread(pid, until: «8 bit value»)
   binread(pid, :line)    == binread(pid, until: ?\n)
~~~

**Comment by josevalim** [comment]
@pragdave it is part of the IO protocol that ships with Erlang. The protocol does support a `get_until` message, which means we could support something similar to what you wrote or even something more complex: http://erlang.org/doc/apps/stdlib/io_protocol.html

It is unclear though if it would work for binary files.

**Comment by josevalim** [comment]
I will close this for now as the original question has been answered. If there is interest on a new feature, we can discuss those in the mailing list. Thank you!

**Comment by marciol** [comment]
For historical reasons, seems that it was finally implemented: https://github.com/elixir-lang/elixir/pull/11081
