### ISSUE TITLE
Macro.underscore("Foo_Bar") produces "foo__bar" when likely "foo_bar" expected

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#6456]
### Current behavior
```
iex> Macro.underscore("Foo_Bar")
"foo__bar"  # Note the double ?_
```
### Expected behavior

```
iex> Macro.underscore("Foo_Bar")
"foo_bar"  # Note the single ?_
```
I have a PR ready to submit if the issue is accepted.

**Comment by josevalim** [comment]
We did this change in the past and it caused issues because camelcasing it
again would return a different result. You can do a prepass and remove
double underscores but I believe we shouldn't change Elixir. In any case,
thanks for the PR!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
