### ISSUE TITLE
Add option to fail tests when test scripts contain warnings

### ISSUE THREAD

**Issue by scouten** [elixir-lang/elixir#6476]
I would like to see ExUnit have an option to fail (exit with non-zero status and appropriate warnings) whenever any `.exs` file has a compilation warning.

The solution suggested in https://github.com/elixir-lang/elixir/issues/3223#issuecomment-87724948 does not satisfy this request because:

* It _will_ fail when compiled files (*.ex) contain compilation warnings, but …
* It _will **not**_ fail when the test scripts (*.exs) contain warnings.

I would like to be able to fail a build due to warnings in the .exs files and I see no way to do so today.

**Comment by josevalim** [comment]
I believe you can set warnings_as_errors via `Code.compiler_options` at the top of your mix.exs file. If you would prefer an option to `mix test`, please do send a pull request. Thank you!

**Comment by scouten** [comment]
I couldn't find an example of using `Code.compiler_options` but the technique described in https://stackoverflow.com/questions/31982577/is-it-possible-to-get-the-compiler-to-exit-early-failing-the-build-if-a-compil worked for me.

**Comment by deadtrickster** [comment]
Hello

I have unused variable in my test/file.exs and I have warnings_as_errors in my mix.exs.
 When I run `mix test` first time (no _build yet) warnings printed and compile fails with
`Execution failed due to warnings while using the --warnings-as-errors option`. Just as expected.
If I run `mix test` second time however, warnings as printed but tests compile doesn't fail and tests continue.

Elixir 1.4.4 OTP 20

Thanks

**Comment by harlantwood** [comment]
> I believe you can set warnings_as_errors via Code.compiler_options at the top of your mix.exs file. 

To make this explicit, add to your mix project:

    elixirc_options: [warnings_as_errors: true]
