### ISSUE TITLE
Improve the error message if Logger is not started when capturing logs in ExUnit

### ISSUE THREAD

**Issue by fertapric** [elixir-lang/elixir#6540]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.0
```
* Operating system: macOS Sierra 10.12.6 (16G29)

### Current behavior

Capture Log in ExUnit requires Logger to be started before running the test suite. However, if you forget to start Logger, you get an error similar to this: 

```
** (EXIT from #PID<0.322.0>) exited in: ExUnit.CaptureLog.add_capture(#PID<0.323.0>, [level: nil])
         ** (EXIT) {:error, :noproc}
```

### Expected behavior

I would expect a clearer message, explaining what's wrong with my setup.

**Comment by kelvinst** [comment]
I'll work on this. @josevalim why did you marked this issue with a `Note: Discussion` label?

**Comment by josevalim** [comment]
@kelvinst it is because we should check if the noproc error message is already better today. Giving better error messages is great but sometimes it is counter-intuitive with the let it crash approach. But in case the message is still not clear, then yes, we should definitely do something.

**Comment by fishcakez** [comment]
I think we can solve this by how we generate the exit reason, rather than needing to add a nice error message manually.

If we look at `:proc_lib.start` return value:
https://github.com/elixir-lang/elixir/blob/b89d010b1d01a1b66f08303616d3e684f51f8191/lib/ex_unit/lib/ex_unit/capture_log.ex#L102
If there is a crash in the spawned process the return is `{:error, exit_reason}`, and we want to pass that exit reason as `exit({exit_reason, mfa})` to get a pretty (and correct) error in the formatter. Likely we also want to make sure that we send back `{:error, exit_reason}` when sending a non-ok ack:
https://github.com/elixir-lang/elixir/blob/b89d010b1d01a1b66f08303616d3e684f51f8191/lib/ex_unit/lib/ex_unit/capture_log.ex#L119
That last part may require handling a couple of `other` values.

**Comment by fishcakez** [comment]
Just to be clear we can see this in the output logged, we want the `{:error, :noproc}` part to be `:noproc`:
```
** (EXIT from #PID<0.322.0>) exited in: ExUnit.CaptureLog.add_capture(#PID<0.323.0>, [level: nil])
         ** (EXIT) {:error, :noproc}
```
This format is created by calling approximately:
```elixir
exit({{:error, :noproc}, {ExUnit.CaptureLog, :add_capture, [..]})
```
And we want it to be:
```elixir
exit({:noproc, {ExUnit.CaptureLog, :add_capture, [..]})
```
When `:gen_event` calls fail such as `:gen_event.add_sup_handler` they call `exit/1` with the `:DOWN` reason of the gen_event, i.e. `exit(reason)`, which is `exit(:noproc)` when there is no process. Other behaviours call `exit({reason, {mod, fun, args}})`, like above, to give a nicer error for us to handle.
