### ISSUE TITLE
Suggestion: Base.is_encoded(string, base \\ 64) 

### ISSUE THREAD

**Issue by izelnakri** [elixir-lang/elixir#6558]
```elixir
  Base.is_encoded("656C69786972206973207468652062657374", 16) # true
  Base.is_encoded("elixir is the best", 16) # false

  Base.is_encoded("ZWxpeGlyIGlzIHRoZSBiZXN0") # true
```

**Comment by whatyouhide** [comment]
Hey @izelnakri, thanks for the suggestion!

Elixir's issue tracker is reserved for bug reports and TODO-ish items, not for feature discussions. For those, we use the [elixir-lang-core](https://groups.google.com/forum/#!forum/elixir-lang-core) mailing list so that the whole community can participate in the discussion of the feature; if the community agrees on the feature, then we move to actual implementation with possible connected issue. I suggest you write your proposal there and see what everyone thinks :)
