### ISSUE TITLE
Misleading compiler error messages when keywords used as function names

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#6567]
### Environment

* Elixir versions (elixir --version): 1.3, 1.4, 1.5

### Current behavior

When trying to compile a module with one of the functions named `end`
```
defmodule TestModule do
  def good_name_1(), do: :ok
  def good_name_2(), do: :ok
  def start(), do: :ok
  def end(), do: :ok # line 5
  def good_name_3(), do: :ok
  def good_name_4(), do: :ok
end
```
the compiler returns an error with invalid line number
```
== Compilation error in file lib/test_module.ex ==
** (SyntaxError) lib//test_module.ex:8: unexpected token: end
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
I run into this bug early on when learning Elixir and had to do binary search commenting out parts of a big module to narrow it down.

As a side note i wasn't able to find an up to date and complete list of reserved words, the one in [syntax-reference](https://hexdocs.pm/elixir/1.5.1/syntax-reference.html) is incomplete. There is a bigger [unofficial one](https://www.tutorialspoint.com/elixir/elixir_basic_syntax.htm) but it's probably out of date. I tried some of them as function names and some result in errors with wrong line numbers, some give correct line number but not very helpful message `	(SyntaxError) unexpectedly reached end of line. The current expression is invalid or incomplete`. The ones with `__NAME__` pass silently with no error.

### Expected behavior
An appropriate message like
`** (SyntaxError) lib/test_module.ex:5: Cannot use reserved keyword 'end' as function name`

**Comment by josevalim** [comment]
Thanks for the report.

Unfortunatly this error happens way before we even know we are trying to define a function. It happens early when converting the text into tokens.

The best we can do is say where the previous end was located, but even though, if you a code like this:

```elixir
defmodule TestModule do
  def good_name_1(), do: :ok
  def good_name_2(), do: :ok
  def start(), do: :ok
  def end(), do: :ok # line 5
  def good_name_3() do
    :ok
  end
end
```

We would say the last "end" was in the previous line and that wouldn't be very helpful. Errors with mismatched brackets, parentheses, do/end are always hard to track, exactly because they happen early on when we know little about the code semantics.

**Comment by josevalim** [comment]
And the reserved words have been added to the syntax reference: e5404aec607284276bec050d885a4c6c9948e2b8. Great idea.

**Comment by lukaszsamson** [comment]
Maybe a regex blacklist pass with sth like def\s*(def|end|if|else|...) before doing full syntax parsing would do. It wouldn't probably catch 100% of errors but event 80% is a big win.

**Comment by josevalim** [comment]
@lukaszsamson I am really against such kind of checks because a grammar is much more complex than a regex and there is always the chance of false positives. For example, this would actually be valid code:

```elixir
def = 1
fn -> def end
```

I will try some improvements in the parser but sometimes sometimes a bad token error is as good as it gets. :S
