### ISSUE TITLE
Orthogonal use of key-value pairs

### ISSUE THREAD

**Issue by ElectricCoffee** [elixir-lang/elixir#6635]
Playing around I've found that the `key: value` syntax seems to be somewhat artificially restricted in its use, like for example, I see that `key: value` is short-hand for `{:key, value}` when used in things like keyword lists:

```elixir
> [foo: 12, bar: 13] === [{:foo, 12}, {:bar, 13}]
true
```

I'm just thinking, for the sake of making the language feel more consistent, wouldn't it also be nice to have this syntax apply literally everywhere else?

```elixir
> foo: 12
** (SyntaxError) iex:3: syntax error before: foo
```
... seems like such a weird error to get.

It would be nice to be able to do things like these:
```elixir
# examples of this in action
def broker do
  receive do
    create: {id, payload} -> # do stuff
    delete: id -> # do other stuff
  end
end

def delete(id, pid) do
   message = delete: id
   send pid, message
end
```

Like, I get it's a very minor change, but (to me) it just makes a lot of sense to have the syntax just be universal. Why restrict it to only be used in lists and maps, when it could be equally useful everywhere?

It could also work in functions, making `def generate(start, to: end)` be short-hand for `def generate(start, {:to, end})`.

**Comment by josevalim** [comment]
Please use the mailing list for feature proposals, the issues tracker is for actionable issues only (or features that have already been agreed to be included in the language).

But generally speaking, the issue this would add with the current syntax is of ambiguity. If you write:

    foo(bar: baz)

do you know mean:

    foo({:bar, baz})

or:

    foo([{:bar, baz}])

You could say the latter for backwards compatibility but it would be inconsistent. And what about this:

    foo(one: two, another, bar: baz)

ir it:

    foo({:one, two}, another, [{:bar, baz}])

?

Your proposal extension would bring even more ambiguities because it would be unclear when you stop adding elements to the tuple. For example,  `foo(one: two, another, bar: baz)` is equivalent to `foo({:one, two, another}, {:bar, baz})` or `foo({:one, two}, another, {:bar, baz})` or `foo({:one, two, another, {:bar, baz}})` or even something else?
