### ISSUE TITLE
Splitting string into characters has empty string at the end

### ISSUE THREAD

**Issue by SteveAlexander** [elixir-lang/elixir#6653]
Splitting string with empty string as a separator unexpectedly (for me) results in an extra empty string at the end of the output.

While it's possible to remove said empty string using the `trim: true` option, the default behaviour seems counter-intuitive.

Elixir 1.5.1

### Current behavior

```
iex(1)> String.split("123", "")
["1", "2", "3", ""]

iex(2)>  String.split("123", "", trim: true)
["1", "2", "3"]
```

### Expected behavior

```
iex(1)> String.split("123", "")
["1", "2", "3"]

iex(2)>  String.split("123", "", trim: true)
["1", "2", "3"]
```

**Comment by josevalim** [comment]
Hi @SteveAlexander!

We recently had a long discussion about this because of this behaviour:

    String.replace("123", "", "x")
    #=> "x1x2x3x"

Which then proposes that we would need to return an empty string *before* and *after*. We even tried to fix it on #6566 but the fact it would be backwards incompatible and inconsistent with how regex split works makes us unable to change the current behaviour.
