### ISSUE TITLE
mix dialyze

### ISSUE THREAD

**Issue by orenbenkiki** [elixir-lang/elixir#671]
Add a "mix dialyze" task that runs the dialyzer on the Elixir project.

**Comment by mremond** [comment]
I see that ticket is closed. Is inclusion of dialyze task into Elixir core still considered ? Do you need feedback from real apps ?

**Comment by josevalim** [comment]
@mremond it is not considered because I think the dialyzer-elixir integration still needs a lot of work to fit with our tooling. In particular, reports in dialyzer are very confusing and do not fit our philosophy of great error messages. We would also need to teach dialyzer to print terms in Elixir format and not Erlang. However, if you want to use it, dialyze from @fishcakez is great: https://github.com/fishcakez/dialyze

**Comment by mremond** [comment]
Sure, understand. I have already integrated it in my project. I am so used to Erlang message that my brain made the translation for me and I did not notice format needed to be improved. All is fine, thanks !
