### ISSUE TITLE
Ensure doc tests and other code in docs are properly formatted

### ISSUE THREAD

**Issue by joshprice** [elixir-lang/elixir#6920]
Can't see this raised anywhere but what was the plan for formatting code in doc strings?

A simple example I've noticed where function calls are missing parentheses: https://github.com/elixir-lang/elixir/blob/v1.5.2/lib/elixir/lib/string.ex#L461-L474

Presumably code in doc strings needs to be formatted also otherwise it will create inconsistency and possible confusion. Given the specialised nature of doc tests, should all rules be applied? Are there any which don't apply?

Similar to #6918

**Comment by KronicDeth** [comment]
@joshprice I asked @josevalim the same question at ElixirConf 2017 after his Keynote on the formatter, he said no, the formatter wasn't meant to format doctest examples.

On your question about which rules would be different: the most obvious one to me is that `|>` has to occur on the end of the line instead of the beginning because of the way doctest `iex>` parsing works the same as real `iex>` parsing and a `|>` on the next line won't be seen before the first line is assumed to be complete and executed.

**Comment by josevalim** [comment]
Yup, it is right now too complicated to apply it to doctests, but by having an standard, code in doctests will converge to that direction. Thank you.
