### ISSUE TITLE
Logger doc clarification

### ISSUE THREAD

**Issue by beedub** [elixir-lang/elixir#6941]
https://github.com/elixir-lang/elixir/blob/f7dede6e8d08dcf8c9c9cea15ab546bcecba3efd/lib/logger/lib/logger.ex#L36-L38

Given the doc and code sample, I'm wondering _why_ it's recommended to use functions whenever the message is expensive to compute. Is this because the function is evaluated within the current process, and not the logger process? (The following lines in the paragraph don't _seem_ to be related, but can't confirm)

**Comment by whatyouhide** [comment]
It's recommended to use functions when the message is expensive to compute because such functions will only be called when the Logger had to log the message, thus avoiding needless expensive computation when the logger level would prevent the expensive-to-compute message being logged. Does this make sense?

I'm going to close this issue as there is not bug with Elixir but feel free to comment here if you don't find what I wrote down clear.

**Comment by beedub** [comment]
That's makes sense and what I thought, so I think there's actually a bug in the documentation then?

https://github.com/elixir-lang/elixir/blob/f7dede6e8d08dcf8c9c9cea15ab546bcecba3efd/lib/logger/lib/logger.ex#L38-L40

Specifically here, the example above uses a function, so the message isn't evaluated right? It seems like the docs are expecting the example to be using a string instead of a function

**Comment by bschaeffer** [comment]
👍 because in the above example, the message is **not evaluated** or interpolated regardless of log level.

**Comment by whatyouhide** [comment]
Ah, that's right. Can you open up a PR with a fix @beedub? :)

**Comment by beedub** [comment]
@whatyouhide https://github.com/elixir-lang/elixir/pull/6942
