### ISSUE TITLE
Mix xref does not include sub-app paths

### ISSUE THREAD

**Issue by jfornoff** [elixir-lang/elixir#6963]
### Environment

`master` Elixir / Mix

### Current behavior
`mix xref callers` only shows `lib/bar.ex` within umbrella applications.

### Expected behavior
`mix xref callers` should include the path to the sub app, like `apps/foo/lib/bar.ex`

I'd be happy to offer a hand with this, just opening the issue to make sure this is not intended behavior or tied to problems that I don't know about :-)

**Comment by josevalim** [comment]
The xref task is recursive which means that any command actually runs in each umbrella project individually. That's why you see relative paths but you should also see something like `==> app_name` before each printed output.

This behaviour can either be described as intentional or as a problem you don't know about but changing it may have larger consequences, so I would say we should stick with the current approach for now.

Thanks for the report! :heart:

**Comment by jfornoff** [comment]
Thanks for the heads-up, that makes sense. 👍 
I cannot confirm the output of `==> app_name` though, that might be a separate issue though

**Comment by josevalim** [comment]
Reopening this then. It seems we are using IO.write in some of those while we should be using Mix.shell.info. :)

**Comment by hauleth** [comment]
@josevalim what about adding new "internal" flag `--in-umbrella` for `mix test`, `mix xref` or any other `mix` task that need to be ran recursively and then handle it there. It would enormously help with Vim or similar tools integrations.

**Comment by AndrewDryga** [comment]
@hauleth mix xref already have `--include-siblings` flag.

```
--include-siblings - include dependencies that have :in_umbrella set to
    true in the current project in the reports. This can be used to find
    callers or analyze graphs between projects
```

**Comment by hauleth** [comment]
@AndrewDryga I am talking especially about `mix test` as I would <3 to be able to have umbrella-relative paths in output as it would significantly improve UX when using Vim QuickFix window with tests.

So instead of `tests/xyz_test.exs` there would be `apps/abc/tests/xyz_test.exs` when `mix test` is ran on Umbrella.

**Comment by wojtekmach** [comment]
@hauleth one problem with `mix test` outputting `apps/abc/test/xyz_test.exs` is that you still wouldn't be able to do `mix test apps/abc/test/xyz_test.exs` (https://github.com/elixir-lang/elixir/issues/5650) so that would be counterintuitive.

The entire test output should be customizable via formatter so maybe try writing a custom "umbrella-aware" one that would output paths?

**Comment by wojtekmach** [comment]
@hauleth here's a quick'n'dirty such formatter: https://gist.github.com/wojtekmach/8aee5de5e3763d78529be2ced4ff07db. I only tested it in a very simple umbrella.

The only difference from stock CLIFormatter is this line: https://gist.github.com/wojtekmach/8aee5de5e3763d78529be2ced4ff07db#file-umbrella_formatter-ex-L15

You can use this by doing: `ExUnit.start(formatters: [UmbrellaFormatter])` in `test/test_helper.exs`
