### ISSUE TITLE
mix deps.update <package> updates dependencies even when not necessary

### ISSUE THREAD

**Issue by adamniedzielski** [elixir-lang/elixir#7030]
I'm not sure if this is a bug or an expected behaviour, but I couldn't find any source that could explain this. Feel free to close if that's an expected behaviour.

### Environment

* Elixir & Erlang versions (elixir --version):

```
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.2
```

* Operating system: Mac OS High Sierra
* Hex: 0.17.1

### Steps to reproduce

1. Clone https://github.com/adamniedzielski/mix-check
2. Run `mix deps.update tzdata`
3. Look at the changes in `mix.lock`

### Current behavior

1. `tzdata` is updated to `0.5.13` (latest version as of today)
2. `hackney` is updated to `1.10.1` (latest version as of today)

### Expected behavior

1. `tzdata` is updated to `0.5.13` (latest version as of today)
2. `hackney` is not updated at all

### Reasoning

1. updating `hackney` is not required to update `tzdata`. The new version of `tzdata` doesn't require this new version of `hackney`.
2. there is no command that allows us to update only `tzdata`. Updating only a single library is helpful if we want to minimize the scope of our changes as much as possible

**Comment by josevalim** [comment]
@ericmj, the reason why we unlock Hackney is to give Hex the flexibility to
also bump it if necessary. However, I think that if we don’t unlock
Hackney, Hex would update to the maximum allowed version, right?

So what if we unlock Hackney only if it is not a top level dependency?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
By default we also update children of a dependency because that's more useful in the majority of cases otherwise you would also have to list every child dependency that you may not even know about or care about.

I understand that also only updating a single dependency can be useful in some cases, but we would need a new option/flag for this because we still want the current behaviour in the majority of cases. You can get the same behaviour today by doing `mix do deps.unlock tzdata, deps.get`, this should only update tzdata.

> However, I think that if we don’t unlock Hackney, Hex would update to the maximum allowed version, right?

If we don't unlock hackney it will be locked, which means that if tzdata bumps the requirement on hackney we can't update tzdata which will be confusing to users.

> So what if we unlock Hackney only if it is not a top level dependency?

We can try this but my belief is that it will cause user confusion in more cases than people want to update strictly a single dependency. It would be better to use `mix do deps.unlock tzdata, deps.get` to update a single dependency or introduce a new command or flag for this.

**Comment by adamniedzielski** [comment]
I checked how this works in Bundler and:
1. `bundle update <library>` will update the dependencies as well (so this matches the behaviour of `mix deps.update <library>`)
2. `bundle update --source <library>` will only update the library. Honestly, I think that the flag name is not very intuitive here and the documentation doesn't highlight this use case
3. `bundle update --conservative <library>` - "do not allow shared dependencies to be updated". I've just learned about this flag

From a user perspective I wouldn't mind having a flag here 😄. However, I do understand that it has a cost from the maintainer perspective.

**Comment by ericmj** [comment]
I think `--source` and `--conservative` flags would be nice to have.

That means we either have to move the update/unlock logic [1] to Mix, which may be wrong because different SCMs may want different logic. We can emulate `--source` by unlocking the dependency writing the new lock file to `mix.lock` and sending the lock to Hex. `--conservative` would require new code and we can't emulate it from Mix.

We should also probably document how Hex updates dependencies, like this [2]. Should this documentation be in Mix, where people can easily find it, or in Hex where it arguably should be.

[1] https://github.com/hexpm/hex/blob/master/lib/hex/remote_converger.ex#L323-L361
[2] http://bundler.io/man/bundle-update.1.html#OVERLAPPING-DEPENDENCIES

**Comment by josevalim** [comment]
@ericmj I think we can do everything from Mix. The `--conservative` flag would simply unlock the dependencies explicitly given.

**Comment by ericmj** [comment]
If we do everything in Mix we need to change behaviour in Hex or Hex will continue to unlock all children. To not break for users using older Elixir versions we need to introduce a new on RemoteConverger function that does not unlock.

**Comment by josevalim** [comment]
Oh, I see. I thought Hex relied only on what we unlocked. I thought Hex only unlocked what we unlocked.

**Comment by josevalim** [comment]
@ericmj if that's the case, I would rather update the docs for `mix deps.update` and mention users can go with `mix deps.unlock` route.

**Comment by ericmj** [comment]
> Oh, I see. I thought Hex relied only on what we unlocked. I thought Hex only unlocked what we unlocked.

The child unlocking happens in Hex, Mix does the same thing in the converger but Hex doesn't use it so we do something similar before running the resolver.

**Comment by ericmj** [comment]
> if that's the case, I would rather update the docs for mix deps.update and mention users can go with mix deps.unlock route.

Should we document how Hex updates dependencies in Mix docs?

**Comment by josevalim** [comment]
@ericmj it doesn't seem to be anything specific to Hex though? Both Mix and Hex behave the same.

**Comment by ericmj** [comment]
:heart:

**Comment by adamniedzielski** [comment]
💚
