### ISSUE TITLE
Code formater change code logic

### ISSUE THREAD

**Issue by fazibear** [elixir-lang/elixir#7034]
### Environment

* Elixir & Erlang versions (elixir --version): 1.6.0-dev
* Operating system: OSX

### Current behavior

Code changes after `mix format`:

```
-    |> Enum.at((crc ^^^ byte) &&& 0xff)
+    |> Enum.at(crc ^^^ byte &&& 0xFF)
```
```
-    (crc >>> 8) ^^^ crc_table(byte, crc)
+    crc >>> (8 ^^^ crc_table(byte, crc))
```

```
-    |> Enum.reduce(crc, fn(value, crc) ->
-      (crc >>> 8) ^^^ Enum.at(@table, (crc ^^^ value) &&& 0x00ff)
-    end)
+    |> Enum.reduce(crc, fn value, crc ->
+         crc >>> (8 ^^^ Enum.at(@table, crc ^^^ value &&& 0x00FF))
+       end)
```

### Expected behavior

Don't change code logic

**Comment by ericmj** [comment]
Your first example is correct behavior because `^^^` has higher precedence than `&&&`.

The two other examples are indeed incorrect and it's because the operator table are not the same https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_parser.yrl#L54 https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/code/identifier.ex#L33.

**Comment by OvermindDL1** [comment]
> Your first example is correct behavior because ^^^ has higher precedence than &&&.

I really *really* do not like this though, I keep parenthesis around many of such math/logic operators so I don't have to mentally freak out about precedence ordering because I really mentally just freeze every time I see such unparenthesized math/logic operators...  >.>

**Comment by NobbZ** [comment]
I do prefer parens around operators as well, since I'm a polyglot I often
have to deal with some slight edge cases where language a does have
precedence just the other way round or its the same precedence in language
A but they differ when in language B...

OvermindDL1 <notifications@github.com> schrieb am Mi., 15. Nov. 2017, 16:21:
