### ISSUE TITLE
Inconsistency between DateTime and NaiveDateTime creation

### ISSUE THREAD

**Issue by lexun** [elixir-lang/elixir#7070]
Creating a `NaiveDateTime` with `new` or `from_iso8601` will pass invalid times right into the date struct, where `DateTime` will fix issues with part of the time being out of bounds. 

In some ways this makes sense due to `DateTime` depending on `Calendar.ISO`, but the difference in behavior can be surprising. The documentation describes the uniqueness of a `NaiveDateTime` being only that it does not have a time zone.

### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.5.1
* Operating system: Mac OS Sierra 10.12.6

### Current behavior

When given seconds that are out of bounds, `DateTime` corrects the problem.

```elixir
iex(1)> DateTime.from_iso8601("2017-11-28T11:32:60Z")
{:ok, #DateTime<2017-11-28 11:33:00Z>, 0}
```

`NaiveDateTime` preserves it.
```elixir
iex(2)> NaiveDateTime.from_iso8601("2017-11-28T11:32:60Z")
{:ok, ~N[2017-11-28 11:32:60]}
```

### Expected behavior

Changes from 32 minutes and 60 seconds, to 33 minutes and 0 seconds:
```elixir
iex(2)> NaiveDateTime.from_iso8601("2017-11-28T11:32:60Z")
{:ok, ~N[2017-11-28 11:33:00]}
```

**Comment by JulioDeLeon** [comment]
I would like to work on this but I have a question. So base of the following examples:

`iex(2)> DateTime.from_iso8601("2017-11-28T11:32:60Z")`
`{:ok, #DateTime<2017-11-28 11:33:00Z>, 0}`

`iex(3)> NaiveDateTime.from_iso8601("2017-11-28T11:32:60Z")`
`{:ok, ~N[2017-11-28 11:32:60]}`

`iex(4)> DateTime.from_iso8601("2017-11-28T11:32:61Z")`
`{:error, :invalid_time}`

`iex(5)> NaiveDateTime.from_iso8601("2017-11-28T11:32:61Z")`
`{:error, :invalid_time}`

Why is 60 determine the carry over and not all values above 59?  I would argue that any values above 59 would be in invalid in this case.

**Comment by JulioDeLeon** [comment]
I would like to work on this but I have a question. So base of the following examples:

`iex(2)> DateTime.from_iso8601("2017-11-28T11:32:60Z")`
`{:ok, #DateTime<2017-11-28 11:33:00Z>, 0}`

`iex(3)> NaiveDateTime.from_iso8601("2017-11-28T11:32:60Z")`
`{:ok, ~N[2017-11-28 11:32:60]}`

`iex(4)> DateTime.from_iso8601("2017-11-28T11:32:61Z")`
`{:error, :invalid_time}`

`iex(5)> NaiveDateTime.from_iso8601("2017-11-28T11:32:61Z")`
`{:error, :invalid_time}`

Why does 60 determine the carry over and not all values above 59?  I would argue that any values above 59 would be in invalid in this case.

**Comment by JulioDeLeon** [comment]
I would like to work on this but I have a question. So base of the following examples:

`iex(2)> DateTime.from_iso8601("2017-11-28T11:32:60Z")`
`{:ok, #DateTime<2017-11-28 11:33:00Z>, 0}`

`iex(3)> NaiveDateTime.from_iso8601("2017-11-28T11:32:60Z")`
`{:ok, ~N[2017-11-28 11:32:60]}`

`iex(4)> DateTime.from_iso8601("2017-11-28T11:32:61Z")`
`{:error, :invalid_time}`

`iex(5)> NaiveDateTime.from_iso8601("2017-11-28T11:32:61Z")`
`{:error, :invalid_time}`

Why does 60 determine the carryover and not all values above 59?  I would argue that any values above 59 would be in invalid in this case.

**Comment by lexun** [comment]
Oh, I didn't even check that. I assumed that since 60 rolled over that higher values would do the same. I suppose just returning `:invalid_time` makes more since in either case.

I wonder why 60 was chosen here instead of 59:
https://github.com/elixir-lang/elixir/blame/master/lib/elixir/lib/calendar/iso.ex#L340

**Comment by josevalim** [comment]
I believe this is working as intended. We need to support 60 because of leap seconds. When we have DateTime, then we can normalize that against the timezone information.

The only question is if we should continue normalizing this information when creating a DateTime in UTC. Elixir itself doesn't have a list of leap seconds.

@lau, thoughts?

**Comment by lau** [comment]
Right
`DateTime.from_iso8601("2017-11-28T11:32:60Z")`
is not valid, but we can only really know that if we have a list of the leap seconds. tzdata has a list of leap seconds.

`2015-06-30T23:59:60Z` is valid because that is a leap second. It is different from `2015-07-01 00:00:00Z`.

```
"2015-06-30T23:59:60Z" |> DateTime.from_iso8601
{:ok, #DateTime<2015-07-01 00:00:00Z>, 0}
```
I don't think it is right to return a date in July, when one in June was provided in the input.

In the future it would be nice to be able to validate based on a library (e.g. tzdata) that has the list of leap seconds. However given the same arguments, one particular function should probably not work differently depending on whether an optional dependency is there or not.

One thing to note is that unix time does not support leap seconds in the sense that the leap second is represented as the same number as another second.

**Comment by josevalim** [comment]
@lau I believe the issue though is that we are saying DateTime in Elixir supports UTC... but apparently we don't because don't consider leap seconds.

The question is:

1. should we say that both NaiveDateTime and DateTime do not support leap seconds
2. should we overlap on both (i.e. convert 60 to the next minute)
3. should we add support for leap seconds in Elixir (separate from tzdata) since it is a smaller list which is much simpler to keep

**Comment by lau** [comment]
@josevalim

I think `NaiveDateTime` and `DateTime` structs should continue to support leap seconds.

I don't think converting 60 to the next minute is good when creating new structs. E.g. if asking for 2008-12-31 23:59:60Z you should not get a DateTime from 2009. That second is perfectly valid. For NaiveDateTime we don't have a way of validating leap seconds because we don't know the timezone. So it makes sense to allow the second field to be 60 for any NaiveDateTime.

However for certain calculations it might make sense to treat a DateTime where the second is `60` as the next second. Because the `add` functions already ignore leap seconds. And especially for NaiveDateTime it becomes strange to do calculations with leap seconds.

tzdata from IANA provides the timezone information and it is similar to timezones in that you never know exactly when there will be an update in the future. However the leap seconds are announced 6 months ahead of time. So if you have up to date leap second information you can make future calculations taking leap seconds into account some months in advance with a reasonable assurance that they will be correct.

Whereas timezone changes can happen days before they take effect. It would be unfortunate to have the leap second data tied to the version of Elixir - if for instance some timezone data came with an was compiled with a certain version of Elixir. It might make sense to have a behaviour/interface for just the leap second part so a library can implement just the leap seconds and a tzdata library can implement both the timezones and leap second data. There might be some edge cases where people don't have a few MB RAM for timezones but they do have space for a list of leap seconds. Even though even a Raspberry Pi has a lot of RAM. But if you are going to update the leap seconds, in most cases I would imagine that you can also get the list of new timezones. The `tar.gz` with the tzdata is only around 300KB.

Imagine having a behaviour where Elixir can be configured to use a list of leap seconds. It would be used for calculations that take leap seconds into account and for validations when creating DateTime structs with a second field with a value of 60. So if you have a library that provides leap seconds then DateTime.from_iso8601("2008-12-31 23:59:60Z") will check that it is valid and return
`{:ok, #DateTime<2008-12-31 23:59:60Z>, 0}`
instead of 
`{:ok, #DateTime<2009-01-01 00:00:00Z>, 0}` as it does today. And if no leap second library is provided then it would return some error, like `{:error, :no_leap_second_data_available_60_second_input}`.

If you have a list of leap seconds you can do some cool calculations like how many actual SI seconds there were between e.g. 2007-01-01 00:00:00Z and 2017-01-01 00:00:00Z. Or you can calculate it pretending that there are no leap seconds. Functions like `DateTime.diff` could have an optional boolean argument for taking leap seconds into account. E.g. `use_leap_seconds \\ false`. Performance would be worse, but it would be more correct. Although sometimes you want to not to take them into account on purpose. Because a lot of system - for instance Unix time - don't.

**Comment by josevalim** [comment]
Thanks @lau!

It still feels like we are missing something because, even if DateTime.from_iso returned `{:ok, #DateTime<2008-12-31 23:59:60Z>, 0}`, at the moment we add `0 seconds` to that datetime, it would flip over to `#DateTime<2009-01-01 00:00:00Z>` exactly because our engine does not consider leap seconds.

I am wondering now if it is best to not allow datetimes to be represented with leap seconds but still include diff functions that support leap seconds.

**Comment by josevalim** [comment]
To sum up this conversation: the NaiveDateTime behaviour is correct. Since we don't have timezone information, we can't take leap seconds into account. DateTime does have all of the relevant information to consider leap seconds but we don't have the leap seconds information. This should be supported eventually. Maybe when timezone support is added.
