### ISSUE TITLE
Logger disabling in testing environment

### ISSUE THREAD

**Issue by jakub-gonet** [elixir-lang/elixir#7154]
Wells, I just wanna propose to add some setting to disable logger (or to be specific: its output in console) in tests env while keeping some way to refer to them; ideally in config.exs. For now I'm using `Logger.remove_backend(:console)` at top of every test which logs something, but this isn't very convenient.

**Comment by whatyouhide** [comment]
Hey @jakub-gonet, you can use [`ExUnit.CaptureLog.capture_log/2`](https://hexdocs.pm/ex_unit/ExUnit.CaptureLog.html#capture_log/2) for fine-grained control over capturing logs and using the logged output. Otherwise, ExUnit supports a `:capture_log` tag so you can suppress the output of a test by doing

```elixir
@tag :capture_log
test "my test" do
  # ...
end
```

or of an entire test case with `@moduletag :capture_log`.

**Comment by jakub-gonet** [comment]
Didn't know about this tag, its definitely more elegant than removing backend, thanks!
