### ISSUE TITLE
Strange result of pattern matching on structs

### ISSUE THREAD

**Issue by amatalai** [elixir-lang/elixir#7156]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.6.0-rc.0 (182c730) (compiled with OTP 20)
* Operating system: macOS 10.13.2 - High Sierra

### Current behavior

```elixir
defmodule Foo do
  defstruct [bar: :baz]
end

iex(1)> %{} = %Foo{}
%Foo{bar: :baz}
iex(2)> %struct{} = %Foo{}
true
iex(3)> struct
Foo
```
Second line returned `true`. In previous elixir versions same code returns struct from right side of `=`
### Expected behavior
```elixir
iex(1)> %{} = %Foo{}
%Foo{bar: :baz}
iex(2)> %struct{} = %Foo{}
%Foo{bar: :baz}
iex(3)> struct
Foo
```

**Comment by dmlittle** [comment]
I tried taking a look at this issue but I'm not comfortable enough with Erlang to be able to fix it. Using [`git bisect`](https://git-scm.com/docs/git-bisect) I was able to find that the regression was originally introduced in #6347 when the matching logic was changed to validate struct names.

**Comment by fishcakez** [comment]
@dmlittle looking at that PR I think the bug is at https://github.com/elixir-lang/elixir/blob/25dc8d8d4f27ca105d36b06f3f23dbbd0b823fd0/lib/elixir/src/elixir_erl_pass.erl#L28. This Erlang AST is returning `true` on a match with a struct var due to the `[True]` body element, whereas we want to be returning the value of the expression on the right side, i.e. `[ResultVar]`.

**Comment by dmlittle** [comment]
@fishcakez awesome! I think I know how to solve this issue now. I'll put up a PR and see if there are any other changes needed.
