### ISSUE TITLE
Errors raised in the init() for GenServer are never reported after its restart

### ISSUE THREAD

**Issue by konstantinzolotarev** [elixir-lang/elixir#7173]
### Environment

* Elixir & Erlang versions (elixir --version): 1.5.3 (Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace])
* Operating system: MacOS

### Current behavior
Here is application sample: 
https://github.com/konstantinzolotarev/sample_app

In sample: https://github.com/konstantinzolotarev/sample_app/blob/master/apps/fetcher/lib/fetcher/balance.ex#L10

If worker starts and random number is `1`, everything works fine.
If worker get number `2` on first start it shows error:
```
13:47:33.227 [info]  Got 2

=INFO REPORT==== 3-Jan-2018::13:47:33 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application fetcher: Fetcher.Application.start(:normal, []) returned an error: shutdown: failed to start child: Fetcher.Balance
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Test exception
            (fetcher) lib/fetcher/balance.ex:14: Fetcher.Balance.init/1
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

But if worker starts with `1` and after that Supervisor restart it (I killed process using `:observer`)
After restart Application failing without any logs.
```
iex(3)> :observer.start
:ok
iex(4)>
13:47:11.711 [info]  Got 2

13:47:11.711 [info]  Got 2

13:47:11.712 [info]  Got 2

13:47:11.712 [info]  Application fetcher exited: shutdown
```

### Expected behavior
Even after Supervisor restarts worker and it fails - it should show fail log for every exception.

**Comment by fishcakez** [comment]
Hi @konstantinzolotarev. The main log messages are only sent if a process crashes after it has started, i.e. `init/1` has returned `:ok`. However log reports are still sent to Erlang's `error_logger` but these are not enabled by default. To enable them from the command line:
```
$ iex --logger-sasl-reports true -S mix
```
Or via config:
```elixir
config :logger, handle_sasl_reports: true
```
The sasl reports (so called as logged by Erlang's `sasl`) are lower level information and error logs that show a detailed understanding of what is happening in terms of processes starting and stopping. Likely you want to have these on in production because you can go through the log and get a clear understanding of how the system failed at a higher level. However for dev/testing they are probably too noisy unless you need them to debug.

The goal of an `init/1` is to recover the process to a good state. If the process can not initialize it's state in the `init/1` callback then the error should be because of something that the process depends on not working correctly. For example it could be that a process or ETS table does not exist, the hardware is broken, the configuration is not set or some other prerequisite for the process to run. In this situation we are assuming that another part of the Elixir system is in a bad state. Likely a process has crashed and we need to trigger restarts higher up the supervision tree. The log message we want is for the process that crashed and got the system into a bad state not the process that couldn't start because the process it depends on crashed. 

This is achieved by failing to initialize and triggering the parent supervisor to try again until it gives up. Then let the grandparent supervision try until the process thats broken gets restarted. If this doesn't work then our application is broken and won't run correctly, so it stops. In prod it takes the VM down and maybe we can do something else, even if it requires human intervention like replace the machine. This is expected because we don't write applications that never crash so `init/1` should not just be thought of as just run on start up, but "recover" the process get to a good state at any time.

However if this is the initial startup then we make the assumption that the process's requirement can never be met because we never got in a healthy state, so we stop immediately. Hopefully this fails the deployment before we get bad code running. Also we get the error - you showed it 😄  - in this situation with minimal logging.

**Comment by fishcakez** [comment]
As a small note, if we included all or a subet of the sasl reports by default we would get a lot of duplicate log: every time there was a crash after an `init/1`.

**Comment by konstantinzolotarev** [comment]
@fishcakez Awesome. 
Thank you very much for explanation.
