### ISSUE TITLE
put_assoc/4 gets called when 3 params are supplied

### ISSUE THREAD

**Issue by goravbhootra** [elixir-lang/elixir#7186]
### Current behavior
`> e = Repo.get(Event, 1)`
%Eventyr.Events.Event{...}

`> Ecto.Changeset.put_assoc(%Registration{}, :event, e)`
** (FunctionClauseError) no function clause matching in Ecto.Changeset.put_assoc/4
The following arguments were given to Ecto.Changeset.put_assoc/4:

    # 1 %Eventyr.Registrations.Registration{}
    # 2 :event
    # 3 %Eventyr.Events.Event{}
    # 4 []
Why is the fourth parameter getting inserted?

### Expected behavior

Ecto.Changeset.put_assoc/3 should get called

### Environment
Erlang/OTP 20 [erts-9.2] [source] [64-bit] 
Elixir 1.5.3

* Operating system: Mac OS 10.12.6

**Comment by pdawczak** [comment]
Just a clarification, [`Ecto.Changeset.put_assoc`](https://github.com/elixir-ecto/ecto/blob/v2.2.7/lib/ecto/changeset.ex#L1098) accepts 4th argument, which is supposed to be an option keyword list, and by default (if not provided) it is assigned with empty list (`[]`).

In order to [`put_assoc`](https://hexdocs.pm/ecto/Ecto.Changeset.html#put_assoc/4) to work, first argument provided should be `Changeset`, not _final struct_.

**Comment by josevalim** [comment]
As @pdawczak explained. :)
