### ISSUE TITLE
Record.extract/2 cannot extract records from files that depend on other include files

### ISSUE THREAD

**Issue by brennana** [elixir-lang/elixir#7195]
I noticed that `Record.extract/2` is unable to extract records if, for example, that record uses definitions from other include files.

Using the [pkt](https://github.com/msantos/pkt/tree/master/include) library as an example, the following will fail to compile since the `ipv4` record uses definitions that are defined in `pkt/include/pkt_ipproto.hrl`:

```elixir
Record.extract(:ipv4, from_lib: "pkt/include/pkt_ipv4.hrl")
```

However, I see that since the record extractor uses `epp`, it would be possible to pass `:epp.parse_file/2` options via `extract` concerning extra include files that are necessary for extraction of records. I'm not sure how this should look--perhaps just by giving `Record.extract/2` and friend an `includes` option or something.

```elixir
Record.extract(:ipv4, from_lib: "pkt/include/pkt_ipv4.hrl", includes: ["pkt/include/pkt_ipproto.hrl"])
```

**Comment by josevalim** [comment]
@brennana The includes is not enough because the includes value should be a list of directories for relative includes. In my opinion the ipv4.hrl should include any other header file it depends on, but it doesn't, so we can't address it here.

In any case, your idea of passing options to `:epp.parse_file/2` is excellent. I am going to push it to master in a second and you should be able to solve this by specifying the macro value directly:

```elixir
Record.extract(:ipv4, from_lib: "pkt/include/pkt_ipv4.hrl", macros: [IPPROTO_TCP: 6])
```
