### ISSUE TITLE
Apparent @compile :nowarn_unused_vars regression on 1.7.0-dev

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#7293]
### Environment

Master branch of Elixir Jan 31st
Erlang/OTP 20 [erts-9.2] [source] [64-bit] 
Elixir (1.7.0-dev) 
Mac OSX Sierra

### Current behavior

I have two modules marked with `@compile :nowarn_unused_vars` which on 1.5.3 and 1.6.1 works correctly - no warning are emitted.  On 1.7.0-dev the warning are emitted.

The use case is multiple functions generated at compile time which share several parameters but in which not all function bodies use all the parameters,  It is impractical to work out what parameters should be marked with a leading `_` so suppressing warnings is appropriate.

No errors are raised or warnings issued with regard to the use of the `@compile :nowarn_unused_vars` directive.

### Expected behavior

`@compile :nowarn_unused_vars` should work as expected, this appears to be a regression from 1.6.1.

I'm reasonably sure this was working properly until the last couple of days but I was unable to find the commit the made the change and my reading of `Kernel.@` didn't clarify whether this is an intentional change or not.

**Comment by michalmuskala** [comment]
The fact that the warning worked before was accidental in a way. Before 1.7, the elixir compiler relied on the erlang compiler (and the `erl_lint` pass to do the validation). 1.7 moves handling of most of such warnings directly to the elixir compiler (the plan is to disable `erl_lint` since it gives noticeable performance benefits and we can provide more precise warnings from elixir).

Tracking issue: https://github.com/elixir-lang/elixir/issues/5800

**Comment by kipcole9** [comment]
Thanks, understood (at least a little bit).  What expectations should I have for 1.7 then?  

I can revert to an old implementation that was a bit tacky because it used `Code.eval_quoted` to avoid the warnings - then I moved to the `@compile` directive.  Perhaps the `Code.eval_quoted` approach won't work in 1.7 either?

If the intention is to remove "support" for `@compile` then perhaps good to showa deprecation message or issue a compile time warning?

As a library author I tend to think that for a library user these warning are at best a distraction and at worst tend to reduce confidence in the lib. So I'd like some sustainable way to suppress these warnings since I know exactly how and why they occur.

**Comment by michalmuskala** [comment]
Can you link to the problematic code? Is it public? Perhaps there's some other way to avoid those warnings?

**Comment by kipcole9** [comment]
The module which generates the error: https://github.com/kipcole9/cldr/blob/master/lib/cldr/plural_rules/cardinal.ex which `uses` https://github.com/kipcole9/cldr/blob/master/lib/cldr/plural_rules/plural_rule.ex

I will close this issue since its not a bug.  If you are kind enough to take a look and make any recommendations in the issues tracker on the repo it would be much appreciated.

**Comment by pragdave** [comment]
Can I ask for this to be reopened?

I have code where there are unused variables injected my macros (OK, maybe not ideal, bit its a fact of life), and now I can't disable warnings.

I do believe it's a regression, as [the doc](https://hexdocs.pm/elixir/Module.html#module-compile) says:

> Defines options for module compilation. This is used to configure both Elixir and *Erlang* compilers, as any other compilation pass added by external tools. For example:

(emphasis mine)

Here's a simple example. This isn't the actual code, so suggesting I use `_a` won't be helpful :)

~~~ elixir
defmodule Play do
  @compile :nowarn_unused_vars
  def t do
    a = 1
  end
end
~~~

~~~ console
$ mix compile
Compiling 3 files (.ex)
warning: variable "a" is unused         <-------------- this is the dummy test file above
  lib/test.ex:6

warning: variable "setups" is unused    <------------------ this is from the macro
  lib/table_setups.ex:1

Generated table_setups app

$ elixir -v
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:
1] [hipe]

Elixir 1.7.4 (compiled with Erlang/OTP 19)
~~~

(yes, there's an Erlang mismatch: I've switched to using `asdf`)


Cheers


Dave

**Comment by josevalim** [comment]
Hi @pragdave,

Yes, you are correct, we do officially document it supports Erlang compiler options. The trouble though is that we are no longer executing this Erlang pass and the Elixir compiler is the one emitting those warnings. This allows us to emit better error messages and it paved the way for the 5% compilation improvements now in Elixir v1.8. Unfortunately, I believe considering the attribute option would be too complicate for our compilers.

Could you please link to the macro? Maybe we can find alternative solutions. 

Here are some notes: we don't emit unused variable warnings for variable in macros, unless you are injecting user variables. However, if you are injecting user variables, it likely means it is interacting with the user code, and isn't it a bit too much to disable warnings for the *whole module* because a macro is being used? I personally catch what would be many bugs due to unused variable warnings, so being able to disable it for a whole module is a cons in my opinion.

In Plug, we also inject user variables, via a `conn`, and we get rid of the warnings by adding the following at the beginning of the function:

    _ = var!(conn)

This is also removed by the compiler at some point, so it won't have an impact at runtime. Please let me know your thoughts.

**Comment by pragdave** [comment]
Ah, of course. I’d forgotten I could assign it to `_`



...


Dave
