### ISSUE TITLE
Inline multiple :maps calls into VM operations

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#7353]
We can do it for `:maps.put/3` (always) and for `:maps.merge/2` when the left side is a map.

**Comment by michalmuskala** [comment]
If implemented, this needs to check carefully if we don't hit the same issues as in https://github.com/elixir-lang/elixir/pull/7032. If we do, we need to wait with implementation until support for OTP 19 is dropped.

**Comment by OvermindDL1** [comment]
If there are multiple put/3 calls then I'd imagine most people would use merge.  However, what about a `Map.put_many` that takes a keyword list (or other enumerable?), which if statically defined (like `Map.put_many(theMap, a: 1,  b: 2, c: 2)`) would be trivial to optimize (otherwise it'd decompose to a reduce or so unless the VM has a better method, I don't know the map related VM calls as they are a bit after my time...).

That would be of course in addition to collapsing multiple `:maps.put/3` calls anyway.  ^.^

**Comment by josevalim** [comment]
@OvermindDL1 I would rather optimize maps:merge if possible rather than introduce a function only because you may need it in case of optimizations.

**Comment by OvermindDL1** [comment]
I do most often use maps:merge with a hardcoded map to merge in so that would be fairly trivial to optimize.

**Comment by josevalim** [comment]
Moving this to #5851 as well then.

**Comment by ggcampinho** [comment]
I'm working on this, PR will come soon ;)

**Comment by josevalim** [comment]
Closing in favor of #8223.
