### ISSUE TITLE
h helper not work properly with imported functions

### ISSUE THREAD

**Issue by Eiji7** [elixir-lang/elixir#7381]
### Environment

Both `Erlang` and `Elixir` are installed using [asdf](https://github.com/asdf-vm/asdf) version manager.

```
$ asdf current
elixir         1.6.1-otp-20
erlang         20.2.3
…
```
Funtoo Linux current x86-64bit on intel64-ivybridge

### Current behavior

```elixir
h Enum.take
# displays documentation
import Enum
# returns: Enum
h take
# displays error: No documentation for Kernel.take was found
```

### Expected behavior

I'm not sure if we even really need `h` helper working for imported functions. I just noticed this bug when trying to show documentation for `where/3` for module `Ecto.Query` (in documentation examples we are importing this module). The real problem is that `h` helper looks for this function in wrong module i.e. `Kernel`.

**Comment by josevalim** [comment]
Yes, I believe we don't consider imports altogether in autocomplete but we can start doing so since autocomplete has enough context now.

**Comment by dmlittle** [comment]
@josevalim I tried giving this a try. I think I might have the right approach but I want to confirm before I write tests and put up a PR. How does [this](https://github.com/dmlittle/elixir/commit/44d9c66e259c822ee97d2809f458285b8e976a97) look? 

As a side note, is it normal that `__ENV__` is set to whatever the `__ENV__` is when the module is created/loaded and not updated over time? I guess it makes sense but at the same time can't the environment change over time? I originally tried replacing `@default_files` in `IEx.Introspection.find_decompose_fun/1` with `__ENV__.requires` but those values were not updated when a new module was imported in the IEx shell. Because of this I resorted to passing through the `__CALLER__` enviroment

**Comment by josevalim** [comment]
@dmlittle you should have the `__CALLER__` outside of the quote. Also we don't want the list of requires but rather the list of `functions` and `macros`. So I would recommend something like this:

  defmacro open(term) do
    quote do
      IEx.Introspection.open(unquote(IEx.Introspection.decompose(term, __CALLER__)))
    end
  end

And in decompose you look into functions and macros.

What do you think?

**Comment by dmlittle** [comment]
@josevalim sounds good, I'll put up a PR!
