### ISSUE TITLE
Formatter adds newlines in triple quotes with interpolation

### ISSUE THREAD

**Issue by blatyo** [elixir-lang/elixir#7395]
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.6.1 (compiled with OTP 20)

* Operating system: 
Mac

### Current behavior

[Here's](https://github.com/conduitframework/conduit/commit/16b9dcb19e774d646fd21e64b17316e192b8d73b#diff-b251e8c32d45e824becf8015a168d6b2L145) an example from real code.

This code:

``` elixir
Code.format_string!(~S[
"""
When I have a docstring with really long lines, I sort of expect them to not be modified.
However, if there is an interpolation in a docstring such as #{inspect 1}, it will insert newlines into this line.
"""
], line_length: 70) |> IO.puts()
```

Generates:

``` elixir
"""
When I have a docstring with really long lines, I sort of expect them to not be modified.
However, if there is an interpolation in a docstring such as #{
  inspect(
    1
  )
}, it will insert newlines into this line.
"""
```

### Expected behavior

Generates:

``` elixir
"""
When I have a docstring with really long lines, I sort of expect them to not be modified.
However, if there is an interpolation in a docstring such as #{inspect(1)}, it will insert newlines into this line.
"""
```

**Comment by josevalim** [comment]
I am not sure there is something we can do about it because, if the interpolation doesn't break, then the function call inside the interpolation will break:

```
"""
When I have a docstring with really long lines, I sort of expect them to not be modified.
However, if there is an interpolation in a docstring such as #{
  inspect(1)
}, it will insert newlines into this line.
"""
```

Your case is a bit worst because both are happening.

In general, when you have long lines, the formatter will break when it sees the opportunity to.

**Comment by blatyo** [comment]
One thing I noticed was that if I bump up the `line_length` to `80`, it doesn't break even though the line is longer than `80`. Is it already trying to do something?

**Comment by josevalim** [comment]
@blatyo when you increase it to 80, then the interpolation happens before the end of the line, so it is considered as "fit" and it moves on with the rest of the line. Since the rest of the line does not have a place to broken apart, it just fits everything. We could fix this particular issue... but should we?

Btw, I have checked this locally, and the example you pasted became this:

```elixir
"""
When I have a docstring with really long lines, I sort of expect them to not be modified.
However, if there is an interpolation in a docstring such as #{
  inspect(1)
}, it will insert newlines into this line.
"""
```

which is correct according to the formatter specification.

The only protip I can give to help you is to break it into smaller lines and use `\` at the end of the line so it doesn't end-up with a new line in the final output. Like this:

```
"""
When I have a docstring with really long lines, \
I sort of expect them to not be modified.
However, if there is an interpolation in a docstring \
such as #{inspect 1}, it will insert newlines into this \
line.
"""
```

I am afraid there is nothing else we could really do.

We could also simply not break in interpolations inside heredocs. But I am afraid we would just be opening ourselves for a different style of bug reports where we should be breaking interpolations but we are not.

**Comment by blatyo** [comment]
My preference is probably to not break inside heredocs and I agree that could lead to style bug reports arguing for the opposite. To me, heredocs mean "as I typed it", sort of like `<pre>` tags in html. 

The specific place I ran into it in the real world was here: 
https://github.com/conduitframework/conduit/blob/16b9dcb19e774d646fd21e64b17316e192b8d73b/lib/conduit/plug/message_actions.ex#L145-L147

It's code where I'm generating a doctest, which is what makes it particularly hard, because there's no clear place that a break would make sense. Since it's markdown as well, it would appear out of place to write:

``` elixir
"""
## Examples
    import Conduit.Plug.MessageActions
    plug :#{unquote(action)}, #{inspect(unquote(value))}
    
    iex> import Conduit.Plug.MessageActions
    iex> message = #{unquote(action)}(%Conduit.Message{}, &(&1), \
#{inspect(unquote(value))})
    iex> message.#{unquote(field)}
    #{inspect(unquote(value))}
"""
```

**Comment by josevalim** [comment]
Thanks for the follow up @blatyo!

In your case, I think the best would be to break those lines into variables and maybe inject them? It seems you are using a quote, you could also build the full `iex>` lines outside of the quote and inject the whole line with unquote.

For now, I don't think there is anything else for us to do here. We will keep on collecting feedback but there is no obvious answer at the moment.
