### ISSUE TITLE
weird state with gen_server changes on erlang 20.2 and elixir 1.6.1

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#7399]
You can get into a weird state on Erlang 20.2 and Elixir 1.6.1, this happens after calling a recompile and if you have a gen_server send a message to its handle info withing a 100ms~ margin of the recompile.
```
=WARNING REPORT==== 27-Feb-2018::04:31:48 ===
** Undefined handle_info in 'Elixir.Daemon.DaemonGen'
** Unhandled message: tick
```
Before this would be a crash. Now the message is discarded. The weird is this, handle_info is defined, its defined as

```
    def handle_info(_, s) do
        exit(:unhandled_msg)
    end
```

But it still gets ignored. This is probably because the module is in an unloaded state for around 50-100ms :(. 

To make my point clear is this. send(Undefined.Module, :hi), is a crash, so why is send to a non-existent (unloaded due to recompile/0 being called) gen_server a WARNING + message discard? I understand its being sent to a pid in the second case.  Overall it makes the system feel brittle, running 100,000s of gen_servers eventually something will happen where one will get into this weird discarded message state. And then good luck debugging it.

**Comment by josevalim** [comment]
When you are calling recompile, we unload the modules to be recompiled and then compile them again. In this time interval, if you attempt to invoke an existing GenServer, the callback for those GenServers won't be available, calling a message to be logged.

This is not supposed to happen in production because production systems should not call `recompile()`. If you want to update code in production, then you should build releases and go through the proper code upgrade steps.

**Comment by josevalim** [comment]
To quote the documentation of the `recompile` function:

> The application is not restarted after compilation, which means any long running process may crash as any changed module will be temporarily removed and recompiled, without going through the proper code changes callback.

And then:

> This function is meant to be used for development and debugging purposes. Do not depend on it in production code.

**Comment by vans163** [comment]
@josevalim I know this about recompile. What I am saying is before this lead to a crash in the gen_server receiving the message. Now it leads to the message being dropped + a warning, the warning is that the handle_info is not defined, BUT IT IS DEFINED.

**Comment by josevalim** [comment]
It is not defined while you are recompiling the code. Once you call recompile, all modules currently defined are removed until they are made available back again.

**Comment by josevalim** [comment]
Btw, the fact it emits a warning now is a change in OTP 20, where handle_info is no longer necessary to be implemented. It emits a warning now when the function is not available, which is the case when the module is removed for recompilation.

And as said previously, this is not supposed to happen in production if you define your own `handle_info/2`, because modules are not supposed to be removed in production.

**Comment by vans163** [comment]
@josevalim Jeez I see now. This is so annoying to deal with maybe one day I will fix the compiler.  Production is development for us.  We can code up interconnected services very quickly, when things like this happen it makes it so annoying, if you had a crash here you would recover your state after sup restarts the gen_server. This makes it so you need to take down the whole app and restart it.
