### ISSUE TITLE
Typo in NaiveDateTime moduledoc; new/7 instead of new/8.

### ISSUE THREAD

**Issue by jung-hunsoo** [elixir-lang/elixir#7445]
There's a typo in NaiveDateTime moduledoc([code](https://github.com/elixir-lang/elixir/blob/972bca67c484ba3826f4f623837dcd78dd991327/lib/elixir/lib/calendar/naive_datetime.ex#L7)).

There's no more `new/7` which is then replaced with `new/8` since some previous version.

I tried to make a PR, but it seems a bit complicated. So I left an issue instead.

Thanks as always!

**Comment by wojtekmach** [comment]
you're right that there's now `new/8` but technically speaking `new/7` and `new/6` still exist because the last 2 arguments have defaults. But yes, probably makes sense to use `new/8` from now on.

If you'd still want to submit a PR I'd be happy to help, what problems did you run into? Also, for doc changes I usually go for editing straight in GitHub which is super convenient:

<img width="1254" alt="zrzut ekranu 2018-03-12 o 13 39 58" src="https://user-images.githubusercontent.com/76071/37284226-04a2691c-25fb-11e8-8489-cfac59d7adbc.png">

**Comment by jung-hunsoo** [comment]
@wojtekmach Oh sorry I wasn't in a master brance. Thanks.
