### ISSUE TITLE
`Code.format_string!` Makes certain cases less readable (IMHO)

### ISSUE THREAD

**Issue by athal7** [elixir-lang/elixir#7473]
### Environment

* Elixir & Erlang versions (elixir --version): 
```bash
$ elixir --version
Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.2 (compiled with OTP 20)
```
* Operating system: `macOS 10.12.6`

### Current behavior

```elixir
iex|1 ▶ "Enum.map([%{foo: 'bar'}], &(&1.foo))" |> Code.format_string! |> IO.write

Enum.map([%{foo: 'bar'}], & &1.foo)
```

```elixir
iex|2 ▶ """
  with {:ok, user} <- My.Repo.get(User, id),
       {:ok, _}    <- User.authenticate(user, token) do
         {:ok, user}
       else
         _ ->
           {:error, "Unauthorized"}
       end
""" |> Code.format_string! |> IO.write

with {:ok, user} <- My.Repo.get(User, id),
     {:ok, _} <- User.authenticate(user, token) do
  {:ok, user}
else
  _ ->
    {:error, "Unauthorized"}
end
```

```elixir
iex|3 ▶ """
[
  {"first", "second", "third"},
  {"fourth", "fifth", "sixth"}
]
""" |> Code.format_string! |> IO.write

[
  {"first", "second", "third"},
  {"fourth", "fifth", "sixth"}
]
```

### Desired behavior

Keep parens for short-hand anonymous function:

```elixir
iex|1 ▶ "Enum.map([%{foo: 'bar'}], &(&1.foo))" |> Code.format_string! |> IO.write

Enum.map([%{foo: 'bar'}], &(&1.foo))
```

Keep vertically aligned match and arrows in with statement (or even better, make it so when it is not yet):
```elixir
iex|2 ▶ """
  with {:ok, user} <- My.Repo.get(User, id),
       {:ok, _}    <- User.authenticate(user, token) do
         {:ok, user}
       else
         _ ->
           {:error, "Unauthorized"}
       end
""" |> Code.format_string! |> IO.write

with {:ok, user} <- My.Repo.get(User, id),
     {:ok, _}    <- User.authenticate(user, token) do
  {:ok, user}
else
  _ ->
    {:error, "Unauthorized"}
end
```

Vertically align tuple elements:
```elixir
iex|3 ▶ """
[
  {"first", "second", "third"},
  {"fourth", "fifth", "sixth"}
]
""" |> Code.format_string! |> IO.write

[
  {"first",  "second", "third"},
  {"fourth", "fifth",  "sixth"}
]
```

**Comment by whatyouhide** [comment]
Hey @athal7, thanks for the issue!

Everyone has a personal preference but the goal of the formatter is to put these personal preferences aside and have folks use a consistent style across teams, projects, and across the whole community. Since the formatter adopts one specific style, there's always gonna be people that would prefer a different style. It's practically impossible to make everyone happy with every decision in the formatter style.

The formatter is behaving as expected for the `& &1.foo` call, and we don't plan on changing that particular style.

As far as alignment goes (both for `with` clauses and for tuple elements, there's a much longer and interesting discussion in #6647.

I'm closing this as I covered all three examples you posted. 💟

**Comment by athal7** [comment]
Thank you for the prompt reply @whatyouhide ! I look forward to participating in any future polling around formatter preferences, per @josevalim's indication in https://github.com/elixir-lang/elixir/issues/6647.
