### ISSUE TITLE
Function capture support using variables

### ISSUE THREAD

**Issue by NJichev** [elixir-lang/elixir#7500]
### The issue

Say we have a simple module:

```elixir
defmodule Math do
  def zero?(0), do: true
  def zero?(_), do: false
end
```
And we want to capture the function by using these variables:

```elixir
{m, f, a} = {Math, :zero?, 1}
```
Using `&` - we cannot:
```elixir
&m.f/a
** (CompileError) iex:8: invalid args for &, expected an expression in the format of &Mod.fun/arity, &local/arity or a capture containing at least one argument as &1, got: m.f() / a
```
What we could do is use `make_fun`:
```elixir
:erlang.make_fun(m, f, a).(0) #=> true
```
### Expected behaviour(API could be different):

```elixir
{m, f, a} = {Math, :zero?, 1}
&{m, f, a}
# or
&m.f/a
#=> &Math.zero?/1
```

This will be useful when writing some macros for removing boiler-plate and the code would be only in elixir.

**Comment by josevalim** [comment]
We cannot support `&m.f/a` because we would take `f` to be the literal function name and not a variable.

My suggestion: introduce a `Function` module with a `capture/3` function and a `info/1` and `info/2` functions that delegate to `erlang:fun_info/1` and `erlang:fun_info/2`.

We could add `Function.apply/2` as well but our official policy is to not duplicate functions that exist in `Kernel` in the other modules.

**Comment by michalmuskala** [comment]
I'm not really sure about `Function.capture/3`. Implementation-wise, I think we should expand it into `fun M:F/A` instead of calling `erlang:make_fun/3`, just because it's not documented. But we don't really compile anything outside of `Kernel` into syntax when translating to erlang.

**Comment by josevalim** [comment]
I would say this isn’t much different from inlining, which is something we
do in all data-structure modules.

We also had plans to inline Map.merge and Map.put into instructions, we
just didn’t do it yet due to OTP version constraints.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
