### ISSUE TITLE
Compiling Elixir files causes erl.exe to crash

### ISSUE THREAD

**Issue by bramhaag** [elixir-lang/elixir#7591]
### Environment

* Elixir & Erlang versions (elixir --version):  Erlang/OTP 20 [erts-9.3] [smp:2:2] [ds:2:2:10] [async-threads:10] Elixir 1.6.4 (compiled with OTP 19)
* Operating system: Windows 10 64-bit Home

### Current behavior

Compiling any Elixir file with `elixirc file.ex` and `iex -S file.ex` causes erl.exe to stop responding and crash. The Event Viewer gives me the following information:
```
Faulting application name: erl.exe, version: 0.0.0.0, time stamp: 0x5aa846d5
Faulting module name: ntdll.dll, version: 10.0.16299.64, time stamp: 0xac8afc81
Exception code: 0xc00000fd
Fault offset: 0x00044318
Faulting process id: 0x10c8
Faulting application start time: 0x01d3dbc865a5e62d
Faulting application path: C:\Program Files (x86)\erl9.3\bin\erl.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 5b87dd42-83e2-4f09-9572-2adf6b169f68
Faulting package full name: 
Faulting package-relative application ID: 
```

This happens with Elixir 1.6 and 1.6.4 (I have not tested other versions) with both Erlang 9.2 (64 bit) and Erlang 9.3 (32 bit). It does not appear to matter what code I try to compile, a simple hello world example does not work.

**Comment by josevalim** [comment]
Can you run erlang fine? What happens if you type `erl` or `erl.exe`?

**Comment by bramhaag** [comment]
That works fine

**Comment by josevalim** [comment]
What happens if you do `elixir -e ":ok"`?

**Comment by OvermindDL1** [comment]
A crash in ntdll.dll like that is generally a hardware issue, and it's also generally not repeatable and rather is random unless it is caused by hard disk corruption.

Thus:

0. What about what jose states to do with `elixir -e ":ok"`?
1. Does it happen every time on a single project?
2. Does it happen on multiple projects?
3. Does it happen if you entirely *purge* every trace of erlang and elixir both and then reinstall?
4. Have you scanned your disk via `sfc /scannow` and `Dism /Online /Cleanup-Image /RestoreHealth`?
5. Have you performed a memtest86 memory scan for an extended period (say, overnight)?
6. What is the temperature of the CPU, motherboard, and RAM at the times that the crash happens?

**Comment by bramhaag** [comment]
@josevalim The same happens with `elixir -e ":ok"`, erl crashes.
@OvermindDL1:
0. erl crashes
1. yes
2. yes
3. will try
4. will try
5. will try
6. CPU: 40C (There are no temperature sensors for the motherboard and RAM in this laptop, however the back of the laptop doesn't feel hot)

**Comment by bramhaag** [comment]
This is kind of interesting, after running `Dism /Online /Cleanup-Image /RestoreHealth` `elixir -e ":ok"` does not crash erl.exe anymore (it doesn't give me any output either), building projects still doesn't work though.

**Comment by bramhaag** [comment]
I've nuked both elixir and erlang installs and re-installed them. `elixir -e ":ok"` works but compiling anything still crashes erl.exe

**Comment by bramhaag** [comment]
Turns out this happened because the script was located in a OneDrive folder. This also explains the weird `elixir -e ":ok"` behaviour: When the current working directory is in a OneDrive folder, it crashes; it doesn't in other folders.

The Erlang bug report can be found [here](https://bugs.erlang.org/browse/ERL-615)
