### ISSUE TITLE
Logger (conceptual?) issues

### ISSUE THREAD

**Issue by BlueHotDog** [elixir-lang/elixir#7639]
### Environment

* Elixir 1.6.4 Erlang/OTP 20
* Operating system: Ubuntu

There are a couple of issues with Logger, if my application crashes while trying to boot, i dont get the application key in the metadata object.
Another issue is that if the logger backend itself crashes, it does so silently.
(i discovered this by doing IO.puts(metadata) and getting nothing..)

**Comment by josevalim** [comment]
@BlueHotDog can you please open up a separate issue for each of those and include all the information necessary, including a proper way to reproduce the issue? If necessary, a sample application. Otherwise we may spend a lot of time just trying to reproduce those. We want to make sure those issues are actionable and reproducible. Thank you.

**Comment by josevalim** [comment]
Btw, I want to say that the application metadata is not guaranteed, unfortunately. This may improve with Erlang OTP 21, which provides with #7494 but logs coming from OTP do not include metadata information.

For the handler crash not being reported, I cannot reproduce it locally. You get the reports as long as you have two handlers installed. If you have a single handler, then there isn't much we can do to report it.

**Comment by BlueHotDog** [comment]
1) https://github.com/elixir-lang/elixir/issues/7640
2) https://github.com/elixir-lang/elixir/issues/7641
