### ISSUE TITLE
Elixir logger crashes silently

### ISSUE THREAD

**Issue by BlueHotDog** [elixir-lang/elixir#7640]
### Environment

Elixir 1.6.4 Erlang/OTP 20
Operating system: Ubuntu

### Current behavior

When logger backend itself crashes, it does so silently.
(i discovered this by doing IO.puts(metadata) and getting nothing..)

### Expected behavior

Not sure how to solve this, but i expect that if a logger backend does crash i would at least see something in StdErr

**Comment by josevalim** [comment]
I am not sure what we could do here. The issue is that the Logger dog feeds itself. The logger uses GenEvent that uses the logger to log about failures. So when a handler crashes, there is nothing to report the errors. I will leave this open for discussion and see if someone can suggest alternatives.

**Comment by eksperimental** [comment]
Logger dog. Thats a great name for an Elixir developer's pet! 🐕

**Comment by josevalim** [comment]
We have discussed this and unfortunately there isn't much we can do here. If a custom logger handler crashes and there is no other handler, then there is indeed nowhere we can report errors to.
