### ISSUE TITLE
Explore if cond could be a regular macro

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#7693]
Currently `cond` is a special form handled by the compiler. The primary reason for this, in the past, was to correctly handle variable scoping and limit leaking variables between clauses.

Currently, after we changed the scoping rules of `case`, I believe, it should be possible to implement `cond` as a regular macro on top of `case`.

Note: the new implementation should make sure to optimise boolean matches in case a pure-boolean operator is used.

**Comment by OvermindDL1** [comment]
Hmm, I've never checked actually, do the `case` and `if` forms lower to the same `case` in Erlang Core?  If not then there might be a performance optimization that is worth keeping them separate, if so then it sounds good to me.  :-)

(Though honestly I'd say not even for/with/etc.../almost/anything should be special forms beyond things like `case`, and even it could be a macro too to a lowered form...)

> Note: the new implementation should make sure to optimise boolean matches in case a pure-boolean operator is used.

+1

**Comment by michalmuskala** [comment]
`case` is a special form, `if` is a regular macro that compiles to `case`.

**Comment by OvermindDL1** [comment]
> case is a special form, if is a regular macro that compiles to case.

I meant erlang's `case`/`if`, not Elixir's (since elixirs case compiles to erlangs case and elixirs cond compiles to erlangs if).

**Comment by michalmuskala** [comment]
Elixir `cond` compiles to `case` as well - it can't compile to erlang's `if` since it supports only guards, while elixir's `case` supports any expressions.

Ultimately, they all compile to `case` at the core erlang level.

**Comment by OvermindDL1** [comment]
> while elixir's cond supports any expressions.

It does?!?  I've been using it like Erlang's `if`!  Whoops!  ^.^;

Then definitely yeah, it should be a macro (as should for/with/etc, and putting things in bodies instead of N-arity args ^.^;).  :-)

**Comment by mmartinson** [comment]
A behaviour of `cond` I had been wondering about for a while and that I think that could be helpful to have made a bit more explicit, especially if there are changes made to the implementation, is the evaluation order of match expressions. I had been curious in particular about whether they are all evaluated in advance, or only when they are checked, and also whether variable assignments in the expression are available in the body. I saw some code recently (can't remember where, in ecto maybe), that suggests they are both lazy evaluated and that variable assignments are available. I only bring it up now thinking it could be good to be explicit about these behaviours so that a rewrite as a macro keeps all the same semantics

**Comment by mmartinson** [comment]
@michalmuskala you mentioned changes in scoping rules to `case`. Could you point me to where I could learn about that some more?

**Comment by OvermindDL1** [comment]
@mmartinson Currently `case` 'leaks' variables out of it's scope, it is set to be changed so that no longer happens.

**Comment by josevalim** [comment]
Closing in favor of the PR.
