### ISSUE TITLE
Function with multi-clause style collapses awkwardly with single clause

### ISSUE THREAD

**Issue by chrismccord** [elixir-lang/elixir#7718]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.6.0
* Operating system: OSX 10.13.4

### Current behavior

I've found functions with multi-clause style collapses awkwardly when a single clause is used. Given the following code block:

```elixir
SomeModule.long_function_name_that_approaches_max_columns(argument, acc, fn
  %SomeStruct{key: key}, acc -> more_code(key, acc)
end)
```

The formatter produces:

```elixir
SomeModule.long_function_name_that_approaches_max_columns(argument, acc, fn %SomeStruct{
                                                                              key: key
                                                                            },
                                                                            acc ->
  more_code(key, acc)
end)
```

### Expected behavior

The formatter does not change the original code. I realize using the multi-clause style could be "cheating" in this case, but if you add a second clause, the formatter does not change the code, and the formatted code in this case is very awkwardly styled. Thanks for taking a look!

**Comment by josevalim** [comment]
This should be a straight-forward change. Either we are only checking for newlines if you have more than two clauses or the newline checking is only between clauses, which means it won't work here.

**Comment by Sihui** [comment]
@chrismccord 
>  if you add a second clause, the formatter does not change the code

Can you provide an example? 

For my formatted result is a bit different than yours (but still awkard)

```elixir
# Ex 1
# Original
SomeModule.long_function_name_that_approaches_max_columns(argument, acc, fn
   %SomeStruct{key: key}, acc -> more_code(key, acc)
 end)
# Formatted
SomeModule.long_function_name_that_approaches_max_columns(argument, acc, fn %SomeStruct{key: key},
                                                                            acc ->
  more_code(key, acc)
end)

# Ex 2
# Original
SomeModule.long_function_name_that_approaches_max_columns(argument, acc, fn
  %SomeStruct{key: key}, %SomeStruct{key: key}, acc -> more_code(key, acc)
end)
# Formatted
SomeModule.long_function_name_that_approaches_max_columns(argument, acc, fn %SomeStruct{key: key},
                                                                            %SomeStruct{key: key},
                                                                            acc ->
  more_code(key, acc)
end)
```

**Comment by josevalim** [comment]
@Sihui I believe he meant:

```
SomeModule.long_function_name_that_approaches_max_columns(argument, acc, fn
   %SomeStruct{key: key}, acc -> more_code(key, acc)
   %AnotherStruct{key: key}, acc -> more_code(key, acc)
 end)
```

**Comment by Sihui** [comment]
Thanks, @josevalim.

I took a look. Seems like to some extends, that's actually what we intended.

The place that does that is [Code.formatter#anon_fun_to_algebra](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/code/formatter.ex?utf8=%E2%9C%93#L1622):
```elixir
  # fn x -> y end
  # fn x ->
  #   y
  # end
  defp anon_fun_to_algebra([{:->, meta, [args, body]}] = clauses, _min_line, max_line, state) do
```

So if the `anon_fun` can be fit in one line, we will. If not, we break it into multiple lines in this fashion:

```elixir
fn x ->
   y
end

fn a,
   b,
   c ->
   y
end
```

It becomes awkward when the string before `fn` is long, like this:
```elixir
SomeModule.long_function_name_that_approaches_max_columns(argument, acc,  fn a,
                                                                             b,
                                                                             c ->
   y
end
```

The reason multi-clasues funs being formatted differently is because we have [a different method](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/code/formatter.ex?utf8=%E2%9C%93#L1652) handing that case. 
```elixir
  # fn
  #   args1 ->
  #     block1
  #   args2 ->
  #     block2
  # end
  defp anon_fun_to_algebra(clauses, min_line, max_line, state) do
    {clauses_doc, state} = clauses_to_algebra(clauses, min_line, max_line, state)
    {"fn" |> line(clauses_doc) |> nest(2) |> line("end") |> force_unfit(), state}
  end
```

So in the case of multi-clasue fun, I don't think we are checking user-inputted new lines. We just always put the clauses in a new line.

It would be great if there's a way to check if `fn` is followed by a new line (i.e. `fn\n`) in here. Then we can just do the same thing we do for multi-clasues funs. Unfortunately, I don't see a way to check for `fn\n` in here. Thought?

**Comment by josevalim** [comment]
Hi @Sihui, great analysis. In order to know if `fn` is followed by newlines, we need to [change the parser here](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_parser.yrl#L308).

In that line, you can see the parsing rule that handles `fn` followed by an eoe (end of expression). You should change that line to call annotate_newlines, similar to what we do [here](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_parser.yrl#L320), so we have something like:

    fn_eoe -> 'fn' eoe : annotate_newlines('$2', '$1').

The '$1' syntax means you will pass the first token on the right hand side of `->` and '$2' the second token and so on.

If you do so, you can run `make erlang` and now in the formatter, where we match on `{:fn, meta, _}`, you should have a `:newlines` key inside the `meta`. But remember this field is not always present, so you need to specify a default of 0: `Keyword.get(meta, :newlines, 0)`. Then you need to pass this newline information through the formatter and change the formatting rules accordingly.

**Comment by josevalim** [comment]
You are correct. I am not sure how to move this forward then, I would also need to sit down and try some different approaches, and I won't have the time to do it right now. Sorry.

**Comment by Sihui** [comment]
No worries. I might take another look during the weekend and see if I can come up with something. The `elixir_parser.yrl` is a pretty good read anyway.  :)
