### ISSUE TITLE
File.stream!(path, [], :line) badly handles encodings other than utf8

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#7729]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 20 [erts-9.3.1] Elixir 1.6.5
* Operating system: OSX

### Current behavior

If I understand it correctly, `File.stream!(path, [], :line)` uses `:binary.compile_pattern("\n")` to split file into lines. When the file is encoded in utf16 or utf32 (be or le), this results in ether incomplete or invalid binaries. In case of be encoding this sort of works, e.g. `:unicode.characters_to_binary(string, {:utf16, :big}` returns more or less properly decoded line (often with unnecessary '\n' at the end). The le encoding results in completely wrong lines as the bytes are not aligned properly. `:unicode.characters_to_binary(string, {:utf16, :little}` returns either `{:incomplete, sth, "\n"}` or sth where sth is totally badly decoded string.

### Expected behavior

I'm not sure what is expected here. This function handles BOM markers for utf16 and utf32. It implies that it should be able to properly read such files. Another question is if it should preserve encoding or convert read lines to utf8 binaries.
 If on the other hand this is a by design limitation the it should be documented.

**Comment by michalmuskala** [comment]
For working with encodings other than utf8 an explicit encoding option has to be provided - the default encoding is assumed to be utf8. Something like this should work properly:

```elixir
File.stream!(path, [:utf16], :line)
```

**Comment by josevalim** [comment]
@lukaszsamson besides what @michalmuskala said, do you have a stacktrace or something that shows the error you are getting? We only use the compile pattern for counting lines and that, on its own, should not raise any error, only return an incorrect count. So if you can tell us more about how you are triggering this issue, it will be helpful.

In any case, If you think a documentation PR on how to work with utf16/utf32 files or utf16/utf32 streams will be helpful, then it is definitely appreciated.

@michalmuskala although I think our count lines is broken for utf16/utf32. We will return more lines than we should if we have any other 0xA0 byte.

**Comment by lukaszsamson** [comment]
@michalmuskala it's `File.stream!(path, [encoding: {:utf16, :big}], :line)` and it works fine. However I don't know the file encoding upfront hence I don't force encoding. `:trim_bom` properly detects and removes BOM. The problem is that it detects utf16 or utf32 BOM and then continues to read lines in utf8 mode. The proper behaviour wold be to call `:io.setopts/2` and switch to encoding indicated by BOM.

**Comment by josevalim** [comment]
@lukaszsamson the problem with relying on bom is that bom is not always present and I don't think stream should be responsible for detecting the encoding. Therefore I think it is best if you do an initial file read to figure out the encoding and then pass it as an option.

**Comment by lukaszsamson** [comment]
@josevalim Sure we cannot rely on BOM always being present. But if it is present, then IMO it should work out of the box. And it definitely should not crash when setting encoding and `:trim_bom`.

**Comment by josevalim** [comment]
@lukaszsamson since relying on BOM is a limited behaviour, I don't think we should instruct users to rely on it, because it will eventually break. The responsibility of figuring out the encoding belongs elsewhere, not in the `File` module.

However, if you specify the correct encoding, then it should in no situation fail, regardless of trim_bom, so we can agree there. Can you please send a PR that fixes the `File.stream!("./utf16_be.txt", [{:encoding, {:utf16, :big}}, :trim_bom])` behaviour? In case you can't work on a fix ,a PR that adds those tests will already be very helpful, thank you!

**Comment by lukaszsamson** [comment]
@josevalim That's what IME text editors and browsers do (at least recent ones).
I don't how to fix it really without big changes. I tries adding `io:setopts/2` call with detected encoding after `trim_bom` like suggested in [file:open/2](http://erlang.org/doc/man/file.html#open-2) but it fails in
```
     ** (FunctionClauseError) no function clause matching in :io.request/2

     The following arguments were given to :io.request/2:
     
         # 1
         {:file_descriptor, :prim_file, {#Port<0.16434>, 45}}
     
         # 2
         {:setopts, [encoding: {:utf16, :little}]}
```
Regarding the crash with `{:error, :terminated}`, it seems that passing encoding option to `File.stream!` opens the file in character mode, but `trim_bom` function tries to read it as raw binary.

**Comment by josevalim** [comment]
Yes, browsers, text editors, web applications do that, and you should too, but it is not behind a single function in a low-level API.

Regarding the solution, I don't think we should set the encoding after we open the file, exactly because we don't have an IO device. We need to be able to read and trim the BOM in the encoding that has been specified.

**Comment by OvermindDL1** [comment]
> We need to be able to read and trim the BOM in the encoding that has been specified.

Aren't all the BOM's designed to be invalid bytes in the wrong encodings though?

But still, I'm not a fan of BOM's personally, but I do think there should be a way to change the read/write encoding after a file has been opened, it is entirely feasible that the encoding mode could change over a file in some custom formats and it would be easier to change it as appropriately rather than read in a potentially massive file entirely into memory first.

I could see the merit in having a detect_bom option with a fallback to something else the user specifies as well though, much as I dislike BOM's and think the UTF16/UTF32 encodings are poor designs, windows is indeed a broken OS and uses them often...  PR's welcome I'd guess?  ^.^;

**Comment by josevalim** [comment]
Ping.

**Comment by josevalim** [comment]
> Can you please send a PR that fixes the File.stream!("./utf16_be.txt", [{:encoding, {:utf16, :big}}, :trim_bom]) behaviour?

Ping. :)

**Comment by lukaszsamson** [comment]
Yes. I’ll try to do it today.

**Comment by josevalim** [comment]
Hi @lukaszsamson,  actually, no worries. We want to release v1.7.0-rc today or tomorrow so I will go ahead and fix this. Sorry for the unnecessary ping.

**Comment by josevalim** [comment]
So this was not an issue with UTF16 but rather with any encoding. trim_bom was only working for raw files (without encoding) and we have fixed it so it works with all encodings. Thanks for the report @lukaszsamson!

**Comment by lukaszsamson** [comment]
Your commit breaks utf16 read tests from https://github.com/elixir-lang/elixir/pull/7881
```
  1) test trim BOM via option UTF16 BE (FileTest)
     lib/elixir/test/elixir/file_test.exs:2042
     Assertion with == failed
     code:  assert ["Русский\n"] == bom_line
     left:  ["Русский\n"]
     right: [" 䌄䄄䄄㨄㠄㤀੥"]
     stacktrace:
       lib/elixir/test/elixir/file_test.exs:2050: (test)

  2) test trim BOM via option UTF16 LE (FileTest)
     lib/elixir/test/elixir/file_test.exs:2053
     Assertion with == failed
     code:  assert ["Русский\n"] == bom_line
     left:  ["Русский\n"]
     right: ["䌄䄄䄄㨄㠄㤄਄੥"]
     stacktrace:
       lib/elixir/test/elixir/file_test.exs:2061: (test)
```

**Comment by josevalim** [comment]
@lukaszsamson thanks, I will investigate!
