### ISSUE TITLE
[Formatter] Alignment of arguments and do clause in functions

### ISSUE THREAD

**Issue by stevedomin** [elixir-lang/elixir#7760]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.6.5
* Operating system: macOS

### Current behavior

Hello,

Apologies if this was already discussed but I couldn't find an issue for it.

I know the topic of formatting is highly subjective but I find that the alignment of function arguments and `do` to be hard to read when the function signature exceeds the maximum line length.

Take this function as an example:

```elixir
def do_something_complicated(first_argument, second_argument, third_long_argument, final_argument) do
  do_something()
  do_another_thing()
end
```

Currently, it's formatted like this:

```elixir
def do_something_complicated(
      first_argument,
      second_argument,
      third_long_argument,
      final_argument
    ) do
  do_something()
  do_another_thing()
end
```

It makes it harder to see where the body of the function actually starts. It's also inconsistent with what happens in tests (and with `with` clause wrapped in parenthesis):

```elixir
test "everything works", %{
  context_argument: context_argument   
} do
  assert true
end
```

### Expected behavior

What about having it like this:

```elixir
def do_something_complicated(
  first_argument,
  second_argument,
  third_long_argument,
  final_argument
) do
  do_something()
  do_another_thing()
end
```

**Comment by josevalim** [comment]
The behavior is not inconsistent with “test” and “with” because in the def
case there are two functions calls. One to “def” and another to the
function being defined. Therefore the inner function call should always be
indented according to “def”. If you write “with some_fun(...)” it would
behave like def. And if you add parens to def, then it will behave like
“with” using parens.

So the behavior today is quite consistent and we have no plans to change
it. :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by stevedomin** [comment]
Thanks for the response @josevalim. Makes sense.

I'm using parens everywhere with `with`, now I remember why I added them :)
