### ISSUE TITLE
mix deps.update not updating to latest version

### ISSUE THREAD

**Issue by mmainz** [elixir-lang/elixir#7800]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.6.6 (compiled with OTP 21)
* Operating system: Mac OS 10.13.5

### Current behavior

When I run `mix hex.outdated --all`, I get:
```
Dependency            Current  Latest  Update possible
amqp                  1.0.0    1.0.3   Yes
amqp_client           3.7.3    3.7.6   Yes
bunt                  0.2.0    0.2.0
connection            1.0.4    1.0.4
credo                 0.9.3    0.9.3
db_connection         1.1.3    1.1.3
decimal               1.5.0    1.5.0
distillery            1.5.2    1.5.2
ecto                  2.2.10   2.2.10
exkonsument           3.2.0    3.2.0
goldrush              0.1.9    0.1.9
ink                   0.7.4    0.7.4
jsx                   2.8.2    2.9.0   No
lager                 3.5.1    3.6.3   No
meck                  0.8.10   0.8.10
mock                  0.3.1    0.3.1
poison                3.1.0    3.1.0
poolboy               1.5.1    1.5.1
postgrex              0.13.5   0.13.5
rabbit_common         3.7.3    3.7.6   No
ranch                 1.4.0    1.5.0   No
ranch_proxy_protocol  1.4.4    1.5.0   No
recon                 2.3.2    2.3.5   No

A green version in latest means you have the latest version of a given package. Update possible indicates if your current requirement matches the latest version.
Run `mix hex.outdated APP` to see requirements for a specific dependency.
```

Then I run `mix deps.update --all`, and I get:
```
Resolving Hex dependencies...
Dependency resolution completed:
  amqp 1.0.0
  amqp_client 3.7.3
  bunt 0.2.0
  connection 1.0.4
  credo 0.9.3
  db_connection 1.1.3
  decimal 1.5.0
  distillery 1.5.2
  ecto 2.2.10
  exkonsument 3.2.0
  goldrush 0.1.9
  ink 0.7.4
  jsx 2.8.2
  lager 3.5.1
  meck 0.8.10
  mock 0.3.1
  poison 3.1.0
  poolboy 1.5.1
  postgrex 0.13.5
  rabbit_common 3.7.3
  ranch 1.4.0
  ranch_proxy_protocol 1.4.4
  recon 2.3.2
```

### Expected behavior

I would expect from the documentation of `mix deps.update` that `amqp` and `amqp_client` are updated to their latest versions.

I'm not sure whether this is a bug or whether I just don't understand how this is supposed to work. Or maybe there is a reason why those dependencies aren't updated to their latest versions? But even then I'd expect to at least have feedback or documentation that tells me why that is, because right now this really just looks like a bug to me.

**Comment by ericmj** [comment]
What is likely happening is that other dependencies are imposing version constraints on `amqp` and `amqp_client` when they are updated. Currently `mix hex.outdated` only looks at the version requirements available to it from the mix.lock, it doesn't run a full resolution pass over every dependency to determine if it is possible to update, so it may have false positives in rare cases. Additionally, even if you run a full resolver pass for each dependency, it is impossible to know if an update is possible unless you update a specific dependency with `mix deps.update amqp`, since `--all` unlocks all dependencies it changes the input to the resolver.

Please open this issue on https://github.com/hexpm/hex and include a project that reproduces the issue and we can investigate in more detail.

**Comment by mmainz** [comment]
I think I just found the issue. Just rerunning `mix local.hex` fixed this 🤦‍♂️
Maybe hex should be checking for a newer version every now and then?

**Comment by ericmj** [comment]
It does check once a day and should print a message in yellow that a new version is available. What version were you using before?

**Comment by mmainz** [comment]
It updated from 0.17.3 to 0.17.7. When does it print the message? During operations like `mix deps.get`?
