### ISSUE TITLE
Support for R21 E:R:S in catch

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#7854]
Will support be coming for getting the stack trace in the catch clause?

Currently on erlang r21 this works:
```
try 1/0 catch E:R:S -> S end.
```

But on erlang R21, elixir 1.6.6 this results in compile error:

```
try do 1/0 catch e,r,s -> s end
```

**Comment by michalmuskala** [comment]
Elixir will introduce a `__STACKTRACE__` special pseudo-variable inside the `catch` and `rescue` clauses of `try` that will translate to either the new catch syntax when compiled on Erlang versions with support for those or to old `erlang:get_stracktrace` calls otherwise. Three-argument `catch` won't be supported directly.

More information on this is available in the [Changelog.md](https://github.com/elixir-lang/elixir/blob/8847bc7a9e39798e7aa74a4e199de75fccef055e/CHANGELOG.md#the-__stacktrace__-construct).
