### ISSUE TITLE
Code.get_docs/2 breaking change (1.7)

### ISSUE THREAD

**Issue by teamon** [elixir-lang/elixir#7902]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.7.0-rc0
* Operating system: macos, linux

### Current behavior

Tesla has an option to include/exclude docs for generated functions and we have a test for it: https://github.com/teamon/tesla/blob/master/test/tesla/builder_test.exs#L146. 
When running on elixir 1.7, `Code.get_docs/2` returns `nil` which breaks the test.
I replaced it with `Code.fetch_docs/1` and it passes, but this function is only available since 1.7 so this time the test is broken on earlier elixir versions.

- Test with `Code.get_docs/2` => https://travis-ci.org/teamon/tesla/builds/403879400
- Test with `Code.fetch_docs/1` => https://travis-ci.org/teamon/tesla/builds/403881389

### Expected behavior

I know release notes state:

> To access the new documentation, developers should use Code.fetch_docs/1. The old documentation format is no longer available and the old Code.get_docs/1 function will return nil accordingly.

but since this is elixir 1.7 and not 2.0, shouldn't `Code.get_docs/2` still work as it was in 1.6 and earlier?

(I can work around this with a fallback since this is only a test code)

**Comment by josevalim** [comment]
Hi @teamon! 

We do not consider it a breaking change because `Code.get_docs/2` still returns `nil`, which has always been possible, and an effective part of the contract. For example, in the past, you would get `nil` if the module was not written to disk or if the module was not compiled with docs. Now that the old format is no longer available, we continue return `nil` to signal that.

We do understand that in your code, where you were interested in a single scenario, so you could rule out the `nil` case. But all applications that were accessing `Code.get_docs/2` programmatically had to take `nil` into account and that has not changed.

Thanks for trying the rc!

**Comment by josevalim** [comment]
@teamon maybe a better check is `function_exported?(Code, :fetch_docs, 1)` as you don't hardcode any Elixir specific string.

**Comment by teamon** [comment]
Makes sense, thanks! 

(for reference: https://github.com/teamon/tesla/commit/6f87a3492efbb3a7b65a57f402b016d76fa0b4a6 )
