### ISSUE TITLE
Integer.parse/2 raises FunctionClauseError on count_digits/2 when given nil

### ISSUE THREAD

**Issue by CaldwellYSR** [elixir-lang/elixir#7984]
### Current behavior
`Integer.parse(nil)`

** (FunctionClauseError) no function clause matching in `Integer.count_digits/2`

### Expected behavior

Return `:error` so we can pattern match on it instead of crashing.

**Comment by NobbZ** [comment]
Passing `nil` to it is violating the contract, so raising is fine I think.

**Comment by josevalim** [comment]
@CaldwellYSR you should check for nil then. Create a function called `parse_integer_or_nil` that handles it for you.

The `:error` tuple is only about error in parsing for valid values. For example, if I pass an integer to `File.read`, I want it to fail, because that's a logical error. I don't want it to say badarg.

**Comment by OvermindDL1** [comment]
@CaldwellYSR For note, you really should be using dialyzer (like via the Dialyxir plugin on hex.pm makes it super easy) as it would have caught such typing issues unless your specs are incorrect yourself.  It is highly recommended to use.
