### ISSUE TITLE
Strange try/catch behaviour

### ISSUE THREAD

**Issue by elridion** [elixir-lang/elixir#8078]
### Environment
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]
Elixir 1.7.0 (compiled with Erlang/OTP 20)

Linux version 4.15.0-30-generic (buildd@lgw01-amd64-060) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3))
### Current behavior
After switching to elixir 1.7 some some test in our ExUnit cases no longer compiled.
An easy reproduction is:
```elixir
ExUnit.start()

defmodule AssertionTest do
  use ExUnit.Case, async: true

  test "the truth" do
    try do
      raise "error"
      false
    rescue
      _ -> true
    end
    |> assert
  end
end
```
i yields an `** (CompileError) ... : unhandled operator ->` error.

Strange thing is inserting an `IO.inspect` in between fixes it.
```elixir
ExUnit.start()

defmodule AssertionTest do
  use ExUnit.Case, async: true

  test "the truth" do
    try do
      raise "error"
      false
    rescue
      _ -> true
    end
    |> IO.inspect()
    |> assert
  end
end
```

### Expected behavior
After consulting the ExUnit docs I`m aware that there are assertions especially for cases in which an Exception is expected.

Still the code example resulting in an error should work since its syntactically correct, especially considering that the `IO.inspect` should not make any difference.

**Comment by fertapric** [comment]
I think I fixed this on https://github.com/elixir-lang/elixir/pull/8079. It seems `:elixir_import.special_form('try', 1)` was returning `false`.

As a side note, it seems the code rendered in the error message is not correct:

```elixir
assert try() do
             raise("foo")
             true
           rescue
             _ ->
               false
           end
```

it seems `assert` should be `assert(try ...)` in this case to avoid `the function "assert" cannot handle clauses with the -> operator because it is not macro. Please make sure you are invoking the proper name and that it is a macro`; and `try() do` would raise `missing :catch/:rescue/:after/:else option in "try"`. This is probably not a big issue, but I thought it might be good to improve the `ExUnit.Formatter` for such cases. Should I open an issue?

**Comment by josevalim** [comment]
> This is probably not a big issue, but I thought it might be good to improve the ExUnit.Formatter for such cases. Should I open an issue?

Yes, please!
