### ISSUE TITLE
Linking priv dir in path deps causes issues with generated assets

### ISSUE THREAD

**Issue by ConnorRigby** [elixir-lang/elixir#8160]
### Environment
`elixir --version`:
```
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.6.6 (compiled with OTP 21)
```
`uname --all`:
```
Linux connor-laptop 4.18.4-arch1-1-ARCH #1 SMP PREEMPT Wed Aug 22 07:33:26 UTC 2018 x86_64 GNU/Linux
```

### Current behavior

I don't know where this issue _should_ be filed. If it is decided this can be moved elsewhere, or it is a won'tfix issue please let me know.

If make two new projects, one relying on the other via `path: ` in `mix.exs`, instead of copying all the `priv` data, it is symlinked. I'd assume this is to prevent extra copying things like web assets etc. Issue comes with things like `nif` libraries that are usually stored in the `priv` directory. If you have something that modifies the `compile` step of that `nif` (or port or whatever), it doesn't get recompiled. 

I've made a small project demonstrating this [here](https://github.com/ConnorRigby/elixir-compile-bug)

The main use case for this is in a Nerves project `nif`s and `port`s need to be crosscompiled. (compiled on your host machine to target a different architecture, ie host is x86_64, target is ARM)

When using a `path` dependency, (such as a Phoenix app) from your Nerves app, it will not recompile any of the assets in `priv`, but instead just link them in.  

### Possible solutions

I think the current behavior is fine in most use cases, but in some cases it might be nice to have an option to not link. in the dependency tuple.

**Comment by josevalim** [comment]
Thanks @ConnorRigby!

> Issue comes with things like nif libraries that are usually stored in the priv directory. If you have something that modifies the compile step of that nif (or port or whatever), it doesn't get recompiled.

Just to clarify, why is that? What are you using to clarify those dependencies? Is it because we are using a symlink and what you are using does not follow them?

Btw, you can set `build_embedded: true` in parent/root/main project `mix.exs`, inside `def project`, and then it should copy all assets and never symlink.

**Comment by ConnorRigby** [comment]
Ah i didn't know about `build_embedded`. That seems like the solution. I'll PR some doc updates to elixir-make.

> Just to clarify, why is that? What are you using to clarify those dependencies? Is it because we are using a symlink and what you are using does not follow them?

The symlinks are followed correctly. What is happening is a nif or port is compiled for x86_64. (your host machine) and then is copied to a Nerves device filesystem and it is unable to load due to the wrong architecture. 

As to why id doesn't get recompiled, that is a `make` feature/bug. [this](https://stackoverflow.com/questions/14840474/make-target-which-depends-on-an-environment-variable) question sort of explains it nicely. This issue could probably be fixed by implementing NIFs in that way, but it would require all NIFs and Ports etc to work this way

**Comment by josevalim** [comment]
@ConnorRigby could you change `make` to use `readlink` or something like that when listing the dependencies? Or would that be too complicated?

**Comment by ConnorRigby** [comment]
Well the problem is that it is of sub dependencies, not just dependencies I (or any other end user) use.

For example this is happening to users setting up Phoenix with Sqlite.Ecto2 which uses `esqlite3`, an Erlang/Rebar lib that doesn't even use `elixir-make`. If it hadn't been symlinked, it would have seen that there is no `_build/rpi3/dev/esqlite3/priv/nif.so` file, and build it. but since `_build/rpi3/dev/esqlite3/priv` is symlinked to `../custom_phoenix_app/_build/dev/esqlite3/priv`, `make` thinks that file has already been compiled even though it is now out of date.

**Comment by josevalim** [comment]
Oh, I see. Is `build_embedded` a satisfactory answer then?

**Comment by ConnorRigby** [comment]
Yep, we may just need to change the default on the new Nerves project generator. Feel free to close. Thanks again!

**Comment by fhunleth** [comment]
I just ran into this same problem, but `build_embedded: true` doesn't resolve the issue. I don't think that it ever did.

Here's an example project that demonstrates the issue: https://github.com/fhunleth/test_build_embedded. 

The problem is that the C compilation always happens in the same directory, the source directory. `build_embedded` causes the build products to be copied into the appropriate directories under `_build`, but it does that after compilation. That's too late. 

A few ideas on fixes:
1. `Makefile`'s always rebuild everything. 
2. Pass "build" and "install" paths into the `Makefile`. Update the `Makefile` to use them.
3. Copy/symlink path dependencies under `deps` and compile them there. 

The first one could be done by changing `elixir_make` to run `make clean all` to build. I'm not super excited about this.

The second one requires libraries that have C code to be updated to use the paths.

I have the feeling that the third one could be confusing since you wouldn't want to copy all files over blindly. 

Maybe there's another option?
