### ISSUE TITLE
Is this a bug? [H | T]

### ISSUE THREAD

**Issue by chenge** [elixir-lang/elixir#8166]
result is [H | T] in iex no error. Elixir 1.6

I think it should give a error.

Thanks.

**Comment by kipcole9** [comment]
Perhaps I'm being too pedantic but given you have to actually *delete* the issue template in order to enter your message and the template is pretty clear about what the issue tracker is for I wonder why you continue to raise issues against the community guidelines?  José was really patient the last couple of times.  The [Elixir Forum](https://elixirforum.com) and Elixir Slack are great places for peer-to-peer discussion.

In the simple case you raise any number of people in both places would have noted that:

1. In Elixir, `H` and `T` are atoms
2. and therefore `[H | T]` is valid

You can get information on any term in `iex` by using the helper `I`

```
Interactive Elixir (1.7.3) - press Ctrl+C to exit (type h() ENTER for help)
iex> i H
Term
  H
Data type
  Atom
Raw representation
  :"Elixir.H"
Reference modules
  Atom
Implemented protocols
  IEx.Info, Inspect, String.Chars, List.Chars
```

Please would you consider playing nicely within the community guidelines?

**Comment by josevalim** [comment]
@chenge as @kipcole9 said, please use the forum and similar for questions. If it is an actual bug, I am certain the community will help you build an adequate bug report too.

Thanks @kipcole9!

**Comment by chenge** [comment]
@kipcole9 Sorry，I didn't note the guide and rules. I know now, and thanks for your telling.

@Jose, I'll goto the forum. Thanks for your great Elixir, it brings back fun of programming. Hope to have chance to see you in China.
