### ISSUE TITLE
inconsistent unquote behaviour using the pipe operator

### ISSUE THREAD

**Issue by hylkealons** [elixir-lang/elixir#8331]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 21 [erts-10.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
```
* Operating system: MacOS Mojave

### Current behaviour

This code fails (using ExUnit):
```elixir
@methods ~w(....)
  Enum.each(@methods, fn method_name ->
    test "#{method_name} calls adapter with the right args" do
      method =  method_name |> unquote() |> String.to_atom()
      #( ... )
    end
  end)
```
 
with the error: 
```
** (CompileError) (..file...): unquote called outside quote
    (elixir) expanding macro: Kernel.|>/2
 (..file..): MyTest."test count calls adapter with the right args"/1
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/parallel_compiler.ex:209: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

While this works:
```elixir
@methods ~w(....)
  Enum.each(@methods, fn method_name ->
    test "#{method_name} calls adapter with the right args" do
      function = unquote(function_name) |> String.to_atom()
      #( ... )
    end
  end)
```
 
### Expected behavior

I would expect the pipe operator to work for unquote without throwing the exception

**Comment by josevalim** [comment]
The reason why this does not work (and it cannot work) is because the `unquote` is expanded BEFORE the pipe operator. That's because unquote is used to be the AST itself. Macros, such as the pipe operator, are evaluated only after the AST is built.

However, I think we can probably improve the error message and make `|>` explicitly raise something more meaningful if you are attempting to pipe into unquote.

Good find!
