### ISSUE TITLE
Remove ":" from stacktrace output

### ISSUE THREAD

**Issue by DenisGorbachev** [elixir-lang/elixir#8333]
### Environment

* Erlang/OTP 20 [erts-9.3.3.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
* Elixir 1.7.2 (compiled with Erlang/OTP 20)
* Linux Mint 17.3 Rosa

### Current behavior

On error, a stacktrace is displayed:

```
     stacktrace:
       (elixir) lib/gen_server.ex:924: GenServer.call/3
       test/leverex/loans/loan_server_test.exs:193: (test)
```

### Expected behavior

Same stacktrace, but without colons (":")

```
     stacktrace:
       (elixir) lib/gen_server.ex:924 GenServer.call/3
       test/leverex/loans/loan_server_test.exs:193 (test)
```

### Rationale

When a single test fails, I copy the last line from stacktrace and re-run the test with `mix test.watch {filename}`. Currently, I have to remove the ":" manually, which is a slight annoyance, but it add up over time.

**Comment by josevalim** [comment]
Hi @DenisGorbachev!

Since the stacktrace is unified in Elixir, it means changing it here, requires changing it everywhere else, which makes it a much larger discussion. For example, it means all books and materials will now show slightly different stackraces.

For this reason, I want to be really be sure this is the way to go. Therefore, can you please send an e-mail to the mailing list to start this discussion? If you can provide examples of stacktraces in other languages for reference, that would be even better.

Thanks!
