### ISSUE TITLE
Function `__info__/1` is referenced in the docs but not documented

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#8376]
### Environment

* Elixir 1.7.3 

### Current behavior

Function `__info__/1` is referenced in the [Module](https://hexdocs.pm/elixir/Module.html) docs but it is not documented.

### Expected behavior

Provide documentation for the `__info__/1` function, or a link to somewhere it is documented.

**Comment by mguimas** [comment]
Probably it is worthwhile to also document that every module has a `module_info/0,1` function too, and describe how it is different from `__info__/1`.

**Comment by mguimas** [comment]
Unfortunately I do not know about BEAM chunks, nevertheless the documentation for `__info__/1` should somehow appear in the docs. Thanks.

**Comment by mguimas** [comment]
I even think that the documentation for all exported symbols in a module, whether generated or not, should appear in the docs.

The idea is: if something in a module is callable from the outside then it should be documented. 

Thanks.

**Comment by michalmuskala** [comment]
The documentation of the module, in general, documents the public API for consumers to use, there might be a lot of functions that are callable and that are not documented (done by using `@doc false`). `__info__/1`, `module_info/0,1` and `behaviour_info/1` are sort of a metadata and I don't think documenting them on every single module would be useful - they would be just noise in the documentation and would be distracting instead of helpful. If you read the documentation once, it would never change. Furthermore, the return value of some of the callbacks (`module_info` in particular) depends on the VM you're running the code on and differs between OTP releases, so it's difficult to document it in a uniform way.

We should definitely document somewhere that those "default functions" exist and maybe what they do (probably in the `Module` module), but I don't think doing anything more would be helpful.

**Comment by josevalim** [comment]
@michalmuskala I am thinking that, because `__info__/1` is actually callable, we should go ahead and add it to the chunk as well, so it appears as `__info__`. FWIW, this was used to happen, but it probably got lost at some point.

**Comment by michalmuskala** [comment]
One option could be to document all those functions as callbacks in the `Module` module, then we could link them nicely.

**Comment by eksperimental** [comment]
> @michalmuskala I am thinking that, because `__info__/1` is actually callable, we should go ahead and add it to the chunk as well, so it appears as `__info__`. FWIW, this was used to happen, but it probably got lost at some point.

Yes, I remember reading about it.
It got lost in v1.7 probably with the new fetch_docs function
