### ISSUE TITLE
Unable to escape inline code ending in backslash and render it properly with IEx and ExDoc

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8382]
#8373 introduced a change in the IEx module.

```diff
-    * by hitting `Ctrl+\ `
+    * by hitting `Ctrl+\`
```

It removes a spaces before closing the backtick,
It is partially fixed by adding a space after the backslash as it originally was. The problem with this approach is that IEx understands that we are escaping a whitespace, and it shows
"• by hitting Ctrl+"

the solution is to write the documentation as: 
```
    * by hitting `Ctrl+\\\ `
```
which renders nicely in IEx, but in the HTML generated by ExDoc, it looks like: 

```
by hitting Ctrl+\\\
```

I don't know if this is an issue with Earkmark, or it also happens with other engines, or if this should be fixed in IEx,
I haven't investigated further, but I prefer to share the issue and discuss it before investing time

**Comment by josevalim** [comment]
Great find @eksperimental!

It is an issue on the IO.ANSI.Docs tool in Elixir. I will move this issue to the Elixir repo. The backslash is never used for escaping of backticks, although it is used for the escape of `*`, `_` and others.

**Comment by eksperimental** [comment]
I would like to look into fixing this one. 
What Should we do then. allow the escaping?
CommonMark allows the escaping of punctuation but not the rest of the characters
https://spec.commonmark.org/0.28/#backslash-escapes

**Comment by josevalim** [comment]
Following common mark is good. I plan to fix the first part today, which is
to disable escaping inside code blocks, but a PR that handles escaping in
general is welcome.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Closing in favor of #8384.

**Comment by josevalim** [comment]
That's awesome @Hanspagh! I wouldn't necessarily open an issue, because it is rather exploratory and not strictly an issue with Elixir, but I want to make sure you get the support necessary. Therefore, what if we open up a thread on the forum and you copy me there? I would also copy @tmbb, they are probably interested too. Alternatively you can post your questions on nimble_parsec issues tracker. :)

**Comment by tmbb** [comment]
I'm not very interested actually...  Have you ever looked a the Markdown spec? It's extremely context-sensitive. NimbleParsec might help in implementing inline markup but that's a small component of a Markdown parser.

You'd need something else to assemble lines into blocks and stuff like that.

**Comment by eksperimental** [comment]
Make it a CommonMark parser, not just another MarkDown parser if possible

**Comment by josevalim** [comment]
@tmbb and @eksperimental, good points!

**Comment by tmbb** [comment]
The relevant section of the spec is [Appendix: A parsing strategy](https://spec.commonmark.org/0.28/#appendix-a-parsing-strategy).

The parsing strategy they suggest *can not* be implemented with NimbleParsec, because the parsing strategy is highly context-sensitive. I believe it might be possible to implement *part* of that as a context-insensitive grammar, but I'm not sure.

Parsing markdown seems like a job more suited to something like ExSpirit than NimbleParsec. But I can look into it again.

**Comment by OvermindDL1** [comment]
NimbleParsec really needs to be enhanced with context-sensitive/state functionality so I can finally deprecate ExSpirit.  ^.^
