### ISSUE TITLE
Compile errors when matching valid sigils

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#8434]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.4 (compiled with Erlang/OTP 21)

### Current behavior

```
iex(2)> a=~N[2017-05-02 20:49:29.000000]            
** (SyntaxError) iex:2: unexpected token: ":" (column 19, codepoint U+003A)
```
```
iex(8)> a=~r/hello/i      
** (CompileError) iex:8: undefined function a/0
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
```
`a =~...` fails as well 
### Expected behavior

The code above should work fine as in other cases operator `=` does not need to be followed by whitespace

**Comment by kipcole9** [comment]
I expect this is because you are not using the `=` operator, you are using the `=~` operator (since there is no whitespace).  `a= ~N[2017-05-02 20:49:29.000000]` returns the expected result.

**Comment by ericmj** [comment]
`=~` is an operator that will be parsed before `=~N[]`. Add spaces to fix the error.

**Comment by ericmj** [comment]
They are not inconsistent because there is no `===~` operator, but there is a `=~` operator. The tokenizer is greedy and will usually try to parse the longest token it can.

There are many other cases where whitespace affect parsing. Maybe it should be documented that whitespace can affect parsing and that tokenizer is greedy with a few examples, but I don't think documenting specially about operators or sigils is beneficial since this is a more general issue.
