### ISSUE TITLE
Ability to set custom owner for the Task

### ISSUE THREAD

**Issue by virtual-light** [elixir-lang/elixir#8484]
```
** (ArgumentError) task %Task{owner: #PID<0.681.0>, pid: #PID<0.726.0>, ref: #Reference<0.2348683121.524289.256702>} must be queried from the owner but was queried from #PID<0.724.0>
```

Just wondering, why such useful ability as passing task to another process (and awaiting from it) is missing in the language? Will elixir support this feature in further releases?

**Comment by josevalim** [comment]
The task is wired to send a message back to the owner and also linked to it. It is essential to how tasks behave. However, since tasks are just regular processes, you could implement your own abstraction that sends the message to whoever you want.

Btw, please ask questions on the elixirforum or the elixir-lang-core mailing list. :)
