### ISSUE TITLE
Application config gets overridden by umbrella config while testing

### ISSUE THREAD

**Issue by webdeb** [elixir-lang/elixir#8535]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.6.1
* Operating system: OSX

### Current behavior

when you run `mix test` inside an `apps/subapp` directory the upper umbrella configurations override 
the configs in `apps/subapp/config/test.exs` file.

### Expected behavior

When running `mix xyz` inside the `apps/subapp` only the actual configs for this app are applied, not the umbrella configs.

**Comment by josevalim** [comment]
This is completely up to your control. If you notice your `mix.exs`, you will see that it is actually loading the parent config application which then loads the children one. You can change it but we don't recommend you to. The reason is that umbrella children were meant to run together (and they always run together if you run from the root), so if you start diverging their configurations, it may mean that tests pass from the root but not from the inside the app directory (or vice-versa). If you feel like those apps are diverging, then maybe it is better to break those applications apart.

**Comment by webdeb** [comment]
Hi José, 

> then maybe it is better to break those applications apart.

this is funny, because initially I thought I am doing exactly this, with the umbrella pattern.
Now I've realized, thats not the case.
https://elixir-lang.org/getting-started/mix-otp/dependencies-and-umbrella-projects.html

But it makes further "apart-breaking" easier.

Thanks!

**Comment by josevalim** [comment]
Yes, precisely. Umbrellas are "what if i break them apart but manage them together". The next step is to manage them separately too.
