### ISSUE TITLE
broken links in syntax reference doc

### ISSUE THREAD

**Issue by rogpeppe** [elixir-lang/elixir#8723]
There are four references in [this page](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Syntax%20Reference.md) to a "Unicode Syntax" page [here](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/unicode-syntax.html), which doesn't seem to exist any more.

There's another broken link too: [Elixir's naming conventions](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/naming-conventions.html)

**Comment by wojtekmach** [comment]
The link is broken on GitHub as pages are markdown files, not html files, and not sure if it can change. These pages are meant to be rendered using ExDoc and they work: https://hexdocs.pm/elixir/1.8.0/syntax-reference.html#atoms

**Comment by wojtekmach** [comment]
Does the link I pasted above not work for you?

**Comment by rogpeppe** [comment]
Oh, my bad - I skimmed the link and thought it was about ExDoc, not the syntax reference itself.
Thanks!

Perhaps it might be nice if there was a link to that hexdocs.pm hierarchy from somewhere obvious on elixir-lang.org - the language reference being quite an important aspect of the language.

**Comment by wojtekmach** [comment]
We link from https://elixir-lang.org/docs.html to hexdocs so I believe the syntax reference page is relatively easy to find. Do you have a  suggestion how to make it easier if needed?

**Comment by josevalim** [comment]
We do link to our docs here: https://elixir-lang.org/docs.html (in the top menu) but then you need to figure out that this information is in "Pages". We could make this information more available in the docs page but this is not a straight-forward problem to solve because then a lot of people who are new to the language may end-up jumping to those references early on and  that may not be the best  way for them to learn the language. So we tend to focus on putting the things that are relevant to everyone first and those who want in depth resources have to dig a bit deeper (in this case, it is clicking on one link called "Pages"). Maybe that's the issue, "Pages" could have a better name.

In any case, I believe the original issue here has been "addressed". Thanks!

**Comment by rogpeppe** [comment]
I'll just say that I looked quite hard for reference docs for the language and only found it (after several google searches) by browsing through the github markdown source. I would never have thought to click on the obscure "Pages" link.

I'd suggest having a link to "Reference documentation" from somewhere in the [docs page](https://elixir-lang.org/docs.html) with direct links to the various pages:

- Syntax reference
- Unicode Syntax
- Compatibility and Deprecations
- Guards
- Library Guidelines
- Naming Conventions
- Operators
- Typespecs
- Writing Documentation

> a lot of people who are new to the language may end-up jumping to those references early on and that may not be the best way for them to learn the language.

Conversely, for people who are experienced in programming languages and want to know what the rules actually are, it's very useful to be able to find the reference docs... :)

**Comment by josevalim** [comment]
> The singular form "Reference" would work better from my point of view.

@rogpeppe perfect.
