### ISSUE TITLE
Elixir compiler unexpectedly omits warnings

### ISSUE THREAD

**Issue by tim2CF** [elixir-lang/elixir#8810]
### Environment

* Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Operating system: macOS 10.14.3

### Current behavior

In some cases Elixir compiler unexpectedly omits warnings in case of macro usage. Example:

file `hello.ex`

```
defmodule Hello do
  defmacro world do
    quote location: :keep do
      defmodule World do
        def foo(bar), do: nil
      end
    end
  end
end
```

and then in file `world.ex`

```
import Hello
world()
```

then mix compile gives 0 warnings - in this simple example I expected warning for unused variable, but it probably omits other warnings as well.

### Expected behavior

Compiler should give warnings regarding source code generated by Elixir macros.

**Comment by josevalim** [comment]
Elixir does not emit many warnings from macros because macros often inject variables that may or may not be used (and therefore may or may not warn), provide definitions that may or may not be used, and so on. It is a explicit design decision because if we enable it, then applications will get tons and tons of warnings that cannot be fixed due to optional behaviour.

If you want to get warnings, then following macro best practices and reducing the amount of code that is generated inside the quote/unquote will provide the best benefits (i.e. keep the code inside quote minimum and always have it delegate to something else instead).

**Comment by tim2CF** [comment]
@josevalim but in some cases compiler emits warnings, for example for undefined modules:

```
defmodule Hello do
  defmacro world do
    quote location: :keep do
      defmodule World do
        def foo(bar), do: Notexist.func(bar)
      end
    end
  end
end
```

then 

```
Iljas-iMac:hello timcf$ mix compile
Compiling 2 files (.ex)
warning: function Notexist.func/1 is undefined (module Notexist is not available)
  lib/hello.ex:5
```

Is there any boundary when compiler emits warnings and where it does not?

**Comment by josevalim** [comment]
Yes, we do not emit many warnings, but some are still emitted. Usually warnings about unused  variables, unused definitions, never match clauses, and similar are discarded.

**Comment by tim2CF** [comment]
Does it make sense to have `quote do` option opposite to `:generated`, maybe something like `:strict` to force compiler to check generated `quote do` expression properly? In most cases compiler warnings can be very useful

**Comment by josevalim** [comment]
@tim2CF we could start emitting some warnings back and gradually push users to add generated (it is a relatively new addition).

However, variables are slightly trickier because we control when to emit warnings for variables based on their context. That's because if a macro attempts to define variables in the user context, then we want to warn for those variables too even if they come from macros:

```elixir
defmodule Hello do
  defmacro world do
    quote location: :keep do
      defmodule World do
        def foo(var!(bar)), do: nil
      end
    end
  end
end
```

**Comment by tim2CF** [comment]
Honestly I'm not big fan of `var!` expressions, because it makes code less predictable and more complex. 
But I like idea of `quote-unquote` expressions while compiler can validate generated code as normal code written manually
