### ISSUE TITLE
Got incomplete stacktrace with some code

### ISSUE THREAD

**Issue by tony612** [elixir-lang/elixir#8829]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Operating system: 
macOS 10.14.1

### Current behavior

```elixir
defmodule Foo do
  def foo() do
    ids = [1, 2, 3]
    bar(ids)
  end

  def bar(ids) do
    get_in([foo: 1], [123])
  end
end

Foo.foo
```
Got incomplete stacktrace when running this code:
```
$ mix run wrong_stack.exs
** (ArgumentError) the Access calls for keywords expect the key to be an atom, got: 123
    (elixir) lib/access.ex:343: Access.get/3
    (elixir) lib/code.ex:767: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:146: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
```

### Expected behavior

I expect to have stacktrace in `Foo.bar` in `wrong_stack.exs`.

Some of my friends guess the reason is tail recursive optimization. I added something to the end of `Foo.bar`, it works, like
```diff
defmodule Foo do
  # ...
  def bar(ids) do
    get_in([foo: 1], [123])
+    ""
  end
end
```

Hope this can be improved, which is very helpful. Thank you!

**Comment by josevalim** [comment]
This happens because of tail call optimization. Everytime the last entry in a function is a function call, the current stacktrace entry is replaced by the new one. This is extremely important for loops and recursion, which is why we don't plan to change this behaviour. Otherwise recursive and co-recursive functionis would eventually fill the stack. Thank you!
