### ISSUE TITLE
Reordering module definitions may result in different compiler messages

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#8836]
### Environment

$ elixir --version
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
### Current behavior

I am having here a situation where the same module is being defined in two `lib/**/*.ex` files. One of these files if very long (well as very as ~500 lines) and the other has 35 lines, all of code.

In the longer file if I put the duplicated module at the very begining I get a message

`** (CompileError) long_file.ex:1: cannot define module Duplicated because it is currently being defined in short_file.ex`

but if I put the definition at the end of `long_file` I get the message

`warning: redefining module Duplicated (current version loaded from ...)`

This behavior seems somewhat undesirable, and is possibly being caused by some kind of race condition that potentially may have some other unknown effects.

### Expected behavior

The expected behavior is to receive a `warning: redefining module ...` independently of the order in which modules are defined.

**Comment by mguimas** [comment]
This duplicate module issue does not happen when modules are defined serially inside the same file, in which case we get `warning: redefining module ...`

**Comment by mguimas** [comment]
A potential solution is to serialize the compilation of modules with the same name but in different files.

I do not know the implications of this, so I cannot help any further.

**Comment by josevalim** [comment]
The compiler works in parallel so this is bound to happen. It is likely that on a different computer, it may always fail or always raise a warning.

> A potential solution is to serialize the compilation of modules with the same name but in different files.

This cannot be done because the compiler does not know which module will be compiled. Remember, they can generated dynamically during compilation, at any time.

Therefore, this is a consequence of the parallel compiler and unfortunately there isn't anything we can do about it besides disabling parallel compilation, which would be a huge no-no.

**Comment by mguimas** [comment]
Yep, this

> Remember, they can generated dynamically during compilation, at any time.

blocks any attempt to fix the issue I believe.

Thanks
