### ISSUE TITLE
String.to_charlist(table_name <> record_id) can't work under List.flatten

### ISSUE THREAD

**Issue by shahryarjb** [elixir-lang/elixir#8868]
Hello, today I found a problem with `String.to_charlist(table_name <> record_id)` under `List.flatten`

first code that works:

```elixir
  def test1(table_name, record_id, _field_name) do
      [
        "HMSET",
        String.to_charlist(table_name <> record_id),
        ["name", "shahryar"]
      ]
  end
```
![screenshot 2019-03-08 at 7 58 26 pm](https://user-images.githubusercontent.com/8413604/54041289-903c6b00-41dc-11e9-9bcb-ddb77587ad35.png)

second code that doesn't work

```elixir
  def test(table_name, record_id, _field_name) do
    List.flatten(
      [
        "HMSET",
        String.to_charlist(table_name <> record_id)
      ], ["name", "shahryar"]
    )
  end
```
![screenshot 2019-03-08 at 7 57 43 pm](https://user-images.githubusercontent.com/8413604/54041253-79961400-41dc-11e9-8431-30520de4fa26.png)

why are those functions different? I couldn't found any doc about it.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): v1.8.0
* Operating system: mac os last version

Thanks

**Comment by whatyouhide** [comment]
You should not convert the string to a charlist, as a charlist is a list of integer codepoints but the API you're using (Redix?) requires strings. If you use `String.to_charlist/1` with flattening, it will expand the charlist (which again is a list of integer codepoints) to the integers themselves, and that's why that won't work either.
