### ISSUE TITLE
Should guards defined with defguard be able to be called as functions?

### ISSUE THREAD

**Issue by chriseyre2000** [elixir-lang/elixir#8871]
### Precheck

* Do not use the issues tracker for help or support (try Elixir Forum, Stack Overflow, IRC, etc.)
* For proposing a new feature, please start a discussion on the Elixir Core mailing list: https://groups.google.com/group/elixir-lang-core
* For bugs, do a quick search and make sure the bug has not yet been reported
* Please disclose security vulnerabilities privately at elixir-security@googlegroups.com
* Finally, be nice and have fun!

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
* Operating system: 

### Current behavior

Include code samples, errors and stacktraces if appropriate.

### Expected behavior

A short description on how you expect the code to behave.

**Comment by chriseyre2000** [comment]
defguardp can be used as a function but only after it has been defined in a module.

Is this intentional? Functions can be called before they are defined.

**Comment by whatyouhide** [comment]
Hey @chriseyre2000, that behavior is intentional since it is the behaviour used by macros in Elixir. If you want to use a macro in the same module where you define it, you have to define it physically before using it in the code. `defguard` ends up defining a normal macro so the behavior is the same.
