### ISSUE TITLE
File.touch/1 returns an error if the current user is not the owner, even tough permissions would allow it (touches file anyways if it doesn't exist)

### ISSUE THREAD

**Issue by Awlexus** [elixir-lang/elixir#8875]
### Environment
```bash
$ iex --version
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

IEx 1.8.1 (compiled with Erlang/OTP 21)
```
Arch Linux x86_64 4.20.13-arch1-1-ARCH

### Current behavior
```bash
not_root $ ll
total 13K
drwxrwxrwx 1 root root    0 Sep 21 20:10 _build
drwxrwxrwx 1 root root    0 Sep 21 20:06 config
drwxrwxrwx 1 root root 4.0K Feb  3 03:28 deps
drwxrwxrwx 1 root root    0 Feb  3 03:26 lib
drwxrwxrwx 1 root root    0 Sep 21 20:11 rel
drwxrwxrwx 1 root root    0 Sep 21 20:06 test
-rwxrwxrwx 1 root root  657 Feb  3 03:28 mix.exs
-rwxrwxrwx 1 root root 2.5K Feb  3 03:28 mix.lock
-rwxrwxrwx 1 root root  482 Sep 21 20:06 README.md
not_root $ i
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> File.touch "asdfasdf"
{:error, :eperm}
iex(2)>
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^C not_root $ ll
total 13K
drwxrwxrwx 1 root root    0 Sep 21 20:10 _build
drwxrwxrwx 1 root root    0 Sep 21 20:06 config
drwxrwxrwx 1 root root 4.0K Feb  3 03:28 deps
drwxrwxrwx 1 root root    0 Feb  3 03:26 lib
drwxrwxrwx 1 root root    0 Sep 21 20:11 rel
drwxrwxrwx 1 root root    0 Sep 21 20:06 test
-rwxrwxrwx 1 root root    0 Mar 10 21:20 asdfasdf
-rwxrwxrwx 1 root root  657 Feb  3 03:28 mix.exs
-rwxrwxrwx 1 root root 2.5K Feb  3 03:28 mix.lock
-rwxrwxrwx 1 root root  482 Sep 21 20:06 README.md
not_root $ i # Some time later
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> File.touch "asdfasdf"
{:error, :eperm}
iex(2)>
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^C not_root $ ll
total 13K
drwxrwxrwx 1 root root    0 Sep 21 20:10 _build
drwxrwxrwx 1 root root    0 Sep 21 20:06 config
drwxrwxrwx 1 root root 4.0K Feb  3 03:28 deps
drwxrwxrwx 1 root root    0 Feb  3 03:26 lib
drwxrwxrwx 1 root root    0 Sep 21 20:11 rel
drwxrwxrwx 1 root root    0 Sep 21 20:06 test
-rwxrwxrwx 1 root root    0 Mar 10 21:20 asdfasdf
-rwxrwxrwx 1 root root  657 Feb  3 03:28 mix.exs
-rwxrwxrwx 1 root root 2.5K Feb  3 03:28 mix.lock
-rwxrwxrwx 1 root root  482 Sep 21 20:06 README.md
not_root $ touch asdfasdf # To prove that it normally works
not_root $ ll
total 13K
drwxrwxrwx 1 root root    0 Sep 21 20:10 _build
drwxrwxrwx 1 root root    0 Sep 21 20:06 config
drwxrwxrwx 1 root root 4.0K Feb  3 03:28 deps
drwxrwxrwx 1 root root    0 Feb  3 03:26 lib
drwxrwxrwx 1 root root    0 Sep 21 20:11 rel
drwxrwxrwx 1 root root    0 Sep 21 20:06 test
-rwxrwxrwx 1 root root    0 Mar 10 21:26 asdfasdf
-rwxrwxrwx 1 root root  657 Feb  3 03:28 mix.exs
-rwxrwxrwx 1 root root 2.5K Feb  3 03:28 mix.lock
-rwxrwxrwx 1 root root  482 Sep 21 20:06 README.md
```
### Expected behavior
The File should both times be touched and return `:ok`

**Comment by josevalim** [comment]
Hi @Awlexus!

Unfortunately I cannot reproduce this. Do you have more precise steps? Here is what I tried:

    $ sudo mix new foo
    $ sudo chmod a+rxw foo
    $ iex
    > File.touch("foo")

And it works just fine (on MacOS).

You can also try this:

    :file.write("foo", "bar")

and see what it returns. If it returns eperm and writes the file, then it is most likely an Erlang issue rather than Elixir one.

**Comment by Awlexus** [comment]
I used a slightly different command for setting the permissions, but it returns the same error anyways
```bash
$ sudo mix new foo
$ sudo chmod 777 foo -R 
$ iex
> File.touch("foo")
** (File.Error) could not touch "foo": not owner
    (elixir) lib/file.ex:590: File.touch!/2
```

I tried running `:file.write("foo", "bar")`, but I'm not sure whether I was supposed to literally run that, because It returns `{:error, :badarg}`

**Comment by josevalim** [comment]
sorry, it is supposed to be :file.write_file("foo", "bar"). Can you please
give it another try?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Awlexus** [comment]
No problem writing the file
```elixir
> ls
.formatter.exs     .gitignore         README.md          config             lib
mix.exs            test
> :file.write_file "foo", "bar"
:ok
> ls
.formatter.exs     .gitignore         README.md          config             foo
lib                mix.exs            test
> File.read "foo"
{:ok, "bar"}
> File.touch! "."
** (File.Error) could not touch ".": not owner
    (elixir) lib/file.ex:590: File.touch!/2

```

**Comment by josevalim** [comment]
It seems to be an issue with changed the mtime then? Can we somehow have access to write the file but not to change its stats such as mtime?

**Comment by wanton7** [comment]
Is this related? https://unix.stackexchange.com/questions/64848/cannot-touch-m-a-writable-file

**Comment by josevalim** [comment]
Thanks @wanton7. That can potentially be the root cause. @Awlexus does the `touch -m` flag work for you?

**Comment by Awlexus** [comment]
Good catch.
No, the command fails with the same error message as seen in the question

**Comment by josevalim** [comment]
So the behavior is consistent. I think we should document it and call it a
day. Thanks everyone!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by blast-hardcheese** [comment]
👋 Please pardon the necro, but closing the loop for future internet historians

Since `File.touch/2` is used in [`lib/mix/lib/mix/compilers/elixir.ex`](https://github.com/elixir-lang/elixir/commit/093525855f8aac091975e633df14bdaf4bfc0502#diff-bc4b0dd25f31b7902a1ac08f97d4685e989a0d49bf4e3a56e4b4a01c7bf98538R412), the impacted platforms will be unable to run common tasks (in this case, I'm trying to debug a platform-specific bug where `mix test` cannot be run:

![image](https://github.com/user-attachments/assets/91046214-0378-46e0-a6f6-ef2d25444fce)

Since the relevant bits of the compiler have been in place for so long, it's likely not a burning fire to be fixed, but in case others end up here I wanted to close the loop.

**Comment by ericmj** [comment]
The point of `File.touch/1` is to update the mtime. If you only want to create a file there are other APIs for that.

In this case the compiler uses mtime for incremental compilation, without mtime we would always have to recompile the whole project including the dependencies, given that we ensure the project is compiled in many mix tasks this would not be feasible.

We could add an option to the compiler to use a different way to do incremental compilation that does not require mtime but that would be a major change. There are other places that would require changes for common Elixir workflows, for example fetching packages would require adding an option to `:erl_tar.extract/1` to not set the mtimes from the tarball. I am sure there are also other places where mtimes are required.

@blast-hardcheese Can you explain the use case for having privileges to write to a file but not change its mtime?

**Comment by blast-hardcheese** [comment]
@ericmj Thank you for the follow-up and explanation! I also see discussion in the other issue as well, so I'll cut to the chase. 

Unlike the above investigation where `touch -m` turned out to fail with a similar error, inside Replit's managed environment `touch -m` succeeds while,`File.touch/1` fails with the above error. This was my reason for commenting here, though I guess it could just as easily have been a new issue. 

I tried `strace mix test` but nothing jumped out, am I right in assuming I need to somehow instrument the underlying runtime? Any advice on how to get meaningful traces, or anything else we can try?
