### ISSUE TITLE
slack mods

### ISSUE THREAD

**Issue by natetech333** [elixir-lang/elixir#8931]
People on Slack are running an Elixir group and the moderators/admins are bullying people if anyone asks serious questions about Slack, privacy, policies, CoC's etc... I feel that your open source group needs to approve who can open a group under the Elixir copyright. And they really need professional training and need to prove they are qualified before being approved to open a group. The moderators talk about how they enjoy watching fights. And everything is turned into a fight on the group. They are not following any kind of process or even executing the CoC in context. All the moderators need to use their real names because they hide behind avatars and screen names in order to bully people they disagree with. Unless this is addressed, I fear that this community will remain non-inclusive to other people with questions and different backgrounds. Especially people who speak other languages.

Just because I wanted to know about the security policies... I was called a conspiracy theorist, troll, told to leave and told that they enjoyed to watch fights... and that the internet is designed for people to fight. All 3 of the moderators need removed before they destroy your open source project. 3 of the mods are in your contributors list. I'd even recommend you remove them from the github.

**Comment by tinyshell666** [comment]
yeap. I see them make jokes and have fun with their friends on it. As a foreigner, I do not feel welcome on it either. Try the forum. I hope Elixir enforce the new codes.

**Comment by natetech333** [comment]
1 of the mods said that the internet was made for fighting. If that's the kind of mods that this project is allowing to run their group, it's turning me away from wanting to use this project. I would expect http://plataformatec.com.br/ requires some kind of qualifications and training to be an official group for Elixir. The person didn't even point to anything wrong in the code of conduct before banning people. It is just a small group of friends who say whatever they want. Then police everyone else. I am starting to understand why all of these new codes are popping up. But the moderators are the problem, half the time. It's really pushing away women and other backgrounds, and genders.

**Comment by tinyshell666** [comment]
you culd file a complaint with the cyber bullying authorities in my country. and we have organizations to handle them.

**Comment by adkron** [comment]
The slack channel is not the language and is not Plataformatec.

**Comment by natetech333** [comment]
I understand. But is there something that can be done about making sure groups are run by qualified professionals before allowing them to use the Elixir name?

**Comment by kipcole9** [comment]
I admit to being puzzled by your observations since as one of the 23,000 member of the Elixir slack i've not seen the behaviour you're describing and I scrolled back as far as I could in General and Beginner (where I typically go) and didn't seen anything.

That said, this is a software issue tracker and the request you would have seen when you opened the issue would have been to respect that this is an issue tracker.

Therefore irrespective of the merit of your concerns, this isn't the place for that conversation and I would expect this "issue" to be closed when one of the core team visits.

If you wish to speak about intellectual property around Elixir then I suggest you direct a message directly to Plataformatec.

**Comment by josevalim** [comment]
The slack channel is **not**  an official Elixir channel. As mentioned in our code of conduct, the official channels are:

* The official GitHub projects and code reviews.
* The official elixir-lang mailing lists.
* The #elixir-lang IRC channel on Freenode.

There are many places where folks talk about Ellixir: slack, telegram, linkedin, facebook, many of them not even in english, and the core team is not responsible to them. My suggestion is to bring the code of conduct to other admins/mods and ask them to follow it, as they are representing part of the community, and ask them to be clarify when banning/kicking people.

> Just because I wanted to know about the security policies...

We have a mailing list where we would announce security releases if ever there is one. Check the README.

>  3 of the mods are in your contributors list. I'd even recommend you remove them from the github.

Elixir has 800+ contributors. And yes, it is likely that people who contribute are also the ones interested in maintaining groups around the language. Once again, the community is large, we can't keep tabs on 800+ developers. The plus side is, if there are indeed 3 bad actors, I am quite sure we can survive 3 bad actors and Elixir won't be destroyed because of them. As I said, my suggestion is to reach out to other admins/mods.
