### ISSUE TITLE
incorrect "always matches" warning

### ISSUE THREAD

**Issue by anujgoyal** [elixir-lang/elixir#8969]
This _"warning: this clause cannot match because a previous clause at line 2 always matches
  iex:7"_ seems incorrect.  The one is join (arity 2) the other is join (arity 3).

```
$ cat concat.ex 
defmodule Concat do
  def join(a, b) do
    IO.puts "***First join"
    a <> b
  end

  def join(a, b, sep \\ " ") do
    IO.puts "***Second join"
    a <> sep <> b
  end
end


$ iex
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> import_file("concat.ex")
warning: redefining module Concat (current version loaded from Elixir.Concat.beam)
  iex:1

warning: this clause cannot match because a previous clause at line 2 always matches
  iex:7

{:module, Concat,
 <<70, 79, 82, 49, 0, 0, 6, 28, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 153,
   0, 0, 0, 17, 13, 69, 108, 105, 120, 105, 114, 46, 67, 111, 110, 99, 97, 116,
   8, 95, 95, 105, 110, 102, 111, 95, 95, ...>>, {:join, 3}}
iex(2)> Concat.join("foo","bar")
***First join
"foobar"
iex(3)> Concat.join("foo","bar", "*")
***Second join
"foo*bar"
iex(4)>
```

**Comment by josevalim** [comment]
The warning is correct, although the warning could be much clearer. The key to understand the warning is that `def join(a, b, sep \\ " ") do` with a default argument will define a `def join(a, b)` clause, which is the one that emits the warning.

However, because the warning is emitted down within the Erlang compiler, the contextual information is lost, and we can't put things back together. Maybe things will change in the future and we will move the detection of the warning up to Elixir land, but unfortunately for now, we can't fix it.

In any case, thank you for the reporting the issue.
