### ISSUE TITLE
Trivial name change suggestion

### ISSUE THREAD

**Issue by pragdave** [elixir-lang/elixir#9034]
`(Dynamic)Supervisor.which_children` is a misleading name, as it implies that a degree of filtering is available: "which children like ice cream?"

Could I suggest `list_children` or simply `children` as a preferred alias?

**Comment by josevalim** [comment]
Unfortunately we are just sticking with the names from OTP. In particular, OTP requires this exact function to exist in order to perform hot code upgrades. We could duplicate the API but I am not sure if that would be worth it. If it wasn't for the OTP requirement, I agree we should change it.

Thanks Dave!

**Comment by pragdave** [comment]
Your thumbnail picture makes it look like _you_ like ice cream, anyway... :)
