### ISSUE TITLE
xref does not check aliases if they're only used in (ecto) macros

### ISSUE THREAD

**Issue by fenollp** [elixir-lang/elixir#9083]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.2 (compiled with Erlang/OTP 21)
```
* Operating system: 
```
Darwin baobao 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64 i386 MacBookPro14,1 Darwin
```

### Current behavior

```elixir
# With either ecto 2.2.12 or 3.1.4
defmodule Prefix.Helper.B do
  import Ecto.Query
  # This module does not exist
  alias Prefix.A

  # Uncomment this to get the compilation warning
  # def wat, do: A.wth()

  def a do
    A |> join(:left, [a], b in A, a.id == b.a_id)
  end
end
```
```
mix compile
# No warnings, returns 0.
```

### Expected behaviour

Compilation warning saying something along the lines of `warning: module Prefix.A is not available`.

Note: mentioning the inexistent module `Prefix.A` from outside Ecto's `join` macro does indeed show a meaningful enough warning. Try it by uncommenting `wat/0`.

If there's an alias to a module and the module does not exist at compile time, surely Mix should complain.

**Comment by josevalim** [comment]
`xref` does not check for modules unless you invoke them. The issue here is not in Mix, but rather Ecto, that converts the query syntax into a notation that has not call at all. You can imagine that the code transforms to this:

    {:query, {:join, A, quote(do: a.id == b.a_id)}}

There is no call for Mix to see, so nothing for us to warn on. Perhaps Ecto could emit a AST like this:

    {:query, {:join, A.__schema__(...), quote(do: a.id == b.a_id)}}

Which would make Mix check but that would be an Ecto issue, so feel free to report it there, thanks!
