### ISSUE TITLE
Improve DateTime documentation with how to use timezone databases

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#9148]
### Environment

Elixir 1.8.2

### Current behavior

The documentation of the `DateTime` module does not inform readers how to use / choose / configure timezone databases. There are no practical examples of this, only fake examples.

### Expected behavior

The documentation should provide real examples of how to use / choose / configure time zone databases, like

```
iex(8)> datetime = DateTime.utc_now()
#DateTime<2019-06-17 20:30:41.706622Z>
iex(9)> DateTime.shift_zone(datetime, "Africa/Abidjan", Tzdata.TimeZoneDatabase)
{:ok, #DateTime<2019-06-17 20:30:41.706622+00:00 GMT Africa/Abidjan>}
iex(10)> datetime = DateTime.utc_now()
#DateTime<2019-06-17 20:31:04.094127Z>
iex(11)> DateTime.shift_zone(datetime, "Africa/Maputo", Tzdata.TimeZoneDatabase)
{:ok, #DateTime<2019-06-17 22:31:04.094127+02:00 CAT Africa/Maputo>}
```

This should avoid developers loosing time figuring things out.

**Comment by mguimas** [comment]
The example above is with `Tzdata` library. The documentation should refer to recognized libraries in the community.

I wonder why does not Elixir come with such a library? 🤔

**Comment by wojtekmach** [comment]
> The documentation of the DateTime module does not inform readers how to use / choose / configure timezone databases. There are no practical examples of this, only fake examples.

Have you seen the section about setting it in the module doc? https://hexdocs.pm/elixir/DateTime.html?#module-time-zone-database. How would you improve it?

Setting the DB like that is preferred because you'd usually have one tz db per application anyway and so you don't need to keep passing it around.

> The example above is with Tzdata library. The documentation should refer to recognized libraries in the community.

I believe official Elixir docs seldom (if ever) mention 3rd party packages so that would be my guess why it's omitted. Since tzdata is the de facto tz db I tend to agree it could be mentioned.

> I wonder why does not Elixir come with such a library? 

A timezone db is only as good as it's up to date and keeping it fresh is tricky. Also, if something doesn't have to be in core it usually isn't. :)

**Comment by whatyouhide** [comment]
> I believe official Elixir docs seldom (if ever) mention 3rd party packages so that would be my guess why it's omitted. Since tzdata is the de facto tz db I tend to agree it could be mentioned.

We sometimes do (like we mention Jason in the releases documentation). I think it's fine as long as we don't "push" people too much, that is, it's fine to use tzdata as an example of a timezone database but I wouldn't say it's a "standard" library or anything like that.

**Comment by josevalim** [comment]
A pull request that adds a link to the tzdata library under the session mentioned by @wojtekmach could be a nice addition. Anyone interested please do submit a pull request, thank you.
