### ISSUE TITLE
Add NaiveDateTime.local_now

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#9150]
While we have generally avoided adding local API to our Calendar types, sometimes said information can be very useful, such as in embedded devices, command line scripts, and so on.

/cc @lau

**Comment by lau** [comment]
These functions would be very sharp tools that could the cut person wielding them if not careful :) There are a few cases where asking the computer for "local time" is useful. For instance if you run a desktop app and want to simply display a clock with the current local time without having a "local" time zone identifier (e.g. "Europe/London").

Inevitably it also would cause many bugs for people who would use it incorrectly. For instance it should not be used on servers. I wrote something about that here: http://www.creativedeletion.com/2015/08/07/why-not-to-use-server-local-time.html Docs could perhaps help with a lot of warnings ☠ and documentation about when it can be used safely and when to use UTC or time zones instead.

**Comment by josevalim** [comment]
Perfect. I agree with putting many warnings in place as well

**Comment by lau** [comment]
Related: perhaps there should be a `DateTime.now!/2` (with exclamation point) function to make it slightly easier for people to do `DateTime.now!("Europe/London")` and get a `DateTime` returned without it being wrapped in an {:ok, } tuple.

Just so that things in general are easier to work with but especially to avoid an "easiness bias" towards other functions. E.g. someone might want to get the current time and could either go with NaiveDateTime.local_now or DateTime.now. Even a small thing like getting it not wrapped in a tuple could make someone chose one over the other. In general I think it is good if people chose based on what is "correct" instead of what seems "easy" in the moment.

**Comment by josevalim** [comment]
> perhaps there should be a DateTime.now!/2

I think we already have it. :)

**Comment by lau** [comment]
Great. I should have checked master, not 1.9 :)

**Comment by lau** [comment]
I think these "_local" functions have a small niche where they would make sense to use in production and many will probably use them incorrectly. But some people want these kinds of functions and adding them can be an opportunity to help/educate about issues with local time (in general, transcending Elixir) instead of just not having the functionality.

**Comment by wojtekmach** [comment]
Are we going to use `:calendar.local_time` etc to compute it?

Just realised we can do this:

```
~% elixir -e "IO.inspect :calendar.local_time"
{{2019, 6, 19}, {21, 8, 3}}

~% TZ="America/New_York" elixir -e "IO.inspect :calendar.local_time"
{{2019, 6, 19}, {15, 8, 16}}
```

so whoever picks it up, please make sure to mention it! (it's not mentioned in erlang calendar docs)

**Comment by josevalim** [comment]
@wojtekmach we will use `:erlang.localtime`. The calendar one just delegates to it.

Regarding the TZ environment variable, it is a feature of the OS/terminal:

    $ TZ="America/New_York" date
    Wed Jun 19 15:22:27 EDT 2019

**Comment by michalmuskala** [comment]
What if instead of having those functions we would have ones to cast UTC values to locals? It would make the local versions more verbose and naturally discourage their use unless really needed.

**Comment by josevalim** [comment]
Unfortunately we don't have a public API to know the local timezone and its offset. :( Last time I checked it required a good amount of fiddling to kinda work across OSes.

**Comment by michalmuskala** [comment]
We have `erlang:universaltime_to_localtime` - could this be leveraged for the implementation?

**Comment by lau** [comment]
How about doing only `NaiveDateTime.local_now` and not `Time.local_now` nor `Date.local_today`? At least at first. The last two are just shortcuts for `to_time` or `to_date` anyway. It is hard to take the functions away after adding them and in most cases the use of them should be discouraged anyway.

**Comment by josevalim** [comment]
@michalmuskala does `erlang:universaltime_to_localtime` consider the time offset from the input or does it use the current machine time offset?

@lau fine by me!

**Comment by michalmuskala** [comment]
It uses the operating system's support to figure that out. For what it's worth, in a brief test it seems it does take into account the DST:

```elixir
iex(1)> univ_summer = {{2019, 6, 21}, {7, 16, 39}}
{{2019, 6, 21}, {7, 16, 39}}
iex(2)> :erlang.universaltime_to_localtime(univ_summer)
{{2019, 6, 21}, {9, 16, 43}}
iex(4)> univ_winter = {{2019, 1, 21}, {7, 16, 39}}
{{2019, 1, 21}, {7, 16, 39}}
iex(5)> :erlang.universaltime_to_localtime(univ_winter)
{{2019, 1, 21}, {8, 16, 39}}
```

**Comment by josevalim** [comment]
@michalmuskala nice! Some pending questions are:

1. Can some Linux distributions not have a timezone database? Also, does it work on Windows? For the second, we can push the above as a test in a PR so we run it on Windows.

2. But perhaps more importantly, does it mean that now users need to update both the machine timezone database and the Elixir-language TZ database? Will users remember to do both for their servers.

**Comment by michalmuskala** [comment]
For the 2, I think we should have a tzdatabase package that just uses whatever is on the system and does not pull its own. Pulling our own always seemed problematic to me with regards to integration with other systems.

**Comment by josevalim** [comment]
@michalmuskala if there is a good, non-native interface for doing so across OSes, I am all ears.

**Comment by michalmuskala** [comment]
On most unixes it's a matter of reading correct files from couple of locations. That's what the Ruby's tzdata gem is doing. Windows doesn't ship with the database in an accessible format anyway, so there we'd need our own. I'm pretty sure we'd be able to solve it with some sort of fallback to the pulled in version if we can't find the system one or something similar. I guess in this case some sort of support for system-dependent packages would be nice.

**Comment by lau** [comment]
Using the systems time zone database conversion sounds like it just got a lot more complicated. Adding a lot of complication so that people can do something that is usually a bad idea. Should it be a separate library?

If it has to be done, why not simply do `NaiveDateTime.from_erl!(:calendar.local_time)` ? Why make it more complicated? What are the use cases for this besides showing a clock on a desktop machine? Just because something is possible doesn't mean it should be done.

**Comment by josevalim** [comment]
>  What are the use cases for this besides showing a clock on a desktop machine? 

And this is enough as a use case. If we want Elixir to continue to grow into areas like embedded systems, scripting, GUIs then we need to acknowledge those are valid use cases even though it is detrimental to the use case of servers, distsys, etc.

Also, as mentioned above, forcing folks to go through the Erlang API does not give us the opportunity to talk about all of the scenarios were using local time is a bad idea.

I don't think a separate package is reasonable here since we do have calendar types and the capability exists in Erlang. If Erlang did not provide it, then I would agree as a separate thing.

When it comes to OS integration, then I agree a separate package would be the way to go, as it is not fully provided by Erlang.

**Comment by lau** [comment]
I appreciate looking into all the possibilities of what could be done. That being said, would something like `def local_now, do: NaiveDateTime.from_erl!(:calendar.local_time)` not be sufficient? Although with :calendar.local_time being called in the `System` module.

**Comment by josevalim** [comment]
@lau I don't want to introduce a new API that returns tuples. One option is to add `NDT.from_unix` and use `System.os_time(:second)` but I think you will have even more reservations with `NDT.from_unix`.

**Comment by lau** [comment]
@josevalim My question was more about if `:calendar.local_time` would not be sufficient for `System` to call. The tuple in this example would only be in the `System` API. What if a function in `System` calls `:calendar.local_time` and returns the time in some other form that is not a tuple? A map like `Calendar.naive_datetime()`? Or a simplified version of that map.

> One option is to add NDT.from_unix and use System.os_time(:second) but I think you will have even more reservations with NDT.from_unix.

Yes, UNIX time is always UTC so we cannot convert from UNIX with a `NaiveDateTime`.

**Comment by josevalim** [comment]
> What if a function in System calls :calendar.local_time and returns the time in some other form that is not a tuple?

We could have System.local_time, but then it should return time a `NaiveDateTime`.

**Comment by lau** [comment]
> We could have System.local_time, but then it should return a NaiveDateTime.

That makes sense.

A different subject is the name "local time". It is a bit ambiguous. In some people's minds it is anything that is not UTC. Or the time local to the user of an application. "local" in itself doesn't say "which" local it is. In this case it is "the local time of the machine" or "local time of the system". I'm not sure which different name for the function would be better. `local_machine_now` or `local_system_now` perhaps.

**Comment by wojtekmach** [comment]
I think System.local_time sounds good to me, agreed about it being NDT.

(One minor nice thing about it is NDT.utc_now returns with milliseconds and I believe Erlang only has local time down to seconds.)

**Comment by josevalim** [comment]
@lau the fact it is on `System` gives the idea of "machine", so I am fine with `local_time` in this sense. However,  we already have `os_time` and `system_time` in the System module, so adding a `local_time` function can be confusing, as it behaves different from the other two. Something like `os_naive_datetime` would work but it doesn't sound great to me.

@wojtekmach  `os_time(:microsecond)` actually gives us microseconds so maybe we can compute "local_time" from it.

**Comment by lau** [comment]
@josevalim About the name I am mostly concerned about the name of a function being added to `NaiveDateTime`. Would a `System.local_time/0` function basically have an alias in `NaiveDateTime`?

**Comment by wojtekmach** [comment]
Instead of an alias, how about only  NaiveDateTime.system_time? I think system prefix is nice for the reason José mentioned, that its tied to the machine.

**Comment by josevalim** [comment]
@lau in this case I wouldn't add a function to NaiveDateTime at all.

**Comment by josevalim** [comment]
Folks, just to make sure this doesn't day, my biggest concern with adding those to System is that the system functions are low-level and all of the `_time` APIs return integers. So I am rolling back to the proposal of adding the functions to the calendar module, but I am fine to change the name to something more obvious if `local_now` and `local_today` are not clear enough. @lau and @wojtekmach can you think of any name more explicit?

The other option is to introduce some sort of function that creates Time, Date and NaiveDateTime from the OS values. We can't call that `from_unix`, because the UNIX Epoch implies UTC, but maybe there is another name we can use? Would that be an alternative?

**Comment by wojtekmach** [comment]
I think `NaiveDateTime.local_now`, `Time.local_now`, and `Date.local_today` are good. As @lau mentioned, introducing just `NaiveDateTime.local_now` for now is fine too, it's trivial to get the date or time out of it. It's hard for me to draw the line, but I'd say that getting the local time is indeed such a common functionality that it should be as simple as possible, just one function call. Finally, as far as naming goes, I think the names are ok, and we can always link to them from existing `utc_now/utc_today` functions which should help in discoverability.

**Comment by lau** [comment]
@wojtekmach It might be a common thing to do, but it should not be common IMHO :) One way to find bugs is to run `git grep :erlang.localtime` (or equivalent for other languages) on a codebase. It even happened in the Elixir codebase years ago. I don't remember ever having needed that functionality. If there are good uses for it other than displaying a clock on a desktop machines I would like to know. Seriously, I would be happy to hear about other examples of good uses for it.

Having more than one function (ie. `Time.local_now` and `Date.local_today`) just means more ways that people can get into trouble. More "foot guns" as it were. And of course every function in a module adds a cost of the API having more functions for users to navigate and the cost of having to be maintained "forever". Besides `to_date` and `to_time` functions being available, the functions are polymorphic in the sense that you can pass for instance a `NaiveDateTime` to the function `Date.leap_year?/1`  without having to make it into a `Date` struct first.

@josevalim I agree that it is not a good idea to use a UNIX time style integer exactly for the reason you mention about UTC. Are you suggesting to not have a function for it in `System` at all? So a `NaiveDateTime.local_now` function would call Erlang directly without calling the `System` module?

I haven't come up with a better function name than `NaiveDateTime.local_now` since I wrote that comment (https://github.com/elixir-lang/elixir/issues/9150#issuecomment-504477121) about it.

**Comment by josevalim** [comment]
@lau my suggestion was to have something like `System.local_time` that returns the time in integer but we would need an API to create a NaiveDateTime from said integer.

**Comment by lau** [comment]
Erlangs "Gregorian seconds" as used in `:calendar.datetime_to_gregorian_seconds/1` etc. is an example of such an integer that does not imply UTC, but I guess we don't want to introduce Gregorian seconds to the API?

I see a lot of functions in the `System` module that return something other than integers. "Local" datetime and Unix time are different. Is an integer the best type for a "local" datetime? Should they be the same just because they both are datetimes? Maybe it's better that they are not the same - so that two won't be mixed up. Maybe the fact that it is not an integer like some other functions is a good thing because it returns a different kind of thing.

The other time related functions that return an integer do not return the same thing. Not everything should be an integer. In this case there is more information to be stored that can reasonably be stored in an integer and make sense - that the datetime is *not* UTC.

If a `NaiveDateTime` struct is too "high level" for `System` would a simpler map work better? I remember you didn't want more Erlang style datetime tuples, but I don't remember exactly why or if it only applied to the `Date`,`Time` etc. modules.

**Comment by josevalim** [comment]
> I see a lot of functions in the System module that return something other than integers. "Local" datetime and Unix time are different. 

I was saying that the `time` related functions in System return integers. They are also from the Unix epoch, so adding a gregorian version wouldn't be helpful either. The Erlang version returns integers from Unix epoch even for the local case.

The other issue with making System return a NaiveDateTime is that it adds a cyclic dependency between the modules, which is generally a smell (and Elixir may warn when this happens in the future).

And generally speaking, I wouldn't like to introduce a new format. Adding a new format may add complexity and confusion, so in that case, I would rather go with the original proposal. I just want to be sure we have explored all venues before doing so.

**Comment by lau** [comment]
@josevalim 
>   Adding a new format may add complexity and confusion, so in that case, I would rather go with the original proposal.

Would it return a fake unix time? I'm not sure how the integer would represent local time. Adding this new function that returns a different kind of thing adds inherent complexity. Pretending that it is less complex and making it look deceptively like a unix timestamp can add confusion on its own.

> I was saying that the time related functions in System return integers. 

I see only two that are similar: System.os_time and System.system_time. They have to do with time but they return a different thing that local time. 

> The other issue with making System return a NaiveDateTime is that it adds a cyclic dependency between the modules, which is generally a smell (and Elixir may warn when this happens in the future).

That makes sense. Struct is out. A simpler map does not have that problem:

```elixir
%{
  day: 30,
  hour: 17,
  microsecond: {0, 0},
  minute: 16,
  month: 7,
  second: 45,
  year: 2019
}
```

> The Erlang version returns integers from Unix epoch even for the local case.

Erlang returns a tuple, right? Which one returns a local time in integer?

```elixir
:erlang.localtime
{{2019, 7, 30}, {11, 10, 14}}
```

All that said if the System function has to return an integer, what would the documentation say? Something like "Returns fake unix integer - only for use by NaiveDateTime.local_now function - do not use this function directly"?

**Comment by josevalim** [comment]
Oh, I thought os:system_time was the local time, but I was wrong. That said, I agree. A fake Unix time is not a good option nor is a map (I.e a new format). So we should roll with the originally proposed API. As I said? I just wanted to make sure we explored all options.

So one last discussion, the name. Is local_now enough? Or we want something more verbose like os_local_now?

**Comment by lau** [comment]
> So one last discussion, the name. Is local_now enough? Or we want something more verbose like os_local_now?

I like the name `os_local_now`. It communicates something about where "local" comes from.

>  So we should roll with the originally proposed API. 

Just to be clear - which one is that? One where `:erlang.localtime` is called in a function in the `NaiveDateTime` module?

**Comment by josevalim** [comment]
> I like the name os_local_now. It communicates something about where "local" comes from.

Although later I realized that for utc_now the time is also coming from the OS. :S

> Just to be clear - which one is that? One where :erlang.localtime is called in a function in the NaiveDateTime module?

Correct.

**Comment by lau** [comment]
@josevalim That sounds good to me.

`os_local_now` vs `utc_now` makes sense because there isn't the same ambiguity about where UTC "comes from", whereas "local" is ambiguous. I think `os_local_now` will be better because it is longer and says more, but I don't think just `local_now` a bad name.

**Comment by kelvinst** [comment]
IMHO `local_now` is good enough, as just `os_local_now` is not actually clearing all the confusion about where UTC comes from, we would still need to document it very well. And anyways, for anyone that is planning to use this function, the ideal is that one reads carefully the documentation before doing so, the ambiguity must be clarified on the docs IMO.

**Comment by wojtekmach** [comment]
I have this:

```
iex> :erlang.localtime
{{2019, 10, 31}, {15, 51, 41}}

iex> :erlang.system_time(:second) |> DateTime.from_unix!()
~U[2019-10-31 14:51:44Z]
```

I think we want the new functions to return what `:erlang.localtime` does except as structs.

My understanding is by "system time" we mean "Erlang System Time" [1] which is runtime's view of "POSIX time" which is roughly UTC (except for leap seconds) and so in my example returning "15:51" for "system time" would be confusing.

So maybe `local_now` (either just on NaiveDateTime as @lau originally proposed, or on all calendar modules) after all?

[1] http://erlang.org/doc/apps/erts/time_correction.html#erlang-system-time

**Comment by lau** [comment]
Hi @josevalim and @wojtekmach. I hope you are having a good day/evening :)

> Sorry folks this got stale. I also re-read the whole discussion and I missed @wojtekmach's comment, which perhaps is the best option:
> 
> ```
> Date.system_date
> Time.system_time
> NaiveDateTime.system_time
> ```
> 
> I think it is very clear where it is coming from. @lau, do you prefer that over `local_now` and `local_today`?

I think `NaiveDateTime.local_now` is much better than `NaiveDateTime.system_time`. Because system time on POSIX systems is often understood as the same thing as unix time - e.g. basically UTC* . The function `:erlang.system_time` is called **exactly the same** name: `system_time` and returns UTC*.

To reiterate about why I think it is best to only add it to NaiveDateTime and not to other modules:
- It causes bugs. A bug even snuck into earlier versions of Elixir because of :erlang.localtime(). And the bugs caused are insidious, subtle and intermittent. The fewer functions in the API that use "local time" the better
- Most people never need NaiveDateTime.local_now let alone a Date or Time version where some of the information is thrown away
- While easy to add, it would be impossible to remove the functions from other modules (Time, Date) again without breaking the API.
- If you do need a `Date` or `Time` the functions `NaiveDateTime.to_date/1` or `NaiveDateTime.to_time/1` can be used. It is not hard to convert to `Date` or `Time` if really wanted or needed.
- Having the "convenience factor" and similarity of it in 3 different modules along with utc_now, utc_today etc. could be seen as an encouragement to use along with the UTC flavor.

It would be easier to cheer for adding the extra functions. But I discourage it in the hope of helping others to avoid bugs.

I agree with https://github.com/elixir-lang/elixir/issues/9150#issuecomment-548417554 . Something like this in `NaiveDateTime` should do it:

```elixir
  def local_now do
    {{year, month, day}, {hour, minute, second}} = :erlang.localtime()
    {:ok, ndt} = NaiveDateTime.new(year, month, day, hour, minute, second)
    ndt
  end
```
*) (when there's no leap second)

**Comment by josevalim** [comment]
Perfect. We are on the same page then. I have changed the title accordingly, a PR is welcome.

**Comment by lau** [comment]
Cool. I'll open a PR soon.

**Comment by josevalim** [comment]
Closing in favor of the PR, thanks @lau!
