### ISSUE TITLE
Discuss single and double quoted string

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#92]
Today, "double quoted" returns a binary in erlang while 'single quoted' a list. This is very convenient because we often need to use both formats in Erlang. However, this may also be confusing as most people wouldn't remind the difference between them.

We need to discuss if we want to leave this way or change the single quoted format to something else. This may not be an issue if editors explicitly use different syntax highlighting for each type. In many functional languages, a single quoted string is not the same as a double quoted string.

**Comment by gilons** [comment]
Actually in Erlang there is nothing like single quote strings . Erlang consider single quoted string as atoms

try running is_atom('santers') in the shell returns true or is_atom('Santers') returns true .
So single quotes are just used in erlang to have atoms starting with capital leters since, Santers in erlang will be treated as a variable.to make it be treated as an atom just put it in single quotes .

**Comment by josevalim** [comment]
Yes! My text was poorly written. By “returns a list in Erlang” I meant to
say “returns an Erlang list”. And so on.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
