### ISSUE TITLE
RFC: defunion and pattern matching

### ISSUE THREAD

**Issue by alexrp** [elixir-lang/elixir#925]
I find that I often want a saner way than tuples + atoms to work with data structures that have a closed set of possible types/representations - that is, discriminated unions.

It would be nice if we had a `defunion` macro that did this. For example, a simple type system could be represented like so:

```
defunion TypeSystem do
    defcase Integer, []
    defcase Float, []
    defcase String, []

    defcase Array, element: t
    defcase Pointer, pointee: t
    defcase Function, args: [t],
                      return: t

    # ...
end
```

Or a simple C-ish AST:

```
defunion ExprTree do
    @typep token :: Token.t

    defcase IntegerExpr, literal: token
    defcase FloatExpr, literal: token
    defcase StringExpr, literal: token
    defcase VarExpr, literal: token

    defcase ArrayExpr, open_bracket: token,
                       elements: [t],
                       close_bracket: token

    defcase NotExpr, operand: t
    defcase NegExpr, operand: t
    defcase ComplExpr, operand: t

    defcase AddExpr, lhs: t,
                     plus: token,
                     rhs: t
    defcase SubExpr, lhs: t,
                     minus: token,
                     rhs: t
    defcase MulExpr, lhs: t,
                     star: token,
                     rhs: t
    defcase DivExpr, lhs: t,
                     slash: token,
                     rhs: t
    defcase RemExpr, lhs: t,
                     percent: token,
                     rhs: t

    defcase AndExpr, lhs: t(),
                     ampersand: token,
                     rhs: t
    defcase OrExpr, lhs: t,
                    pipe: token,
                    rhs: t
    defcase XorExpr, lhs: t,
                     caret: token,
                     rhs: t

    defcase AddrExpr, ampersand: token,
                      operand: t
    defcase DerefExpr, star: token,
                       operand: t

    defcase CondExpr, keyword: token,
                      condition: t,
                      question: token,
                      true: t,
                      colon: token,
                      false: t
end
```

So, the `defunion` macro takes one argument which is the union body. Inside that body, `defcase` can be invoked which takes two arguments: The case name and a list of `Kernel.Typespec`-compatible type(s) that make up the case. The names in the list are purely for documentation purposes.

Let's consider representation. We have a union like:

```
defunion Foo do
    defcase Bar, c: char_list
    defcase Baz, b: integer, c: float
end
```

The type `t` for this union is:

```
@type t :: {Foo, {Bar, char_list} | {Baz, integer, float}}
```

(Let me know if this is in any way incompatible with record function dispatch.)

As with records, unions get a module that contains reflection functions such as `__union__` and whatever functions the programmer defines in the `defunion` body.

Now, the interesting part of all this is really pattern matching. With Elixir's macro system, we have some very interesting opportunities for statically ensuring correctness.

Of course, one could pattern match on a union like so:

```
case some_union do
    {SomeUnion, {Case1, f1}} -> # ...
    {SomeUnion, {Case2, f1, f2, f3}} when f1 == 42 -> # ...
    # ...
end
```

And this would work fine but doesn't give us what is really important when dealing with discriminated unions: Statically-ensured handling of all cases.

Thus, every union module gets a `match/2` macro. The first argument is the union, while the second argument is a list of cases.

For example:

```
SomeUnion.match some_union do
    {Case1, f1} -> # ...
    {Case2, f1, _, f3) when f3 == 42 -> # ...
    {Case3, f1} when is_float(f1) -> # ...
    _ -> # All other cases...
end
```

The result value of the `match` macro is whatever the chosen branch's last expression is (i.e. it works just like a `case`).

This just looks like a slightly more verbose `case`, but the trick is that since the AST that holds all the case patterns is passed to `match`, it can check for exhaustiveness, invalid patterns, impossible types, etc. All at compile time.

Thoughts?

**Comment by X4lldux** [comment]
@josevalim  I went after your suggestion and implemented this proof-of-concept as a separate library - http://github.com/X4lldux/disc_union. Same as with @alexrp initial description, any "types" are just for documentation purposes and are NOT checked, or even used for anything else, anywhere. Syntax is a little ML-like, but that should not be of any importance at this stage (It's just less verbose than the one suggested by alex ;) ). 

Do check tennis kata example (in _example_ folder) Even after this one example, I'm pretty convinced this way would be a great way to improve DDD in Elixir (more on DDD with types: http://www.slideshare.net/ScottWlaschin/domain-driven-design-with-the-f-type-system-functional-londoners-2014 ).

**Comment by josevalim** [comment]
This is really neat, thanks for sharing!

I see you used typespec types. I was wondering what it would look like if the types would actually be made by expressions that are valid guards. It would make the types more strict and you could compiled the guards along-side the patterns.

Thoughts?

**Comment by X4lldux** [comment]
As described, for now, they're only for code documentation, and they don't have any meaning. I didn't want to concentrate on being type-strict at this stage, when even generated macros and functions, don't have typespecs generated too. And I didn't want to implement a third typing mechanism (we have BEAM primitives, typespecs from Dialyzer and another would be here). Although, type checking is something would be a real sweet thing to have!

For now, there's one thing that bugs me more: we have compile-time errors when we misspell a case tag in `case/2` or `from/1` macros - writing a `Score.from {Pointz, 1, 2}` would result in: 
```
== Compilation error on file example/tennis_kata.exs ==
** (UndefinedUnionCaseError) undefined union case: {Pointz, 1, 2}
    (disc_union) expanding macro: Score.from/1
    (disc_union) example/tennis_kata.exs:38: Tennis.run_test_match/0
```
But there's no such error if dynamic constructors are misspelled!  A misspelled `Score.pointz/2` would be caught only at run-time.
I was thinking about implementation catching this using `@after_compile` hook, but that would require me to parse bytecode and I don't think it's the right thing to do here. I believe, the compiler, at the last stage of compilation, knows which functions are defined in a module and could catch such mistakes. I don't think that should break anything, because ErlangVM allows us to redefine an existing module, but not add new functions into it - so all existing functions and macros are known!
I'm also aware of limitations of this:
```Elixir
Score.pointz 1,2 # would be caught by such a early warning system

mod = Score
mod.pointz 1, 2  # would not be caught
```
but better something than nothing. Though, a developer knows that it's not possible to invoke macros like that, so that should not be a big deal either. To be honest, I did't look at the compiler, so I can't be sure it's possible to implement it ther. 

What's your take on this? Or maybe we should tackle this in a different issue?

**Comment by josevalim** [comment]
@X4lldux we are having a similar discussion to this in the elixir-lang-core mailing list.

Both Elixir and Erlang do not expect the function you are calling to exist during compilation time. The best idea for now is to have a post-compile step that would check for undefined modules as well as undefined functions being called.

Another approach is to enable this only partially. For example, if a module has been required, we could perform such checks because then, by definition, it is available during compilation time. We should certainly tackle this in a different issue though.

**Comment by josevalim** [comment]
See #4540.

**Comment by X4lldux** [comment]
@josevalim about the types in discriminated unions. Please see X4lldux/disc_union#3 and X4lldux/disc_union#2.
