### ISSUE TITLE
Unused variables does not emit warning when checked in guard

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#9345]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): master

### Current behavior

variables that are never used but are checked in the guard do not emit a warning.
please see in this example:
```elixir
defmodule TestUnusedVariableGuard do
  def does_not_warn(ast, compiled) when is_map(compiled) do
    ast
  end  

  def does_warn(ast, compiled) do
    ast
  end  
end
```

```console
Compiling 1 file (.ex)
warning: variable "compiled" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/test_unused_variable_guard.ex:6: TestUnusedVariableGuard.does_warn/2
```

the var `compiled` is white-listed just becuase we check it in the guards, but it is never used in the body of the function.

### Expected behavior

Warn about the variable being unused

**Comment by josevalim** [comment]
Yes, using it in a guard is enough to use it. For example, imagine this clause:

    def foo(bar, baz) when bar == baz do

I don’t need to check baz again because I know it is equals.

Or these clauses:

    def foo(bar, %{key: value}) do
    def foo(bar, map) when is_map(map) do

In this code I want to know if map has a key and if it doesn’t, I don’t care about the map contents, only that it’s map. Emitting a warm here would invalidate valid code today.

**Comment by eksperimental** [comment]
You are totally right! sorry for the false alarm
