### ISSUE TITLE
Verification pass is not running on IEx/test files

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#9362]
Adding

    def bar(foo) when is_integer(foo) and is_map(foo), do: foo

is not printing any warnings in test. This may be cause we don't write any .beam files in disk?

**Comment by ericmj** [comment]
How did you check test files? When I run `mix test` in a mix project I get the warning.

`.iex.exs` is evaled so the `ParallelCompiler` is not used.

If you run `elixir -r test_file.exs` it won't run because it calls `Code.require_file/1` which also skips the `ParallelCompiler`.

Should I look into how we can run the checker when evaling and calling `Code.require_file/1`?

**Comment by josevalim** [comment]
During eval is not necessary but let’s give require_file a try!
