### ISSUE TITLE
Inspect.Opts docs missing syntax_coloring missing types

### ISSUE THREAD

**Issue by VitorTrin** [elixir-lang/elixir#9391]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.9.1

### Current behavior

Inspect.Opts explains the list of types that the `syntax_coloring` can colorize. I found list is missing a big one, `:string`, and I tried to see if it was missing any other, but I couldn't find a complete list of types looking at the code or even something that pointed in that direction. Can I colorize characters? Can I colorize every sigil, or is regex special?

### Expected behavior

The complete list of types in the docs or a link that points to the full list

**Comment by josevalim** [comment]
>  Can I colorize characters? Can I colorize every sigil, or is regex special?

That's the issue. :) Because inspect is a protocol, it means that you can colorize any data type, as long as the data type uses the coloring feature. So the benefit is that it is extensible, the downside is that it is hard to come up with an aggregated list. But sure, we should keep the ones in core up to date. i will add string and see if there are any others missing.
