### ISSUE TITLE
Warn when same guard check is repeated, and when a guard is not necessary

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#9405]
Reading @michalmuskala 's comment https://github.com/elixir-lang/elixir/pull/9402#discussion_r334404511 I noticed that Elixir is not warning about this either, it happens when by pattern matching we already check that a variable is a list, but we unnecessarily run a guard to check it.

```elixir
  def count([_] = list) when is_list(list) and is_list(list),
    do: :one
```

and since side-effects are not allowed in guards, it could also warn about running the same guard twice, a mistake that can happen in long guards.

Is there a chance that the Elixir compiler could warn about these two cases?

**Comment by josevalim** [comment]
Any kind of type checking is generally speaking very complex and not really the work of the compiler to check. For example, this is also a bit redundant:

    def count(list) when is_list(list) and length(list) > 0

Since length only works with lists, `is_list` is actually not necessary, but we shouldn't warn on this case, so the rules end-up being very manual and potentially complex for little gain.

In any case, I will let @ericmj decide if this is worthy or not, but if not, feel free to close it Eric.

**Comment by eksperimental** [comment]
@josevalim what about checking against running the same guard more than twice? maybe more worth the effort since it will be a general case that would apply to any kind of guard

**Comment by ericmj** [comment]
It is not straightforward to check if running the same guard more than once is wrong, this is for example valid code: `length(list) > 0 and length(list) < 10`.

**Comment by josevalim** [comment]
Yes, macros can also add redundant checks. For exmaple, if you do `foo in 1..10 or foo in 20..30`, `is_integer` is added twice. So we need to take that into account or also learn how to navigate `or`. Again, it can get really complex if we don't want to have false positives and I don't think it should be the job of the compiler to handle this complexity. For all purposes, it is valid code.
