### ISSUE TITLE
~S does not parse correctly a terminal reverse slash.

### ISSUE THREAD

**Issue by ityonemo** [elixir-lang/elixir#9471]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
``` 
Erlang/OTP 22 [erts-10.5.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.9.2 (compiled with Erlang/OTP 21)
```
* Operating system: 
```
Linux ... 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### Current behavior

`sigil_S` doesn't work for a terminal slash.
E.g:
```
iex> ~S(\)
...>
```
Fails on other bounding tokens as well, such as "", //, etc.  Causes a TokenMissingError in code files.

### Expected behavior

From: https://hexdocs.pm/elixir/Kernel.html#sigil_S/2
> It simply returns a string without escaping characters and without interpolations.

```
iex> ~S(\)
"\\"
```

Since this is a rare corner case putting a warning in the `Kernel.sigil_S/2` docs would probably be acceptable.

**Comment by josevalim** [comment]
Good find. Definitely a bug. We don't respect escape characters anywhere in upper case sigils, so we shouldn't escape this one. Here are more examples:

```elixir
iex(7)> ~S(\))
")"
iex(8)> ~S(\])
"\\]"
```

It shouldn't matter that the sigil is `(` and `)`. Unfortunately this may break existing code relying on the wrong behaviour, but since it is a bug fix, we should do it, unless many people are bitten by it.

Another option is to document that we generally don't escape except the terminator itself (but it may be confusing).

**Comment by josevalim** [comment]
So this feature is used by LiveView and many other places, for example, in cases like this:

```elixir
~S"""
Does foobar:

    ~L"\""
    example
    "\""
"""
```

So I think we need to document it only allows escaping of the terminator character itself. This may be a better choice anyway because of things like Regex, that disables escape characters but still enable escape of regexes tokens.
