### ISSUE TITLE
Enum.max returns nil from a list even if it has other valid values along with nil.

### ISSUE THREAD

**Issue by dronabanerjee** [elixir-lang/elixir#9639]
### Precheck

* Do not use the issue tracker for help or support (try Elixir Forum, Stack Overflow, IRC, etc.)
* For proposing a new feature, please start a discussion on the Elixir Core mailing list: https://groups.google.com/group/elixir-lang-core
* For bugs, do a quick search and make sure the bug has not yet been reported
* Please disclose security vulnerabilities privately at elixir-security@googlegroups.com
* Finally, be nice and have fun!

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
* Operating system: 

### Current behavior

Include code samples, errors and stacktraces if appropriate.

### Expected behavior

A short description on how you expect the code to behave.

**Comment by dronabanerjee** [comment]
Current behavior:
iex(3)> Enum.max([2,6,nil,1])
nil

iex(4)> Enum.max([2,6,0,1])
6

Expected behavior:
iex(3)> Enum.max([2,6,nil,1])
6

iex(4)> Enum.max([2,6,0,1])
6

**Comment by kipcole9** [comment]
Given that comparisons are done based on Erlang/Elixir term order I wouldn't expect this to be changed. The term order is:
```
number < atom < reference < function < port < pid < tuple < map < list < bitstring
```
And since `nil` is an atom it will compare as greater than a number. Changing this would be a breaking change to the runtime which I wouldn't expect to be considered.

**Comment by fertapric** [comment]
@dronabanerjee as @kipcole9 commented, this is due to `Enum.max` using Erlang's term ordering to calculate the maximal element. You can learn more about Elixir's term ordering in the ["Operators" section of the documentation](https://hexdocs.pm/elixir/master/operators.html#term-ordering).

Just to clarify, `nil` is an atom because Elixir allows to skip the leading `:` for the atoms `false`, `true`, and `nil`. You can learn more in the ["Atoms" sections of the "Basic types" documentation](https://hexdocs.pm/elixir/master/operators.html#term-ordering).

I would suggest to do a first pass to remove any `nil` from the list 🙂 

I'm going to close this one since this is the expected behaviour and it won't be changed.

**Comment by eksperimental** [comment]
@dronabanerjee you need to filter them first.

```elixir
iex(8)> [2,6,nil,1] |> Enum.filter(&is_integer/1) |> Enum.max()
6
iex(9)> [2,6,nil,1] |> Enum.filter(&is_integer/1) |> Enum.min()
1
```

**Comment by eksperimental** [comment]
and if you still want  `nil` to be returned, you can use the `Enum.max_by/3` function

```elixir
iex(12)> [2, 6, nil, 1] |> Enum.max_by(fn(x) when is_integer(x) -> x; _ -> 0 end)      
6
iex(13)> [2, 6, nil, 1] |> Enum.min_by(fn(x) when is_integer(x) -> x; _ -> 0 end)
nil
```
