### ISSUE TITLE
@enforce_keys doesn't work when defined after defstruct

### ISSUE THREAD

**Issue by vnbrs** [elixir-lang/elixir#9647]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.2 (compiled with Erlang/OTP 22)
* Operating system: macOS 10.14.6 (18G1012)

### Current behavior
When defining a struct with the `defstruct` macro, `@enforce_keys` will not work if it were defined after the macro. For example:

```
defmodule Car do
  defstruct [:model, :year]
  @enforce_keys [:model]
end

iex(3)> %Car{}
%Car{model: nil, year: nil}
```

### Expected behavior
The expected behaviour would be:

```
defmodule Car do
  defstruct [:model, :year]
  @enforce_keys [:model]
end

iex(3)> %Car{}
** (ArgumentError) the following keys must also be given when building struct Car: [:model]
    expanding struct: Car.__struct__/1
```

In my point of view, `@enforce_keys` should be a parameter of `defstruct`.

**Comment by josevalim** [comment]
Note you receive a warning that `@enforce_keys` is not used. Plus this is the same behaviour as all other module attributes. If you have a `@doc` after a function, then it won't work either.

Furthermore, the advantage of having it as an attribute, instead of a parameter, is that it composes nicely with tools that may define the struct for you. For example, in Ecto you can do:

    @enforce_keys [...]
    schema "..."

Given the existing warning and the composability, we don't plan to change to the current API. In any case, thanks for the proposal.
