### ISSUE TITLE
Accept << ... :: size(@attr) >> in module attributes, or make its error message more specific

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#9707]
### Environment

```
$ elixir --version
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```

### Current behavior

This line of code

```
@sha_zero << 0 :: @sha1_size_bytes * 8 >>
```

generates compilation error

```
size in bitstring expects an integer or a variable as argument, got: Module.__get_attribute__(..., :sha1_size_bytes, ...)
```

but the same binary is accepted in

```
def foo, do: << 0 :: @sha1_size_bytes * 8 >>
```

### Expected behavior

Either accept the first case, or make its error message more case-specific.

**Comment by ericmj** [comment]
This issue is not specific to binaries, any syntax construct or macro that expects a literal will not work with attributes in the module body. Since it's a general issue and not specific to binaries it's hard to give an error message for it.

One solution could be to translate `Module.__get_attribute__(:attr)` to `@attr` in `Macro.to_string/1`, but it is fragile to special case specific functions calls in `to_string/1`. I don't think we can improve this error message. While the error message is not perfect it says it cannot use "get attribute" and you are using an attribute so at least it is leading you in the right direction.

**Comment by mguimas** [comment]
The situation seems related to the context where the syntax construct  is used, which is compile-time in the first case, and runtime in the second.

Perhaps it is more easy to change the error message to indicate that such use of this syntax construct, or of another affected by the same restriction, is not valid at compile-time ...

Anyway, the error is easy to fix, though confusing because it depends on context, hence the issue was opened.

**Comment by ericmj** [comment]
> Perhaps it is more easy to change the error message to indicate that such use of this syntax construct, or of another affected by the same restriction, is not valid at compile-time ...

It is difficult to do that because every place that expects certain literals or AST at compile time will have to do this check and have a custom error message. We have N number of language constructs that expects a certain AST at compile time and M number of constructs that will work at runtime but not compile time so we would N*M custom error messages.

It is not feasible unless there is another way to improve the error message.

**Comment by josevalim** [comment]
To add to what @ericmj said, it can also be recursive. You could have a macro that expands to the module attribute, so even if we tried to look at the code immediately, the module attribute may already not be there. We are generally really glad to improve error messages, but unfortunately this is a won't fix. Sorry.
