### ISSUE TITLE
runtime_config_path using it with multiple files

### ISSUE THREAD

**Issue by steffenix** [elixir-lang/elixir#9742]
I would like to have multiple runtime_config_path file configurable using runtime_config_path.

So far I have tried to use the ``config_providers` with a config provider and  `copy_extra_files`.
 ```
config_providers: [{Config.Reader, "/opt/app/releases/#{project[:version]}/umbrella.exs"}]
```

I feel like it's a little bit fragile, and so far work only on my docker image because of the absolute path.

**Comment by josevalim** [comment]
Hi @steffenix. We don't plan to support this directly but you can implement it by using custom steps.

The custom step can change the `config_providers` configuration, by adding custom readers, and also copy any of the necessary files inside the release. Elixir v1.10.0 also includes "rel/overlay", which will automatically copy the file inside the release, in case you want to simply refer to a config file on the release root or similar.

**Comment by D4no0** [comment]
Is there any reason not to support such a feature? 

It becomes really messy when you need to compile a config file, move it to releases and then later reference correctly to it from custom provider.

**Comment by D4no0** [comment]
Okay it seems I got it working, the problem is that the documentation is very messy. 

Distilery uses tuples in overlays like `{:mkdir, "configs"}`, however with releases you can just point to a specific folder, witch seems a downside, since in a lot of cases you would want a specific configuration file.

I think that documentation of releases should be updated with at least an example on how to use overlays.

**Comment by D4no0** [comment]
For the record this is the final working solution
```
releases: [
        web: [
          applications: [my_app: :permanent],
          config_providers: [{Config.Reader, {:system, "RELEASE_ROOT", "/releases.exs"}}],
          overlays: "apps/my_app/config"
        ]
```

**Comment by AndrewDryga** [comment]
Did anyone solved a case where you have multiple apps in an umbrella that depend on each other and have their own `releases.exs`? I guess the only way to solve it right now would be to write code that traverses dependencies and applies them as overlays compiling one `releases.exs` from multiple files?

**Comment by lukaszsamson** [comment]
@AndrewDryga I had to write a shell script that traverses apps and builds one final concated `release.exs`. Yes, it is suboptimal.

**Comment by josevalim** [comment]
You don’t need shell scripts per se. You can use custom steps or pass a function when building a release to assemble those at release time. Although I would strongly discourage this approach as you can have conflicting configs and you may find out about those only too late. That’s the reason why we moved away from per-app configs in umbrella.

**Comment by AndrewDryga** [comment]
@josevalim the problem is that you can't put everything in one file for umbrella, because `System.fetch_env!/1` would crash the release (there is no reason to set all possible environment variables for every container and it's bad to have all secrets security-wise).

And duplicating configuration in multiple `releases.exs` files for app that is a dependency for 5 others is code duplication and it would be easy to miss something when updating in one place but not others.
