### ISSUE TITLE
Mix.exs warnings_as_errors setting is not respected for .exs test scripts

### ISSUE THREAD

**Issue by DmitryKakurin** [elixir-lang/elixir#9751]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]
Elixir 1.9.4 (compiled with Erlang/OTP 20)

* Operating system: 
Windows 10

### Current behavior
I have `elixirc_options: [warnings_as_errors: true]` set in `mix.exs` file and some warnings in my Unit Tests, but `mix test` only reports the warnings, and does not fail the test compilation.

### Expected behavior
Unit Tests compilation should fail.

I'm pretty sure it's a regression in one of the recent versions of Elixir, as I remember it was behaving properly a few months back.

**Comment by josevalim** [comment]
Test files are not compiled, so elixirc_options have no effect in test files. Maybe you had some compiled files in your test directory, such as test/support in Phoenix apps, but this has no effect for the *.exs files and I don’t think it did.

If it did work on previous versions, then please let us know which version and the exact setup, so we can investigate it. Otherwise this is behaving as the config says. Thanks!

**Comment by DmitryKakurin** [comment]
@josevalim is there any other way to fail `mix test` command if .exs test files generate build warnings?
