### ISSUE TITLE
Spurious error from `mix deps.update` on Elixir 1.10

### ISSUE THREAD

**Issue by bismark** [elixir-lang/elixir#9806]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

```
$ elixir --version
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.10.1 (compiled with Erlang/OTP 22)
```

* Operating system: 

MacOS 10.15.3

### Current behavior

`mix deps.update` on Elixir 1.10 is throwing a spurious "Dependencies have diverged" error when upgrading a package. Interestingly the update appears to succeed and everything works fine afterwards. I've created a minimal reproduction here: https://github.com/bismark/elixir-mix-bug

### Expected behavior

No error is thrown.

**Comment by maennchen** [comment]
I experienced the same error. It happens when the mix.lock is created by an old version of hex and a newer version of hex is used to install.

I believe it is caused by the new checksum that was introduced by hex.

This should probably be reported in the hex repository instead. (I didn’t check if it already was.)

@bismark This should be solved for you if you either recreate the lockfile with a new hex version (mix local.hex) or if you install an older hex version on all machines running that code.

**Comment by ericmj** [comment]
Thanks for the report. Not sure if this is a mix or hex bug but I will investigate.

**Comment by lukaszsamson** [comment]
@maennchen I'm not sure if this is hex problem. I run into this issue before the recent hex update.

**Comment by maennchen** [comment]
@lukaszsamson I had this exact problem when the CI had a newer version of hex installed than I had locally.

After updating hex & recreating the lock locally (the diff showed that checksums were added), the CI passed again.

Maybe this error can also be caused by other scenarios, but the one I experienced was probably a hex problem. (CI & local machine both run Elixir 1.9.4 on OTP 22 and not 1.10.x)
