### ISSUE TITLE
Mix format exceed line length at ==

### ISSUE THREAD

**Issue by arxeiss** [elixir-lang/elixir#9809]
### Environment
* Elixir & Erlang/OTP versions (elixir --version):
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.10.0 (compiled with Erlang/OTP 22)
* Operating system: Ubuntu 18.04 LTS

### Current behaviour
This is 
**Formatter:**
```elixir
[
  line_length: 120,
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"]
]
```

**My test file**
```elixir
defmodule Day3Test do
  use ExUnit.Case

  test "Correct line intersection" do
    assert Day3.lines_intersect(%{p1: %{x: 10, y: 5}, p2: %{x: 10, y: -5}}, %{p1: %{x: 2, y: -4}, p2: %{x: 2, y: -2}}) ==
             nil
    assert Day3.lines_intersect(%{p1: %{x: 4, y: 5}, p2: %{x: 8, y: 5}}, %{p1: %{x: -10, y: -7}, p2: %{x: -20, y: -7}}) ==
             nil
  end
end
```

### Expected behavior
In the first assert, the second `=` of last `==` is 121st character on the line. In the second assert both `==` characters exceed line length.
I had to set line_length to 116 to actually wrap those lines. I expect that nothing can exceed maximum line length.

**Comment by josevalim** [comment]
Yes, this is noted in the docs where we mention that the maximum length is when we start to break constructs. For example, if you have this:

    Foo.Bar.very_long_function_name_that_exceeds_limit(...)

We have nothing to do besides break it on the first parens. If we break prematurely, then it leads to highly nested code. Similarly here, our first opportunity to break is after `==`. if you want to be safe, reduce the line length to give some margin for errors. Otherwise it is not something we can fix on our sides.

**Comment by josevalim** [comment]
In any case, thanks for the report! :heart:
