### ISSUE TITLE
Mix tasks always run with the logger level set to debug in 1.10.1

### ISSUE THREAD

**Issue by joseph-lozano** [elixir-lang/elixir#9816]
### Precheck

* Do not use the issue tracker for help or support (try Elixir Forum, Stack Overflow, IRC, etc.)
* For proposing a new feature, please start a discussion on the Elixir Core mailing list: https://groups.google.com/group/elixir-lang-core
* For bugs, do a quick search and make sure the bug has not yet been reported
* Please disclose security vulnerabilities privately at elixir-security@googlegroups.com
* Finally, be nice and have fun!

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.10.1
* Operating system: 

### Current behavior

When running a mix task in a project, the logger level is always set to `:debug`, despite what the config says. I have a repo that demostrates this: https://github.com/joseph-lozano/logger-elixir-bug

When you run `mix demo` the output is `:debug`. But if you do `iex -S mix` and run `Logger.level()`, it is `:warn`

### Expected behavior

When running in a mix task, the logger output should be the same as what is configured.

**Comment by josevalim** [comment]
Yes, you need to call `Mix.Task.run "app.start"`for the logger configuration to take place. Otherwise, your Logger can depend on backends and other configuration defined by your application, and making this configuration apply early, before your app is compiled or starts, is going to cause the logger to crash.
