### ISSUE TITLE
Add linear representation functions to Calendar types

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#9831]
Our Calendar types have historically missed a feature that allows them to be converted to an integer. The reason for this is that, although Unix Epoch is the standard, the Unix Epoch is normalized to UTC, so converting a naive datetime to Unix Epoch could be misleading.

However, there are many situations where converting to an integer can be useful. For example, when sorting large lists of datetimes, working on integers can be much more efficient. Given we can't standardize on Unix Epoch, my proposal is to standardize on gregorian seconds with the following functions:

```elixir
Date.to_gregorian_days(date)
Date.from_gregorian_days(days, calendar \\ Calendar.ISO)
NaiveDateTime.to_gregorian_seconds(naive_datetime)
NaiveDateTime.from_gregorian_seconds(seconds, microseconds \\ {0, 0}, calendar \\ Calendar.ISO)
```

They will mirror the `from_erl`/`to_erl` APIs. I also would like to introduce similar functions for Time, but those are not gregorian related. We could call `Time.to_seconds_after_midnight` or `Time.from_seconds_after_midnight` but I am not convinced about those, so I am glad to punt on it.

/cc @kipcole9 @Qqwy @lau

**Comment by lau** [comment]
Sounds good to me.

**Comment by Qqwy** [comment]
:thinking: We currently already have `Calendar.naive_datetime_to_iso_days` and `Calendar.time_to_day_fraction` which when called together on e.g. a (Naive)DateTime would form a tuple akin `{days :: int, {parts_in_day :: int, parts_per_day :: int}}` that would be quick to sort or to use for other purposes, although some care is required since we are working with a fraction.

That might be enough. Conversions to Gregorian seconds can only be done for calendars that are compatible with these. Many are, but not all of them. 

Of course, we could also take the tuple mentioned above and calculate `days * parts_per_day + parts_in_day` (this does make the assumption that all calendar entries have the same `parts_in_day` value) or days + `parts_per_day/parts_in_day` (resulting in loss of precision by turning it into a float, but no further assumptions are made).


I think we should write a benchmark to compare the performance characteristics of:
- ISOday/fraction tuples: large lists of `{int, {int, int}}` where the latter two are considered as fraction.
- large lists of 'ISOday/fraction' represented as floats.
- 'Gregorian microseconds': large lists of (big) integers.

The results of this might tell us if it is worth it to create a specialized linear representation that is limited to only certain kinds of calendars.

**Comment by Qqwy** [comment]
And a side question: What is your use-case for converting _back_ from a linear representation into a Calendar type?

**Comment by josevalim** [comment]
@Qqwy unfortunately the fractional bits in iso_days is not a linear representation regarding to Erlang Term Ordering.

> And a side question: What is your use-case for converting back from a linear representation into a Calendar type?

Just completeness.

**Comment by Qqwy** [comment]
> @Qqwy unfortunately the fractional bits in iso_days is not a linear representation regarding to Erlang Term Ordering.
> 
> > And a side question: What is your use-case for converting back from a linear representation into a Calendar type?
> 
> Just completeness.

 @kipcole9 might be able to shed more light on this, but I suspect that the conversion ('back') from a linear representation to a Calendar type might be much more difficult than the other way around.

**Comment by NickNeck** [comment]
Should `to_gregorian_seconds` and `to_gregorian_days` better called `to_seconds` and `to_days` because `Date` and `NaivDatetime` containing the type of the used `calendar`.

**Comment by josevalim** [comment]
@NickNeck we need to choose a uniform representation, because the goal is sorting. IF they are not uniform, they can I cannot compare across calendars. Yes, it should also work for negative datetimes.

I am willing to go forward with this, I just need @kipcole9's blessings. :)

**Comment by kipcole9** [comment]
Nobody needs my blessing! :-)

Its a pity we can't unify the linear functions with the ISOday/fraction tuples since that would be conceptually really clean. But as you pointed out, the tuples won't sort as a user would expect.

I don't see any issues on my calendars with this proposal.  Just vaguely uncomfortable that now we have two internal representations of time since epoch (ISODays/fractions and gregorian seconds). One for conversion, one for comparison.

**Comment by josevalim** [comment]
To be clear, the Gregorian ones is no my internal and we will compute it automatically from the ISO one. So it should be just an extra reference point.

**Comment by josevalim** [comment]
Closing in favor of PR, thanks @ukrbublik!
