### ISSUE TITLE
Improving ExUnit.Diff.compute/3 for numbers

### ISSUE THREAD

**Issue by michelboaventura** [elixir-lang/elixir#9848]
### Environment
* Elixir & Erlang/OTP versions (elixir --version): 
```Bash
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.0-dev (c0ffc15) (compiled with Erlang/OTP 22)
```
* Operating system:

Gentoo/Linux

### Current behavior

On `ExUnit` running a simple `assert 1000 == 1100` give me a strange diff:

![image](https://user-images.githubusercontent.com/111037/75478101-1fa5d580-597c-11ea-8606-f715e57bab4c.png)

Digging into `ExUnit.Diff` it seems that when both sides of the assert are numbers they are converted to Strings and end up compared with `String.myers_difference/2`. Being greedy and focused on string difference I think Myers' algorithm may not be the best choice for diffing two numbers.

### Expected behavior

It would be nice if the diff had more meaning on this instance, showing something like `1-0-00` and `1+1+00`. On the other hand I understand that this is an heuristic and diff is a complex subject. For instance, {n}vim does it right, but they have a ton of code just for diff alone :) https://github.com/neovim/neovim/tree/master/src/nvim/xdiff

**Comment by josevalim** [comment]
Yes, I think you nailed it at the end. There are some cases where myers is not the best solution and this is not an issue with numbers only. There are alternative solutions but they may be more complex both in terms of code, memory usage, and runtime costs. If someone knows a better diff strategy for numbers alone, then please let us know and will gladly consider it, but otherwise it is just an expected behaviour of the myers algorithm. Thanks for the report!

**Comment by michelboaventura** [comment]
Thanks José. I will spend some time trying to understand what nvim does and play with it on Elixir. Maybe I can came up with something nice.

Cheers
