### ISSUE TITLE
Compilation work not cached if there is an error

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#9895]
OTP22.1 Elixir 1.9.1

Modules that compiled successfully are recompiled over and over if the compilation fails with an error. This is noticeable on very large projects with expensive macros.

**Comment by josevalim** [comment]
Yes, this is by design. Caching when there are errors can make the project be stuck, as it is impossible for us to know from where the root cause came from. For example, a.ex maybe compile successfully but it is the one causes b.ex to recompile and fail. We also manage timestamps with a single Entry for the whole project. Such change would require having a last compiled timestamp per source file, which may introduce its own issues too.

**Comment by vans163** [comment]
To me it seemed like modules that don't depend on any other modules, could be cached.  (No calls to alias, import, etc). But this is fine if its intended.
