### ISSUE TITLE
Can't append a key-value tuple to a list when using special syntax

### ISSUE THREAD

**Issue by rinpatch** [elixir-lang/elixir#9930]
# Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [hipe]

Elixir 1.10.2 (compiled with Erlang/OTP 22)
```
* Operating system: Void Linux, 5.4.28_1 kernel

### Current behavior

```
iex(5)> [force: true | [stale_error_field: :id]]   
** (CompileError) iex:5: misplaced operator |/2

The | operator is typically used between brackets as the cons operator:

    [head | tail]

where head is a single element and the tail is the remaining of a list.
It is also used to update maps and structs, via the %{map | key: value} notation,
and in typespecs, such as @type and @spec, to express the union of two types
    (stdlib 3.12) lists.erl:1354: :lists.mapfoldl/3
    (stdlib 3.12) lists.erl:1355: :lists.mapfoldl/3
```

However, this works fine:
```
iex(5)> [{:force, true} | [stale_error_field: :id]]
[force: true, stale_error_field: :id]
```

### Expected behavior

```
iex(5)> [force: true | [stale_error_field: :id]] 
[force: true, stale_error_field: :id]
```

**Comment by josevalim** [comment]
Correct. That's because you can write this in typespecs:

    [foo: integer() | atom()]

Which you want to be interpreted as:

    [foo: (integer() | atom())]

And not as you propose. Unfortunately, there is nothing we can do to fix this. Fixing one scenario will break the other. You need to either use tuples, as you mentioned, or write it as: `[force: true] ++ others`, which is semantically equivalent.

Thank you!
