### ISSUE TITLE
Strange Mix behaviour when only some of the XDG env variables are set

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/elixir#9939]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
  ```
  Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

  Elixir 1.10.2 (compiled with Erlang/OTP 22)
  ```
* Operating system: `Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin`
### Current behavior

When I set only `XDG_CONFIG_HOME` and no other `XDG_*` variables then the `~/.mix` is still created.

### Expected behavior

Mix should conform to the XDG in all options if any of its environment variables are set (or preferably should conform fully). In other words, if there is `XDG_CONFIG_HOME` set Mix should assume that `XDG_DATA_HOME` has default value (which is `~/.local/share`) and vice versa.

**Comment by josevalim** [comment]
We will continue doing it per environment variable as I don’t think we should set it if any other variable is set. If this behavior is not desired, then I would rather remove support for XDG, given we are not following the spec according to you. Thanks!

**Comment by tsloughter** [comment]
@josevalim the docs say:

> Mix also falls back to the XDG_DATA_HOME and XDG_CONFIG_HOME environment variables when storing its contents and configuration.

I don't think that is clear that if you set ` XDG_CONFIG_HOME` but not `XDG_DATA_HOME` that it will be using `~/.mix` instead of `$XDG_CONFIG_HOME/mix`.

Also reading the docs I at first interpreted them to be saying mix falls back to XDG if `MIX_HOME` isn't set, but that isn't the case.

While I think XDG should be followed by default (keep backwards compatibility by checking `~/.mix` first) it is probably useful to at least update the docs.

At least since I use `asdf` for Elixir it does not pollute my home directory, only hex does :)

**Comment by ericmj** [comment]
@tsloughter Can you clarify this:

> I don't think that is clear that if you set XDG_CONFIG_HOME but not XDG_DATA_HOME that it will be using ~/.mix instead of $XDG_CONFIG_HOME/mix.

Looking at the code it seems the XDG variables are considered individually, meaning that if XDG_CONFIG_HOME is set it does not affect where data is stored and if XDG_DATA_HOME it does not affect where configuration is stored. I feel like this is what is expected, setting one variable should not change the defaults of other variables.

> Also reading the docs I at first interpreted them to be saying mix falls back to XDG if MIX_HOME isn't set, but that isn't the case.

Can you point to the section in the docs that is unclear so that we can fix it?

I opened this PR to clarify some of the defaults: https://github.com/elixir-lang/elixir/pull/9938.

**Comment by tsloughter** [comment]
@ericmj oh, maybe the odd part is that `~/.mix` is used for both configuration and for data? That is what had me confused I'm guessing.

The docs I quoted are what I found confusing. It lists variables like `MIX_HOME` and then says "fallback" is to `XDG_CONFIG_HOME` if it isn't set. Which read to me like if I don't set `MIX_HOME` it will use XDG in general, not just the environment variables -- but that is partly my own context/assumptions reading into it.

#9938 adding the defaults makes it clearer. I'd just remove the term "fallback" and say like, "if the user does not set MIX_HOME then XDG_CONFIG_HOME and XDG_DATA_HOME are checked and if they aren't set the defaults are used"

**Comment by ericmj** [comment]
> oh, maybe the odd part is that ~/.mix is used for both configuration and for data? That is what had me confused I'm guessing.

I may be wrong but I think this is the convention for applications that store files in the root of the home directory and do not follow XDG defaults.

> The docs I quoted are what I found confusing. It lists variables like MIX_HOME and then says "fallback" is to XDG_CONFIG_HOME if it isn't set. Which read to me like if I don't set MIX_HOME it will use XDG in general, not just the environment variables -- but that is partly my own context/assumptions reading into it.

> #9938 adding the defaults makes it clearer. I'd just remove the term "fallback" and say like, "if the user does not set MIX_HOME then XDG_CONFIG_HOME and XDG_DATA_HOME are checked and if they aren't set the defaults are used"

Thanks for the explanation, I pushed a commit to the PR that should clarify this.

**Comment by tsloughter** [comment]
> I may be wrong but I think this is the convention for applications that store files in the root of the home directory and do not follow XDG defaults.

Yup, you are right. I think I was confused just because there isn't a `MIX_CONFIG_HOME` and `MIX_DATA_HOME` (guessing its the archives, rebar3, rebar etc individual env vars?) to make clear that this separation of data is known by mix. My first thought was simply that mix put everything in the "config home" so that would be all you needed to set.
